---
permalink: api-automation/concept_manage_psl.html 
sidebar: sidebar 
keywords: manage, performance, service, level 
summary: Active IQ Unified Manager 의 스토리지 공급자 API를 사용하여 성능 서비스 수준을 보고, 만들고, 수정하고, 삭제할 수 있습니다. 
---
= API를 사용하여 성능 서비스 수준 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager 의 스토리지 공급자 API를 사용하여 성능 서비스 수준을 보고, 만들고, 수정하고, 삭제할 수 있습니다.



[[view-performance-service-levels]]
== 성능 서비스 수준 보기

다음 방법을 사용하면 스토리지 작업 부하에 할당하기 위한 성능 서비스 수준을 볼 수 있습니다.  API는 시스템에서 정의한 성능 서비스 수준과 사용자가 생성한 성능 서비스 수준을 모두 나열하고 모든 성능 서비스 수준의 속성을 검색합니다.  특정 성과 서비스 수준을 쿼리하려면 성과 서비스 수준의 고유 ID를 입력하여 세부 정보를 검색해야 합니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
얻다
 a| 
`/storage-provider/performance-service-levels`

`/storage-provider/performance-service-levels/\{key}`

|===


[[add-performance-service-levels]]
== 성능 서비스 수준 추가

시스템에서 정의한 성능 서비스 수준이 스토리지 워크로드에 필요한 서비스 수준 목표(SLO)를 충족하지 못하는 경우, 다음 방법을 사용하여 사용자 정의 성능 서비스 수준을 만들고 이를 스토리지 워크로드에 할당할 수 있습니다.  생성하려는 성과 서비스 수준에 대한 세부 정보를 입력하세요.  IOPS 속성의 경우 유효한 값 범위를 입력했는지 확인하세요.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
우편
 a| 
`/storage-provider/performance-service-levels`

|===


[[delete-performance-service-levels]]
== 성능 서비스 수준 삭제

다음 방법을 사용하여 특정 성능 서비스 수준을 삭제할 수 있습니다.  작업 부하에 할당된 성능 서비스 수준이거나 사용 가능한 유일한 성능 서비스 수준인 경우 성능 서비스 수준을 삭제할 수 없습니다.  특정 성과 서비스 수준을 삭제하려면 성과 서비스 수준의 고유 ID를 입력 매개변수로 제공해야 합니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
삭제
 a| 
`/storage-provider/performance-service-levels/\{key}`

|===


[[modify-performance-service-levels]]
== 성능 서비스 수준 수정

다음 방법을 사용하여 성능 서비스 수준을 수정하고 해당 속성을 업데이트할 수 있습니다.  시스템에서 정의되거나 작업 부하에 할당된 성능 서비스 수준은 수정할 수 없습니다.  특정 성능 서비스 수준을 수정하려면 고유 ID를 제공해야 합니다.  업데이트하려는 IOPS 속성과 유효한 값을 입력해야 합니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
반점
 a| 
`/storage-provider/performance-service-levels/\{key}`

|===


[[view-aggregate-capabilities-based-on-performance-service-levels]]
== 성능 서비스 수준에 따른 집계 기능 보기

다음 방법을 사용하면 성능 서비스 수준을 기반으로 집계 기능을 쿼리할 수 있습니다.  이 API는 데이터 센터에서 사용 가능한 집계 목록을 반환하고 해당 집계에서 지원할 수 있는 성능 서비스 수준 측면에서 기능을 나타냅니다.  볼륨에 워크로드를 프로비저닝하는 동안 특정 성능 서비스 수준을 지원하는 집계 기능을 확인하고 해당 기능에 따라 워크로드를 프로비저닝할 수 있습니다.  집계를 지정하는 기능은 API를 사용하여 워크로드를 프로비저닝하는 경우에만 사용할 수 있습니다.  이 기능은 Unified Manager 웹 UI에서 사용할 수 없습니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
얻다
 a| 
`/storage-provider/aggregate-capabilities`

`/storage-provider/aggregate-capabilities/\{key}`

|===