---
permalink: api-automation/concept_modify_workloads_workflow.html 
sidebar: sidebar 
keywords: modify, storage, workloads 
summary: 스토리지 작업 부하를 수정하려면 매개변수가 누락된 LUN이나 파일 공유를 업데이트하거나 기존 매개변수를 변경해야 합니다. 
---
= API를 사용하여 스토리지 워크로드 수정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 작업 부하를 수정하려면 매개변수가 누락된 LUN이나 파일 공유를 업데이트하거나 기존 매개변수를 변경해야 합니다.

이 워크플로는 LUN 및 파일 공유에 대한 성능 서비스 수준을 업데이트하는 예를 들어보겠습니다.

[NOTE]
====
워크플로는 LUN 또는 파일 공유에 성능 서비스 수준이 프로비저닝되었다고 가정합니다.

====


[[modify-file-shares]]
== 파일 공유 수정

파일 공유를 수정하는 동안 다음 매개변수를 업데이트할 수 있습니다.

* 용량 또는 크기.
* 온라인 또는 오프라인 설정.
* 보관 효율성 정책.
* 성능 서비스 수준.
* 액세스 제어 목록(ACL) 설정.
* 정책 설정을 내보냅니다.  파일 공유에서 내보내기 정책 매개변수를 삭제하고 기본(빈) 내보내기 정책 규칙을 되돌릴 수도 있습니다.


[NOTE]
====
단일 API 실행 중에는 매개변수를 하나만 업데이트할 수 있습니다.

====
이 절차에서는 파일 공유에 성능 서비스 수준을 추가하는 방법을 설명합니다.  다른 파일 공유 속성을 업데이트하는 데도 동일한 절차를 사용할 수 있습니다.

. 업데이트하려는 파일 공유의 CIFS 공유 또는 NFS 파일 공유 키를 가져옵니다.  이 API는 데이터 센터의 모든 파일 공유를 쿼리합니다.  이미 파일 공유 키를 알고 있다면 이 단계를 건너뛰세요.
+
[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
얻다
 a| 
`/storage-provider/file-shares`

|===
. 획득한 파일 공유 키로 다음 API를 실행하여 파일 공유의 세부 정보를 확인하세요.
+
[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
얻다
 a| 
`/storage-provider/file-shares/\{key}`

|===
+
출력에서 파일 공유의 세부 정보를 확인합니다.

+
[listing]
----
"assigned_performance_service_level": {
        "key": null,
        "name": "Unassigned",
        "peak_iops": null,
        "expected_iops": null,
        "_links": {}
      },
----
. 이 파일 공유에 할당하려는 성능 서비스 수준에 대한 키를 가져옵니다.  현재로서는 정책이 할당되지 않았습니다.
+
[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
성능 서비스 수준
 a| 
얻다
 a| 
`/storage-provider/performance-service-levels`

|===
+
[NOTE]
====
시스템 정의 성능 서비스 수준의 세부 정보를 검색하려면 다음을 설정하세요. `system_defined` 입력 매개변수 `true` .  출력에서 파일 공유에 적용하려는 성능 서비스 수준의 키를 얻습니다.

====
. 파일 공유에 성능 서비스 수준을 적용합니다.
+
[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공업체
 a| 
반점
 a| 
`/storage-provider/file-shares/\{key}`

|===
+
입력 시에는 업데이트하려는 매개변수와 파일 공유 키만 지정해야 합니다.  이 경우에는 성과 서비스 수준의 핵심이 됩니다.

+
*샘플 cURL*

+
[listing]
----
curl -X POST "https://<hostname>/api/storage-provider/file-shares"`-H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>" -d
"{
\"performance_service_level\": { \"key\": \"1251e51b-069f-11ea-980d-fa163e82bbf2\" },
}"
----
+
JSON 출력에는 홈 및 파트너 노드의 액세스 엔드포인트가 성공적으로 생성되었는지 확인하는 데 사용할 수 있는 Job 개체가 표시됩니다.

. 출력에 표시된 작업 개체 키를 사용하여 성능 서비스 수준이 파일 공유에 추가되었는지 확인합니다.
+
[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
관리 서버
 a| 
얻다
 a| 
`/management-server/jobs/\{key}`

|===
+
Job 객체의 ID로 쿼리하면 파일 공유가 성공적으로 업데이트되었는지 확인할 수 있습니다.  오류가 발생한 경우 오류를 해결하고 API를 다시 실행하세요.  성공적으로 생성되면 파일 공유를 쿼리하여 수정된 객체를 확인합니다.

+
[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
얻다
 a| 
`/storage-provider/file-shares/\{key}`

|===
+
출력에서 파일 공유의 세부 정보를 확인합니다.

+
[listing]
----
"assigned_performance_service_level": {
        "key": "1251e51b-069f-11ea-980d-fa163e82bbf2",
        "name": "Value",
        "peak_iops": 75,
        "expected_iops": 75,
        "_links": {
            "self": {
                "href": "/api/storage-provider/performance-service-levels/1251e51b-069f-11ea-980d-fa163e82bbf2"
            }
        }
----




[[update-luns]]
== LUN 업데이트

LUN을 업데이트하는 동안 다음 매개변수를 수정할 수 있습니다.

* 용량 또는 크기
* 온라인 또는 오프라인 설정
* 저장 효율성 정책
* 성능 서비스 수준
* LUN 맵


[NOTE]
====
단일 API 실행 중에는 매개변수를 하나만 업데이트할 수 있습니다.

====
이 절차에서는 LUN에 성능 서비스 수준을 추가하는 방법을 설명합니다.  다른 LUN 속성을 업데이트하는 데도 동일한 절차를 사용할 수 있습니다.

. 업데이트하려는 LUN의 LUN 키를 가져옵니다.  이 API는 데이터 센터의 모든 LUN에 대한 세부 정보를 반환합니다.  이미 LUN 키를 알고 있다면 이 단계를 건너뛰세요.
+
[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공업체
 a| 
얻다
 a| 
`/storage-provider/luns`

|===
. 획득한 LUN 키로 다음 API를 실행하여 LUN의 세부 정보를 확인하세요.
+
[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공업체
 a| 
얻다
 a| 
`/storage-provider/luns/\{key}`

|===
+
출력에서 LUN의 세부 정보를 확인합니다.  이 LUN에 성능 서비스 수준이 할당되지 않았음을 확인할 수 있습니다.

+
*샘플 JSON 출력*

+
[listing]
----

  "assigned_performance_service_level": {
        "key": null,
        "name": "Unassigned",
        "peak_iops": null,
        "expected_iops": null,
        "_links": {}
      },
----
. LUN에 할당하려는 성능 서비스 수준에 대한 키를 얻습니다.
+
[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
성능 서비스 수준
 a| 
얻다
 a| 
`/storage-provider/performance-service-levels`

|===
+
[NOTE]
====
시스템 정의 성능 서비스 수준의 세부 정보를 검색하려면 다음을 설정하세요. `system_defined` 입력 매개변수 `true` .  출력에서 LUN에 적용하려는 성능 서비스 수준의 키를 얻습니다.

====
. LUN에 성능 서비스 수준을 적용합니다.
+
[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공업체
 a| 
반점
 a| 
`/storage-provider/lun/\{key}`

|===
+
입력 시에는 LUN 키와 함께 업데이트하려는 매개변수만 지정해야 합니다.  이 경우에는 성과 서비스 수준의 핵심입니다.

+
*샘플 cURL*

+
[listing]
----
curl -X PATCH "https://<hostname>/api/storage-provider/luns/7d5a59b3-953a-11e8-8857-00a098dcc959" -H "accept: application/json" -H "Content-Type: application/json" H "Authorization: Basic <Base64EncodedCredentials>" -d
"{ \"performance_service_level\": { \"key\": \"1251e51b-069f-11ea-980d-fa163e82bbf2\" }"
----
+
JSON 출력에는 업데이트한 LUN을 확인하는 데 사용할 수 있는 작업 개체 키가 표시됩니다.

. 획득한 LUN 키로 다음 API를 실행하여 LUN의 세부 정보를 확인하세요.
+
[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공업체
 a| 
얻다
 a| 
`/storage-provider/luns/\{key}`

|===
+
출력에서 LUN의 세부 정보를 확인합니다.  이 LUN에 성능 서비스 수준이 할당된 것을 볼 수 있습니다.

+
*샘플 JSON 출력*

+
[listing]
----

     "assigned_performance_service_level": {
        "key": "1251e51b-069f-11ea-980d-fa163e82bbf2",
        "name": "Value",
        "peak_iops": 75,
        "expected_iops": 75,
        "_links": {
            "self": {
                "href": "/api/storage-provider/performance-service-levels/1251e51b-069f-11ea-980d-fa163e82bbf2"
            }
----

