---
permalink: api-automation/concept_events_api.html 
sidebar: sidebar 
keywords: view, events, system, details 
summary: 이벤트 API를 사용하면 데이터 센터의 모니터링 클러스터에 대해 생성된 이벤트를 검색할 수 있습니다. 
---
= API를 사용하여 이벤트 및 알림 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그만큼 `events` , `alerts` , 그리고 `scripts` API는 다음과 같습니다. `management-server` 카테고리를 사용하면 Active IQ Unified Manager 환경에서 알림과 관련된 이벤트, 알림 및 스크립트를 관리할 수 있습니다.



== 이벤트 보기 및 수정

Unified Manager는 Unified Manager가 모니터링하고 관리하는 클러스터에 대해 ONTAP 에서 생성된 이벤트를 수신합니다.  이러한 API를 사용하면 클러스터에 대해 생성된 이벤트를 보고, 이를 해결하고 업데이트할 수 있습니다.

실행하여 `GET` 에 대한 방법 `/management-server/events` API를 사용하면 과거 데이터를 포함하여 데이터 센터의 이벤트를 쿼리할 수 있습니다.  이름, 영향 수준, 영향 영역, 심각도, 상태, 리소스 이름, 리소스 유형 등의 내장 필터를 사용하여 특정 이벤트를 확인하세요.  리소스 유형 및 영역 매개변수는 이벤트가 발생한 스토리지 개체에 대한 정보를 반환하고, 영향 영역은 가용성, 용량, 구성, 보안, 보호 및 성능과 같이 이벤트가 발생한 문제에 대한 정보를 반환합니다.

이 API에 대해 PATCH 작업을 실행하면 이벤트에 대한 해결 워크플로를 활성화할 수 있습니다.  이벤트를 자신 또는 다른 사용자에게 할당하고 이벤트 수신을 확인할 수 있습니다.  이벤트를 트리거한 문제를 해결하기 위해 리소스에 대한 단계를 수행하면 이 API를 사용하여 이벤트를 해결됨으로 표시할 수 있습니다.

이벤트에 대한 자세한 내용은 다음을 참조하세요.link:../events/concept_manage_events.html["이벤트 관리"] .

[cols="4*"]
|===
| 범주 | HTTP 동사 | 길 | 설명 


 a| 
관리 서버
 a| 
얻다
 a| 
`/management-server/events`
`/management-server/events/{key}`
 a| 
Get ALL 메서드를 실행하면 응답 본문은 데이터 센터의 모든 이벤트에 대한 이벤트 세부 정보로 구성됩니다.  특정 키로 이벤트 세부 정보를 검색하면 특정 이벤트의 세부 정보를 보고 리소스에서 다음 작업 세트를 실행할 수 있습니다.  응답 본문은 해당 이벤트의 세부정보로 구성됩니다.



 a| 
관리 서버
 a| 
반점
 a| 
`management-server/events/{key}`
 a| 
이 API를 실행하여 이벤트를 할당하거나 상태를 확인됨 또는 해결됨으로 변경합니다.  이 방법을 사용하면 이벤트를 자신 또는 다른 사용자에게 할당할 수도 있습니다.  이는 동기적 작업입니다.

|===


== 알림 관리

이벤트는 자동으로 지속적으로 생성됩니다.  Unified Manager는 이벤트가 특정 필터 기준을 충족할 때만 알림을 생성합니다.  알림을 생성할 이벤트를 선택할 수 있습니다.  를 사용하여 `/management-server/alerts` API를 사용하면 특정 이벤트나 특정 심각도 유형의 이벤트가 발생할 때 자동으로 알림을 보내도록 알림을 구성할 수 있습니다.

알림에 대한 자세한 내용은 다음을 참조하세요.link:../events/concept_manage_alerts.html["알림 관리"] .

[cols="4*"]
|===
| 범주 | HTTP 동사 | 길 | 설명 


 a| 
관리 서버
 a| 
얻다
 a| 
`/management-server/alerts`
`/management-server/alerts/{key}`
 a| 
alert 키를 사용하여 환경에 있는 모든 기존 알림이나 특정 알림을 쿼리합니다.  사용자 환경에서 생성된 알림에 대한 정보(알림 설명, 작업, 알림이 전송된 이메일 ID, 이벤트 및 심각도 등)를 볼 수 있습니다.



 a| 
관리 서버
 a| 
우편
 a| 
`/management-server/alerts`
 a| 
이 방법을 사용하면 특정 이벤트에 대한 알림을 추가할 수 있습니다.  경고 이름, 경고가 적용되는 물리적 또는 논리적 리소스 또는 이벤트, 경고가 활성화되었는지 여부, SNMP 트랩을 발행하는지 여부를 추가해야 합니다.  알림 스크립트를 추가하는 경우 작업, 알림 이메일 ID, 스크립트 세부 정보 등 알림을 생성하려는 추가 세부 정보를 추가할 수 있습니다.



 a| 
관리 서버
 a| 
패치 및 삭제
 a| 
`management-server/events/{key}`
 a| 
이러한 방법을 사용하면 특정 알림을 수정하고 삭제할 수 있습니다.  설명, 이름, 알림 활성화 및 비활성화 등 다양한 속성을 수정할 수 있습니다.  알림이 더 이상 필요하지 않으면 알림을 삭제할 수 있습니다.

|===

NOTE: 알림을 추가하기 위한 리소스를 선택할 때 리소스로 클러스터를 선택하더라도 해당 클러스터 내의 스토리지 개체가 자동으로 선택되지 않는다는 점에 유의하세요.  예를 들어, 모든 클러스터의 모든 중요 이벤트에 대한 알림을 생성하면 클러스터 중요 이벤트에 대한 알림만 받게 됩니다.  노드, 집계 등의 중요 이벤트에 대한 알림은 받지 않습니다.



== 스크립트 관리

를 사용하여 `/management-server/scripts` API를 사용하면 알림이 트리거될 때 실행되는 스크립트와 알림을 연결할 수도 있습니다.  스크립트를 사용하면 Unified Manager에서 여러 스토리지 개체를 자동으로 수정하거나 업데이트할 수 있습니다.  스크립트는 알림과 연결되어 있습니다.  이벤트로 인해 알림이 발생하면 스크립트가 실행됩니다.  사용자 정의 스크립트를 업로드하고 알림이 생성되면 실행을 테스트할 수 있습니다.  스크립트에 알림을 연결하면 Unified Manager에서 이벤트에 대한 알림이 발생할 때 스크립트가 실행됩니다.

스크립트에 대한 자세한 내용은 다음을 참조하세요.link:../events/concept_manage_scripts.html["스크립트 관리"] .

[cols="4*"]
|===
| 범주 | HTTP 동사 | 길 | 설명 


 a| 
관리 서버
 a| 
얻다
 a| 
`/management-server/scripts`
 a| 
이 API를 사용하면 사용자 환경에 있는 모든 기존 스크립트를 쿼리할 수 있습니다.  표준 필터와 정렬 작업을 사용하여 특정 스크립트만 봅니다.



 a| 
관리 서버
 a| 
우편
 a| 
`/management-server/scripts`
 a| 
이 API를 사용하여 스크립트에 대한 설명을 추가하고 알림과 관련된 스크립트 파일을 업로드합니다.

|===