---
permalink: api-automation/concept_manage_sep.html 
sidebar: sidebar 
keywords: manage, storage, efficiency, policy 
summary: 스토리지 공급자 API를 사용하여 스토리지 효율성 정책을 보고, 만들고, 수정하고, 삭제할 수 있습니다. 
---
= API를 사용하여 스토리지 효율성 정책 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 공급자 API를 사용하여 스토리지 효율성 정책을 보고, 만들고, 수정하고, 삭제할 수 있습니다.

[NOTE]
====
다음 사항에 유의하세요.

* Unified Manager에서 워크로드를 생성하는 동안 스토리지 효율성 정책을 할당하는 것은 필수가 아닙니다.
* 정책이 워크로드에 할당된 후에는 워크로드에서 스토리지 효율성 정책의 할당을 해제할 수 없습니다.
* 워크로드에 중복 제거 및 압축과 같은 일부 스토리지 설정이 ONTAP 볼륨에 지정된 경우, Unified Manager에서 스토리지 워크로드를 추가할 때 적용하는 스토리지 효율성 정책에 지정된 설정으로 해당 설정을 덮어쓸 수 있습니다.


====


[[view-storage-efficiency-policies]]
== 스토리지 효율성 정책 보기

다음 방법을 사용하면 스토리지 워크로드에 스토리지 효율성 정책을 할당하기 전에 해당 정책을 볼 수 있습니다.  이 API는 시스템에서 정의한 모든 스토리지 효율성 정책과 사용자가 생성한 모든 스토리지 효율성 정책을 나열하고 모든 스토리지 효율성 정책의 속성을 검색합니다.  특정 스토리지 효율성 정책을 쿼리하려면 정책의 고유 ID를 입력하여 세부 정보를 검색해야 합니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
얻다
 a| 
`/storage-provider/storage-efficiency-policies`

`/storage-provider/storage-efficiency-policies/\{key}`

|===


[[add-storage-efficiency-policies]]
== 스토리지 효율성 정책 추가

다음 방법을 사용하여 사용자 지정 스토리지 효율성 정책을 만들고, 시스템 정의 정책이 스토리지 워크로드에 대한 프로비저닝 요구 사항을 충족하지 못하는 경우 해당 정책을 스토리지 워크로드에 할당할 수 있습니다.  생성하려는 스토리지 효율성 정책의 세부 정보를 입력 매개변수로 입력합니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
우편
 a| 
`/storage-provider/storage-efficiency-policies`

|===


[[delete-storage-efficiency-policies]]
== 스토리지 효율성 정책 삭제

다음 방법을 사용하여 특정 스토리지 효율성 정책을 삭제할 수 있습니다.  워크로드에 할당된 스토리지 효율성 정책이나 사용 가능한 유일한 스토리지 효율성 정책인 경우 스토리지 효율성 정책을 삭제할 수 없습니다.  특정 스토리지 효율성 정책을 삭제하려면 스토리지 효율성 정책의 고유 ID를 입력 매개변수로 제공해야 합니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
삭제
 a| 
`/storage-provider/storage-efficiency-policies/\{key}`

|===


[[modify-storage-efficiency-policies]]
== 스토리지 효율성 정책 수정

다음 방법을 사용하여 저장소 효율성 정책을 수정하고 해당 속성을 업데이트할 수 있습니다.  시스템에서 정의되거나 워크로드에 할당된 스토리지 효율성 정책은 수정할 수 없습니다.  특정 스토리지 효율성 정책을 수정하려면 스토리지 효율성 정책의 고유 ID를 제공해야 합니다.  또한, 업데이트하려는 부동산과 그 가치를 제공해야 합니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
반점
 a| 
`/storage-provider/storage-efficiency-policies/\{key}`

|===