---
permalink: api-automation/concept_rest_services_offered_in_unified_manager_apis.html 
sidebar: sidebar 
keywords: rest, services, offer, active iq, unified, manager 
summary: Active IQ Unified Manager API를 사용하기 전에 제공되는 REST 서비스와 운영에 대해 알고 있어야 합니다. 
---
= Active IQ Unified Manager 에서 제공되는 REST 서비스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager API를 사용하기 전에 제공되는 REST 서비스와 운영에 대해 알고 있어야 합니다.

API 서버를 구성하는 데 사용되는 프로비저닝 및 관리 API는 읽기(GET) 또는 쓰기(POST, PATCH, DELETE) 작업을 지원합니다.  다음은 API에서 지원하는 GET, PATCH, POST, DELETE 작업의 몇 가지 예입니다.

* GET의 예: `GET /datacenter/cluster/clusters` 데이터 센터의 클러스터 세부 정보를 검색합니다.  반환되는 최대 레코드 수 `GET` 연산은 1000입니다.
+
[NOTE]
====
API를 사용하면 지원되는 속성별로 레코드를 필터링, 정렬, 순서 지정할 수 있습니다.

====
* POST의 예: `POST /datacenter/svm/svms` 사용자 정의 스토리지 가상 머신(SVM)을 생성합니다.
* PATCH의 예: `PATCH /datacenter/svm/svms/{key}` 고유 키를 사용하여 SVM의 속성을 수정합니다.
* DELETE의 예: `DELETE /storage-provider/access-endpoints/{key}` 고유 키를 사용하여 LUN, SVM 또는 파일 공유에서 액세스 엔드포인트를 삭제합니다.


API를 사용하여 수행할 수 있는 REST 작업은 운영자, 스토리지 관리자 또는 애플리케이션 관리자 사용자의 역할에 따라 달라집니다.

[cols="2*"]
|===
| 사용자 역할 | 지원되는 REST 메서드 


 a| 
연산자
 a| 
데이터에 대한 읽기 전용 액세스.  이 역할이 있는 사용자는 모든 GET 요청을 실행할 수 있습니다.



 a| 
스토리지 관리자
 a| 
모든 데이터에 대한 읽기 권한.  이 역할이 있는 사용자는 모든 GET 요청을 실행할 수 있습니다.

또한 특정 활동(예: 스토리지 서비스 개체 및 스토리지 관리 옵션 관리)을 수행하기 위한 쓰기 액세스 권한(PATCH, POST 및 DELETE 요청 실행)도 있습니다.



 a| 
애플리케이션 관리자
 a| 
모든 데이터에 대한 읽기 및 쓰기 액세스 권한.  이 역할을 가진 사용자는 모든 기능에 대해 GET, PATCH, POST 및 DELETE 요청을 실행할 수 있습니다.

|===
모든 REST 작업에 대한 자세한 내용은 _온라인 API 문서_를 참조하세요.
