---
permalink: api-automation/concept_security_apis.html 
sidebar: sidebar 
keywords: manage, user 
summary: 보안 범주의 API를 사용하여 Active IQ Unified Manager 에서 선택한 클러스터 개체에 대한 사용자 액세스를 제어할 수 있습니다.  로컬 사용자나 데이터베이스 사용자를 추가할 수 있습니다.  인증 서버에 속한 원격 사용자나 그룹을 추가할 수도 있습니다.  사용자에게 할당한 역할의 권한에 따라 사용자는 Unified Manager에서 저장소 개체를 관리하거나 데이터를 볼 수 있습니다. 
---
= API를 사용하여 사용자 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
API를 사용할 수 있습니다 `security` Active IQ Unified Manager 에서 선택된 클러스터 개체에 대한 사용자 액세스를 제어하는 ​​범주입니다.  로컬 사용자나 데이터베이스 사용자를 추가할 수 있습니다.  인증 서버에 속한 원격 사용자나 그룹을 추가할 수도 있습니다.  사용자에게 할당한 역할의 권한에 따라 사용자는 Unified Manager에서 저장소 개체를 관리하거나 데이터를 볼 수 있습니다.

[NOTE]
====
이러한 작업을 실행하려면 애플리케이션 관리자 역할이 있어야 합니다.  Unified Manager 웹 UI를 사용하여 이러한 설정을 구성할 수도 있습니다.

====
API는 다음과 같습니다. `security` 카테고리는 키 매개변수가 아닌 사용자 이름인 users 매개변수를 사용자 엔터티의 고유 식별자로 사용합니다.

[cols="3*"]
|===
| HTTP 동사 | 길 | 설명 


 a| 
`GET`

`POST`
 a| 
`/security/users`

`/security/users`
 a| 
이러한 방법을 사용하면 사용자 세부 정보를 얻거나 Unified Manager에 새 사용자를 추가할 수 있습니다.

사용자 유형에 따라 사용자에게 특정 역할을 추가할 수 있습니다.  사용자를 추가하는 동안 로컬 사용자, 유지 관리 사용자, 데이터베이스 사용자에 대한 비밀번호를 제공해야 합니다.



 a| 
`GET`

`PATCH`

`DELETE`
 a| 
`/security/users/\{name}`
 a| 
GET 메서드를 사용하면 이름, 이메일 주소, 역할, 권한 유형 등 사용자의 모든 세부 정보를 검색할 수 있습니다.  PATCH 방식을 사용하면 세부 정보를 업데이트할 수 있습니다.  DELETE 메서드를 사용하면 사용자를 제거할 수 있습니다.

|===