---
permalink: api-automation/concept_rest_api_versioning_in_unified_manager_apis.html 
sidebar: sidebar 
keywords: api, version, active iq, unified, manager 
summary: Active IQ Unified Manager 의 REST API URI는 버전 번호를 지정합니다.  예를 들어, /v2/datacenter/svm/svms.  /v2/datacenter/svm/svms의 버전 번호 v2는 특정 릴리스에서 사용된 API 버전을 나타냅니다.  버전 번호는 클라이언트가 처리할 수 있는 응답을 다시 전송하여 클라이언트 소프트웨어에 대한 API 변경의 영향을 최소화합니다. 
---
= Active IQ Unified Manager 의 API 버전
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager 의 REST API URI는 버전 번호를 지정합니다.  예를 들어, `/v2/datacenter/svm/svms.` 버전 번호 `v2` ~에 `/v2/datacenter/svm/svms` 특정 릴리스에서 사용된 API 버전을 나타냅니다.  버전 번호는 클라이언트가 처리할 수 있는 응답을 반환함으로써 클라이언트 소프트웨어에 대한 API 변경의 영향을 최소화합니다.

이 버전 번호의 숫자 부분은 릴리스와 관련하여 증가합니다.  버전 번호가 있는 URI는 향후 릴리스에서 이전 버전과의 호환성을 유지하는 일관된 인터페이스를 제공합니다.  예를 들어 버전이 없는 동일한 API도 찾을 수 있습니다. `/datacenter/svm/svms,` 버전이 없는 기본 API를 나타냅니다.  기본 API는 항상 최신 버전의 API입니다.

[NOTE]
====
Swagger 인터페이스의 오른쪽 상단에서 사용할 API 버전을 선택할 수 있습니다.  기본적으로 가장 높은 버전이 선택됩니다.  Unified Manager 인스턴스에서 사용 가능한 특정 API의 가장 높은 버전(증분 정수 기준)을 사용하는 것이 좋습니다.

====
모든 요청에 대해 사용하려는 API 버전을 명시적으로 요청해야 합니다.  버전 번호가 지정되면 서비스는 애플리케이션이 처리하도록 설계되지 않은 응답 요소를 반환하지 않습니다.  REST 요청에는 버전 매개변수를 포함해야 합니다.  이전 버전의 API는 몇 번의 릴리스 이후 결국 더 이상 사용되지 않게 되었습니다.  이 릴리스에서는 `v1` 해당 API 버전은 더 이상 사용되지 않습니다.
