---
permalink: api-automation/concept_workflow_intro.html 
sidebar: sidebar 
keywords: common, workflows, storage, management 
summary: 공통 워크플로는 클라이언트 애플리케이션 개발자에게 Active IQ Unified Manager API가 클라이언트 애플리케이션에서 어떻게 호출되어 공통 스토리지 관리 기능을 실행할 수 있는지에 대한 예를 제공합니다.  이 섹션에는 몇 가지 샘플 워크플로가 포함되어 있습니다. 
---
= 스토리지 관리를 위한 공통 API 워크플로
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
공통 워크플로는 클라이언트 애플리케이션 개발자에게 Active IQ Unified Manager API가 클라이언트 애플리케이션에서 어떻게 호출되어 공통 스토리지 관리 기능을 실행할 수 있는지에 대한 예를 제공합니다.  이 섹션에는 몇 가지 샘플 워크플로가 포함되어 있습니다.

워크플로에서는 일반적으로 사용되는 스토리지 관리 사용 사례 중 일부를 설명하고, 사용할 수 있는 샘플 코드도 제공합니다.  각 작업은 하나 이상의 API 호출로 구성된 워크플로 프로세스를 사용하여 설명됩니다.



== 워크플로에서 사용되는 API 호출을 이해합니다.

Unified Manager 인스턴스에서 모든 REST API 호출에 대한 세부 정보가 포함된 온라인 문서 페이지를 볼 수 있습니다.  이 문서에서는 온라인 문서의 세부 내용을 반복하지 않습니다.  이 문서의 워크플로 샘플에서 사용된 각 API 호출에는 설명서 페이지에서 호출을 찾는 데 필요한 정보만 포함되어 있습니다. 특정 API 호출을 찾으면 입력 매개변수, 출력 형식, HTTP 상태 코드, 요청 처리 유형을 포함한 호출의 전체 세부 정보를 검토할 수 있습니다.

워크플로 내의 각 API 호출에 대해 다음 정보가 포함되어 있어 설명서 페이지에서 호출을 찾는 데 도움이 됩니다.

* 카테고리: API 호출은 문서 페이지에서 기능적으로 관련된 영역이나 카테고리로 정리됩니다. 특정 API 호출을 찾으려면 페이지 하단으로 스크롤하여 해당 API 범주를 클릭하세요.
* HTTP 동사(호출): HTTP 동사는 리소스에서 수행되는 작업을 식별합니다. 각 API 호출은 단일 HTTP 동사를 통해 실행됩니다.
* 경로: 경로는 호출을 수행하는 일부로 작업이 적용되는 특정 리소스를 결정합니다. 경로 문자열은 핵심 URL에 추가되어 리소스를 식별하는 완전한 URL을 형성합니다.

