---
permalink: api-automation/concept_data_center_apis.html 
sidebar: sidebar 
keywords: manage, storage, objects, data center 
summary: 데이터 센터 카테고리의 REST API를 사용하면 클러스터, 노드, 집계, 스토리지 VM, 볼륨, LUN, 파일 공유, 네임스페이스 등 데이터 센터의 스토리지 개체를 관리할 수 있습니다.  이러한 API는 객체의 구성을 쿼리하는 데 사용할 수 있으며, 일부 API를 사용하면 객체를 추가, 삭제 또는 수정하는 작업을 수행할 수 있습니다. 
---
= API를 사용하여 데이터 센터의 스토리지 객체를 관리합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
REST API는 다음과 같습니다. `datacenter` 카테고리를 사용하면 클러스터, 노드, 집계, 스토리지 VM, 볼륨, LUN, 파일 공유, 네임스페이스 등 데이터 센터의 스토리지 객체를 관리할 수 있습니다.  이러한 API는 객체의 구성을 쿼리하는 데 사용할 수 있으며, 일부 API를 사용하면 객체를 추가, 삭제 또는 수정하는 작업을 수행할 수 있습니다.

이러한 API의 대부분은 필터링, 정렬, 페이지 매김 지원 기능을 갖춘 클러스터 간 집계를 제공하는 GET 호출입니다.  이러한 API를 실행하면 데이터베이스에서 데이터가 반환됩니다.  따라서 새로 생성된 객체는 응답에 나타나기 위해 다음 획득 주기까지 발견되어야 합니다.

특정 객체의 세부 정보를 조회하려면 해당 객체의 고유 ID를 입력하여 세부 정보를 확인해야 합니다.  예를 들어, 스토리지 객체의 메트릭 및 분석 정보는 다음을 참조하세요.link:concept_metrics_apis.html["성능 지표 보기"] .

[listing]
----
curl -X GET "https://<hostname>/api/datacenter/cluster/clusters/4c6bf721-2e3f-11e9-a3e2-00a0985badbb" -H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
[NOTE]
====
CURL 명령, 예제, 요청 및 API에 대한 응답은 Swagger API 인터페이스에서 사용할 수 있습니다.  Swagger에 표시된 대로 특정 매개변수를 기준으로 결과를 필터링하고 정렬할 수 있습니다.  이러한 API를 사용하면 클러스터, 볼륨 또는 스토리지 VM과 같은 특정 스토리지 개체에 대한 결과를 필터링할 수 있습니다.

====


[[apis-for-storage-objects-in-your-data-center]]
== 데이터 센터의 스토리지 객체를 위한 API

[cols="3*"]
|===
| HTTP 동사 | 길 | 설명 


 a| 
`GET`
 a| 
`/datacenter/cluster/clusters`

`/datacenter/cluster/clusters/\{key}`
 a| 
이 방법을 사용하면 데이터 센터 전체의 ONTAP 클러스터 세부 정보를 볼 수 있습니다.  API는 클러스터의 IPv4 또는 IPv6 주소, 노드 상태, 성능, 용량, 고가용성(HA) 쌍과 같은 노드에 대한 정보를 반환하고 클러스터가 All SAN 어레이인지 여부를 나타냅니다.



 a| 
`GET`
 a| 
`/datacenter/cluster/licensing/licenses /datacenter/cluster/licensing/licenses/\{key}`
 a| 
데이터 센터의 클러스터에 설치된 라이선스의 세부 정보를 반환합니다.  필요한 기준에 따라 결과를 필터링할 수 있습니다.  라이선스 키, 클러스터 키, 만료 날짜, 라이선스 범위 등의 정보가 반환됩니다.  라이선스 키를 입력하면 특정 라이선스의 세부 정보를 검색할 수 있습니다.



 a| 
`GET`
 a| 
`/datacenter/cluster/nodes`

`/datacenter/cluster/nodes/\{key}`
 a| 
이 방법을 사용하면 데이터 센터의 노드 세부 정보를 볼 수 있습니다.  노드의 클러스터, 노드 상태, 성능 용량 및 고가용성(HA) 쌍에 대한 정보를 볼 수 있습니다.



 a| 
`GET`
 a| 
`/datacenter/protocols/cifs/shares`

`/datacenter/protocols/cifs/shares/\{key}`
 a| 
이 방법을 사용하면 데이터 센터의 CIFS 공유에 대한 세부 정보를 볼 수 있습니다.  클러스터, SVM, 볼륨 세부 정보 외에도 ACL(액세스 제어 목록)에 대한 정보도 반환됩니다.



 a| 
`GET`
 a| 
`/datacenter/protocols/nfs/export-policies`

`/datacenter/protocols/nfs/export-policies/\{key}`
 a| 
이 방법을 사용하면 지원되는 NFS 서비스에 대한 내보내기 정책의 세부 정보를 볼 수 있습니다.

클러스터 또는 스토리지 VM에 대한 내보내기 정책을 쿼리하고 NFS 파일 공유 프로비저닝을 위해 내보내기 정책 키를 재사용할 수 있습니다.  워크로드에 대한 내보내기 정책 할당 및 재사용에 대한 자세한 내용은 "CIFS 및 NFS 파일 공유 프로비저닝"을 참조하세요.



 a| 
`GET`
 a| 
`/datacenter/storage/aggregates`

`/datacenter/storage/aggregates/\{key}`
 a| 
이 방법을 사용하면 데이터 센터의 집계 컬렉션을 보거나 해당 집계에 대한 워크로드 프로비저닝 또는 모니터링을 위한 특정 집계를 볼 수 있습니다.  클러스터 및 노드 세부 정보, 사용된 성능 용량, 사용 가능한 공간과 사용된 공간, 스토리지 효율성 등의 정보가 반환됩니다.



 a| 
`GET`
 a| 
`/datacenter/storage/luns`

`/datacenter/storage/luns/\{key}`
 a| 
이 방법을 사용하면 전체 데이터 센터의 LUN 컬렉션을 볼 수 있습니다.  클러스터 및 SVM 세부 정보, QoS 정책, igroup 등 LUN에 대한 정보를 볼 수 있습니다.



 a| 
`GET`
 a| 
`/datacenter/storage/qos/policies`

`/datacenter/storage/qos/policies/\{key}`
 a| 
이 방법을 사용하면 데이터 센터의 스토리지 개체에 적용 가능한 모든 QoS 정책의 세부 정보를 볼 수 있습니다.  클러스터 및 SVM 세부 정보, 고정 또는 적응 정책 세부 정보, 해당 정책에 적용 가능한 개체 수와 같은 정보가 반환됩니다.



 a| 
`GET`
 a| 
`/datacenter/storage/qtrees`

`/datacenter/storage/qtrees/\{key}`
 a| 
이 방법을 사용하면 모든 FlexVol 볼륨이나 FlexGroup 볼륨에 대한 데이터 센터 전반의 Qtree 세부 정보를 볼 수 있습니다.  클러스터 및 SVM 세부 정보, FlexVol volume, 내보내기 정책 등의 정보가 반환됩니다.



 a| 
`GET`
 a| 
`/datacenter/storage/volumes`

`/datacenter/storage/volumes/{key}`
 a| 
이 방법을 사용하면 데이터 센터의 볼륨 컬렉션을 볼 수 있습니다.  SVM 및 클러스터 세부 정보, QoS 및 내보내기 정책, 볼륨이 읽기-쓰기, 데이터 보호 또는 부하 공유 유형인지 여부와 같은 볼륨에 대한 정보가 반환됩니다.

FlexVol 및 FlexClone 볼륨의 경우 해당 집계에 대한 정보를 볼 수 있습니다.  FlexGroup 볼륨의 경우 쿼리는 구성 집계 목록을 반환합니다.



 a| 
`GET`

`POST`

`DELETE`

`PATCH`
 a| 
`/datacenter/protocols/san/igroups`

`/datacenter/protocols/san/igroups/{key}`
 a| 
특정 LUN 대상에 액세스할 권한이 있는 개시자 그룹(igroup)을 할당할 수 있습니다.  기존 igroup이 있는 경우 할당할 수 있습니다.  igroup을 생성하여 LUN에 할당할 수도 있습니다.

이러한 방법을 사용하면 각각 igroup을 쿼리, 생성, 삭제 및 수정할 수 있습니다.

주의 사항:

* `POST:`igroup을 생성하는 동안 액세스 권한을 할당할 스토리지 VM을 지정할 수 있습니다.
* `DELETE:`특정 igroup을 삭제하려면 igroup 키를 입력 매개변수로 제공해야 합니다.  이미 LUN에 igroup을 할당한 경우 해당 igroup을 삭제할 수 없습니다.
* `PATCH:`특정 igroup을 수정하려면 igroup 키를 입력 매개변수로 제공해야 합니다.  업데이트하려는 속성과 해당 속성의 값도 입력해야 합니다.




 a| 
`GET`

`POST`

`DELETE`

`PATCH`
 a| 
`/datacenter/svm/svms`

`/datacenter/svm/svms/\{key}`
 a| 
이러한 방법을 사용하면 스토리지 가상 머신(스토리지 VM)을 보고, 만들고, 삭제하고, 수정할 수 있습니다.

* `POST:`생성하려는 스토리지 VM 객체를 입력 매개변수로 입력해야 합니다.  사용자 정의 스토리지 VM을 만든 다음 필요한 속성을 할당할 수 있습니다.
* `DELETE:`특정 스토리지 VM을 삭제하려면 스토리지 VM 키를 제공해야 합니다.
* `PATCH:`특정 스토리지 VM을 수정하려면 스토리지 VM 키를 제공해야 합니다.  업데이트하려는 속성과 해당 값도 입력해야 합니다.


|===

NOTE: 주의 사항:

환경에서 SLO 기반 워크로드 프로비저닝을 활성화한 경우 스토리지 VM을 생성하는 동안 CIFS 또는 SMB, NFS, FCP, iSCSI 등 LUN 및 파일 공유를 프로비저닝하는 데 필요한 모든 프로토콜을 지원하는지 확인하세요.  스토리지 VM이 필요한 서비스를 지원하지 않으면 프로비저닝 워크플로가 실패할 수 있습니다.  각 유형의 워크로드에 대한 서비스도 스토리지 VM에서 활성화하는 것이 좋습니다.

환경에서 SLO 기반 워크로드 프로비저닝을 활성화한 경우 스토리지 워크로드가 프로비저닝된 스토리지 VM을 삭제할 수 없습니다.  CIFS 또는 SMB 서버가 구성된 스토리지 VM을 삭제하면 이 API는 로컬 Active Directory 구성과 함께 CIFS 또는 SMB 서버도 삭제합니다.  그러나 CIFS 또는 SMB 서버 이름은 Active Directory 구성에 계속 남아 있으므로 Active Directory 서버에서 수동으로 삭제해야 합니다.



[[apis-for-network-elements-in-your-data-center]]
== 데이터 센터의 네트워크 요소를 위한 API

데이터 센터 카테고리의 다음 API는 사용자 환경의 포트 및 네트워크 인터페이스, 특히 FC 포트, FC 인터페이스, 이더넷 포트 및 IP 인터페이스에 대한 정보를 검색합니다.

[cols="3*"]
|===
| HTTP 동사 | 길 | 설명 


 a| 
`GET`
 a| 
`/datacenter/network/ethernet/ports`

`/datacenter/network/ethernet/ports/{key}`
 a| 
데이터 센터 환경의 모든 이더넷 포트에 대한 정보를 검색합니다.  포트 키를 입력 매개변수로 사용하면 해당 포트의 정보를 볼 수 있습니다.  클러스터 세부 정보, 브로드캐스트 도메인, 상태, 속도, 유형과 같은 포트 세부 정보, 포트가 활성화되었는지 여부 등의 정보가 검색됩니다.



 a| 
`GET`
 a| 
`/datacenter/network/fc/interfaces`

`/datacenter/network/fc/interfaces/{key}`
 a| 
이 방법을 사용하면 데이터 센터 환경의 FC 인터페이스 세부 정보를 볼 수 있습니다.  인터페이스 키를 입력 매개변수로 사용하면 해당 인터페이스의 정보를 볼 수 있습니다.  클러스터 세부 정보, 홈 노드 세부 정보, 홈 포트 세부 정보와 같은 정보가 검색됩니다.



 a| 
`GET`
 a| 
`/datacenter/network/fc/ports`

`/datacenter/network/fc/ports/{key}`
 a| 
데이터 센터 환경의 노드에서 사용되는 모든 FC 포트에 대한 정보를 검색합니다.  포트 키를 입력 매개변수로 사용하면 해당 포트의 정보를 볼 수 있습니다.  클러스터 세부 정보, 포트 설명, 지원되는 프로토콜, 포트 상태 등의 정보가 검색됩니다.



 a| 
`GET`
 a| 
`/datacenter/network/ip/interfaces`

`/datacenter/network/ip/interfaces/{key}`
 a| 
이 방법을 사용하면 데이터 센터 환경의 IP 인터페이스 세부 정보를 볼 수 있습니다.  인터페이스 키를 입력 매개변수로 사용하면 해당 인터페이스의 정보를 볼 수 있습니다.  클러스터 세부 정보, IP 공간 세부 정보, 홈 노드 세부 정보, 장애 조치가 활성화되었는지 여부 등의 정보가 검색됩니다.

|===