---
permalink: api-automation/concept_manage_fileshares_api.html 
sidebar: sidebar 
keywords: manage, file, share 
summary: /storage-provider/file-shares API를 사용하면 데이터 센터 환경에서 CIFS 및 NFS 파일 공유 볼륨을 보고, 추가하고, 수정하고, 삭제할 수 있습니다. 
---
= API를 사용하여 파일 공유 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `/storage-provider/file-shares` 데이터 센터 환경에서 CIFS 및 NFS 파일 공유 볼륨을 보고, 추가하고, 수정하고, 삭제할 수 있는 API입니다.

파일 공유 볼륨을 프로비저닝하기 전에 SVM이 생성되었고 지원되는 프로토콜로 프로비저닝되었는지 확인하세요.  프로비저닝 중에 성능 서비스 수준(PSL)이나 스토리지 효율성 정책(SEP)을 할당하는 경우 파일 공유를 만들기 전에 PSL이나 SEP를 만들어야 합니다.



[[view-file-shares]]
== 파일 공유 보기

다음 방법을 사용하면 Unified Manager 환경에서 사용 가능한 파일 공유 볼륨을 볼 수 있습니다.  Active IQ Unified Manager 에서 ONTAP 클러스터를 데이터 소스로 추가하면 해당 클러스터의 스토리지 워크로드가 Unified Manager 인스턴스에 자동으로 추가됩니다.  이 API는 Unified Manager 인스턴스에 자동 및 수동으로 추가된 파일 공유를 검색합니다.  이 API를 파일 공유 키와 함께 실행하면 특정 파일 공유의 세부 정보를 볼 수 있습니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
얻다
 a| 
`/storage-provider/file-shares`

`/storage-provider/file-shares/\{key}`

|===


[[add-file-shares]]
== 파일 공유 추가

다음 방법을 사용하여 SVM에 CIFS 및 NFS 파일 공유를 추가할 수 있습니다.  생성하려는 파일 공유의 세부 정보를 입력 매개변수로 입력해야 합니다.  이 API를 사용하여 FlexGroup 볼륨을 추가할 수 없습니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
우편
 a| 
`/storage-provider/file-shares`

|===
[NOTE]
====
액세스 제어 목록(ACL) 매개변수 또는 내보내기 정책 매개변수가 제공되는지에 따라 CIFS 공유 또는 NFS 파일 공유가 생성됩니다.  ACL 매개변수에 대한 값을 제공하지 않으면 CIFS 공유가 생성되지 않고, 기본적으로 NFS 공유가 생성되어 모든 사용자에게 액세스 권한이 제공됩니다.

====
*데이터 보호 볼륨 생성*: SVM에 파일 공유를 추가하면 기본적으로 마운트되는 볼륨 유형은 다음과 같습니다. `rw` (읽기-쓰기).  데이터 보호(DP) 볼륨을 생성하려면 다음을 지정하세요. `dp` 에 대한 값으로서 `type` 매개변수.



[[delete-file-shares]]
== 파일 공유 삭제

다음 방법을 사용하여 특정 파일 공유를 삭제할 수 있습니다.  특정 파일 공유를 삭제하려면 파일 공유 키를 입력 매개변수로 입력해야 합니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
삭제
 a| 
`/storage-provider/file-shares/\{key}`

|===


[[modify-file-shares]]
== 파일 공유 수정

다음 방법을 사용하여 파일 공유를 수정하고 속성을 업데이트할 수 있습니다.

특정 파일 공유를 수정하려면 파일 공유 키를 제공해야 합니다.  또한, 업데이트하려는 속성과 해당 속성을 입력해야 합니다.

[NOTE]
====
이 API를 한 번 호출하면 속성을 하나만 업데이트할 수 있습니다.  여러 개의 업데이트가 있는 경우 이 API를 여러 번 실행해야 합니다.

====
[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
반점
 a| 
`/storage-provider/file-shares/\{key}`

|===