---
permalink: api-automation/concept_verify_svm_workflow.html 
sidebar: sidebar 
keywords: verify, svms, clusters 
summary: '파일 공유나 LUN을 프로비저닝하기 전에 클러스터에 SVM(스토리지 가상 머신)이 생성되었는지 확인해야 합니다.' 
---
= API를 사용하여 클러스터의 SVM 확인
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
파일 공유나 LUN을 프로비저닝하기 전에 클러스터에 SVM(스토리지 가상 머신)이 생성되었는지 확인해야 합니다.

[NOTE]
====
워크플로는 ONTAP 클러스터가 Unified Manager에 추가되었고 클러스터 키가 획득되었다고 가정합니다.  클러스터에는 LUN과 파일 공유를 프로비저닝하는 데 필요한 라이선스가 있어야 합니다.

====
. 클러스터에 SVM이 생성되었는지 확인합니다.
+
[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
데이터센터
 a| 
얻다
 a| 
`/datacenter/svm/svms`
`/datacenter/svm/svms/\{key}`

|===
+
*샘플 cURL*

+
[listing]
----
curl -X GET "https://<hostname>/api/datacenter/svm/svms" -H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
. SVM 키가 반환되지 않으면 SVM을 생성합니다.  SVM을 생성하려면 SVM을 프로비저닝하는 클러스터 키가 필요합니다.  SVM 이름도 지정해야 합니다.  다음 단계를 따르세요.
+
[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
데이터센터
 a| 
얻다
 a| 
`/datacenter/cluster/clusters`
`/datacenter/cluster/clusters/\{key}`

|===
+
클러스터 키를 가져옵니다.

+
*샘플 cURL*

+
[listing]
----
curl -X GET "https://<hostname>/api/datacenter/cluster/clusters" -H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
. 출력에서 클러스터 키를 가져온 다음 SVM을 생성하기 위한 입력으로 사용합니다.
+
[NOTE]
====
SVM을 생성하는 동안 CIFS, NFS, FCP, iSCSI 등 LUN과 파일 공유를 프로비저닝하는 데 필요한 모든 프로토콜을 지원하는지 확인하세요.  SVM이 필요한 서비스를 지원하지 않으면 프로비저닝 워크플로가 실패할 수 있습니다.  각 유형의 워크로드에 대한 서비스도 SVM에서 활성화하는 것이 좋습니다.

====
+
[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
데이터센터
 a| 
우편
 a| 
`/datacenter/svm/svms`

|===
+
*샘플 cURL*

+
SVM 객체 세부 정보를 입력 매개변수로 입력합니다.

+
[listing]
----
curl -X POST "https://<hostname>/api/datacenter/svm/svms" -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: Basic <Base64EncodedCredentials>" "{ \"aggregates\": [ { \"_links\": {}, \"key\": \"1cd8a442-86d1,type=objecttype,uuid=1cd8a442-86d1-11e0-ae1c-9876567890123\",
\"name\": \"cluster2\", \"uuid\": \"02c9e252-41be-11e9-81d5-00a0986138f7\" } ],
\"cifs\": { \"ad_domain\": { \"fqdn\": \"string\", \"password\": \"string\",
\"user\": \"string\" }, \"enabled\": true, \"name\": \"CIFS1\" },
\"cluster\": { \"key\": \"1cd8a442-86d1-11e0-ae1c-123478563412,type=object type,uuid=1cd8a442-86d1-11e0-ae1c-9876567890123\" },
\"dns\": { \"domains\": [ \"example.com\", \"example2.example3.com\" ],
\"servers\": [ \"10.224.65.20\", \"2001:db08:a0b:12f0::1\" ] },
\"fcp\": { \"enabled\": true }, \"ip_interface\": [ { \"enabled\": true,
\"ip\": { \"address\": \"10.10.10.7\", \"netmask\": \"24\" },
\"location\": { \"home_node\": { \"name\": \"node1\" } }, \"name\":
\"dataLif1\" } ], \"ipspace\": { \"name\": \"exchange\" },
\"iscsi\": { \"enabled\": true }, \"language\": \"c.utf_8\",
\"ldap\": { \"ad_domain\": \"string\", \"base_dn\": \"string\",
\"bind_dn\": \"string\", \"enabled\": true, \"servers\": [ \"string\" ] },
\"name\": \"svm1\", \"nfs\": { \"enabled\": true },
\"nis\": { \"domain\": \"string\", \"enabled\": true,
\"servers\": [ \"string\" ] }, \"nvme\": { \"enabled\": true },
\"routes\": [ { \"destination\": { \"address\": \"10.10.10.7\",
\"netmask\": \"24\" }, \"gateway\": \"string\" } ],
\"snapshot_policy\": { \"name\": \"default\" },
\"state\": \"running\", \"subtype\": \"default\"}"
----
+
JSON 출력에는 생성한 SVM을 확인하는 데 사용할 수 있는 Job 개체 키가 표시됩니다.

. 쿼리에 대한 작업 객체 키를 사용하여 SVM 생성을 확인합니다.  SVM이 성공적으로 생성되면 SVM 키가 응답으로 반환됩니다.
+
[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
관리 서버
 a| 
얻다
 a| 
`/management-server/jobs/\{key}`

|===

