---
permalink: api-automation/concept_manage_lun.html 
sidebar: sidebar 
keywords: manage, lun 
summary: /storage-provider/luns API를 사용하면 데이터 센터 환경의 LUN을 보고, 추가하고, 수정하고, 삭제할 수 있습니다. 
---
= API를 사용하여 LUN 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `/storage-provider/luns` 데이터 센터 환경에서 LUN을 보고, 추가하고, 수정하고, 삭제하기 위한 API입니다.

LUN을 프로비저닝하기 전에 SVM이 생성되었고 지원되는 프로토콜로 프로비저닝되었는지 확인하세요.  프로비저닝 중에 성능 서비스 수준(PSL)이나 스토리지 효율성 정책(SEP)을 할당하는 경우 LUN을 생성하기 전에 PSL이나 SEP를 생성해야 합니다.



== LUN 보기

다음 방법을 사용하여 Unified Manager 환경에서 LUN을 볼 수 있습니다.  Active IQ Unified Manager 에서 ONTAP 클러스터를 데이터 소스로 추가하면 해당 클러스터의 스토리지 워크로드가 Unified Manager 인스턴스에 자동으로 추가됩니다.  이 API는 Unified Manager 인스턴스에 자동 및 수동으로 추가된 모든 LUN을 검색합니다.  LUN 키로 이 API를 실행하면 특정 LUN의 세부 정보를 볼 수 있습니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
얻다
 a| 
`/storage-provider/luns`

`/storage-provider/luns/\{key}`

|===


== LUN 추가

다음 방법을 사용하여 SVM에 LUN을 추가할 수 있습니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
우편
 a| 
`/storage-provider/luns`

|===
[NOTE]
====
cURL 요청에서 입력에 선택적 매개변수 volume_name_tag에 대한 값을 제공하면 LUN을 생성하는 동안 볼륨의 이름을 지정할 때 해당 값이 사용됩니다.  이 태그를 사용하면 볼륨을 쉽게 검색할 수 있습니다.  요청 시 볼륨 키를 제공하면 태그 지정이 건너뜁니다.

====


== LUN 삭제

다음 방법을 사용하여 특정 LUN을 삭제할 수 있습니다.  특정 LUN을 삭제하려면 LUN 키를 제공해야 합니다.

[NOTE]
====
ONTAP 에서 볼륨을 생성한 다음 Unified Manager를 통해 해당 볼륨에 LUN을 프로비저닝한 경우 이 API를 사용하여 모든 LUN을 삭제하면 ONTAP 클러스터에서도 볼륨이 삭제됩니다.

====
[cols="3*"]
|===
| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
삭제
 a| 
`/storage-provider/luns/\{key}`

|===


== LUN 수정

다음 방법을 사용하여 LUN을 수정하고 속성을 업데이트할 수 있습니다.  특정 LUN을 수정하려면 LUN 키를 제공해야 합니다.  업데이트하려는 LUN 속성과 해당 값도 입력해야 합니다.  이 API를 사용하여 LUN 어레이를 업데이트하려면 "API 사용에 대한 권장 사항"의 권장 사항을 검토해야 합니다.

[NOTE]
====
이 API를 한 번 호출하면 속성을 하나만 업데이트할 수 있습니다.  여러 개의 업데이트가 있는 경우 이 API를 여러 번 실행해야 합니다.

====
|===


| 범주 | HTTP 동사 | 길 


 a| 
스토리지 제공자
 a| 
반점
 a| 
`/storage-provider/luns/\{key}`

|===