---
permalink: api-automation/reference_authentication_errors.html 
sidebar: sidebar 
keywords: http, status, code, active iq, unified manager 
summary: API를 실행하거나 문제를 해결하는 동안 Active IQ Unified Manager API에서 사용되는 다양한 HTTP 상태 코드와 오류 코드를 알고 있어야 합니다. 
---
= Active IQ Unified Manager 에서 사용되는 HTTP 상태 코드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
API를 실행하거나 문제를 해결하는 동안 Active IQ Unified Manager API에서 사용되는 다양한 HTTP 상태 코드와 오류 코드를 알고 있어야 합니다.

다음 표에는 인증과 관련된 오류 코드가 나열되어 있습니다.

[cols="3*"]
|===
| HTTP 상태 코드 | 상태 코드 제목 | 설명 


 a| 
200
 a| 
OK
 a| 
동기 API 호출이 성공적으로 실행되면 반환됩니다.



 a| 
201
 a| 
생성됨
 a| 
Active Directory 구성과 같은 동기 호출을 통한 새로운 리소스 생성.



 a| 
202
 a| 
수락됨
 a| 
LUN 및 파일 공유 생성 등의 프로비저닝 기능에 대한 비동기 호출이 성공적으로 실행되면 반환됩니다.



 a| 
400
 a| 
잘못된 요청입니다
 a| 
입력 검증에 실패했음을 나타냅니다.  사용자는 요청 본문에 유효한 키를 입력하는 등 입력 내용을 수정해야 합니다.



 a| 
401
 a| 
허가되지 않은 요청
 a| 
해당 리소스를 볼 권한이 없습니다/권한 없음.



 a| 
403
 a| 
금지된 요청
 a| 
귀하가 접근하려고 하는 리소스에 접근하는 것은 금지되어 있습니다.



 a| 
404
 a| 
리소스를 찾을 수 없습니다
 a| 
접근하려고 했던 리소스를 찾을 수 없습니다.



 a| 
405
 a| 
허용되지 않는 메서드
 a| 
허용되지 않는 메서드입니다.



 a| 
429
 a| 
요청이 너무 많습니다
 a| 
사용자가 특정 시간 내에 너무 많은 요청을 보냈을 때 반환됩니다.



 a| 
500
 a| 
내부 서버 오류
 a| 
내부 서버 오류입니다.  서버로부터 응답을 받지 못했습니다.  이 내부 서버 오류는 영구적일 수도 있고 그렇지 않을 수도 있습니다.  예를 들어, 다음을 실행하는 경우 `GET` 또는 `GET ALL` 작업을 수행하다가 이 오류가 발생하면 최소 5번 이상 이 작업을 반복하는 것이 좋습니다.  영구적인 오류인 경우 반환되는 상태 코드는 계속 500입니다.  작업이 성공하면 반환되는 상태 코드는 200입니다.

|===