---
permalink: api-automation/reference_recommendations_to_use_um_apis.html 
sidebar: sidebar 
keywords: recommendations, apis, active iq, unified, manager 
summary: Active IQ Unified Manager 에서 API를 사용할 때는 특정 권장 사례를 따라야 합니다. 
---
= Active IQ Unified Manager 용 API 사용에 대한 권장 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager 에서 API를 사용할 때는 특정 권장 사례를 따라야 합니다.

* 유효한 실행을 위해서는 모든 응답 콘텐츠 유형이 다음 형식이어야 합니다.
+
[listing]
----
application/json
----
* API 버전 번호는 제품 버전 번호와 관련이 없습니다.  Unified Manager 인스턴스에 사용 가능한 최신 버전의 API를 사용해야 합니다.  Unified Manager API 버전에 대한 자세한 내용은 " Active IQ Unified Manager 의 REST API 버전 관리" 섹션을 참조하세요.
* Unified Manager API를 사용하여 배열 값을 업데이트하는 경우 값의 전체 문자열을 업데이트해야 합니다.  배열에 값을 추가할 수 없습니다.  기존 배열만 교체할 수 있습니다.
* 예를 들어 메트릭 API의 IOPS 및 성능과 같이 이중 값을 제외한 모든 쿼리 매개변수에 파이프(|) 및 와일드카드(+*+)와 같은 필터 연산자를 사용할 수 있습니다.
* 필터 연산자 와일드카드(+*+)와 파이프(|)를 조합하여 사용하여 객체를 쿼리하지 마세요.  잘못된 개수의 객체를 검색할 수도 있습니다.
* 필터에 값을 사용할 때 값에 아무것도 포함되지 않았는지 확인하십시오. `?` 성격.  이는 SQL 주입의 위험을 완화하기 위한 것입니다.
* 참고 사항 `GET` (모든) API에 대한 요청은 최대 1000개의 레코드를 반환합니다.  쿼리를 설정하여 실행하더라도 `max_records` 매개변수에 1000보다 큰 값을 입력하면 1000개의 레코드만 반환됩니다.
* 관리 기능을 수행하려면 Unified Manager UI를 사용하는 것이 좋습니다.

