---
permalink: reporting/concept_unified_manager_databases_accessible_for_reporting.html 
sidebar: sidebar 
keywords: unified manager, databases, access, custom, reporting 
summary: Unified Manager는 모니터링하는 클러스터의 데이터를 저장하기 위해 MySQL 데이터베이스를 사용합니다.  데이터는 MySQL 데이터베이스의 다양한 스키마에 저장됩니다. 
---
= 사용자 정의 보고를 위해 접근 가능한 Unified Manager 데이터베이스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 모니터링하는 클러스터의 데이터를 저장하기 위해 MySQL 데이터베이스를 사용합니다.  데이터는 MySQL 데이터베이스의 다양한 스키마에 저장됩니다.

다음 데이터베이스의 모든 테이블 데이터를 사용할 수 있습니다.

[cols="2*"]
|===
| 데이터 베이스 | 설명 


 a| 
넷앱_모델
 a| 
ONTAP 컨트롤러의 객체에 대한 데이터입니다.



 a| 
넷앱_모델_뷰
 a| 
보고서 도구 사용에 적합한 ONTAP 컨트롤러의 객체에 대한 데이터입니다.



 a| 
넷앱_성능
 a| 
클러스터별 성능 카운터.



 a| 
오컴
 a| 
UI 필터링, 정렬 및 일부 파생 필드의 계산을 지원하기 위한 Unified Manager 애플리케이션 데이터 및 정보입니다.



 a| 
ocum_report
 a| 
재고 구성 및 용량 관련 정보에 대한 데이터입니다.



 a| 
오컴_리포트_버트
 a| 
보고서 도구 사용에 적합한 재고 구성 및 용량 관련 데이터에 대한 뷰입니다.



 a| 
오피엠
 a| 
성능 구성 설정 및 임계값 정보.



 a| 
스케일모니터
 a| 
Unified Manager 애플리케이션 상태 및 성능 문제에 대한 데이터입니다.



 a| 
vmware_model
 a| 
NetApp 스토리지에 호스팅된 데이터스토어에 대한 VMware 개체 데이터입니다.



 a| 
vmware_model_view
 a| 
NetApp 스토리지에 호스팅된 데이터 저장소의 VMware 개체 데이터에 대한 뷰로, 보고서 도구 사용에 적합합니다.



 a| 
vmware_성능
 a| 
NetApp 스토리지에 호스팅된 데이터스토어에 대한 VMware 성능 카운터 데이터입니다.

|===
보고 사용자(보고서 스키마 역할이 있는 데이터베이스 사용자)는 이러한 테이블의 데이터에 액세스할 수 있습니다.  이 사용자는 Unified Manager 데이터베이스에서 직접 보고 및 기타 데이터베이스 보기에 대한 읽기 전용 액세스 권한을 갖습니다.  이 사용자는 사용자 데이터나 클러스터 자격 증명 정보가 포함된 테이블에 액세스할 수 있는 권한이 없습니다.
