---
permalink: reporting/reference_reporting_limitations.html 
sidebar: sidebar 
keywords: reporting, limitations 
summary: 새로운 Active IQ Unified Manager 보고 기능에는 알아야 할 몇 가지 제한 사항이 있습니다. 
---
= 보고 제한 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새로운 Active IQ Unified Manager 보고 기능에는 알아야 할 몇 가지 제한 사항이 있습니다.



== 이전 버전의 Unified Manager에서 작성된 기존 보고서

Unified Manager 9.5 및 이전 릴리스에서는 .rptdesign 파일로 생성 및 가져온 기존 보고서의 일정과 수신자만 편집할 수 있습니다.  Unified Manager 9.5 이하 버전에서 제공된 표준 보고서를 사용자 지정한 경우, 해당 사용자 지정 보고서는 새 보고 도구로 가져올 수 없습니다.

.rptdesign 파일에서 가져온 기존 보고서를 편집해야 하는 경우 다음 중 하나를 수행하여 가져온 보고서를 제거하세요.

* 새 뷰를 만들고 해당 뷰에서 보고서를 예약합니다(권장)
* 보고서 위에 마우스를 올려놓고 SQL을 복사한 다음 외부 도구를 사용하여 데이터를 가져옵니다.


기본 보기는 사용자 정의 없이도 보고서로 생성될 수 있습니다.  새로운 보고 솔루션을 사용하면 사용자 정의 보고서를 다시 만들 수 있습니다.



== 일정 및 보고서 관계

저장된 각 보고서에 대해 수신자를 원하는 대로 조합하여 다양한 일정을 만들 수 있습니다.  하지만 여러 보고서에 대해 일정을 재사용할 수는 없습니다.



== 신고 보호

적절한 권한이 있는 모든 사용자는 보고서를 편집하거나 삭제할 수 있습니다.  다른 사용자가 저장된 보기나 일정을 삭제하거나 변경하는 것을 막을 방법은 없습니다.



== 이벤트 보고서

이벤트 보기를 사용자 지정하고 결과 보고서를 CSV 형식으로 다운로드할 수는 있지만, 반복 이벤트 보고서를 생성하고 배포하도록 예약할 수는 없습니다.



== 보고서 첨부 파일

이메일 본문에 보고서를 넣을 수 없습니다.  대신 보고서는 PDF, Excel 또는 CSV 첨부 파일로만 전송됩니다.
