---
permalink: performance-checker/concept_performance_threshold_policies_when_object_is_moved.html 
sidebar: sidebar 
keywords: happens, performance, threshold, policies, object, moved 
summary: 성능 임계값 정책은 스토리지 개체에 할당되므로 개체를 이동하면 이동이 완료된 후에도 할당된 모든 임계값 정책이 해당 개체에 연결된 상태로 유지됩니다.  예를 들어, 볼륨이나 LUN을 다른 집계로 이동하는 경우 임계값 정책은 새 집계의 볼륨이나 LUN에 대해 계속 활성화됩니다. 
---
= 객체가 이동되면 성능 임계값 정책은 어떻게 되나요?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능 임계값 정책은 스토리지 개체에 할당되므로 개체를 이동하면 이동이 완료된 후에도 할당된 모든 임계값 정책이 해당 개체에 연결된 상태로 유지됩니다.  예를 들어, 볼륨이나 LUN을 다른 집계로 이동하는 경우 임계값 정책은 새 집계의 볼륨이나 LUN에 대해 계속 활성화됩니다.

임계값 정책(조합 정책)에 대한 보조 카운터 조건이 있는 경우(예: 추가 조건이 집계 또는 노드에 할당된 경우) 보조 카운터 조건은 볼륨 또는 LUN이 이동된 새 집계 또는 노드에 적용됩니다.

변경된 임계값 정책을 사용하는 개체에 대해 새로운 활성 이벤트가 존재하는 경우 해당 이벤트는 더 이상 사용되지 않음으로 표시되고 임계값 정책은 새로 정의된 임계값 정책으로 카운터 모니터링을 시작합니다.

볼륨 이동 작업으로 인해 ONTAP 정보 변경 이벤트를 보냅니다.  이동 작업이 완료된 시간을 나타내기 위해 성능 탐색기 페이지와 워크로드 분석 페이지의 이벤트 타임라인에 변경 이벤트 아이콘이 나타납니다.

[NOTE]
====
객체를 다른 클러스터로 이동하면 사용자 정의 임계값 정책이 객체에서 제거됩니다.  필요한 경우 이동 작업이 완료된 후 개체에 임계값 정책을 할당해야 합니다.  그러나 동적 및 시스템 정의 임계값 정책은 개체가 새 클러스터로 이동된 후 해당 개체에 자동으로 적용됩니다.

====


== HA 인수 및 반환 중 임계값 정책 기능

고가용성(HA) 구성에서 인수 또는 반환 작업이 발생하는 경우 한 노드에서 다른 노드로 이동된 개체는 수동 이동 작업과 동일한 방식으로 임계값 정책을 유지합니다.  Unified Manager는 15분마다 클러스터 구성 변경 사항을 확인하므로 새 노드로의 전환으로 인한 영향은 클러스터 구성의 다음 폴링 때까지 식별되지 않습니다.

[NOTE]
====
15분의 구성 변경 수집 기간 내에 인수 및 반환 작업이 모두 발생하는 경우 성능 통계가 한 노드에서 다른 노드로 이동하지 않을 수 있습니다.

====


== 집계 이전 중 임계값 정책 기능

다음을 사용하여 한 노드에서 다른 노드로 집계를 이동하는 경우 `aggregate relocation start` 명령을 실행하면 모든 개체에 단일 및 조합 임계값 정책이 모두 유지되고 임계값 정책의 노드 부분이 새 노드에 적용됩니다.



== MetroCluster 전환 중 임계값 정책 기능

MetroCluster 구성에서 한 클러스터에서 다른 클러스터로 이동하는 개체는 사용자 정의 임계값 정책 설정을 유지하지 않습니다.  필요한 경우 파트너 클러스터로 이동된 볼륨과 LUN에 임계값 정책을 적용할 수 있습니다.  객체가 원래 클러스터로 다시 이동한 후에는 사용자가 정의한 임계값 정책이 자동으로 다시 적용됩니다.

자세한 내용은 다음을 참조하세요.link:../storage-mgmt/concept_volume_behavior_during_switchover_and_switchback.html["스위치오버 및 스위치백 중 볼륨 동작"] .
