---
permalink: performance-checker/concept_set_up_graphite_to_receive_performance_data.html 
sidebar: sidebar 
keywords: setting, graphite, receive, performance, data, unified manager 
summary: Graphite는 컴퓨터 시스템의 성능 데이터를 수집하고 그래프로 표현하는 개방형 소프트웨어 도구입니다.  Unified Manager에서 통계 데이터를 받으려면 Graphite 서버와 소프트웨어를 올바르게 구성해야 합니다. 
---
= Unified Manager에서 성능 데이터를 수신하도록 Graphite를 설정합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Graphite는 컴퓨터 시스템의 성능 데이터를 수집하고 그래프로 표현하는 개방형 소프트웨어 도구입니다.  Unified Manager에서 통계 데이터를 받으려면 Graphite 서버와 소프트웨어를 올바르게 구성해야 합니다.

NetApp Graphite나 다른 타사 도구의 특정 버전을 테스트하거나 검증하지 않습니다.


NOTE: Graphite 서버는 Unified Manager에서 볼륨에 대한 성능 데이터를 받지 않습니다.

설치 지침에 따라 Graphite를 설치한 후 Unified Manager에서 통계 데이터 전송을 지원하려면 다음과 같이 변경해야 합니다.

* 에서 `/opt/graphite/conf/carbon.conf` 파일, 분당 Graphite 서버에서 생성할 수 있는 최대 파일 수는 _200_으로 설정해야 합니다.(`*MAX_CREATES_PER_MINUTE = 200*` ).
+
구성에 포함된 클러스터 수와 전송하기로 선택한 통계 개체에 따라 처음에 만들어야 할 새 파일이 수천 개일 수 있습니다.  분당 200개의 파일을 처리하는 경우 모든 메트릭 파일이 처음 생성되기까지 15분 이상 걸릴 수 있습니다.  모든 고유한 메트릭 파일이 생성된 후에는 이 매개변수가 더 이상 관련이 없습니다.

* IPv6 주소를 사용하여 배포된 서버에서 Graphite를 실행하는 경우 LINE_RECEIVER_INTERFACE의 값은 `/opt/graphite/conf/carbon.conf` 파일을 "`0.0.0.0`"에서 "`::`"로 변경해야 합니다.(`*LINE_RECEIVER_INTERFACE = ::*` )
* 에서 `/opt/graphite/conf/storage-schemas.conf` 파일, `retentions` 매개변수를 사용하여 빈도를 5분으로 설정하고 보존 기간을 환경에 적합한 일수로 설정해야 합니다.
+
보존 기간은 환경이 허용하는 한 길게 설정할 수 있지만, 적어도 하나의 보존 설정에 대해 빈도 값은 5분으로 설정해야 합니다.  다음 예에서는 Unified Manager에 대한 섹션이 다음을 사용하여 정의됩니다. `pattern` 매개변수와 값은 초기 빈도를 5분으로, 보존 기간을 100일로 설정합니다. `*[OPM]*`

+
`*pattern = ^netapp-performance\..*`

+
`*retentions = 5m:100d*`

+
[NOTE]
====
기본 공급업체 태그가 "`netapp-performance`"에서 다른 것으로 변경된 경우 해당 변경 사항은 다음에 반영되어야 합니다. `pattern` 매개변수도 마찬가지입니다.

====


[NOTE]
====
Unified Manager 서버가 성능 데이터를 보내려고 할 때 Graphite 서버를 사용할 수 없는 경우 데이터가 전송되지 않고 수집된 데이터에 공백이 발생합니다.

====