---
permalink: performance-checker/concept_cluster_components_and_why_they_can_be_in_contention.html 
sidebar: sidebar 
keywords: cluster, components, why, contention 
summary: '클러스터 구성 요소가 경합에 들어가면 클러스터 성능 문제를 식별할 수 있습니다.  해당 구성 요소를 사용하는 워크로드의 성능이 저하되고 클라이언트 요청에 대한 응답 시간(대기 시간)이 늘어나 Unified Manager에서 이벤트가 발생합니다.' 
---
= 클러스터 구성 요소와 이들이 경쟁에 참여할 수 있는 이유
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 구성 요소가 경합에 들어가면 클러스터 성능 문제를 식별할 수 있습니다.  해당 구성 요소를 사용하는 워크로드의 성능이 저하되고 클라이언트 요청에 대한 응답 시간(대기 시간)이 늘어나 Unified Manager에서 이벤트가 발생합니다.

경쟁 상태에 있는 구성 요소는 최적의 수준에서 성능을 발휘할 수 없습니다.  성능이 저하되었고, _피해자_라고 불리는 다른 클러스터 구성 요소와 워크로드의 성능으로 인해 지연 시간이 증가했을 수 있습니다.  구성 요소를 경쟁에서 벗어나게 하려면 작업 부하를 줄이거나 더 많은 작업을 처리할 수 있는 능력을 높여야 합니다. 이렇게 하면 성능이 정상 수준으로 돌아갈 수 있습니다.  Unified Manager는 5분 간격으로 워크로드 성능을 수집하고 분석하므로 클러스터 구성 요소가 지속적으로 과도하게 사용되는 경우에만 감지합니다.  5분 간격 내에 짧은 시간 동안만 지속되는 과도한 사용의 일시적인 급증은 감지되지 않습니다.

예를 들어, 스토리지 집계는 하나 이상의 워크로드가 I/O 요청을 처리하기 위해 경쟁하고 있기 때문에 경합을 겪을 수 있습니다.  전체적으로 다른 작업 부하가 영향을 받아 성능이 저하될 수 있습니다.  집계된 활동량을 줄이려면 여러 가지 조치를 취할 수 있습니다. 예를 들어, 하나 이상의 작업 부하를 덜 바쁜 집계나 노드로 옮겨 현재 집계의 전반적인 작업 부하 수요를 줄이는 것입니다.  QoS 정책 그룹의 경우 처리량 한도를 조정하거나 작업 부하를 다른 정책 그룹으로 이동하여 작업 부하가 더 이상 제한되지 않도록 할 수 있습니다.

Unified Manager는 다음 클러스터 구성 요소를 모니터링하여 해당 구성 요소가 경쟁 상태에 있을 때 경고합니다.

* *회로망*
+
클러스터의 외부 네트워킹 프로토콜에 의한 I/O 요청의 대기 시간을 나타냅니다.  대기 시간이란 클러스터가 I/O 요청에 응답하기 전에 "전송 준비" 트랜잭션이 완료될 때까지 기다리는 시간입니다.  네트워크 구성 요소가 경합 중이면 프로토콜 계층에서 대기 시간이 길어져 하나 이상의 작업 부하 지연에 영향을 미치고 있음을 의미합니다.

* *네트워크 처리*
+
프로토콜 계층과 클러스터 간의 I/O 처리와 관련된 클러스터의 소프트웨어 구성 요소를 나타냅니다.  이벤트가 감지된 이후 네트워크 처리를 담당하는 노드가 변경되었을 수 있습니다.  네트워크 처리 구성 요소가 경합 중이면 네트워크 처리 노드의 높은 활용도가 하나 이상의 작업 부하의 지연 시간에 영향을 미치고 있음을 의미합니다.

+
액티브-액티브 구성에서 All SAN 어레이 클러스터를 사용하는 경우 두 노드 모두에 대한 네트워크 처리 지연 값이 표시되므로 노드가 부하를 동등하게 공유하는지 확인할 수 있습니다.

* *QoS 제한 최대*
+
작업 부하에 할당된 스토리지 서비스 품질(QoS) 정책 그룹의 처리량 최대(피크) 설정을 나타냅니다.  정책 그룹 구성 요소가 경합 중이면 정책 그룹의 모든 작업 부하가 설정된 처리량 한도로 조절되고 있음을 의미하며, 이는 해당 작업 부하 중 하나 이상의 대기 시간에 영향을 미칩니다.

* *QoS 제한 최소값*
+
다른 워크로드에 할당된 QoS 처리량 최소(예상) 설정으로 인해 발생하는 워크로드 지연을 나타냅니다.  특정 작업 부하에 설정된 QoS 최소값이 약속된 처리량을 보장하기 위해 대부분의 대역폭을 사용하는 경우, 다른 작업 부하가 제한되고 지연 시간이 더 길어집니다.

* *클러스터 상호 연결*
+
클러스터된 노드가 물리적으로 연결된 케이블과 어댑터를 나타냅니다.  클러스터 상호 연결 구성 요소가 경합 중이면 클러스터 상호 연결에서 I/O 요청에 대한 대기 시간이 길어져 하나 이상의 작업 부하 대기 시간에 영향을 미치고 있음을 의미합니다.

* * Data Processing*
+
클러스터와 작업 부하가 포함된 스토리지 집계 간의 I/O 처리와 관련된 클러스터의 소프트웨어 구성 요소를 나타냅니다.  이벤트가 감지된 이후 데이터 처리를 담당하는 노드가 변경되었을 수 있습니다.  데이터 처리 구성 요소가 경합 중이라는 것은 데이터 처리 노드의 높은 활용도가 하나 이상의 워크로드의 대기 시간에 영향을 미치고 있음을 의미합니다.

* *볼륨 활성화*
+
모든 활성 볼륨의 사용량을 추적하는 프로세스를 나타냅니다.  1000개가 넘는 볼륨이 활성화된 대규모 환경에서 이 프로세스는 노드를 통해 동시에 리소스에 액세스해야 하는 중요 볼륨의 수를 추적합니다.  동시 활성 볼륨 수가 권장되는 최대 임계값을 초과하면 일부 비중요 볼륨에서 여기에 명시된 대로 지연이 발생합니다.

* * MetroCluster 리소스*
+
MetroCluster 구성에서 클러스터 간에 데이터를 미러링하는 데 사용되는 NVRAM 및 ISL(스위치 간 링크)을 포함한 MetroCluster 리소스를 나타냅니다.  MetroCluster 구성 요소가 경합 중이면 로컬 클러스터의 작업 부하에서 높은 쓰기 처리량이 발생하거나 링크 상태 문제로 인해 로컬 클러스터에서 하나 이상의 작업 부하의 대기 시간이 영향을 받고 있음을 의미합니다.  클러스터가 MetroCluster 구성에 없으면 이 아이콘이 표시되지 않습니다.

* *집계 또는 SSD 집계 작업*
+
워크로드가 실행되는 스토리지 집계를 나타냅니다.  집계 구성 요소가 경합 중이면 집계의 높은 활용도가 하나 이상의 워크로드의 대기 시간에 영향을 미치고 있음을 의미합니다.  집계는 모든 HDD로 구성되거나 HDD와 SSD의 혼합(Flash Pool 집계), 또는 HDD와 클라우드 계층의 혼합( FabricPool 집계)으로 구성됩니다.  "SSD 집계"는 모든 SSD(올플래시 집계)로 구성되거나 SSD와 클라우드 계층( FabricPool 집계)의 혼합으로 구성됩니다.

* *클라우드 지연 시간*
+
클러스터와 사용자 데이터가 저장된 클라우드 계층 간의 I/O 처리와 관련된 클러스터의 소프트웨어 구성 요소를 나타냅니다.  클라우드 지연 시간 구성 요소가 경합되는 경우 클라우드 계층에서 호스팅되는 볼륨에서 많은 양의 읽기가 하나 이상의 워크로드의 지연 시간에 영향을 미치고 있음을 의미합니다.

* * SnapMirror 동기화*
+
SnapMirror 동기 관계에서 기본 볼륨에서 보조 볼륨으로 사용자 데이터를 복제하는 데 관련된 클러스터의 소프트웨어 구성 요소를 나타냅니다.  동기화 SnapMirror 구성 요소가 경합 중이면 SnapMirror 동기 작업의 활동이 하나 이상의 워크로드의 대기 시간에 영향을 미치고 있음을 의미합니다.


