---
permalink: performance-checker/concept_options_for_improving_workload_performance_from_client.html 
sidebar: sidebar 
keywords: options, improving, workload, performance, client-side 
summary: 성능 이벤트에 관련된 볼륨에 I/O를 보내는 애플리케이션이나 데이터베이스와 같은 클라이언트 작업 부하를 확인하여 클라이언트 측 변경으로 해당 이벤트가 수정될 수 있는지 확인할 수 있습니다. 
---
= 클라이언트 측에서 작업 부하 성능을 개선하기 위한 옵션
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능 이벤트에 관련된 볼륨에 I/O를 보내는 애플리케이션이나 데이터베이스와 같은 클라이언트 작업 부하를 확인하여 클라이언트 측 변경으로 해당 이벤트가 수정될 수 있는지 확인할 수 있습니다.

클러스터의 볼륨에 연결된 클라이언트가 I/O 요청을 늘리면 클러스터는 수요를 충족하기 위해 더 열심히 작동해야 합니다.  클러스터의 특정 볼륨에 대해 많은 I/O 요청을 하는 클라이언트가 누구인지 알고 있다면 볼륨에 액세스하는 클라이언트 수를 조정하거나 볼륨에 대한 I/O 양을 줄여 클러스터 성능을 개선할 수 있습니다.  볼륨이 속한 QoS 정책 그룹에 제한을 적용하거나 늘릴 수도 있습니다.

클라이언트와 해당 애플리케이션을 조사하여 클라이언트가 평소보다 많은 I/O를 보내고 있는지 확인할 수 있으며, 이로 인해 클러스터 구성 요소에서 경합이 발생할 수 있습니다.  이벤트 세부 정보 페이지의 시스템 진단 섹션에는 경합 중인 구성 요소를 사용하는 상위 볼륨 워크로드가 표시됩니다.  특정 볼륨에 어떤 클라이언트가 액세스하는지 알고 있다면 해당 클라이언트로 가서 클라이언트 하드웨어나 애플리케이션이 예상대로 작동하지 않는지, 아니면 평소보다 많은 작업을 수행하고 있는지 확인할 수 있습니다.

MetroCluster 구성에서는 로컬 클러스터의 볼륨에 대한 쓰기 요청이 원격 클러스터의 볼륨으로 미러링됩니다.  로컬 클러스터의 소스 볼륨을 원격 클러스터의 대상 볼륨과 동기화하면 MetroCluster 구성에서 두 클러스터의 수요도 증가할 수 있습니다.  이러한 미러링된 볼륨에 대한 쓰기 요청을 줄이면 클러스터가 수행하는 동기화 작업이 줄어들어 다른 작업 부하에 미치는 성능 영향이 줄어듭니다.
