---
permalink: performance-checker/concept_what_expected_range_of_performance_is.html 
sidebar: sidebar 
keywords: expected, range, performance, latency, forecast, formed 
summary: 지연 시간 예측은 특정 시간에 상한 및 하한 성능 값이 어떻게 될 것인지에 대한 예측입니다.  작업 지연 시간의 경우 상위 값이 성능 임계값을 형성합니다.  실제 값이 성능 임계값을 넘으면 Unified Manager가 동적 성능 이벤트를 트리거합니다. 
---
= 기대되는 성능 범위는 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
지연 시간 예측은 특정 시간에 상한 및 하한 성능 값이 어떻게 될 것인지에 대한 예측입니다.  작업 지연 시간의 경우 상위 값이 성능 임계값을 형성합니다.  실제 값이 성능 임계값을 넘으면 Unified Manager가 동적 성능 이벤트를 트리거합니다.

예를 들어, 정규 업무 시간인 오전 9시에서 오후 5시 사이에 대부분의 직원은 오전 9시에서 오전 10시 30분 사이에 이메일을 확인합니다. 이 시간 동안 이메일 서버에 대한 수요가 증가하면 백엔드 스토리지의 작업 부하 활동이 증가합니다.  직원들은 이메일 클라이언트의 응답 속도가 느리다고 느낄 수도 있습니다.

오후 12시부터 오후 1시까지의 점심시간과 오후 5시 이후 퇴근 시간에는 대부분 직원이 컴퓨터에서 멀어질 가능성이 높습니다.  이메일 서버에 대한 수요는 일반적으로 감소하며, 이에 따라 백엔드 저장소에 대한 수요도 감소합니다.  또는 오후 5시 이후에 시작되어 백엔드 스토리지의 활동을 증가시키는 스토리지 백업이나 바이러스 검사와 같은 예정된 작업 부하 작업이 있을 수 있습니다.

며칠 동안 작업 부하 활동의 증가와 감소에 따라 활동의 예상 범위(대기 시간 예측)가 결정되며, 작업 부하에 대한 상한과 하한이 결정됩니다.  객체의 실제 작업 부하 활동이 상한 또는 하한 경계를 벗어나고 일정 기간 동안 경계 밖에 머무르는 경우, 해당 객체가 과도하게 사용되거나 충분히 사용되지 않고 있음을 나타낼 수 있습니다.



[[how-the-latency-forecast-is-formed]]
== 지연 예측은 어떻게 형성되는가

Unified Manager는 분석을 시작하고 I/O 응답 시간에 대한 지연 시간 예측을 GUI에 표시하기 전에 최소 3일 분의 작업 부하 활동을 수집해야 합니다.  필요한 최소 데이터 수집에는 작업 부하 활동으로 인해 발생하는 모든 변경 사항이 반영되지 않습니다.  Unified Manager는 처음 3일간의 활동을 수집한 후, 24시간마다 오전 12시에 대기 시간 예측을 조정하여 작업 부하 활동의 변화를 반영하고 더욱 정확한 동적 성능 임계값을 설정합니다.

[NOTE]
====
일광 절약 시간제(DST)는 시스템 시간을 변경하는데, 이로 인해 모니터링되는 작업 부하에 대한 성능 통계의 지연 시간 예측이 변경됩니다.  Unified Manager는 지연 시간 예측을 즉시 수정하기 시작하며, 완료하는 데 약 15일이 소요됩니다.  이 기간 동안 Unified Manager를 계속 사용할 수 있지만 Unified Manager는 지연 시간 예측을 사용하여 동적 이벤트를 감지하므로 일부 이벤트가 정확하지 않을 수 있습니다.  시간 변경 이전에 감지된 이벤트는 영향을 받지 않습니다.

====