---
permalink: performance-checker/concept_understand_um_recommendations_to_tier_data_to_cloud.html 
sidebar: sidebar 
keywords: understand, unified manager, recommendations, tier, data, cloud 
summary: '성능: 모든 볼륨 보기는 비활성(콜드) 볼륨에 저장된 사용자 데이터의 크기와 관련된 정보를 표시합니다.  어떤 경우에는 Unified Manager가 FabricPool 지원 집계의 클라우드 계층(클라우드 공급자 또는 StorageGRID )에 비활성 데이터를 계층화하여 이점을 얻을 수 있는 특정 볼륨을 식별합니다.' 
---
= 클라우드로 데이터를 계층화하기 위한 Unified Manager 권장 사항을 이해합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능: 모든 볼륨 보기는 비활성(콜드) 볼륨에 저장된 사용자 데이터의 크기와 관련된 정보를 표시합니다.  어떤 경우에는 Unified Manager가 FabricPool 지원 집계의 클라우드 계층(클라우드 공급자 또는 StorageGRID )에 비활성 데이터를 계층화하여 이점을 얻을 수 있는 특정 볼륨을 식별합니다.

[NOTE]
====
FabricPool ONTAP 9.2에서 도입되었으므로 9.2 이전 버전의 ONTAP 소프트웨어를 사용하는 경우 Unified Manager의 데이터 계층화 권장 사항에 따라 ONTAP 소프트웨어를 업그레이드해야 합니다.  또한, `*auto*` ONTAP 9.4에서 계층화 정책이 도입되었습니다. `*all*` 계층화 정책은 ONTAP 9.6에서 도입되었으므로 자동 계층화 정책을 사용하는 것이 권장되는 경우 ONTAP 9.4 이상으로 업그레이드해야 합니다.

====
성능: 모든 볼륨 보기의 다음 세 필드는 비활성 데이터를 클라우드 계층으로 이동하여 스토리지 시스템의 디스크 활용도를 개선하고 성능 계층의 공간을 절약할 수 있는지 여부에 대한 정보를 제공합니다.

* *티어링 정책*
+
계층화 정책은 볼륨의 데이터가 성능 계층에 남아 있을지 아니면 일부 데이터가 성능 계층에서 클라우드 계층으로 이동될지 여부를 결정합니다.

+
이 필드의 값은 볼륨이 현재 FabricPool 집계에 상주하지 않더라도 볼륨에 설정된 계층화 정책을 나타냅니다.  계층화 정책은 볼륨이 FabricPool 집계에 있는 경우에만 적용됩니다.

* *콜드 데이터*
+
콜드 데이터는 비활성(콜드) 볼륨에 저장된 사용자 데이터의 크기를 표시합니다.

+
볼륨이 배포된 집계에 다음이 필요하기 때문에 ONTAP 9.4 이상 소프트웨어를 사용할 때에만 여기에 값이 표시됩니다. `*inactive data reporting parameter*` 로 설정 `*enabled*` 그리고 최소 냉각 일수 임계값이 충족되었는지(사용하는 볼륨의 경우) `*snapshot-only*` 또는 `*auto*` (티어링 정책).  그렇지 않으면 값은 "`N/A`"로 나열됩니다.

* *클라우드 추천*
+
볼륨의 데이터 활동에 대한 충분한 정보가 수집되면 Unified Manager는 더 이상 조치가 필요하지 않다고 판단하거나 비활성 데이터를 클라우드 계층으로 계층화하여 성능 계층의 공간을 절약할 수 있다고 판단할 수 있습니다.



[NOTE]
====
콜드 데이터 필드는 15분마다 업데이트되지만, 클라우드 권장 사항 필드는 볼륨에서 콜드 데이터 분석을 수행할 때 7일마다 업데이트됩니다.  따라서 정확한 콜드 데이터의 양은 필드마다 다를 수 있습니다.  클라우드 권장 사항 필드에는 분석이 실행된 날짜가 표시됩니다.

====
비활성 데이터 보고가 활성화되면 콜드 데이터 필드에 비활성 데이터의 정확한 양이 표시됩니다.  비활성 데이터 보고 기능이 없으면 Unified Manager는 성능 통계를 사용하여 볼륨에서 데이터가 비활성인지 확인합니다.  이 경우 비활성 데이터의 양은 콜드 데이터 필드에 표시되지 않지만, 클라우드 권장 사항을 보려면 *계층*이라는 단어 위에 커서를 올려 놓으면 표시됩니다.

표시되는 클라우드 권장 사항은 다음과 같습니다.

* *학습*.  추천을 하기에 충분한 데이터가 수집되지 않았습니다.
* *층*.  분석 결과, 볼륨에 비활성(콜드) 데이터가 포함되어 있으며 해당 데이터를 클라우드 계층으로 이동하도록 볼륨을 구성해야 하는 것으로 확인되었습니다.  어떤 경우에는 먼저 볼륨을 FabricPool 지원 집계로 이동해야 할 수도 있습니다.  볼륨이 이미 FabricPool 집계에 있는 다른 경우에는 계층화 정책만 변경하면 됩니다.
* *조치 없음*.  볼륨에 비활성 데이터가 거의 없거나, 볼륨이 이미 FabricPool 집계에서 "`auto`" 계층화 정책으로 설정되어 있거나, 볼륨이 데이터 보호 볼륨입니다.  이 값은 볼륨이 오프라인이거나 MetroCluster 구성에서 사용 중일 때도 표시됩니다.


볼륨을 이동하거나 볼륨 계층화 정책이나 비활성 데이터 집계 보고 설정을 변경하려면 ONTAP System Manager, ONTAP CLI 명령 또는 이러한 도구를 조합하여 사용합니다.

애플리케이션 관리자 또는 스토리지 관리자 역할로 Unified Manager에 로그인한 경우, *계층*이라는 단어 위에 커서를 올려 놓으면 클라우드 권장 사항에서 *볼륨 구성* 링크를 사용할 수 있습니다.  이 버튼을 클릭하면 시스템 관리자에서 볼륨 페이지가 열려 권장되는 변경 사항을 적용할 수 있습니다.
