---
permalink: performance-checker/concept_performance_monitor_of_metrocluster_configurations.html 
sidebar: sidebar 
keywords: performance, monitor, metrocluster, throughput 
summary: Unified Manager를 사용하면 MetroCluster 구성의 클러스터 간 쓰기 처리량을 모니터링하여 쓰기 처리량이 많은 작업 부하를 식별할 수 있습니다.  이러한 고성능 작업 부하로 인해 로컬 클러스터의 다른 볼륨에서 I/O 응답 시간이 길어지는 경우 Unified Manager는 성능 이벤트를 트리거하여 사용자에게 알립니다. 
---
= MetroCluster 구성의 성능 모니터링
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 사용하면 MetroCluster 구성의 클러스터 간 쓰기 처리량을 모니터링하여 쓰기 처리량이 많은 작업 부하를 식별할 수 있습니다.

이러한 고성능 작업 부하로 인해 로컬 클러스터의 다른 볼륨에서 I/O 응답 시간이 길어지는 경우 Unified Manager는 성능 이벤트를 트리거하여 사용자에게 알립니다.


NOTE: Unified Manager는 MetroCluster 구성의 클러스터를 개별 클러스터로 처리합니다.  파트너인 클러스터를 구별하지 않으며 각 클러스터의 쓰기 처리량을 상관시키지 않습니다.

MetroCluster 구성의 로컬 클러스터가 데이터를 파트너 클러스터로 미러링하면 데이터는 NVRAM 에 기록된 다음 ISL(스위치 간 링크)을 통해 원격 집계로 전송됩니다.  Unified Manager는 NVRAM 분석하여 높은 쓰기 처리량으로 인해 NVRAM 과도하게 사용하고 NVRAM 경합 상태에 빠지는 작업 부하를 식별합니다.

응답 시간의 편차가 성능 임계값을 초과하는 워크로드를 _희생자_라고 하며, NVRAM 에 대한 쓰기 처리량의 편차가 평소보다 높아서 경합이 발생하는 워크로드를 _괴롭힘_이라고 합니다.  쓰기 요청만 파트너 클러스터에 미러링되므로 Unified Manager는 읽기 처리량을 분석하지 않습니다.

다음 화면에서 해당 LUN과 볼륨의 작업 부하를 분석하여 MetroCluster 구성의 모든 클러스터의 처리량을 볼 수 있습니다.  클러스터별로 결과를 필터링할 수 있습니다.  왼쪽 탐색 창에서:

* *저장소 > 클러스터 > 성능: 모든 클러스터* 보기. 보다
* *저장소 > 볼륨 > 성능: 모든 볼륨* 보기.
* *저장소 > LUN > 성능: 모든 LUN* 보기.
* *작업 부하 분석 > 모든 작업 부하*


*관련 정보*

link:../performance-checker/reference_performance_event_analysis_and_notification.html["성능 이벤트 분석 및 알림"]

link:../performance-checker/concept_performance_incident_analysis_for_metrocluster_configuration.html["MetroCluster 구성에 대한 성능 이벤트 분석"]

link:../performance-checker/concept_roles_of_workloads_involved_in_performance_incident.html["성능 이벤트에 관련된 작업 부하의 역할"]

link:../performance-checker/task_identify_victim_workloads_involved_in_performance_event.html["성능 이벤트에 관련된 피해자 작업 부하 식별"]

link:../performance-checker/task_identify_bully_workloads_involved_in_performance_event.html["성과 이벤트에 관련된 괴롭힘 작업량 식별"]

link:../performance-checker/task_identify_shark_workloads_involved_in_performance_event.html["성능 이벤트에 관련된 상어 작업량 식별"]
