---
permalink: performance-checker/concept_understand_events_from_adaptive_qos_policies.html 
sidebar: sidebar 
keywords: understand, events, adaptive, qos, policies, defined, block, size 
summary: 적응형 QoS 정책 그룹은 볼륨 크기에 따라 처리량 상한 또는 하한을 자동으로 조정하여 볼륨 크기가 변경되더라도 IOPS 대 TB 비율을 유지합니다.  ONTAP 9.5부터 QoS 정책에서 블록 크기를 지정하여 동시에 MB/s 임계값을 효과적으로 적용할 수 있습니다. 
---
= 정의된 블록 크기가 있는 적응형 QoS 정책의 이벤트를 이해합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
적응형 QoS 정책 그룹은 볼륨 크기에 따라 처리량 상한 또는 하한을 자동으로 조정하여 볼륨 크기가 변경되더라도 IOPS 대 TB 비율을 유지합니다.  ONTAP 9.5부터 QoS 정책에서 블록 크기를 지정하여 동시에 MB/s 임계값을 효과적으로 적용할 수 있습니다.

적응형 QoS 정책에서 IOPS 임계값을 할당하면 각 작업 부하에서 발생하는 작업 수에만 제한이 적용됩니다.  작업 부하를 생성하는 클라이언트에 설정된 블록 크기에 따라 일부 IOPS에는 훨씬 더 많은 데이터가 포함되므로 작업을 처리하는 노드에 훨씬 더 큰 부담을 줍니다.

작업 부하에 대한 MB/s 값은 다음 공식을 사용하여 생성됩니다.

[listing]
----
MB/s = (IOPS * Block Size) / 1000
----
작업 부하가 평균 3,000 IOPS이고 클라이언트의 블록 크기가 32KB로 설정된 경우, 이 작업 부하에 대한 효과적인 MB/s는 96입니다.  동일한 작업 부하가 평균 3,000 IOPS이고 클라이언트의 블록 크기가 48KB로 설정된 경우, 이 작업 부하에 대한 효과적인 MB/s는 144입니다.  블록 크기가 클수록 노드가 50% 더 많은 데이터를 처리하는 것을 볼 수 있습니다.

정의된 블록 크기가 있는 다음의 적응형 QoS 정책을 살펴보고 클라이언트에 설정된 블록 크기에 따라 이벤트가 어떻게 트리거되는지 알아보겠습니다.

정책을 만들고 최대 처리량을 블록 크기 32KB로 2,500 IOPS/TB로 설정합니다.  이를 통해 1TB 용량을 사용한 볼륨의 경우 MB/s 임계값이 80MB/s((2500 IOPS * 32KB) / 1000)로 효과적으로 설정됩니다.  Unified Manager는 처리량 값이 정의된 임계값보다 10% 낮을 경우 경고 이벤트를 생성합니다.  이벤트는 다음과 같은 상황에서 생성됩니다.

|===
| 사용된 용량 2+| 처리량이 이 숫자를 초과하면 이벤트가 생성됩니다. 


|  | 아이옵스 | MB/초 


 a| 
1TB
 a| 
2,250 IOPS
 a| 
72MB/초



 a| 
2TB
 a| 
4,500 IOPS
 a| 
144MB/초



 a| 
5TB
 a| 
11,250 IOPS
 a| 
360MB/초

|===
볼륨이 사용 가능한 공간 중 2TB를 사용하고, IOPS가 4,000이며, 클라이언트에서 QoS 블록 크기가 32KB로 설정된 경우 MB/ps 처리량은 128MB/s((4,000 IOPS * 32KB) / 1000)입니다.  이 시나리오에서는 4,000 IOPS와 128MB/s가 모두 2TB의 공간을 사용하는 볼륨에 대한 임계값보다 낮기 때문에 이벤트가 생성되지 않습니다.

볼륨이 사용 가능한 공간 중 2TB를 사용하고, IOPS가 4,000이며, 클라이언트에서 QoS 블록 크기가 64KB로 설정된 경우 MB/s 처리량은 256MB/s((4,000 IOPS * 64KB) / 1000)입니다.  이 경우 4,000 IOPS는 이벤트를 생성하지 않지만 256MB/s의 MB/s 값은 144MB/s의 임계값을 초과하므로 이벤트가 생성됩니다.

이러한 이유로 블록 크기를 포함하는 적응형 QoS 정책에 대한 MB/s 위반을 기반으로 이벤트가 트리거되면 이벤트 세부 정보 페이지의 시스템 진단 섹션에 MB/s 차트가 표시됩니다.  적응형 QoS 정책에 대한 IOPS 위반으로 인해 이벤트가 트리거되는 경우 시스템 진단 섹션에 IOPS 차트가 표시됩니다.  IOPS와 MB/s 모두에서 침해가 발생하면 두 가지 이벤트가 발생합니다.

QoS 설정 조정에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/performance-admin/index.html["성과 관리 개요"] .
