---
permalink: performance-checker/concept_understand_counter_charts.html 
sidebar: sidebar 
keywords: understand, counter, charts 
summary: 카운터 차트 창의 차트를 사용하면 루트 개체와 상관관계가 있는 개체 그리드에서 추가한 개체에 대한 성능 데이터를 보고 비교할 수 있습니다.  이를 통해 성과 추세를 이해하고 성과 문제를 분리하여 해결할 수 있습니다. 
---
= 카운터 차트 이해하기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
카운터 차트 창의 차트를 사용하면 루트 개체와 상관관계가 있는 개체 그리드에서 추가한 개체에 대한 성능 데이터를 보고 비교할 수 있습니다.  이를 통해 성과 추세를 이해하고 성과 문제를 분리하여 해결할 수 있습니다.

기본적으로 표시되는 카운터 차트는 이벤트, 대기 시간, IOPS, MBps입니다.  선택하여 표시할 수 있는 선택적 차트로는 활용률, 사용된 성능 용량, 사용 가능한 IOPS, IOPS/TB, 캐시 미스 비율 등이 있습니다.  또한 대기 시간, IOPS, MBps, 성능 용량 사용 차트에 대한 전체 값이나 세부 값을 볼 수 있습니다.

성능 탐색기는 기본적으로 특정 카운터 차트를 표시합니다. 스토리지 개체가 모든 카운터 차트를 지원하는지 여부는 중요하지 않습니다.  카운터가 지원되지 않으면 카운터 차트가 비어 있고 메시지가 표시됩니다. `Not applicable for <object>` 표시됩니다.

차트는 루트 개체와 비교 창에서 선택한 모든 개체에 대한 성능 추세를 표시합니다.  각 차트의 데이터는 다음과 같이 정리됩니다.

* *X축*
+
지정된 기간을 표시합니다.  시간 범위를 지정하지 않으면 기본값은 이전 72시간 기간입니다.

* *Y축*
+
선택한 개체에 고유한 카운터 단위를 표시합니다.



추세선 색상은 비교 창에 표시된 개체 이름의 색상과 일치합니다.  추세선의 특정 지점 위에 커서를 놓으면 해당 지점의 시간과 가치에 대한 세부 정보를 볼 수 있습니다.

차트 내에서 특정 기간을 조사하려면 다음 방법 중 하나를 사용할 수 있습니다.

* **<*** 버튼을 사용하여 카운터 차트 창을 페이지 너비에 맞게 확장합니다.
* 커서가 돋보기로 바뀔 때 커서를 사용하여 차트에서 시간대의 일부를 선택하여 해당 영역에 초점을 맞추고 확대합니다.  차트 확대/축소 재설정을 클릭하면 차트를 기본 시간대로 되돌릴 수 있습니다.
* *확대 보기* 버튼을 사용하면 확장된 세부 정보와 임계값 표시기가 포함된 대형 단일 카운터 차트를 표시할 수 있습니다.


[NOTE]
====
가끔 추세선에 간격이 나타납니다.  이러한 차이는 Unified Manager가 스토리지 시스템에서 성능 데이터를 수집하지 못했거나 Unified Manager가 다운되었을 수 있음을 의미합니다.

====