---
permalink: performance-checker/concept_sources_of_performance_events.html 
sidebar: sidebar 
keywords: sources, performance, events 
summary: 성능 이벤트는 클러스터의 작업 부하 성능과 관련된 문제입니다.  이러한 기능은 응답 시간이 느린 스토리지 객체, 즉 높은 대기 시간을 식별하는 데 도움이 됩니다.  동시에 발생한 다른 건강 문제와 함께, 느린 대응 시간의 원인이 되었거나 이에 영향을 미친 문제를 파악할 수 있습니다. 
---
= 성과 이벤트의 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능 이벤트는 클러스터의 작업 부하 성능과 관련된 문제입니다.  이러한 기능은 응답 시간이 느린 스토리지 객체, 즉 높은 대기 시간을 식별하는 데 도움이 됩니다.  동시에 발생한 다른 건강 문제와 함께, 느린 대응 시간의 원인이 되었거나 이에 영향을 미친 문제를 파악할 수 있습니다.

Unified Manager는 다음 소스에서 성능 이벤트를 수신합니다.

* *사용자 정의 성능 임계값 정책 이벤트*
+
사용자가 설정한 사용자 정의 임계값에 따라 성능 문제가 발생합니다.  예를 들어, 집계 및 볼륨과 같은 저장소 개체에 대한 성능 임계값 정책을 구성하면 성능 카운터의 임계값이 초과되면 이벤트가 생성됩니다.

+
이러한 이벤트를 수신하려면 성능 임계값 정책을 정의하고 이를 스토리지 개체에 할당해야 합니다.

* *시스템 정의 성능 임계값 정책 이벤트*
+
시스템에서 정의된 임계값에 따른 성능 문제.  이러한 임계값 정책은 일반적인 성능 문제를 해결하기 위해 Unified Manager 설치에 포함됩니다.

+
이러한 임계값 정책은 기본적으로 활성화되어 있으며, 클러스터를 추가한 직후에 이벤트가 표시될 수 있습니다.

* *동적 성능 임계값 이벤트*
+
IT 인프라의 장애나 오류, 또는 워크로드가 클러스터 리소스를 과도하게 활용하여 발생하는 성능 문제입니다.  이러한 이벤트의 원인은 시간이 지나면서 자체적으로 해결되는 간단한 문제일 수도 있고, 수리 또는 구성 변경으로 해결할 수 있는 문제일 수도 있습니다.  동적 임계값 이벤트는 공유 클러스터 구성 요소를 많이 사용하는 다른 작업 부하로 인해 ONTAP 시스템의 작업 부하가 느리다는 것을 나타냅니다.

+
이러한 임계값은 기본적으로 활성화되어 있으며, 새 클러스터에서 데이터를 수집한 후 3일이 지나면 이벤트가 표시될 수 있습니다.


