---
permalink: performance-checker/concept_use_threshold_policy_with_node_failover_planning_page.html 
sidebar: sidebar 
keywords: threshold, policy, node, failover, planning page 
summary: 잠재적인 장애 조치로 인해 인수 노드의 성능이 허용할 수 없는 수준으로 저하될 경우 성능/노드 장애 조치 계획 페이지에서 알림을 받을 수 있도록 노드 임계값 정책을 만들 수 있습니다. 
---
= 노드 장애 조치 계획 페이지에서 임계값 정책 사용
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
잠재적인 장애 조치로 인해 인수 노드의 성능이 허용할 수 없는 수준으로 저하될 경우 성능/노드 장애 조치 계획 페이지에서 알림을 받을 수 있도록 노드 임계값 정책을 만들 수 있습니다.

"노드 HA 쌍 과다 사용"이라는 시스템 정의 성능 임계값 정책은 임계값이 6회 연속 수집 기간(30분) 동안 위반되면 경고 이벤트를 생성합니다.  HA 쌍의 노드에서 사용된 결합된 성능 용량이 200%를 초과하면 임계값이 위반된 것으로 간주됩니다.

시스템 정의 임계값 정책의 이벤트는 장애 조치로 인해 인수 노드의 대기 시간이 허용할 수 없는 수준으로 증가할 것이라는 사실을 경고합니다.  특정 노드에 대해 이 정책에 의해 생성된 이벤트가 표시되면 해당 노드의 성능/노드 장애 조치 계획 페이지로 이동하여 장애 조치로 인한 예상 대기 시간 값을 확인할 수 있습니다.

이 시스템 정의 임계값 정책을 사용하는 것 외에도 "성능 용량 사용 - 인수" 카운터를 사용하여 임계값 정책을 만든 다음 선택한 노드에 정책을 적용할 수 있습니다.  200%보다 낮은 임계값을 지정하면 시스템 정의 정책의 임계값이 위반되기 전에 이벤트를 수신할 수 있습니다.  시스템 정의 정책 이벤트가 생성되기 전에 알림을 받으려면 임계값을 초과하는 최소 기간을 30분 미만으로 지정할 수도 있습니다.

예를 들어, HA 쌍의 노드에서 사용된 결합된 성능 용량이 10분 이상 175%를 초과하는 경우 경고 이벤트를 생성하는 임계값 정책을 정의할 수 있습니다.  이 정책은 HA 쌍을 형성하는 Node1과 Node2에 적용할 수 있습니다.  Node1 또는 Node2에 대한 경고 이벤트 알림을 받은 후 해당 노드의 성능/노드 장애 조치 계획 페이지를 보고 인수 노드에 미치는 예상 성능 영향을 평가할 수 있습니다.  장애 조치가 발생하는 경우 인수 노드에 과부하가 걸리지 않도록 시정 조치를 취할 수 있습니다.  노드의 결합된 성능 용량이 200% 미만일 때 조치를 취하면, 이 시간 동안 장애 조치가 발생하더라도 인수 노드의 지연 시간이 허용할 수 없는 수준에 도달하지 않습니다.
