---
permalink: performance-checker/concept_how_storage_qos_can_control_workload_throughput.html 
sidebar: sidebar 
keywords: storage, qos, control, workload, throughput 
summary: '워크로드에 대한 초당 I/O(IOPS) 또는 처리량(MB/s) 제한을 제어하기 위해 QoS(서비스 품질) 정책 그룹을 만들 수 있습니다.  워크로드가 기본 정책 그룹과 같이 설정된 제한이 없는 정책 그룹에 있는 경우 또는 설정된 제한이 요구 사항을 충족하지 못하는 경우 제한을 늘리거나 원하는 제한이 있는 새 정책 그룹이나 기존 정책 그룹으로 워크로드를 이동할 수 있습니다.' 
---
= 스토리지 QoS가 작업 부하 처리량을 제어하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
워크로드에 대한 초당 I/O(IOPS) 또는 처리량(MB/s) 제한을 제어하기 위해 QoS(서비스 품질) 정책 그룹을 만들 수 있습니다.  워크로드가 기본 정책 그룹과 같이 설정된 제한이 없는 정책 그룹에 있는 경우 또는 설정된 제한이 요구 사항을 충족하지 못하는 경우 제한을 늘리거나 원하는 제한이 있는 새 정책 그룹이나 기존 정책 그룹으로 워크로드를 이동할 수 있습니다.

"`기존`" QoS 정책 그룹은 개별 작업 부하(예: 단일 볼륨 또는 LUN)에 할당될 수 있습니다.  이 경우 작업 부하가 전체 처리량 한도를 사용할 수 있습니다.  QoS 정책 그룹은 여러 작업 부하에 할당될 수도 있습니다. 이 경우 처리량 제한은 작업 부하 간에 "공유"됩니다.  예를 들어, 3개의 작업 부하에 9,000 IOPS의 QoS 제한을 할당하면 결합된 IOPS가 9,000 IOPS를 초과하지 못합니다.

"`적응형` QoS 정책 그룹은 개별 작업 부하나 여러 작업 부하에 할당될 수도 있습니다.  그러나 여러 작업 부하에 할당된 경우에도 각 작업 부하에는 다른 작업 부하와 처리량 값을 공유하는 대신 전체 처리량 한도가 적용됩니다.  또한, 적응형 QoS 정책은 볼륨 크기에 따라 작업 부하당 처리량 설정을 자동으로 조정하여 볼륨 크기가 변경되더라도 IOPS 대 테라바이트 비율을 유지합니다.  예를 들어, 적응형 QoS 정책에서 최대값을 5,000 IOPS/TB로 설정하면 10TB 볼륨의 처리량 최대값은 50,000 IOPS가 됩니다.  나중에 볼륨 크기가 20TB로 조정되면 적응형 QoS가 최대값을 100,000 IOPS로 조정합니다.

ONTAP 9.5부터 적응형 QoS 정책을 정의할 때 블록 크기를 포함할 수 있습니다.  워크로드가 매우 큰 블록 크기를 사용하고 궁극적으로 처리량의 큰 비율을 사용하는 경우 이를 통해 정책이 IOPS/TB 임계값에서 MB/s 임계값으로 효과적으로 변환됩니다.

공유 그룹 QoS 정책의 경우, 정책 그룹 내 모든 워크로드의 IOPS 또는 MB/s가 설정된 한도를 초과하면 정책 그룹이 워크로드를 조절하여 활동을 제한하는데, 이로 인해 정책 그룹 내 모든 워크로드의 성능이 저하될 수 있습니다.  정책 그룹 제한으로 인해 동적 성능 이벤트가 생성되면 이벤트 설명에 관련 정책 그룹의 이름이 표시됩니다.

성능: 모든 볼륨 보기에서 영향을 받은 볼륨을 IOPS 및 MB/s별로 정렬하여 이벤트에 영향을 미쳤을 수 있는 가장 높은 사용량을 가진 워크로드를 확인할 수 있습니다.  성능/볼륨 탐색기 페이지에서 다른 볼륨이나 볼륨의 LUN을 선택하여 영향을 받는 작업 부하 IOPS 또는 MBps 처리량 사용량과 비교할 수 있습니다.

노드 리소스를 과도하게 사용하는 작업 부하를 보다 제한적인 정책 그룹 설정에 할당하면 정책 그룹이 작업 부하를 조절하여 활동을 제한하고, 이를 통해 해당 노드의 리소스 사용을 줄일 수 있습니다.  하지만 작업 부하가 더 많은 노드 리소스를 사용할 수 있도록 하려면 정책 그룹의 값을 늘릴 수 있습니다.

시스템 관리자, ONTAP 명령 또는 Unified Manager 성능 서비스 수준을 사용하여 다음 작업을 포함하여 정책 그룹을 관리할 수 있습니다.

* 정책 그룹 생성
* 정책 그룹에서 작업 부하 추가 또는 제거
* 정책 그룹 간 작업 부하 이동
* 정책 그룹의 처리량 제한 변경
* 작업 부하를 다른 집계 및/또는 노드로 이동

