---
permalink: performance-checker/concept_cluster_configuration_and_performance_data_collection_activity.html 
sidebar: sidebar 
keywords: cluster, configuration, performance, data, collection, activity 
summary: 클러스터 구성 데이터의 수집 간격은 15분입니다.  예를 들어, 클러스터를 추가한 후 Unified Manager UI에 클러스터 세부 정보가 표시되는 데 15분이 걸립니다.  이 간격은 클러스터를 변경할 때도 적용됩니다. 
---
= 클러스터 구성 및 성능 데이터 수집 활동
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
_클러스터 구성 데이터_의 수집 간격은 15분입니다.  예를 들어, 클러스터를 추가한 후 Unified Manager UI에 클러스터 세부 정보가 표시되는 데 15분이 걸립니다.  이 간격은 클러스터를 변경할 때도 적용됩니다.

예를 들어, 클러스터의 SVM에 두 개의 새 볼륨을 추가하는 경우 다음 폴링 간격(최대 15분) 후에 UI에서 해당 새 객체를 볼 수 있습니다.

Unified Manager는 모니터링되는 모든 클러스터에서 5분마다 현재 _성능 통계_를 수집합니다.  이 데이터를 분석하여 성능 이벤트와 잠재적인 문제를 식별합니다.  5분 단위의 과거 성과 데이터를 30일 동안 보관하고, 1시간 단위의 과거 성과 데이터를 180일 동안 보관합니다.  이를 통해 현재 달의 매우 세부적인 성과 세부 정보와 최대 1년 동안의 일반적인 성과 추세를 볼 수 있습니다.

수집 폴링은 몇 분 간격으로 이루어지므로 모든 클러스터의 데이터가 동시에 전송되지 않아 성능에 영향을 미칠 수 있습니다.

다음 표에서는 Unified Manager가 수행하는 수집 활동을 설명합니다.

|===
| 활동 | 시간 간격 | 설명 


 a| 
성과 통계 여론조사
 a| 
5분마다
 a| 
각 클러스터에서 실시간 성능 데이터를 수집합니다.



 a| 
통계 분석
 a| 
5분마다
 a| 
모든 통계 폴링 후 Unified Manager는 수집된 데이터를 사용자 정의 임계값, 시스템 정의 임계값, 동적 임계값과 비교합니다.

성능 임계값이 초과되면 Unified Manager는 이벤트를 생성하고 지정된 사용자에게 이메일을 보냅니다(구성된 경우).



 a| 
구성 폴
 a| 
15분마다
 a| 
각 클러스터에서 자세한 인벤토리 정보를 수집하여 모든 스토리지 개체(노드, SVM, 볼륨 등)를 식별합니다.



 a| 
요약
 a| 
매 시간마다
 a| 
최근 12개 5분 성과 데이터 수집을 시간당 평균으로 요약합니다.

시간당 평균 값은 일부 UI 페이지에서 사용되며 180일 동안 보관됩니다.



 a| 
예측 분석 및 데이터 정리
 a| 
매일 자정 이후
 a| 
클러스터 데이터를 분석하여 향후 24시간 동안의 볼륨 지연 시간과 IOPS에 대한 동적 임계값을 설정합니다.

30일이 지난 5분 성능 데이터를 데이터베이스에서 삭제합니다.



 a| 
데이터 정리
 a| 
매일 오전 2시 이후
 a| 
180일보다 오래된 이벤트와 180일보다 오래된 동적 임계값을 데이터베이스에서 삭제합니다.



 a| 
데이터 정리
 a| 
매일 오전 3시 30분 이후
 a| 
180일이 지난 1시간 성능 데이터를 데이터베이스에서 삭제합니다.

|===