---
permalink: performance-checker/concept_roles_of_workloads_involved_in_performance_incident.html 
sidebar: sidebar 
keywords: roles, workloads, involved, performance, event 
summary: Unified Manager는 역할을 사용하여 성능 이벤트에서 워크로드의 관련성을 식별합니다.  역할에는 피해자, 괴롭힘꾼, 상어 등이 있습니다.  사용자 정의 워크로드는 동시에 피해자, 괴롭힘꾼, 상어가 될 수 있습니다. 
---
= 성능 이벤트에 관련된 작업 부하의 역할
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 역할을 사용하여 성능 이벤트에서 워크로드의 관련성을 식별합니다.  역할에는 피해자, 괴롭힘꾼, 상어 등이 있습니다.  사용자 정의 워크로드는 동시에 피해자, 괴롭힘꾼, 상어가 될 수 있습니다.

|===
| 역할 | 설명 


 a| 
피해자
 a| 
클러스터 구성 요소를 과도하게 사용하는 다른 워크로드(괴롭힘이라고 함)로 인해 성능이 저하된 사용자 정의 워크로드입니다.  사용자가 정의한 작업 부하만 피해자로 식별됩니다.  Unified Manager는 지연 시간의 편차를 기준으로 피해자 워크로드를 식별합니다. 이벤트 중 실제 지연 시간은 지연 시간 예측(예상 범위)보다 크게 증가했습니다.



 a| 
괴롭히는 사람
 a| 
클러스터 구성 요소를 과도하게 사용하여 피해자라고 하는 다른 워크로드의 성능이 저하된 사용자 정의 또는 시스템 정의 워크로드입니다.  Unified Manager는 이벤트 중에 실제 사용량이 예상 사용량 범위에서 크게 증가한 클러스터 구성 요소 사용량 편차를 기준으로 괴롭힘 워크로드를 식별합니다.



 a| 
상어
 a| 
이벤트에 관련된 모든 워크로드와 비교했을 때 클러스터 구성 요소를 가장 많이 사용하는 사용자 정의 워크로드입니다.  Unified Manager는 이벤트 중에 클러스터 구성 요소의 사용을 기반으로 샤크 워크로드를 식별합니다.

|===
클러스터의 작업 부하는 네트워크 및 데이터 처리를 위한 집계 및 CPU와 같은 많은 클러스터 구성 요소를 공유할 수 있습니다.  볼륨 등의 작업 부하가 클러스터 구성 요소의 사용량을 늘려 구성 요소가 작업 부하 수요를 효율적으로 충족할 수 없는 지점까지 이르면 해당 구성 요소는 경합 상태에 놓이게 됩니다.  클러스터 구성 요소를 과도하게 사용하는 작업 부하는 괴롭힘입니다.  이러한 구성 요소를 공유하고 괴롭힘에 의해 성과에 영향을 받는 다른 작업 부하가 피해자입니다.  중복 제거나 스냅샷 복사와 같은 시스템 정의 워크로드의 활동도 "괴롭힘"으로 확대될 수 있습니다.

Unified Manager가 이벤트를 감지하면 이벤트를 발생시킨 괴롭힘 워크로드, 경합 중인 클러스터 구성 요소, 괴롭힘 워크로드의 활동 증가로 인해 성능이 저하된 피해자 워크로드를 포함하여 관련된 모든 워크로드와 클러스터 구성 요소를 식별합니다.

[NOTE]
====
Unified Manager가 위협적인 워크로드를 식별할 수 없는 경우, 피해 워크로드와 관련 클러스터 구성 요소에 대해서만 경고합니다.

====
Unified Manager는 괴롭힘 워크로드의 희생자가 되는 워크로드를 식별하고, 동일한 워크로드가 괴롭힘 워크로드가 되는 시점을 식별할 수 있습니다.  업무량은 스스로를 괴롭히는 요인이 될 수 있습니다.  예를 들어, 정책 그룹 제한으로 인해 고성능 워크로드가 제한되는 경우 정책 그룹 자체를 포함하여 해당 정책 그룹의 모든 워크로드가 제한됩니다.  진행 중인 성과 이벤트에서 괴롭힘을 주거나 피해를 주는 업무는 역할을 바꾸거나 더 이상 이벤트에 참여하지 않을 수 있습니다.
