---
permalink: performance-checker/concept_what_data_continuity_collection_cycle_is.html 
sidebar: sidebar 
keywords: data, continuity, collection, cycle 
summary: 데이터 연속성 수집 주기는 기본적으로 5분마다 실행되는 실시간 클러스터 성능 수집 주기 외부에서 성능 데이터를 검색합니다.  데이터 연속성 수집을 통해 Unified Manager는 실시간 데이터를 수집하지 못했을 때 발생하는 통계 데이터 공백을 채울 수 있습니다. 
---
= 데이터 연속성 수집 주기란 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 연속성 수집 주기는 기본적으로 5분마다 실행되는 실시간 클러스터 성능 수집 주기 외부에서 성능 데이터를 검색합니다.  데이터 연속성 수집을 통해 Unified Manager는 실시간 데이터를 수집하지 못했을 때 발생하는 통계 데이터 공백을 채울 수 있습니다.

Unified Manager는 다음 이벤트가 발생할 때 과거 성능 데이터에 대한 데이터 연속성 수집 폴링을 수행합니다.

* 클러스터는 처음에 Unified Manager에 추가됩니다.
+
Unified Manager는 지난 15일 동안의 과거 성능 데이터를 수집합니다.  이 기능을 사용하면 클러스터를 추가한 후 몇 시간 만에 해당 클러스터의 2주간의 과거 성능 정보를 볼 수 있습니다.

+
또한, 시스템에서 정의한 임계값 이벤트가 있으면 이전 기간에 대해 보고됩니다.

* 현재 성과 데이터 수집 주기가 예정대로 완료되지 않습니다.
+
실시간 성과 여론조사가 5분 수집 기간을 넘으면 누락된 정보를 수집하기 위해 데이터 연속성 수집 주기가 시작됩니다.  데이터 연속성 수집이 없으면 다음 수집 기간이 건너뜁니다.

* Unified Manager에 일정 시간 동안 액세스할 수 없다가 다음과 같은 상황에서 다시 온라인 상태로 돌아오는 경우가 있습니다.
+
** 다시 시작되었습니다.
** 소프트웨어 업그레이드 중이나 백업 파일을 생성하는 중에 종료되었습니다.
** 네트워크 중단이 복구되었습니다.


* 다음 상황처럼 클러스터에 일정 시간 동안 액세스할 수 없다가 다시 온라인 상태로 돌아오는 경우가 있습니다.
+
** 네트워크 중단이 복구되었습니다.
** 광역 네트워크 연결 속도가 느려서 정상적인 성능 데이터 수집이 지연되었습니다.




데이터 연속성 수집 주기는 최대 24시간 분량의 과거 데이터를 수집할 수 있습니다.  Unified Manager가 24시간 이상 다운되면 UI 페이지에 성능 데이터에 차이가 나타납니다.

데이터 연속성 수집 주기와 실시간 데이터 수집 주기는 동시에 실행할 수 없습니다.  실시간 성능 데이터 수집이 시작되기 전에 데이터 연속성 수집 주기가 완료되어야 합니다.  1시간 이상의 과거 데이터를 수집하기 위해 데이터 연속성 수집이 필요한 경우 알림 창 상단에 해당 클러스터에 대한 배너 메시지가 표시됩니다.
