---
permalink: performance-checker/concept_unified_manager_performance_monitoring_features.html 
sidebar: sidebar 
keywords: unified manager, performance, monitoring, features 
summary: Unified Manager는 ONTAP 소프트웨어를 실행하는 시스템에서 성능 통계를 수집하고 분석합니다.  다양한 클러스터 구성 요소에 대한 다양한 성능 카운터를 모니터링하기 위해 동적 성능 임계값과 사용자 정의 성능 임계값을 사용합니다. 
---
= Unified Manager 성능 모니터링 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 ONTAP 소프트웨어를 실행하는 시스템에서 성능 통계를 수집하고 분석합니다.  다양한 클러스터 구성 요소에 대한 다양한 성능 카운터를 모니터링하기 위해 동적 성능 임계값과 사용자 정의 성능 임계값을 사용합니다.

높은 응답 시간(대기 시간)은 볼륨과 같은 스토리지 객체가 평소보다 느리게 수행되고 있음을 나타냅니다.  이 문제는 볼륨을 사용하는 클라이언트 애플리케이션의 성능이 저하되었음을 나타냅니다.  Unified Manager는 성능 문제가 있는 스토리지 구성 요소를 식별하고 성능 문제를 해결하기 위해 취할 수 있는 제안된 작업 목록을 제공합니다.

Unified Manager에는 다음과 같은 기능이 포함되어 있습니다.

* ONTAP 소프트웨어를 실행하는 시스템의 작업 부하 성능 통계를 모니터링하고 분석합니다.
* 클러스터, 노드, 집계, 포트, SVM, 볼륨, LUN, NVMe 네임스페이스 및 네트워크 인터페이스(LIF)에 대한 성능 카운터를 추적합니다.
* 시간 경과에 따른 작업 부하 활동을 나타내는 자세한 그래프를 표시합니다. 여기에는 IOPS(작업), MB/s(처리량), 지연 시간(응답 시간), 활용도, 성능 용량 및 캐시 비율이 포함됩니다.
* 임계값을 초과하면 이벤트를 트리거하고 이메일 알림을 보내는 사용자 정의 성능 임계값 정책을 만들 수 있습니다.
* 워크로드 활동에 대해 학습하여 성능 문제를 식별하고 경고하는 시스템 정의 임계값과 동적 성능 임계값을 사용합니다.
* 볼륨과 LUN에 적용되는 서비스 품질(QoS) 정책과 성능 서비스 수준 정책(PSL)을 식별합니다.
* 경합 중인 클러스터 구성 요소를 명확하게 식별합니다.
* 클러스터 구성 요소를 과도하게 사용하는 작업 부하와 활동 증가로 인해 성능에 영향을 받는 작업 부하를 식별합니다.

