---
permalink: performance-checker/concept_types_of_workloads_monitored_by_unified_manager.html 
sidebar: sidebar 
keywords: types, workloads, monitored, unified manager 
summary: Unified Manager를 사용하면 사용자 정의 워크로드와 시스템 정의 워크로드의 두 가지 유형의 성능을 모니터링할 수 있습니다. 
---
= Unified Manager에서 모니터링하는 작업 유형
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 사용하면 사용자 정의 워크로드와 시스템 정의 워크로드의 두 가지 유형의 성능을 모니터링할 수 있습니다.

* *_사용자 정의 워크로드_*
+
애플리케이션에서 클러스터로의 I/O 처리량.  이는 읽기 및 쓰기 요청과 관련된 프로세스입니다.  볼륨, LUN, NFS 공유, SMB/CIFS 공유 및 작업 부하가 사용자 정의 작업 부하입니다.

+
[NOTE]
====
Unified Manager는 클러스터의 작업 부하 활동만 모니터링합니다.  애플리케이션, 클라이언트 또는 애플리케이션과 클러스터 간의 경로를 모니터링하지 않습니다.

====
+
다음 중 하나 이상이 워크로드에 해당되는 경우 Unified Manager에서 모니터링할 수 없습니다.

+
** 이는 읽기 전용 모드의 데이터 보호(DP) 복사본입니다.  (DP 볼륨은 사용자 생성 트래픽을 모니터링합니다.)
** 오프라인 데이터 복제본입니다.
** 이는 MetroCluster 구성의 미러링된 볼륨입니다.


* *_시스템 정의 워크로드_*
+
저장 효율성, 데이터 복제 및 시스템 상태와 관련된 내부 프로세스에는 다음이 포함됩니다.

+
** 중복 제거와 같은 저장 효율성
** RAID 재구성, 디스크 스크러빙 등을 포함하는 디스크 상태
** SnapMirror 복사와 같은 데이터 복제
** 경영 활동
** 다양한 WAFL 활동을 포함하는 파일 시스템 상태
** WAFL 스캔과 같은 파일 시스템 스캐너
** VMware 호스트에서 오프로드된 스토리지 효율성 작업과 같은 오프로드 복사
** 볼륨 이동, 데이터 압축 등과 같은 시스템 상태
** 모니터링되지 않는 볼륨




시스템 정의 워크로드에 대한 성능 데이터는 이러한 워크로드에서 사용되는 클러스터 구성 요소가 경합 중인 경우에만 GUI에 표시됩니다.  예를 들어, GUI에서 시스템 정의 워크로드의 이름을 검색하여 해당 성능 데이터를 볼 수는 없습니다.
