---
permalink: performance-checker/concept_collect_data_and_monitor_workload_performance.html 
sidebar: sidebar 
keywords: collect, data, monitor, workload, performance 
summary: Unified Manager는 5분마다 작업 부하 활동을 수집하고 분석하여 성능 이벤트를 식별하고 15분마다 구성 변경 사항을 감지합니다.  최대 30일 동안의 5분 단위 성능 및 이벤트 데이터를 보관하고, 이 데이터를 사용하여 모니터링되는 모든 워크로드에 대한 예상 지연 시간 범위를 예측합니다. 
---
= 데이터 수집 및 워크로드 성능 모니터링
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 5분마다 작업 부하 활동을 수집하고 분석하여 성능 이벤트를 식별하고 15분마다 구성 변경 사항을 감지합니다.  최대 30일 동안의 5분 단위 성능 및 이벤트 데이터를 보관하고, 이 데이터를 사용하여 모니터링되는 모든 워크로드에 대한 예상 지연 시간 범위를 예측합니다.

Unified Manager는 분석을 시작하고 I/O 응답 시간에 대한 지연 시간 예측을 워크로드 분석 페이지와 이벤트 세부 정보 페이지에 표시하기 전에 최소 3일 분의 워크로드 활동을 수집해야 합니다.  이 활동이 수집되는 동안 대기 시간 예측에는 작업 부하 활동으로 인해 발생하는 모든 변경 사항이 표시되지 않습니다.  Unified Manager는 3일간의 활동을 수집한 후 24시간마다 오전 12시에 대기 시간 예측을 조정하여 작업 부하 활동의 변화를 반영하고 더욱 정확한 동적 성능 임계값을 설정합니다.

Unified Manager가 작업 부하를 모니터링하는 처음 4일 동안 마지막 데이터 수집 이후 24시간 이상이 지나면 지연 시간 차트에 해당 작업 부하에 대한 지연 시간 예측이 표시되지 않습니다.  마지막 수집 이전에 감지된 이벤트는 계속 사용할 수 있습니다.

[NOTE]
====
일광 절약 시간제(DST)는 시스템 시간을 변경하는데, 이로 인해 모니터링되는 작업 부하에 대한 성능 통계의 지연 시간 예측이 변경됩니다.  Unified Manager는 지연 시간 예측을 즉시 수정하기 시작하며, 완료하는 데 약 15일이 소요됩니다.  이 기간 동안 Unified Manager를 계속 사용할 수 있지만 Unified Manager는 지연 시간 예측을 사용하여 동적 이벤트를 감지하므로 일부 이벤트가 정확하지 않을 수 있습니다.  시간 변경 이전에 감지된 이벤트는 영향을 받지 않습니다.

====