---
permalink: performance-checker/concept_components_of_performance_explorer_page.html 
sidebar: sidebar 
keywords: components, performance, explorer, page 
summary: '성능 탐색기 페이지를 사용하면 클러스터 내 유사한 개체(예: 클러스터 내 모든 볼륨)의 성능을 비교할 수 있습니다.  이 기능은 성능 이벤트 문제를 해결하고 개체 성능을 미세 조정할 때 유용합니다.  또한 객체를 루트 객체와 비교할 수도 있는데, 루트 객체는 다른 객체를 비교하는 기준이 됩니다.' 
---
= 성능 탐색기 페이지의 구성 요소
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능 탐색기 페이지를 사용하면 클러스터 내의 유사한 개체(예: 클러스터 내의 모든 볼륨)의 성능을 비교할 수 있습니다.  이 기능은 성능 이벤트 문제를 해결하고 개체 성능을 미세 조정할 때 유용합니다.  또한 객체를 루트 객체와 비교할 수도 있는데, 루트 객체는 다른 객체를 비교하는 기준이 됩니다.

*상태 보기로 전환* 버튼을 클릭하면 이 개체의 상태 세부 정보 페이지가 표시됩니다.  어떤 경우에는 문제를 해결하는 데 도움이 될 수 있는 이 개체의 저장소 구성 설정에 대한 중요한 정보를 알아볼 수 있습니다.

성능 탐색기 페이지에는 클러스터 개체 목록과 해당 성능 데이터가 표시됩니다.  이 페이지는 동일한 유형의 모든 클러스터 개체(예: 볼륨 및 개체별 성능 통계)를 표 형식으로 표시합니다.  이 보기는 클러스터 개체 성능에 대한 효율적인 개요를 제공합니다.

[NOTE]
====
표의 어떤 셀에든 "`N/A`"가 나타나면 해당 개체에 대한 I/O가 현재 없기 때문에 해당 카운터에 대한 값을 사용할 수 없음을 의미합니다.

====
성능 탐색기 페이지에는 다음 구성 요소가 포함되어 있습니다.

* *시간 범위*
+
개체 데이터의 시간 범위를 선택할 수 있습니다.

+
미리 정의된 범위를 선택하거나 사용자 정의 시간 범위를 지정할 수 있습니다.

* *보기 및 비교*
+
그리드에 표시할 상관관계 객체의 유형을 선택할 수 있습니다.

+
사용 가능한 옵션은 루트 개체 유형과 사용 가능한 데이터에 따라 달라집니다.  보기 및 비교 드롭다운 목록을 클릭하여 개체 유형을 선택할 수 있습니다.  선택한 개체 유형이 목록에 표시됩니다.

* *필터링*
+
사용자의 선호도에 따라 수신하는 데이터 양을 줄일 수 있습니다.

+
개체 데이터에 적용되는 필터(예: IOPS가 4보다 큰 경우)를 만들 수 있습니다.  최대 4개의 필터를 동시에 추가할 수 있습니다.

* *비교*
+
루트 개체와 비교하기 위해 선택한 개체 목록을 표시합니다.

+
비교 창에 있는 개체의 데이터는 카운터 차트에 표시됩니다.

* *통계 보기*
+
볼륨 및 LUN의 경우 통계를 각 수집 주기(기본값 5분) 후에 표시할지, 아니면 통계를 시간당 평균으로 표시할지 선택할 수 있습니다.  이 기능을 사용하면 NetApp "성능 보장" 프로그램을 지원하는 지연 시간 차트를 볼 수 있습니다.

* *카운터 차트*
+
각 개체 성능 범주에 대한 그래프 데이터를 표시합니다.

+
일반적으로 기본적으로 3~4개의 차트만 표시됩니다.  차트 선택 구성 요소를 사용하면 추가 차트를 표시하거나 특정 차트를 숨길 수 있습니다.  이벤트 타임라인을 표시하거나 숨기도록 선택할 수도 있습니다.

* *이벤트 타임라인*
+
시간 범위 구성 요소에서 선택한 타임라인에서 발생하는 성능 및 상태 이벤트를 표시합니다.


