---
permalink: performance-checker/concept_understand_performance_panels_on_dashboard.html 
sidebar: sidebar 
keywords: understand, performance, panels, dashboard 
summary: Unified Manager 대시보드는 사용자 환경에서 모니터링되는 모든 클러스터의 높은 수준의 성능 상태를 표시하는 몇 가지 패널을 제공합니다.  모든 클러스터 또는 개별 클러스터의 상태를 볼 수 있습니다. 
---
= 대시보드의 성능 패널 이해하기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager 대시보드는 사용자 환경에서 모니터링되는 모든 클러스터의 높은 수준의 성능 상태를 표시하는 몇 가지 패널을 제공합니다.  모든 클러스터 또는 개별 클러스터의 상태를 볼 수 있습니다.

대부분의 패널은 성과 정보를 표시하는 것 외에도 해당 카테고리의 활성 이벤트 수와 지난 24시간 동안 추가된 새 이벤트 수도 표시합니다.  이 정보는 보고된 이벤트를 해결하기 위해 추가적으로 분석해야 할 클러스터를 결정하는 데 도움이 됩니다.  이벤트를 클릭하면 상위 몇 개의 이벤트가 표시되고, 해당 카테고리의 이벤트를 표시하도록 필터링된 이벤트 관리 인벤토리 페이지로 연결되는 링크가 제공됩니다.

다음 패널은 성과 상태를 제공합니다.

* *성능 용량 패널*
+
모든 클러스터를 볼 때 이 패널에는 각 클러스터의 성능 용량 값(지난 1시간 동안의 평균)과 성능 용량이 상한에 도달할 때까지 걸리는 일수(일일 성장률 기준)가 표시됩니다.  막대형 차트를 클릭하면 해당 클러스터의 노드 인벤토리 페이지로 이동합니다.  노드 인벤토리 페이지에는 지난 72시간 동안의 평균 성능 용량이 표시되므로 이 값이 대시보드 값과 일치하지 않을 수 있습니다.

+
단일 클러스터를 볼 때 이 패널에는 클러스터 성능 용량, 총 IOPS 및 총 처리량 값이 표시됩니다.

* *워크로드 IOPS 패널*
+
워크로드 활성 관리가 활성화되어 있고 단일 클러스터를 보고 있는 경우, 이 패널에는 현재 특정 IOPS 범위에서 실행 중인 총 워크로드 수가 표시됩니다.

* *작업 부하 성능 패널*
+
워크로드 활성 관리가 활성화된 경우 이 패널에는 정의된 각 성능 서비스 수준에 할당된 적합 및 비적합 워크로드의 총 수가 표시됩니다.  막대형 차트를 클릭하면 작업 부하 페이지에서 해당 정책에 할당된 작업 부하로 이동합니다.

* *사용 개요 패널*
+
모든 클러스터를 볼 때 가장 높은 IOPS 또는 처리량(MB/초)을 기준으로 클러스터를 정렬하여 볼 수 있습니다.

+
단일 클러스터를 볼 때 해당 클러스터의 작업 부하를 가장 높은 IOPS 또는 처리량(MB/초)을 기준으로 정렬하여 볼 수 있습니다.


