---
permalink: performance-checker/reference_managed_objects_pane.html 
sidebar: sidebar 
keywords: managed, objects, pane 
summary: 성능 요약 탭의 관리 개체 창은 클러스터의 스토리지 개체 유형과 개수에 대한 최상위 개요를 제공합니다.  이 창을 사용하면 각 클러스터의 개체 상태를 추적할 수 있습니다. 
---
= 관리되는 개체 창
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능 요약 탭의 관리 개체 창은 클러스터의 스토리지 개체 유형과 개수에 대한 최상위 개요를 제공합니다.  이 창을 사용하면 각 클러스터의 개체 상태를 추적할 수 있습니다.

관리되는 개체 수는 마지막 수집 기간을 기준으로 한 특정 시점의 데이터입니다.  15분 간격으로 새로운 물체가 발견됩니다.

모든 객체 유형에 연결된 숫자를 클릭하면 해당 객체 유형에 대한 객체 성능 인벤토리 페이지가 표시됩니다.  개체 인벤토리 페이지는 이 클러스터에 있는 개체만 표시하도록 필터링됩니다.

관리되는 객체는 다음과 같습니다.

* *노드*
+
클러스터 내의 물리적 시스템.

* *집계*
+
보호 및 프로비저닝을 위해 단일 단위로 관리할 수 있는 여러 개의 독립 디스크 중복 배열(RAID) 그룹 집합입니다.

* *포트*
+
네트워크 상의 다른 장치에 연결하는 데 사용되는 노드의 물리적 연결 지점입니다.

* *저장 VM*
+
고유한 네트워크 주소를 통해 네트워크 액세스를 제공하는 가상 머신입니다.  SVM은 별도의 네임스페이스에서 데이터를 제공할 수 있으며, 클러스터의 나머지 부분과 별도로 관리할 수 있습니다.

* *권수*
+
지원되는 하나 이상의 액세스 프로토콜을 통해 액세스 가능한 사용자 데이터를 보관하는 논리적 엔터티입니다.  이 계산에는 FlexVol 볼륨과 FlexGroup 볼륨이 모두 포함되며 FlexGroup 구성 요소는 포함되지 않습니다.

* *LUN*
+
FC(Fibre Channel) 논리 장치 또는 iSCSI 논리 장치의 식별자입니다.  논리 단위는 일반적으로 저장 볼륨에 해당하며, 컴퓨터 운영 체제 내에서는 장치로 표현됩니다.

* *네트워크 인터페이스*
+
노드에 대한 네트워크 접근 지점을 나타내는 논리적 네트워크 인터페이스입니다.  이 계산에는 모든 인터페이스 유형이 포함됩니다.


