---
permalink: performance-checker/reference_what_performance_metrics_can_be_monitored_using_thresholds.html 
sidebar: sidebar 
keywords: performance, counters, tracked, thresholds 
summary: IOPS 및 MB/s와 같은 일부 일반적인 성능 카운터에는 모든 스토리지 개체에 대한 임계값을 설정할 수 있습니다.  특정 저장 객체에 대해서만 임계값을 설정할 수 있는 다른 카운터도 있습니다. 
---
= 임계값을 사용하여 추적할 수 있는 성능 카운터는 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IOPS 및 MB/s와 같은 일부 일반적인 성능 카운터에는 모든 스토리지 개체에 대한 임계값을 설정할 수 있습니다.  특정 저장 객체에 대해서만 임계값을 설정할 수 있는 다른 카운터도 있습니다.



== 사용 가능한 성능 카운터

|===
| 저장 객체 | 성능 카운터 | 설명 


 a| 
무리
 a| 
아이옵스
 a| 
클러스터가 초당 처리하는 입출력 작업의 평균 수입니다.



 a| 
MB/초
 a| 
초당 이 클러스터에서 전송되는 데이터의 평균 메가바이트 수입니다.



 a| 
마디
 a| 
아이옵스
 a| 
노드가 초당 처리하는 입출력 작업의 평균 수입니다.



 a| 
MB/초
 a| 
초당 이 노드에서 전송되는 데이터의 평균 메가바이트 수입니다.



 a| 
숨어 있음
 a| 
노드가 애플리케이션 요청에 응답하는 데 걸리는 평균 시간(밀리초)입니다.



 a| 
이용
 a| 
노드의 CPU와 RAM이 사용 중인 평균 비율입니다.



 a| 
사용된 성능 용량
 a| 
노드에서 소비되는 성능 용량의 평균 백분율입니다.



 a| 
사용된 성능 용량 - 인수
 a| 
노드에서 소비되는 성능 용량의 평균 백분율과 파트너 노드의 성능 용량을 합한 값입니다.



 a| 
골재
 a| 
아이옵스
 a| 
초당 집계된 프로세스의 평균 입출력 작업 수입니다.



 a| 
MB/초
 a| 
초당 이 집계에서 전송되는 데이터의 평균 메가바이트 수입니다.



 a| 
숨어 있음
 a| 
집계된 데이터가 애플리케이션 요청에 응답하는 데 걸리는 평균 시간(밀리초)입니다.



 a| 
이용
 a| 
집계된 디스크 중 사용 중인 평균 비율입니다.



 a| 
사용된 성능 용량
 a| 
집계에 의해 소비되는 성능 용량의 평균 백분율입니다.



 a| 
스토리지 VM
 a| 
아이옵스
 a| 
SVM이 초당 처리하는 입출력 작업의 평균 수입니다.



 a| 
MB/초
 a| 
초당 이 SVM에서 전송되는 데이터의 평균 메가바이트 수입니다.



 a| 
숨어 있음
 a| 
SVM이 애플리케이션 요청에 응답하는 데 걸리는 평균 시간(밀리초)입니다.



 a| 
용량
 a| 
아이옵스
 a| 
볼륨이 초당 처리하는 입출력 작업의 평균 수입니다.



 a| 
MB/초
 a| 
초당 이 볼륨에서 전송되는 데이터의 평균 메가바이트 수입니다.



 a| 
숨어 있음
 a| 
볼륨이 애플리케이션 요청에 응답하는 데 걸리는 평균 시간(밀리초)입니다.



 a| 
캐시 미스 비율
 a| 
캐시에서 반환되는 대신 볼륨에서 반환되는 클라이언트 애플리케이션의 읽기 요청의 평균 백분율입니다.



 a| 
LUN
 a| 
아이옵스
 a| 
LUN이 초당 처리하는 입출력 작업의 평균 수입니다.



 a| 
MB/초
 a| 
초당 이 LUN에서 전송되는 데이터의 평균 메가바이트 수입니다.



 a| 
숨어 있음
 a| 
LUN이 애플리케이션 요청에 응답하는 데 걸리는 평균 밀리초 수입니다.



 a| 
네임스페이스
 a| 
아이옵스
 a| 
네임스페이스가 초당 처리하는 평균 입출력 작업 수입니다.



 a| 
MB/초
 a| 
초당 이 네임스페이스에서 전송되는 데이터의 평균 메가바이트 수입니다.



 a| 
숨어 있음
 a| 
네임스페이스가 애플리케이션 요청에 응답하는 데 걸리는 평균 시간(밀리초)입니다.



 a| 
포트
 a| 
대역폭 활용도
 a| 
포트의 사용 가능한 대역폭 중 현재 사용 중인 평균 비율입니다.



 a| 
MB/초
 a| 
초당 이 포트에서 전송되는 데이터의 평균 메가바이트 수입니다.



 a| 
네트워크 인터페이스(LIF)
 a| 
MB/초
 a| 
초당 이 LIF에서 전송되는 데이터의 평균 메가바이트 수입니다.

|===