---
permalink: performance-checker/reference_performance_event_severity_types.html 
sidebar: sidebar 
keywords: performance, event, severity, types 
summary: 각 성과 이벤트는 심각도 유형과 연결되어 있어 즉각적인 시정 조치가 필요한 이벤트의 우선 순위를 지정하는 데 도움이 됩니다. 
---
= 성능 이벤트 심각도 유형
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
각 성과 이벤트는 심각도 유형과 연결되어 있어 즉각적인 시정 조치가 필요한 이벤트의 우선 순위를 지정하는 데 도움이 됩니다.

* *비판적인*
+
시정 조치를 즉시 취하지 않으면 서비스 중단으로 이어질 수 있는 성능 이벤트가 발생했습니다.

+
중요 이벤트는 사용자가 정의한 임계값에서만 전송됩니다.

* *경고*
+
클러스터 개체의 성능 카운터가 정상 범위를 벗어났으며, 심각한 심각도에 도달하지 않도록 모니터링해야 합니다.  이 정도 심각도의 사건은 서비스 중단을 일으키지 않으며, 즉각적인 시정 조치가 필요하지 않을 수도 있습니다.

+
경고 이벤트는 사용자 정의, 시스템 정의 또는 동적 임계값에서 전송됩니다.

* *정보*
+
이 이벤트는 새로운 객체가 발견되거나 사용자 작업이 수행될 때 발생합니다.  예를 들어, 저장소 개체가 삭제되거나 구성이 변경되면 심각도 유형이 정보인 이벤트가 생성됩니다.

+
ONTAP 구성 변경을 감지하면 정보 이벤트를 직접 전송합니다.



자세한 내용은 다음 링크를 참조하세요.

* link:../events/concept_what_happens_when_an_event_is_received.html["이벤트가 수신되면 어떻게 되나요?"]
* link:../events/concept_what_information_is_contained_in_an_alert_email.html["알림 이메일에는 어떤 정보가 포함되어 있나요?"]
* link:../events/task_add_alerts.html["알림 추가"]
* link:../events/task_add_alerts_for_performance_events.html["성능 이벤트에 대한 알림 추가"]

