---
permalink: performance-checker/reference_what_data_does_workload_analyzer_display.html 
sidebar: sidebar 
keywords: workload analyzer, charts, display, data 
summary: 워크로드 분석기 페이지에는 워크로드에 영향을 줄 수 있는 현재 이벤트에 대한 정보, 이벤트를 발생시킨 문제를 해결하기 위한 권장 사항, 성능 및 용량 기록을 분석하기 위한 차트가 표시됩니다. 
---
= 워크로드 분석기는 어떤 데이터를 표시합니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
워크로드 분석기 페이지에는 워크로드에 영향을 줄 수 있는 현재 이벤트에 대한 정보, 이벤트를 발생시킨 문제를 해결하기 위한 권장 사항, 성능 및 용량 기록을 분석하기 위한 차트가 표시됩니다.

페이지 상단에서 분석하려는 작업 부하(볼륨 또는 LUN)의 이름과 통계를 보고자 하는 기간을 지정합니다.  원하는 경우 언제든지 기간을 변경하여 더 짧거나 긴 기간을 볼 수 있습니다.

페이지의 다른 영역에는 분석 결과, 성능 및 용량 차트가 표시됩니다.

[NOTE]
====
LUN에 대한 작업 부하 차트는 볼륨에 대한 차트와 동일한 수준의 통계를 제공하지 않으므로 이 두 가지 유형의 작업 부하를 분석할 때 차이점을 알 수 있습니다.

====
* *이벤트 요약 영역*
+
특정 기간 동안 발생한 이벤트의 수와 유형에 대한 간략한 개요를 표시합니다.  다양한 영향 영역(예: 성능 및 용량)에서 이벤트가 발생하는 경우, 관심 있는 이벤트 유형에 대한 세부 정보를 선택할 수 있도록 이 정보가 표시됩니다. 이벤트 유형을 클릭하면 이벤트 이름 목록이 표시됩니다.

+
해당 기간 동안 이벤트가 하나만 있는 경우, 일부 이벤트에 대해 문제를 해결하기 위한 권장 사항 목록이 나열됩니다.

* *이벤트 타임라인*
+
지정된 기간 동안 발생한 모든 이벤트를 표시합니다.  각 이벤트 위에 커서를 올려 놓으면 이벤트 이름을 볼 수 있습니다.

+
이벤트 세부 정보 페이지에서 *작업량 분석* 버튼을 클릭하여 이 페이지에 도달한 경우 선택한 이벤트의 아이콘이 더 크게 표시되어 이벤트를 식별할 수 있습니다.

* *성능 차트 영역*
+
선택한 시간대에 따라 지연 시간, 처리량(IOPS와 MB/s 모두), 사용률(노드와 집계 모두)에 대한 차트를 표시합니다.  추가 분석을 수행하려는 경우 작업 부하에 대한 성능 탐색기 페이지를 표시하려면 성능 세부 정보 보기 링크를 클릭하세요.

+
** *대기 시간*은 선택한 기간 동안 작업 부하에 대한 대기 시간을 표시합니다.  차트에는 다음 내용을 볼 수 있는 세 가지 보기가 있습니다.
+
*** *전체* 지연 시간
*** *분류* 대기 시간(읽기, 쓰기 및 기타 프로세스로 구분)
*** *클러스터 구성 요소* 지연 시간(클러스터 구성 요소별로 구분)






보다link:concept_cluster_components_and_why_they_can_be_in_contention.html["클러스터 구성 요소와 이들이 경쟁에 참여할 수 있는 이유"] 여기에 표시되는 클러스터 구성 요소에 대한 설명은 다음과 같습니다.  ** *처리량*은 선택한 기간 동안 작업 부하에 대한 IOPS와 MB/s 처리량을 모두 표시합니다.  차트에는 다음을 볼 수 있는 4가지 뷰가 있습니다. *** *전체* 처리량 *** *세부* 처리량(읽기, 쓰기 및 기타 프로세스로 구분) *** *클라우드 처리량*(클라우드에 데이터를 쓰고 클라우드에서 데이터를 읽는 데 사용되는 MB/s. 클라우드에 용량을 계층화하는 워크로드의 경우) *** *예측을 포함한 IOPS*(해당 기간 동안 상한 및 하한 IOPS 처리량 값이 어떻게 될지에 대한 예측) 이 차트에는 구성된 경우 QoS(서비스 품질) 최대 및 최소 처리량 임계값 설정도 표시되므로 시스템이 QoS 정책을 사용하여 의도적으로 처리량을 제한하는 위치를 확인할 수 있습니다.  ** *사용률*은 선택한 기간 동안 워크로드가 실행되는 집계 및 노드에 대한 사용률을 표시합니다.  여기에서 집계나 노드가 과도하게 사용되어 지연 시간이 길어지는지 확인할 수 있습니다.  FlexGroup 볼륨을 분석하면 활용도 차트에 여러 노드와 여러 집계가 나열됩니다.

* *수용 인원 차트 영역*
+
지난 한 달 동안의 작업 부하에 대한 데이터 용량과 스냅샷 용량에 대한 차트를 표시합니다.

+
볼륨의 경우, 추가 분석을 수행하려는 경우 작업 부하에 대한 상태 세부 정보 페이지를 표시하려면 용량 세부 정보 보기 링크를 클릭합니다.  LUN에는 상태 세부 정보 페이지가 없으므로 LUN은 이 링크를 제공하지 않습니다.

+
** *용량 보기*는 작업 부하에 할당된 총 사용 가능 공간과 논리적으로 사용된 공간(모든 NetApp 최적화 후)을 표시합니다.
** *스냅샷 보기*는 스냅샷 복사본에 예약된 총 공간과 현재 사용 중인 공간의 양을 표시합니다.  LUN은 스냅샷 보기를 제공하지 않습니다.
** *클라우드 계층 보기*는 로컬 성능 계층에서 얼마나 많은 용량이 사용되고 있는지, 그리고 클라우드 계층에서 얼마나 많은 용량이 사용되고 있는지를 표시합니다.  이러한 차트에는 해당 작업 부하에 대한 용량이 가득 차기까지 남은 시간에 대한 추정치가 포함되어 있습니다.  이 정보는 과거 사용 내역을 기반으로 하며 최소 10일 분의 데이터가 필요합니다.  남은 용량이 30일 미만이면 Unified Manager는 스토리지를 "거의 가득 참"으로 식별합니다.



