---
permalink: performance-checker/reference_performance_event_analysis_and_notification.html 
sidebar: sidebar 
keywords: performance, event, analysis, notification 
summary: 성능 이벤트는 클러스터 구성 요소의 경합으로 인해 작업 부하의 I/O 성능 문제에 대해 알려줍니다.  Unified Manager는 이벤트를 분석하여 관련된 모든 작업 부하, 경합 중인 구성 요소를 식별하고 이벤트가 여전히 해결해야 할 문제인지 여부를 확인합니다. 
---
= 성능 이벤트 분석 및 알림
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능 이벤트는 클러스터 구성 요소의 경합으로 인해 작업 부하의 I/O 성능 문제에 대해 알려줍니다.  Unified Manager는 이벤트를 분석하여 관련된 모든 작업 부하, 경합 중인 구성 요소를 식별하고 이벤트가 여전히 해결해야 할 문제인지 여부를 확인합니다.

Unified Manager는 클러스터의 볼륨에 대한 I/O 지연 시간(응답 시간)과 IOPS(작업)를 모니터링합니다.  예를 들어, 다른 작업 부하가 클러스터 구성 요소를 과도하게 사용하면 해당 구성 요소는 경쟁 상태에 놓이게 되어 작업 부하 수요를 충족할 수 있는 최적의 수준으로 작업을 수행할 수 없습니다.  동일한 구성 요소를 사용하는 다른 작업 부하의 성능에 영향을 미쳐 대기 시간이 늘어날 수 있습니다.  지연 시간이 동적 성능 임계값을 넘으면 Unified Manager가 성능 이벤트를 트리거하여 사용자에게 알립니다.



== 이벤트 분석

Unified Manager는 지난 15일간의 성능 통계를 사용하여 다음 분석을 수행하여 이벤트에 관련된 피해자 워크로드, 괴롭힘 워크로드 및 클러스터 구성 요소를 식별합니다.

* 지연 시간이 동적 성능 임계값(지연 시간 예측의 상한)을 초과한 피해자 워크로드를 식별합니다.
+
** HDD 또는 Flash Pool 하이브리드 집계(로컬 계층)의 볼륨의 경우 대기 시간이 5밀리초(ms)를 초과하고 IOPS가 초당 10개 작업(ops/sec)을 초과하는 경우에만 이벤트가 트리거됩니다.
** 모든 SSD 집계 또는 FabricPool 집계(클라우드 계층)의 볼륨의 경우 지연 시간이 1ms보다 크고 IOPS가 초당 100ops를 초과하는 경우에만 이벤트가 트리거됩니다.


* 경합 중인 클러스터 구성 요소를 식별합니다.
+
[NOTE]
====
클러스터 상호 연결에서 피해자 워크로드의 대기 시간이 1ms보다 크면 Unified Manager는 이를 심각한 문제로 간주하고 클러스터 상호 연결에 대한 이벤트를 트리거합니다.

====
* 클러스터 구성 요소를 과도하게 사용하여 경합을 일으키는 괴롭힘 작업 부하를 식별합니다.
* 클러스터 구성 요소의 활용도나 활동의 편차를 기준으로 관련 작업 부하를 순위를 매겨 클러스터 구성 요소 사용에서 가장 큰 변화를 보인 괴롭힘꾼과 가장 큰 영향을 받은 피해자를 파악합니다.


이벤트는 잠깐 동안만 발생할 수 있으며, 이벤트가 사용하는 구성 요소가 더 이상 경쟁하지 않으면 자동으로 수정될 수 있습니다.  연속 이벤트는 5분 간격으로 동일한 클러스터 구성 요소에 대해 반복 발생하고 활성 상태를 유지하는 이벤트입니다.  연속적인 이벤트의 경우 Unified Manager는 두 개의 연속된 분석 간격 동안 동일한 이벤트를 감지한 후 경고를 트리거합니다.

이벤트가 해결되면 해당 이벤트는 볼륨의 과거 성능 문제 기록의 일부로 Unified Manager에서 계속 사용할 수 있습니다.  각 이벤트에는 이벤트 유형과 관련된 볼륨, 클러스터, 클러스터 구성 요소를 식별하는 고유한 ID가 있습니다.

[NOTE]
====
하나의 볼륨이 동시에 두 개 이상의 이벤트에 관련될 수 있습니다.

====


== 이벤트 상태

이벤트는 다음 상태 중 하나일 수 있습니다.

* *활동적인*
+
성능 이벤트가 현재 활성화되어 있음을 나타냅니다(새로운 이벤트 또는 확인된 이벤트).  이벤트를 발생시킨 문제가 자체적으로 해결되지 않았거나 해결되지 않았습니다.  저장소 개체의 성능 카운터가 성능 임계값보다 높게 유지됩니다.

* *폐기됨*
+
이벤트가 더 이상 활성화되지 않았음을 나타냅니다.  이벤트를 발생시킨 문제가 스스로 해결되었습니다.  저장소 개체의 성능 카운터가 더 이상 성능 임계값을 초과하지 않습니다.





== 이벤트 알림

이벤트는 대시보드 페이지와 사용자 인터페이스의 다른 여러 페이지에 표시되며, 해당 이벤트에 대한 알림은 지정된 이메일 주소로 전송됩니다.  이벤트에 대한 자세한 분석 정보를 보고 이벤트 세부 정보 페이지와 작업 부하 분석 페이지에서 해결을 위한 제안을 받을 수 있습니다.



== 이벤트 상호작용

이벤트 세부 정보 페이지와 작업 부하 분석 페이지에서 다음과 같은 방법으로 이벤트와 상호 작용할 수 있습니다.

* 이벤트 위로 마우스를 가져가면 이벤트가 감지된 날짜와 시간을 알려주는 메시지가 표시됩니다.
+
동일한 기간에 여러 개의 이벤트가 있는 경우 메시지에는 이벤트 수가 표시됩니다.

* 단일 이벤트를 클릭하면 해당 이벤트에 대한 더 자세한 정보(관련 클러스터 구성 요소 포함)를 보여 주는 대화 상자가 표시됩니다.
+
논쟁의 여지가 있는 구성 요소는 빨간색으로 표시되어 있습니다.  *전체 분석 보기*를 클릭하면 이벤트 세부 정보 페이지에서 전체 분석을 볼 수 있습니다.  동일한 기간에 여러 이벤트가 있는 경우 대화 상자에는 가장 최근의 세 가지 이벤트에 대한 세부 정보가 표시됩니다.  이벤트를 클릭하면 이벤트 세부 정보 페이지에서 이벤트 분석을 볼 수 있습니다.


