---
permalink: performance-checker/reference_types_of_system_defined_performance_threshold_policies.html 
sidebar: sidebar 
keywords: system-defined, performance, threshold, policies, cluster, node. aggregate, qos 
summary: Unified Manager는 클러스터 성능을 모니터링하고 이벤트를 자동으로 생성하는 몇 가지 표준 임계값 정책을 제공합니다.  이러한 정책은 기본적으로 활성화되어 있으며, 모니터링된 성능 임계값이 위반되면 경고 또는 정보 이벤트를 생성합니다. 
---
= 시스템 정의 성능 임계값 정책 유형
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 클러스터 성능을 모니터링하고 이벤트를 자동으로 생성하는 몇 가지 표준 임계값 정책을 제공합니다.  이러한 정책은 기본적으로 활성화되어 있으며, 모니터링된 성능 임계값이 위반되면 경고 또는 정보 이벤트를 생성합니다.

[NOTE]
====
시스템 정의 성능 임계값 정책은 Cloud Volumes ONTAP, ONTAP Edge 또는 ONTAP Select 시스템에서는 활성화되지 않습니다.

====
시스템에서 정의한 성능 임계값 정책에서 불필요한 이벤트를 수신하는 경우 이벤트 설정 페이지에서 개별 정책에 대한 이벤트를 비활성화할 수 있습니다.



[[cluster-threshold-policies]]
== 클러스터 임계값 정책

시스템 정의 클러스터 성능 임계값 정책은 기본적으로 Unified Manager에서 모니터링하는 모든 클러스터에 할당됩니다.

* *클러스터 부하 불균형*
+
클러스터의 다른 노드보다 한 노드가 훨씬 더 높은 부하로 작동하여 잠재적으로 작업 부하 지연에 영향을 미치는 상황을 식별합니다.

+
이 기능은 클러스터의 모든 노드에 대해 사용된 성능 용량 값을 비교하여 24시간 이상 30% 임계값을 초과한 노드가 있는지 확인합니다.  이는 경고 이벤트입니다.

* *클러스터 용량 불균형*
+
클러스터 내 다른 집계보다 한 집계의 사용 용량이 훨씬 더 높은 상황을 식별하여 작업에 필요한 공간에 영향을 미칠 가능성이 있습니다.

+
클러스터 내 모든 집계의 사용된 용량 값을 비교하여 집계 간에 70%의 차이가 있는지 확인합니다.  이는 경고 이벤트입니다.





[[node-threshold-policies]]
== 노드 임계값 정책

시스템 정의 노드 성능 임계값 정책은 기본적으로 Unified Manager에서 모니터링하는 클러스터의 모든 노드에 할당됩니다.

* *성능 용량 사용 임계값 위반*
+
단일 노드가 운영 효율성의 한계를 넘어서 작동하고, 이로 인해 작업 대기 시간에 영향을 미칠 가능성이 있는 상황을 식별합니다.

+
이 기능은 12시간 이상 성능 용량의 100% 이상을 사용하는 노드를 찾아 이를 수행합니다.  이는 경고 이벤트입니다.

* *노드 HA 쌍이 과도하게 활용됨*
+
HA 쌍의 노드가 HA 쌍 운영 효율성의 경계를 넘어서 작동하는 상황을 식별합니다.

+
이는 HA 쌍의 두 노드에 대해 사용된 성능 용량 값을 살펴봄으로써 수행됩니다.  두 노드에서 사용된 결합된 성능 용량이 12시간 이상 200%를 초과하는 경우 컨트롤러 장애 조치로 인해 작업 대기 시간이 영향을 받습니다.  이것은 정보 제공을 위한 행사입니다.

* *노드 디스크 조각화*
+
집계된 디스크가 조각화되어 주요 시스템 서비스를 느리게 하고 노드의 작업 대기 시간에 영향을 미칠 수 있는 상황을 식별합니다.

+
이는 노드의 모든 집계에서 특정 읽기 및 쓰기 작업 비율을 살펴보는 방식으로 수행됩니다.  이 정책은 SyncMirror 재동기화 중이나 디스크 스크럽 작업 중 오류가 발견될 때도 트리거될 수 있습니다.  이는 경고 이벤트입니다.

+
[NOTE]
====
"노드 디스크 조각화" 정책은 HDD 전용 집계만 분석합니다. Flash Pool, SSD 및 FabricPool 집계는 분석되지 않습니다.

====




[[aggregate-threshold-policies]]
== 집계 임계값 정책

시스템 정의 집계 성능 임계값 정책은 Unified Manager에서 모니터링하는 클러스터의 모든 집계에 기본적으로 할당됩니다.

* *전체 디스크가 과도하게 활용됨*
+
집계가 운영 효율성의 한계를 초과하여 작동하여 작업 대기 시간에 영향을 미칠 수 있는 상황을 식별합니다.  이 기능은 집계된 디스크가 30분 이상 95% 이상 활용되는 집계를 찾아 이러한 상황을 식별합니다.  이 다중 조건 정책은 문제의 원인을 파악하기 위해 다음과 같은 분석을 수행합니다.

+
** 집계된 디스크 중 현재 백그라운드 유지 관리 활동이 진행 중인가요?
+
디스크가 진행할 수 있는 백그라운드 유지 관리 활동으로는 디스크 재구성, 디스크 스크러빙, SyncMirror 재동기화, 재패리티 등이 있습니다.

** 디스크 셸프 파이버 채널 상호 연결에 통신 병목 현상이 있습니까?
** 전체적으로 여유 공간이 너무 적습니까?  이 정책에 대한 경고 이벤트는 세 가지 하위 정책 중 하나(또는 그 이상)가 위반된 것으로 간주되는 경우에만 발행됩니다.  전체 디스크의 활용률이 95% 이상인 경우에만 성능 이벤트가 발생하지 않습니다.




[NOTE]
====
"`전체 디스크 과다 사용`" 정책은 HDD 전용 집계와 Flash Pool(하이브리드) 집계를 분석합니다. SSD 및 FabricPool 집계는 분석되지 않습니다.

====


[[workload-latency-threshold-policies]]
== 워크로드 지연 임계값 정책

시스템 정의 워크로드 지연 임계값 정책은 정의된 "예상 지연" 값을 갖는 구성된 성능 서비스 수준 정책이 있는 모든 워크로드에 할당됩니다.

* *성능 서비스 수준에 따라 정의된 작업 부하 볼륨/LUN 대기 시간 임계값 위반*
+
예상 대기 시간 한도를 초과하고 작업 부하 성능에 영향을 미치는 볼륨(파일 공유) 및 LUN을 식별합니다.  이는 경고 이벤트입니다.

+
이는 이전 시간 동안 예상 대기 시간 값을 30% 초과한 작업 부하를 찾아 이를 수행합니다.





[[qos-threshold-policies]]
== QoS 임계값 정책

시스템 정의 QoS 성능 임계값 정책은 ONTAP QoS 최대 처리량 정책(IOPS, IOPS/TB 또는 MB/s)이 구성된 모든 작업 부하에 할당됩니다.  Unified Manager는 작업 부하 처리량 값이 구성된 QoS 값보다 15% 낮을 때 이벤트를 트리거합니다.

* *QoS 최대 IOPS 또는 MB/s 임계값*
+
QoS 최대 IOPS 또는 MB/s 처리량 한도를 초과하고 작업 대기 시간에 영향을 미치는 볼륨과 LUN을 식별합니다.  이는 경고 이벤트입니다.

+
단일 작업 부하가 정책 그룹에 할당되면 이전 1시간 동안의 각 수집 기간 동안 할당된 QoS 정책 그룹에 정의된 최대 처리량 임계값을 초과한 작업 부하를 찾아 이를 수행합니다.

+
여러 작업 부하가 단일 QoS 정책을 공유하는 경우 정책에 포함된 모든 작업 부하의 IOPS 또는 MB/s를 추가하고 해당 합계를 임계값과 비교하여 이를 수행합니다.

* *QoS 피크 IOPS/TB 또는 블록 크기 임계값이 있는 IOPS/TB*
+
적응형 QoS 최대 IOPS/TB 처리량 한도(또는 블록 크기 한도가 있는 IOPS/TB)를 초과하고 작업 대기 시간에 영향을 미치는 볼륨을 식별합니다.  이는 경고 이벤트입니다.

+
이 기능은 적응형 QoS 정책에 정의된 최대 IOPS/TB 임계값을 각 볼륨의 크기에 따라 QoS 최대 IOPS 값으로 변환한 다음, 이전 1시간 동안의 각 성능 수집 기간 동안 QoS 최대 IOPS를 초과한 볼륨을 찾습니다.

+
[NOTE]
====
이 정책은 클러스터에 ONTAP 9.3 이상 소프트웨어가 설치된 경우에만 볼륨에 적용됩니다.

====
+
적응형 QoS 정책에서 "블록 크기" 요소가 정의된 경우 임계값은 각 볼륨의 크기에 따라 QoS 최대 MB/s 값으로 변환됩니다.  그런 다음 이전 1시간 동안의 각 성능 수집 기간 동안 QoS 최대 MB/s를 초과한 볼륨을 찾습니다.

+
[NOTE]
====
이 정책은 클러스터에 ONTAP 9.5 이상 소프트웨어가 설치된 경우에만 볼륨에 적용됩니다.

====

