---
permalink: performance-checker/reference_types_of_performance_counter_charts.html 
sidebar: sidebar 
keywords: types, performance, counter, charts 
summary: 선택한 저장 개체에 대한 카운터 값을 표시하는 표준 성능 차트가 있습니다.  각 분석 카운터 차트는 전체 값을 읽기, 쓰기 및 기타 범주로 구분하여 표시합니다.  또한, 일부 분석 카운터 차트는 확대/축소 보기에서 차트를 표시할 때 추가 세부 정보를 표시합니다. 
---
= 성과 카운터 차트의 유형
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
선택한 저장 개체에 대한 카운터 값을 표시하는 표준 성능 차트가 있습니다.  각 분석 카운터 차트는 전체 값을 읽기, 쓰기 및 기타 범주로 구분하여 표시합니다.  또한, 일부 분석 카운터 차트는 확대/축소 보기에서 차트를 표시할 때 추가 세부 정보를 표시합니다.

다음 표는 사용 가능한 성능 카운터 차트를 보여줍니다.

|===
| 사용 가능한 차트 | 차트 설명 


 a| 
이벤트
 a| 
루트 개체의 통계 차트와 연관하여 중요, 오류, 경고 및 정보 이벤트를 표시합니다.  성과 이벤트 외에도 건강 이벤트가 표시되어 성과에 영향을 줄 수 있는 이유를 전체적으로 파악할 수 있습니다.



 a| 
지연 시간 - 전체
 a| 
애플리케이션 요청에 응답하는 데 필요한 시간(밀리초)입니다.  평균 지연 시간 값은 I/O 가중치를 적용한 값입니다.



 a| 
지연 시간 - 고장
 a| 
Latency Total에 표시된 정보와 동일하지만, 성능 데이터가 읽기, 쓰기 및 기타 지연 시간으로 구분되어 있습니다.  이 차트 옵션은 선택한 개체가 SVM, 노드, 집계, 볼륨, LUN 또는 네임스페이스인 경우에만 적용됩니다.



 a| 
지연 시간 - 클러스터 구성 요소
 a| 
Latency Total에 표시된 정보와 동일하지만, 클러스터 구성 요소별로 성능 데이터가 지연 시간으로 구분되어 있습니다.  이 차트 옵션은 선택한 객체가 볼륨인 경우에만 적용됩니다.



 a| 
IOPS - 총
 a| 
초당 처리되는 입출력 작업 수.  노드에 대해 표시되는 경우, "총계"를 선택하면 로컬 또는 원격 노드에 상주할 수 있는 이 노드를 통과하는 데이터의 IOPS가 표시되고, "총계(로컬)"를 선택하면 현재 노드에만 상주하는 데이터의 IOPS가 표시됩니다.



 a| 
IOPS - 고장
 a| 
IOPS Total에 표시되는 정보와 동일하지만, 성능 데이터가 읽기, 쓰기 및 기타 IOPS로 구분되어 있습니다.  이 차트 옵션은 선택한 개체가 SVM, 노드, 집계, 볼륨, LUN 또는 네임스페이스인 경우에만 적용됩니다.

확대/축소 보기에서 표시되는 볼륨 차트에는 ONTAP 에서 구성된 경우 QoS 최소 및 최대 처리량 값이 표시됩니다.

노드에 대해 표시되는 경우, "분류"를 선택하면 로컬 또는 원격 노드에 상주할 수 있는 이 노드를 통과하는 데이터에 대한 IOPS 분류가 표시되고, "분류(로컬)"를 선택하면 현재 노드에만 상주하는 데이터에 대한 IOPS 분류가 표시됩니다.



 a| 
IOPS - 프로토콜
 a| 
IOPS Total에 표시되는 정보와 동일하지만, 성능 데이터는 CIFS, NFS, FCP, NVMe 및 iSCSI 프로토콜 트래픽에 대한 개별 차트로 구분됩니다.  이 차트 옵션은 선택한 객체가 SVM인 경우에만 적용됩니다.



 a| 
IOPS/TB - 총계
 a| 
작업 부하에 의해 소비되는 총 공간을 기준으로 초당 처리되는 입출력 작업 수(테라바이트)입니다.  I/O 밀도라고도 하는 이 카운터는 주어진 저장 용량으로 얼마나 많은 성능을 제공할 수 있는지 측정합니다.  줌 보기에서 볼륨 차트는 ONTAP 에서 구성된 경우 예상 QoS 값과 최대 처리량 값을 표시합니다.

이 차트 옵션은 선택한 객체가 볼륨인 경우에만 적용됩니다.



 a| 
MB/s - 총계
 a| 
초당 객체와 주고받는 데이터의 메가바이트 수입니다.



 a| 
MB/s - 분석
 a| 
MB/s 차트에 표시된 정보는 동일하지만, 처리량 데이터는 디스크 읽기, 플래시 캐시 읽기, 쓰기 및 기타로 구분됩니다.  확대/축소 보기에서 표시되는 볼륨 차트는 ONTAP 에서 구성된 경우 QoS 최대 처리량 값을 표시합니다.

이 차트 옵션은 선택한 개체가 SVM, 노드, 집계, 볼륨, LUN 또는 네임스페이스인 경우에만 적용됩니다.

[NOTE]
====
Flash Cache 데이터는 노드에 대해서만 표시되며, 노드에 Flash Cache 모듈이 설치된 경우에만 표시됩니다.

====


 a| 
사용된 성능 용량 - 총계
 a| 
노드 또는 집계에서 소비되는 성능 용량의 백분율입니다.



 a| 
사용된 성능 용량 - 고장
 a| 
성능 용량 사용된 데이터는 사용자 프로토콜과 시스템 백그라운드 프로세스로 구분됩니다.  또한, 무료로 제공되는 성능 용량도 표시됩니다.



 a| 
사용 가능한 IOPS - 총계
 a| 
이 객체에서 현재 사용 가능한(무료) 초당 입출력 작업 수입니다.  이 숫자는 Unified Manager가 개체가 수행할 수 있다고 계산한 총 IOPS에서 현재 사용 중인 IOPS를 뺀 결과입니다.  이 차트 옵션은 선택한 개체가 노드나 집계인 경우에만 적용됩니다.



 a| 
활용도 - 총
 a| 
사용 중인 객체의 사용 가능한 리소스 비율입니다.  사용률은 노드의 경우 노드 사용률, 집계의 경우 디스크 사용률, 포트의 경우 대역폭 사용률을 나타냅니다.  이 차트 옵션은 선택한 개체가 노드, 집계 또는 포트인 경우에만 적용됩니다.



 a| 
캐시 미스 비율 - 전체
 a| 
캐시에서 반환되는 대신 디스크에서 반환되는 클라이언트 애플리케이션의 읽기 요청 비율입니다.  이 차트 옵션은 선택한 객체가 볼륨인 경우에만 적용됩니다.

|===