---
permalink: performance-checker/reference_components_of_node_failover_planning_page.html 
sidebar: sidebar 
keywords: components, node, failover, planning page, performance, statistics, grid 
summary: 성능/노드 장애 조치 계획 페이지의 구성 요소는 그리드와 비교 창에 표시됩니다.  이 섹션에서는 노드 장애 조치가 인수 노드의 성능에 미치는 영향을 평가할 수 있습니다. 
---
= 노드 장애 조치 계획 페이지의 구성 요소
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능/노드 장애 조치 계획 페이지의 구성 요소는 그리드와 비교 창에 표시됩니다.  이 섹션에서는 노드 장애 조치가 인수 노드의 성능에 미치는 영향을 평가할 수 있습니다.



== 성능 통계 그리드

성능/노드 장애 조치 계획 페이지에는 지연 시간, IOPS, 활용도, 사용된 성능 용량에 대한 통계가 포함된 표가 표시됩니다.

[NOTE]
====
이 페이지와 성능/노드 성능 탐색기 페이지에 표시되는 대기 시간 및 IOPS 값은 노드 장애 조치를 예측하는 데 사용되는 값에 따라 다른 성능 카운터가 사용되므로 일치하지 않을 수 있습니다.

====
그리드에서 각 노드에는 다음 역할 중 하나가 지정됩니다.

* 주요한
+
파트너가 실패할 때 HA 파트너를 대신하여 작업을 수행하는 노드입니다.  루트 객체는 항상 기본 노드입니다.

* 파트너
+
장애 조치 시나리오에서 실패한 노드입니다.

* 예상 인수
+
기본 노드와 동일합니다.  이 노드에 대해 표시되는 성능 통계는 실패한 파트너를 인수한 후 인수 노드의 성능을 보여줍니다.



[NOTE]
====
인수 노드의 작업 부하가 장애 조치 후 두 노드의 작업 부하를 합친 것과 동일하지만, 예상 인수 노드의 통계는 기본 노드와 파트너 노드의 통계를 합친 것이 아닙니다.  예를 들어, 기본 노드의 지연 시간이 2ms/op이고 파트너 노드의 지연 시간이 3ms/op인 경우, 예상 인수 노드의 지연 시간은 4ms/op가 될 수 있습니다.  이 값은 Unified Manager가 수행하는 계산입니다.

====
루트 개체가 되도록 하려면 파트너 노드의 이름을 클릭하면 됩니다.  성능/노드 성능 탐색기 페이지가 표시된 후 *장애 조치 계획* 탭을 클릭하면 이 노드 장애 시나리오에서 성능이 어떻게 변하는지 확인할 수 있습니다.  예를 들어, Node1이 기본 노드이고 Node2가 파트너 노드인 경우 Node2를 클릭하여 기본 노드로 만들 수 있습니다.  이렇게 하면 어떤 노드가 실패하느냐에 따라 예상 성능이 어떻게 달라지는지 확인할 수 있습니다.



== 비교 창

다음 목록은 기본적으로 비교 창에 표시되는 구성 요소를 설명합니다.

* *이벤트 차트*
+
이는 성능/노드 성능 탐색기 페이지와 동일한 형식으로 표시됩니다.  이는 기본 노드에만 적용됩니다.

* *카운터 차트*
+
그리드에 표시된 성능 카운터에 대한 과거 통계를 표시합니다.  각 차트에서 예상 인수 노드의 그래프는 특정 시점에 장애 조치가 발생했을 경우 예상되는 성능을 보여줍니다.

+
예를 들어, 2월 8일 오전 11시에 예상 인수 노드의 활용도 차트가 73%를 보여준다고 가정해 보겠습니다.  만약 그 시점에 장애 조치가 발생했다면, 인수 노드의 활용도는 73%가 되었을 것입니다.

+
과거 통계는 장애 조치를 시작하기 위한 최적의 시간을 찾는 데 도움이 되며, 이를 통해 인수 노드에 과부하가 걸릴 가능성을 최소화할 수 있습니다.  인수 노드의 예상 성능이 허용 가능한 시간에만 장애 조치를 예약할 수 있습니다.



기본적으로 루트 개체와 파트너 노드에 대한 통계는 비교 창에 표시됩니다.  성능/노드 성능 탐색기 페이지와 달리 이 페이지에는 통계 비교를 위해 객체를 추가할 수 있는 *추가* 버튼이 표시되지 않습니다.

성능/노드 성능 탐색기 페이지에서와 같은 방식으로 비교 창을 사용자 지정할 수 있습니다.  다음 목록은 차트를 사용자 지정하는 예를 보여줍니다.

* 카운터 차트에서 노드 통계를 표시하거나 숨기려면 노드 이름을 클릭하세요.
* *확대 보기*를 클릭하면 새 창에 특정 카운터에 대한 자세한 차트가 표시됩니다.

