---
permalink: performance-checker/reference_performance_data_that_can_be_sent_to_an_external_server.html 
sidebar: sidebar 
keywords: performance, data, external, server 
summary: Unified Manager는 모니터링하는 모든 클러스터에서 다양한 성능 데이터를 수집합니다.  특정 데이터 그룹을 외부 서버로 보낼 수 있습니다. 
---
= 외부 서버로 전송할 수 있는 성능 데이터
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 모니터링하는 모든 클러스터에서 다양한 성능 데이터를 수집합니다.  특정 데이터 그룹을 외부 서버로 보낼 수 있습니다.

차트로 작성하려는 성과 데이터에 따라 다음 통계 그룹 중 하나를 선택하여 보낼 수 있습니다.

|===
| 통계 그룹 | 포함된 데이터 | 세부 


 a| 
성능 모니터
 a| 
다음 개체에 대한 고급 성능 통계:

* LUN
* 볼륨

 a| 
이 그룹은 모니터링되는 모든 클러스터의 모든 LUN과 볼륨에 대한 총 IOPS 또는 대기 시간을 제공합니다.

이 그룹은 가장 적은 수의 통계를 제공합니다.



 a| 
자원 활용
 a| 
다음 개체에 대한 리소스 활용 통계:

* 노드
* 골재

 a| 
이 그룹은 모니터링되는 모든 클러스터의 노드와 물리적 리소스에 대한 활용 통계를 제공합니다.

또한 성능 모니터 그룹에서 수집된 통계도 제공합니다.



 a| 
드릴 다운
 a| 
추적된 모든 개체에 대한 저수준 읽기/쓰기 및 프로토콜별 통계:

* 노드
* 골재
* LUN
* 볼륨
* 디스크
* LIFs
* 포트/NIC

 a| 
이 그룹은 모니터링되는 모든 클러스터의 추적된 7개 객체 유형에 대한 읽기/쓰기 및 프로토콜별 분석을 제공합니다.

또한 성능 모니터 그룹과 리소스 활용도 그룹에서 수집된 통계도 제공합니다.

이 그룹은 가장 많은 통계를 제공합니다.

|===
[NOTE]
====
스토리지 시스템에서 클러스터 또는 클러스터 개체의 이름이 변경되면 이전 개체와 새 개체 모두 외부 서버의 성능 데이터(`metric_path`라고 함)를 포함하게 됩니다.  두 객체는 동일한 객체로 연관되지 않습니다.  예를 들어, 볼륨의 이름을 "`volume1_acct`"에서 "`acct_vol1`"로 변경하면 이전 볼륨의 이전 성능 데이터와 새 볼륨의 새 성능 데이터가 표시됩니다.

====
외부 데이터 공급자에게 전송할 수 있는 모든 성능 카운터 목록은 기술 자료 문서 30096을 참조하세요.

https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Infrastructure_Management%2FActive_IQ_Unified_Manager%2FWhat_are_the_ActiveIQ_Unified_Manager_performance_counters_that_can_be_exported_to_an_External_Data_Provider%253F["외부 데이터 공급자로 내보낼 수 있는 Unified Manager 성능 카운터"]
