---
permalink: performance-checker/task_respond_to_user_defined_performance_threshold_events.html 
sidebar: sidebar 
keywords: user-defined, performance, threshold, events 
summary: Unified Manager를 사용하면 성능 카운터가 사용자 정의 경고 또는 위험 임계값을 넘어선 경우 발생하는 성능 이벤트를 조사할 수 있습니다.  Unified Manager를 사용하여 클러스터 구성 요소의 상태를 확인하여 구성 요소에서 최근에 감지된 상태 이벤트가 성능 이벤트에 영향을 미쳤는지 확인할 수도 있습니다. 
---
= 사용자 정의 성능 임계값 이벤트에 응답
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 사용하면 성능 카운터가 사용자 정의 경고 또는 위험 임계값을 넘어선 경우 발생하는 성능 이벤트를 조사할 수 있습니다.  Unified Manager를 사용하여 클러스터 구성 요소의 상태를 확인하여 구성 요소에서 최근에 감지된 상태 이벤트가 성능 이벤트에 영향을 미쳤는지 확인할 수도 있습니다.

.시작하기 전에
* 운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 새로운 공연 이벤트나 더 이상 진행되지 않는 공연 이벤트가 있어야 합니다.


.단계
. 이벤트에 대한 정보를 보려면 *이벤트 세부 정보* 페이지를 표시하세요.
. 이벤트를 발생시킨 임계값 위반에 대한 설명이 있는 *설명*을 검토하세요.
+
예를 들어, "`456ms/op의 대기 시간 값이 400ms/op의 임계값 설정을 기반으로 경고 이벤트를 트리거했습니다`"라는 메시지는 해당 개체에 대해 대기 시간 경고 이벤트가 발생했음을 나타냅니다.

. 이벤트를 트리거한 임계값 정책에 대한 세부 정보를 표시하려면 정책 이름 위에 커서를 올려놓으세요.
+
여기에는 정책 이름, 평가 중인 성능 카운터, 중요 또는 경고 이벤트로 간주되기 위해 위반해야 하는 카운터 값, 카운터가 해당 값을 초과해야 하는 기간 등이 포함됩니다.

. *이벤트 트리거 시간*을 기록해 두면 이 이벤트에 영향을 줄 수 있는 다른 이벤트가 동시에 발생했는지 조사할 수 있습니다.
. 아래 옵션 중 하나를 따라 이벤트를 자세히 조사하고 성능 문제를 해결하기 위해 수행해야 할 작업이 있는지 확인하세요.
+
|===
| 옵션 | 가능한 조사 조치 


 a| 
소스 개체 이름을 클릭하면 해당 개체의 탐색기 페이지가 표시됩니다.
 a| 
이 페이지에서는 객체 세부 정보를 보고 이 객체를 다른 유사한 저장소 객체와 비교하여 다른 저장소 객체에 비슷한 시기에 성능 문제가 있는지 확인할 수 있습니다.  예를 들어, 동일한 집계에 있는 다른 볼륨에도 성능 문제가 있는지 확인합니다.



 a| 
클러스터 이름을 클릭하면 클러스터 요약 페이지가 표시됩니다.
 a| 
이 페이지에서는 이 개체가 있는 클러스터에 대한 세부 정보를 보고 비슷한 시기에 다른 성능 문제가 발생했는지 확인할 수 있습니다.

|===

