---
permalink: performance-checker/task_view_node_iops_based_on_workloads_on_local_node.html 
sidebar: sidebar 
keywords: view, node, iops, workloads, reside, only, local node 
summary: '노드 IOPS 카운터 차트는 네트워크 LIF를 사용하여 원격 노드의 볼륨에 대한 읽기/쓰기 작업을 수행하는 로컬 노드를 통해서만 작업이 전달되는 위치를 강조할 수 있습니다.  IOPS - "전체(로컬)" 및 "세부 정보(로컬)" 차트는 현재 노드의 로컬 볼륨에만 있는 데이터의 IOPS를 표시합니다.' 
---
= 로컬 노드에만 있는 작업 부하를 기반으로 노드 IOPS 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드 IOPS 카운터 차트는 네트워크 LIF를 사용하여 원격 노드의 볼륨에 대한 읽기/쓰기 작업을 수행하는 로컬 노드를 통해서만 작업이 전달되는 위치를 강조할 수 있습니다.  IOPS - "전체(로컬)" 및 "세부내역(로컬)" 차트는 현재 노드의 로컬 볼륨에만 있는 데이터의 IOPS를 표시합니다.

이러한 카운터 차트의 "`로컬`" 버전은 로컬 볼륨에 있는 데이터에 대한 통계만 표시하기 때문에 성능, 용량 및 활용도에 대한 노드 차트와 비슷합니다.

이러한 카운터 차트의 "로컬" 버전을 이러한 카운터 차트의 일반 전체 버전과 비교하면 원격 노드의 볼륨에 액세스하기 위해 로컬 노드를 통해 많은 트래픽이 이동하는지 확인할 수 있습니다.  로컬 노드를 통과하는 작업이 너무 많아 원격 노드의 볼륨에 도달하지 못하는 경우, 노드의 활용도가 높아져 성능 문제가 발생할 수 있습니다.  이러한 경우 볼륨을 로컬 노드로 이동하거나 해당 볼륨에 액세스하는 호스트의 트래픽을 연결할 수 있는 원격 노드에 LIF를 만들 수 있습니다.

.단계
. 선택한 노드의 *성능/노드 탐색기* 페이지에서 IOPS 차트의 드롭다운 메뉴에서 *전체*를 선택합니다.
+
IOPS - 전체 차트가 표시됩니다.

. *확대 보기*를 클릭하면 새 브라우저 탭에서 차트의 더 큰 버전을 볼 수 있습니다.
. *성능/노드 탐색기* 페이지로 돌아가서 IOPS 차트의 드롭다운 메뉴에서 *전체(로컬)*를 선택합니다.
+
IOPS - 전체(로컬) 차트가 표시됩니다.

. *확대 보기*를 클릭하면 새 브라우저 탭에서 차트의 더 큰 버전을 볼 수 있습니다.
. 두 차트를 나란히 보고 IOPS 값이 상당히 다른 영역을 파악해 보세요.
. 특정 시점의 로컬 IOPS와 전체 IOPS를 비교하려면 커서를 이 영역 위로 이동하세요.

