---
permalink: performance-checker/task_analyze_performance_incident_in_metrocluster.html 
sidebar: sidebar 
keywords: analyzing, dynamic, performance, event, remote, cluster, metrocluster, configuration 
summary: Unified Manager를 사용하면 MetroCluster 구성의 원격 클러스터에서 동적 성능 이벤트를 분석할 수 있습니다.  분석을 통해 원격 클러스터의 이벤트가 파트너 클러스터에서 이벤트를 발생시켰는지 여부를 확인하는 데 도움이 됩니다. 
---
= MetroCluster 구성의 원격 클러스터에 대한 동적 성능 이벤트 분석
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 사용하면 MetroCluster 구성의 원격 클러스터에서 동적 성능 이벤트를 분석할 수 있습니다.  분석을 통해 원격 클러스터의 이벤트가 파트너 클러스터에서 이벤트를 발생시켰는지 여부를 확인하는 데 도움이 됩니다.

.시작하기 전에
* 운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* MetroCluster 구성의 로컬 클러스터에서 성능 이벤트를 분석하고 이벤트 감지 시간을 얻었어야 합니다.
* 성능 이벤트에 관련된 로컬 클러스터와 파트너 클러스터의 상태를 확인하고 파트너 클러스터의 이름을 얻어야 합니다.


.단계
. 파트너 클러스터를 모니터링하는 Unified Manager 인스턴스에 로그인합니다.
. 왼쪽 탐색 창에서 *이벤트*를 클릭하면 이벤트 목록이 표시됩니다.
. *시간 범위* 선택기에서 *지난 1시간*을 선택한 다음 *범위 적용*을 클릭합니다.
. *필터링* 선택기에서 왼쪽 드롭다운 메뉴에서 *클러스터*를 선택하고, 텍스트 필드에 파트너 클러스터의 이름을 입력한 다음 *필터 적용*을 클릭합니다.
+
선택한 클러스터에서 지난 1시간 동안 이벤트가 발생하지 않은 경우, 파트너에서 이벤트가 감지된 시간 동안 클러스터에 성능 문제가 발생하지 않았음을 나타냅니다.

. 선택한 클러스터에서 지난 1시간 동안 이벤트가 감지된 경우 이벤트 감지 시간을 로컬 클러스터의 이벤트 감지 시간과 비교합니다.
+
이러한 이벤트에 데이터 처리 구성 요소에서 경합을 일으키는 괴롭힘 작업 부하가 포함된 경우, 이러한 괴롭힘 중 하나 이상이 로컬 클러스터에서 이벤트를 발생시켰을 수 있습니다.  이벤트를 클릭하면 이벤트를 분석하고 이벤트 세부 정보 페이지에서 이벤트 해결을 위한 제안된 조치를 검토할 수 있습니다.

+
이러한 이벤트에 괴롭힘 워크로드가 포함되지 않은 경우 로컬 클러스터에서 성능 이벤트가 발생하지 않습니다.


