---
permalink: performance-checker/task_respond_to_system_defined_node_resources_overutilized.html 
sidebar: sidebar 
keywords: node, resources, overutilized, performance, events 
summary: Unified Manager는 단일 노드가 운영 효율성의 한계를 초과하여 작동하고 이로 인해 워크로드 대기 시간에 영향을 미칠 가능성이 있는 경우 노드 리소스 과다 사용 경고 이벤트를 생성합니다.  이러한 시스템 정의 이벤트는 많은 작업 부하가 지연으로 인해 영향을 받기 전에 잠재적인 성능 문제를 해결할 수 있는 기회를 제공합니다. 
---
= 노드 리소스가 과도하게 사용되는 성능 이벤트에 대응합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 단일 노드가 운영 효율성의 한계를 초과하여 작동하고 이로 인해 워크로드 대기 시간에 영향을 미칠 가능성이 있는 경우 노드 리소스 과다 사용 경고 이벤트를 생성합니다.  이러한 시스템 정의 이벤트는 많은 작업 부하가 지연으로 인해 영향을 받기 전에 잠재적인 성능 문제를 해결할 수 있는 기회를 제공합니다.

.시작하기 전에
* 운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 새로운 공연 이벤트나 더 이상 진행되지 않는 공연 이벤트가 있어야 합니다.


Unified Manager는 30분 이상 성능 용량의 100% 이상을 사용하는 노드를 찾아 노드 리소스가 과도하게 사용되는 정책 위반에 대한 경고 이벤트를 생성합니다.

시스템 관리자나 ONTAP 명령을 사용하여 다음 작업을 포함하여 이러한 유형의 성능 문제를 해결할 수 있습니다.

* 시스템 리소스를 과도하게 사용하는 볼륨이나 LUN에 QoS 정책을 만들고 적용합니다.
* 작업 부하가 적용된 정책 그룹의 QoS 최대 처리량 한도 감소
* 작업 부하를 다른 집계 또는 노드로 이동
* 노드에 디스크를 추가하거나 더 빠른 CPU와 더 많은 RAM을 갖춘 노드로 업그레이드하여 용량을 늘립니다.


.단계
. 이벤트에 대한 정보를 보려면 *이벤트 세부 정보* 페이지를 표시하세요.
. 이벤트를 발생시킨 임계값 위반에 대한 설명이 있는 *설명*을 검토하세요.
+
예를 들어, "`Perf.  simplicity-02에서 사용된 용량 값이 139%로 인해 데이터 처리 장치의 잠재적인 성능 문제를 식별하기 위한 경고 이벤트가 발생했습니다. `"는 노드 simplicity-02의 성능 용량이 과도하게 사용되어 노드 성능에 영향을 미치고 있음을 나타냅니다.

. *시스템 진단* 섹션에서 세 개의 차트를 검토합니다. 하나는 노드에서 사용된 성능 용량, 다른 하나는 상위 워크로드에서 사용되는 평균 스토리지 IOPS, 다른 하나는 상위 워크로드의 대기 시간에 대한 차트입니다.  이런 식으로 정리하면 노드에서 지연을 유발하는 작업 부하가 무엇인지 확인할 수 있습니다.
+
커서를 IOPS 차트 위로 옮기면 어떤 워크로드에 QoS 정책이 적용되었고 어떤 워크로드에 적용되지 않았는지 확인할 수 있습니다.

. *제안된 작업* 섹션에서 제안 사항을 검토하고 작업 부하로 인한 지연 시간이 증가하는 것을 방지하기 위해 수행해야 할 작업을 결정합니다.
+
필요한 경우 *도움말* 버튼을 클릭하여 성능 이벤트를 해결하기 위해 수행할 수 있는 제안된 작업에 대한 자세한 내용을 확인하세요.


