---
permalink: performance-checker/task_move_workloads_to_another_node_in_different_ha_pair.html 
sidebar: sidebar 
keywords: move, workloads, another, node, different, ha pair 
summary: Unified Manager를 사용하면 현재 워크로드가 실행 중인 HA 쌍보다 사용량이 적은 다른 HA 쌍의 노드에서 집계를 식별하는 데 도움이 될 수 있습니다.  그런 다음 선택한 볼륨을 새 HA 쌍의 집계로 이동할 수 있습니다.  고성능 작업 부하를 덜 바쁜 노드에 모아두면 두 노드의 작업 부하가 더 효율적으로 수행될 수 있습니다. 
---
= 다른 HA 쌍의 다른 노드로 작업 부하 이동
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 사용하면 현재 워크로드가 실행 중인 HA 쌍보다 사용량이 적은 다른 HA 쌍의 노드에서 집계를 식별하는 데 도움이 될 수 있습니다.  그런 다음 선택한 볼륨을 새 HA 쌍의 집계로 이동할 수 있습니다.  고성능 작업 부하를 덜 바쁜 노드에 모아두면 두 노드의 작업 부하가 더 효율적으로 수행될 수 있습니다.

.시작하기 전에
* 운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 클러스터는 최소 두 개의 HA 쌍으로 구성되어야 합니다. 클러스터에 HA 쌍이 하나만 있는 경우 이 수정 프로세스를 사용할 수 없습니다.
* 현재 성능 문제가 발생하고 있는 HA 쌍의 두 노드 이름을 기록했어야 합니다.
* 노드가 성능 이벤트를 수신한 날짜와 시간을 기록했어야 합니다.
* Unified Manager는 한 달 이상의 성과 데이터를 수집하고 분석해야 합니다.


이러한 단계를 수행하면 다음 리소스를 식별하여 고성능 워크로드를 다른 HA 쌍의 활용도가 낮은 노드로 이동할 수 있습니다.

* 동일 클러스터의 다른 HA 쌍에 있는 노드 중 활용도가 낮은 노드
* 가장 적게 활용되는 새 노드의 집계
* 현재 노드에서 가장 높은 성능을 보이는 볼륨


.단계
. 동일한 클러스터의 다른 HA 쌍에 속하는 노드를 식별합니다.
+
.. 왼쪽 탐색 창에서 *저장소* > *클러스터*를 클릭하고 보기 메뉴에서 *성능* > *모든 클러스터*를 선택합니다.
+
성능: 모든 클러스터 보기가 표시됩니다.

.. 현재 클러스터의 *노드 수* 필드에서 숫자를 클릭합니다.
+
성능: 모든 노드 보기가 표시됩니다.

.. 현재 성능 문제가 있는 HA 쌍과 다른 HA 쌍에 있는 노드의 이름을 적어 두세요.


. 새로운 HA 쌍에서 가장 활용도가 낮은 노드를 식별합니다.
+
.. *활용률* 열을 클릭하면 활용률이 가장 낮은 노드순으로 정렬됩니다.
+
또한 가장 큰 *여유 용량*을 가진 노드를 식별할 수도 있습니다.  이는 작업 부하를 이동할 수 있는 잠재적 노드 목록을 제공합니다.

.. 작업 부하를 이동하려는 노드의 이름을 적어 두세요.


. 새 노드에서 가장 활용도가 낮은 집계를 식별합니다.
+
.. 왼쪽 탐색 창에서 *저장소* > *집계*를 클릭하고 보기 메뉴에서 *성능* > *모든 집계*를 선택합니다.
+
성과: 모든 집계 보기가 표시됩니다.

.. *필터링*을 클릭하고 왼쪽 드롭다운 메뉴에서 *노드*를 선택한 다음 텍스트 필드에 노드 이름을 입력하고 *필터 적용*을 클릭합니다.
+
성능: 모든 집계 보기가 이 노드에서 사용할 수 있는 집계 목록과 함께 다시 표시됩니다.

.. *활용률* 열을 클릭하면 활용률이 가장 낮은 순으로 집계가 정렬됩니다.
+
또한 가장 큰 *여유 용량*을 가진 집계를 식별할 수도 있습니다.  이는 작업 부하를 이동하려는 잠재적인 집계 목록을 제공합니다.

.. 작업 부하를 이동하려는 집계의 이름을 적어 두세요.


. 이벤트를 수신한 노드에서 고성능 워크로드를 식별합니다.
+
.. 이벤트의 *이벤트* 세부정보 페이지로 돌아가세요.
.. *영향을 받는 볼륨* 필드에서 첫 번째 노드의 볼륨 수에 대한 링크를 클릭합니다.
+
성능: 모든 볼륨 보기에는 해당 노드의 볼륨이 필터링된 목록으로 표시됩니다.

.. *총 용량* 열을 클릭하여 할당된 가장 큰 공간순으로 볼륨을 정렬합니다.
+
이는 이동하고 싶을 수 있는 잠재적 볼륨 목록을 제공합니다.

.. 이동하려는 볼륨의 이름과 해당 볼륨이 있는 현재 집계의 이름을 적어 두세요.
.. 이 이벤트에 포함된 두 번째 노드에 대해 4c 및 4d 단계를 수행하여 해당 노드에서 이동하려는 볼륨을 식별합니다.


. 새 노드에서 활용도가 낮은 것으로 확인된 집계로 볼륨을 이동합니다.
+
ONTAP System Manager, OnCommand Workflow Automation, ONTAP 명령 또는 이러한 도구를 조합하여 이동 작업을 수행할 수 있습니다.



며칠 후에 이 노드나 집계에서 동일한 유형의 이벤트를 수신하는지 확인하세요.
