---
permalink: performance-checker/task_respond_to_cluster_imbalance_performance_events.html 
sidebar: sidebar 
keywords: cluster, imbalance, performance, events 
summary: Unified Manager는 클러스터의 한 노드가 다른 노드보다 훨씬 높은 부하로 작동하고 이로 인해 작업 부하 대기 시간에 영향을 미칠 가능성이 있는 경우 클러스터 불균형 경고 이벤트를 생성합니다.  이러한 시스템 정의 이벤트는 많은 작업 부하가 지연으로 인해 영향을 받기 전에 잠재적인 성능 문제를 해결할 수 있는 기회를 제공합니다. 
---
= 클러스터 불균형 성능 이벤트에 대응
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 클러스터의 한 노드가 다른 노드보다 훨씬 높은 부하로 작동하고 이로 인해 작업 부하 대기 시간에 영향을 미칠 가능성이 있는 경우 클러스터 불균형 경고 이벤트를 생성합니다.  이러한 시스템 정의 이벤트는 많은 작업 부하가 지연으로 인해 영향을 받기 전에 잠재적인 성능 문제를 해결할 수 있는 기회를 제공합니다.

.시작하기 전에
운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

Unified Manager는 클러스터의 모든 노드에 대해 사용된 성능 용량 값을 비교하여 노드 간에 30%의 부하 차이가 있는지 확인하여 클러스터 불균형 임계값 정책 위반에 대한 경고 이벤트를 생성합니다.

이러한 단계를 통해 다음 리소스를 식별하여 고성능 워크로드를 활용도가 낮은 노드로 이동할 수 있습니다.

* 동일 클러스터에서 활용도가 낮은 노드
* 새 노드에서 가장 적게 활용되는 집계
* 현재 노드에서 가장 높은 성능을 보이는 볼륨


.단계
. 이벤트에 대한 정보를 보려면 *이벤트* 세부 정보 페이지를 표시합니다.
. 이벤트를 발생시킨 임계값 위반에 대한 설명이 있는 *설명*을 검토하세요.
+
예를 들어, "`성능 용량 사용 카운터는 클러스터 Dallas-1-8의 노드 간에 62%의 부하 차이를 나타내며 시스템 임계값 30%에 따라 경고 이벤트를 트리거했습니다`"라는 메시지는 노드 중 하나에서 성능 용량이 과도하게 사용되어 노드 성능에 영향을 미치고 있음을 나타냅니다.

. *제안된 작업*의 텍스트를 검토하여 고성능 볼륨을 고성능 용량 사용 값이 있는 노드에서 성능 용량 사용 값이 가장 낮은 노드로 이동합니다.
. 가장 높고 가장 낮은 성능 용량 사용 값을 갖는 노드를 식별합니다.
+
.. *이벤트 정보* 섹션에서 소스 클러스터의 이름을 클릭합니다.
.. *클러스터/성능 요약* 페이지에서 *관리되는 개체* 영역의 *노드*를 클릭합니다.
.. *노드* 인벤토리 페이지에서 *성능 용량 사용* 열에 따라 노드를 정렬합니다.
.. 가장 높고 가장 낮은 성능 용량 사용 값을 갖는 노드를 식별하고 해당 이름을 적어 둡니다.


. 가장 높은 성능 용량 사용 값을 갖는 노드에서 가장 많은 IOPS를 사용하는 볼륨을 식별합니다.
+
.. 가장 높은 성능 용량 사용 값을 갖는 노드를 클릭하세요.
.. *노드/성능 탐색기* 페이지에서 *보기 및 비교* 메뉴에서 *이 노드의 집계*를 선택합니다.
.. 가장 높은 성능 용량 사용 값을 갖는 집계를 클릭하세요.
.. *집계/성능 탐색기* 페이지에서 *보기 및 비교* 메뉴에서 *이 집계의 볼륨*을 선택합니다.
.. *IOPS* 열로 볼륨을 정렬하고 가장 많은 IOPS를 사용하는 볼륨의 이름과 볼륨이 있는 집계의 이름을 적어 둡니다.


. 가장 낮은 성능 용량 사용 값을 갖는 노드에서 가장 낮은 활용도를 가진 집계를 식별합니다.
+
.. *저장* > *집계*를 클릭하여 *집계* 인벤토리 페이지를 표시합니다.
.. *성과: 모든 집계* 보기를 선택합니다.
.. *필터* 버튼을 클릭하고 4단계에서 기록한 가장 낮은 성능 용량 사용 값을 가진 노드의 이름을 "노드"로 지정하여 필터를 추가합니다.
.. 가장 낮은 성능 용량 사용 값을 갖는 집계의 이름을 적어보세요.


. 과부하된 노드의 볼륨을 새 노드에서 사용률이 낮은 것으로 식별된 집계로 이동합니다.
+
ONTAP System Manager, OnCommand Workflow Automation, ONTAP 명령 또는 이러한 도구를 조합하여 이동 작업을 수행할 수 있습니다.



며칠 후에 이 클러스터에서 동일한 클러스터 불균형 이벤트가 발생하는지 확인하세요.
