---
permalink: performance-checker/task_create_user_defined_performance_threshold_policies.html 
sidebar: sidebar 
keywords: create, user-defined, performance, threshold, policies 
summary: 성능 카운터가 특정 값을 초과하면 알림이 전송되도록 스토리지 개체에 대한 성능 임계값 정책을 만듭니다.  이벤트 알림은 클러스터에 성능 문제가 발생하고 있음을 나타냅니다. 
---
= 사용자 정의 성능 임계값 정책 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능 카운터가 특정 값을 초과하면 알림이 전송되도록 스토리지 개체에 대한 성능 임계값 정책을 만듭니다.  이벤트 알림은 클러스터에 성능 문제가 발생하고 있음을 나타냅니다.

.시작하기 전에
애플리케이션 관리자 역할이 있어야 합니다.

성능 임계값 정책을 만들려면 성능 임계값 정책 만들기 페이지에서 임계값을 입력하세요.  이 페이지에서 모든 정책 값을 정의하여 새 정책을 만들거나 기존 정책의 복사본을 만들고 복사본의 값을 변경할 수 있습니다(복제라고 함).

유효한 임계값은 숫자의 경우 0.001~10,000,000이고, 백분율의 경우 0.001~100이며, 성능 용량 사용 백분율의 경우 0.001~200입니다.

[NOTE]
====
현재 릴리스에서는 카운터 값이 임계값 설정을 초과할 때 이벤트를 전송하는 임계값을 제공합니다.  카운터 값이 임계값 설정 아래로 떨어지면 이벤트를 전송하는 임계값을 설정할 수 없습니다.

====
.단계
. 왼쪽 탐색 창에서 *이벤트 임계값* > *성능*을 선택합니다.
+
성능 임계값 페이지가 표시됩니다.

. 새로운 정책을 구축할지, 아니면 유사한 정책을 복제하여 복제된 버전을 수정할지에 따라 적절한 버튼을 클릭합니다.
+
|===
| 에게... | 딸깍 하는 소리... 


 a| 
새로운 정책을 만듭니다
 a| 
*만들다*



 a| 
기존 정책 복제
 a| 
기존 정책을 선택하고 *복제*를 클릭하세요.

|===
+
성능 임계값 정책 생성 페이지 또는 성능 임계값 정책 복제 페이지가 표시됩니다.

. 특정 저장소 개체에 대해 설정하려는 성능 카운터 임계값을 지정하여 임계값 정책을 정의합니다.
+
.. 저장소 개체 유형을 선택하고 정책의 이름과 설명을 지정합니다.
.. 추적할 성능 카운터를 선택하고 경고 및 중요 이벤트를 정의하는 제한 값을 지정합니다.
+
최소한 하나의 경고 또는 하나의 위험 한도를 정의해야 합니다.  두 가지 유형의 한계를 모두 정의할 필요는 없습니다.

.. 필요한 경우 보조 성능 카운터를 선택하고 경고 및 중요 이벤트에 대한 제한 값을 지정합니다.
+
2차 카운터를 포함하려면 임계값이 초과되고 이벤트가 보고되기 전에 두 카운터가 모두 한도 값을 초과해야 합니다.  조합 정책을 사용하여 특정 개체와 카운터만 구성할 수 있습니다.

.. 이벤트가 전송되기 위해 한계 값이 초과되어야 하는 시간 기간을 선택합니다.


+
기존 정책을 복제할 때는 정책의 새 이름을 입력해야 합니다.

. 정책을 저장하려면 *저장*을 클릭하세요.
+
성능 임계값 페이지로 돌아갑니다.  페이지 상단의 성공 메시지는 임계값 정책이 생성되었음을 확인하고 해당 개체 유형의 인벤토리 페이지에 대한 링크를 제공하여 새 정책을 스토리지 개체에 즉시 적용할 수 있도록 합니다.



이때 저장소 개체에 새로운 임계값 정책을 적용하려면 *지금 개체 유형으로 이동* 링크를 클릭하여 인벤토리 페이지로 이동하면 됩니다.
