---
permalink: performance-checker/task_respond_to_system_defined_qos_policy_group_performance_event.html 
sidebar: sidebar 
keywords: qos, policy, group, performance, events 
summary: 'Unified Manager는 작업 부하 처리량(IOPS, IOPS/TB 또는 MBps)이 정의된 ONTAP QoS 정책 설정을 초과하고 작업 부하 지연에 영향을 미치는 경우 QoS 정책 경고 이벤트를 생성합니다.  이러한 시스템 정의 이벤트는 많은 작업 부하가 지연으로 인해 영향을 받기 전에 잠재적인 성능 문제를 해결할 수 있는 기회를 제공합니다.' 
---
= QoS 정책 그룹 성능 이벤트에 응답
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 작업 부하 처리량(IOPS, IOPS/TB 또는 MBps)이 정의된 ONTAP QoS 정책 설정을 초과하고 작업 부하 지연에 영향을 미치는 경우 QoS 정책 경고 이벤트를 생성합니다.  이러한 시스템 정의 이벤트는 많은 작업 부하가 지연으로 인해 영향을 받기 전에 잠재적인 성능 문제를 해결할 수 있는 기회를 제공합니다.

.시작하기 전에
* 운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 새로운 성과 이벤트, 인정된 성과 이벤트 또는 더 이상 진행되지 않는 성과 이벤트가 있어야 합니다.


Unified Manager는 이전 1시간 동안의 각 성능 수집 기간 동안 작업 부하 처리량이 정의된 QoS 정책 설정을 초과할 경우 QoS 정책 위반에 대한 경고 이벤트를 생성합니다.  수집 기간 동안 워크로드 처리량은 짧은 시간 동안만 QoS 임계값을 초과할 수 있지만 Unified Manager는 차트에 수집 기간 동안의 "평균" 처리량만 표시합니다.  이러한 이유로 차트에 표시된 정책 임계값을 워크로드 처리량이 넘지 않았더라도 QoS 이벤트가 발생할 수 있습니다.

시스템 관리자나 ONTAP 명령을 사용하여 다음 작업을 포함하여 정책 그룹을 관리할 수 있습니다.

* 작업 부하에 대한 새 정책 그룹 생성
* 정책 그룹에서 작업 부하 추가 또는 제거
* 정책 그룹 간 작업 부하 이동
* 정책 그룹의 처리량 제한 변경
* 작업 부하를 다른 집계 또는 노드로 이동


.단계
. 이벤트에 대한 정보를 보려면 *이벤트 세부 정보* 페이지를 표시하세요.
. 이벤트를 발생시킨 임계값 위반에 대한 설명이 있는 *설명*을 검토하세요.
+
예를 들어, "vol1_NFS1에서 IOPS 값이 1,352 IOPS로 인해 작업 부하에 대한 잠재적인 성능 문제를 식별하기 위한 경고 이벤트가 발생했습니다"라는 메시지는 볼륨 vol1_NFS1에서 QoS 최대 IOPS 이벤트가 발생했음을 나타냅니다.

. *이벤트 정보* 섹션을 검토하여 이벤트가 발생한 시기와 이벤트가 진행된 기간에 대한 자세한 내용을 확인하세요.
+
또한 QoS 정책의 처리량을 공유하는 볼륨이나 LUN의 경우 가장 많은 IOPS 또는 MBps를 소모하는 상위 3개 워크로드의 이름을 볼 수 있습니다.

. *시스템 진단* 섹션에서 두 개의 차트를 검토합니다. 하나는 전체 평균 IOPS 또는 MBps(이벤트에 따라 다름)를 나타내는 차트이고, 다른 하나는 지연 시간을 나타내는 차트입니다.  이런 식으로 정리하면 작업 부하가 QoS 최대 한도에 접근했을 때 어떤 클러스터 구성 요소가 지연 시간에 가장 큰 영향을 미치는지 확인할 수 있습니다.
+
공유 QoS 정책 이벤트의 경우, 상위 3개 작업 부하가 처리량 차트에 표시됩니다.  3개 이상의 작업 부하가 QoS 정책을 공유하는 경우 추가 작업 부하가 "기타 작업 부하" 범주에 추가됩니다.  또한, 대기 시간 차트는 QoS 정책에 포함된 모든 작업 부하의 평균 대기 시간을 보여줍니다.

+
적응형 QoS 정책 이벤트의 경우 IOPS 및 MBps 차트는 ONTAP 볼륨 크기에 따라 할당된 IOPS/TB 임계값 정책에서 변환한 IOPS 또는 MBps 값을 표시합니다.

. *제안된 작업* 섹션에서 제안 사항을 검토하고 작업 부하로 인한 지연 시간이 증가하는 것을 방지하기 위해 수행해야 할 작업을 결정합니다.
+
필요한 경우 *도움말* 버튼을 클릭하여 성능 이벤트를 해결하기 위해 수행할 수 있는 제안된 작업에 대한 자세한 내용을 확인하세요.


