---
permalink: performance-checker/task_view_event_details_in_performance_explorer_events_timeline.html 
sidebar: sidebar 
keywords: view, event, details, timeline 
summary: 성능 탐색기의 이벤트 타임라인 창에서 모든 이벤트와 관련 세부 정보를 볼 수 있습니다.  이는 지정된 시간 범위 동안 루트 개체에서 발생한 모든 상태 및 성능 이벤트를 빠르고 효율적으로 볼 수 있는 방법으로, 성능 문제를 해결할 때 도움이 될 수 있습니다. 
---
= 이벤트 타임라인에서 이벤트 세부 정보 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능 탐색기의 이벤트 타임라인 창에서 모든 이벤트와 관련 세부 정보를 볼 수 있습니다.  이는 지정된 시간 범위 동안 루트 개체에서 발생한 모든 상태 및 성능 이벤트를 빠르고 효율적으로 볼 수 있는 방법으로, 성능 문제를 해결할 때 도움이 될 수 있습니다.

이벤트 타임라인 창에는 선택한 기간 동안 루트 개체에서 발생한 중요, 오류, 경고 및 정보 이벤트가 표시됩니다.  각 이벤트의 심각도에는 고유한 타임라인이 있습니다.  단일 이벤트와 여러 이벤트는 타임라인에 이벤트 점으로 표시됩니다.  이벤트 점 위에 커서를 놓으면 이벤트 세부 정보를 볼 수 있습니다.  여러 이벤트의 시각적 세부성을 높이려면 시간 범위를 줄이면 됩니다.  이를 통해 여러 이벤트를 단일 이벤트로 분산하여 각 이벤트를 별도로 보고 조사할 수 있습니다.

이벤트 타임라인의 각 성과 이벤트 점은 이벤트 타임라인 아래에 표시되는 카운터 차트 추세선의 해당 스파이크와 수직으로 정렬됩니다.  이를 통해 이벤트와 전반적인 성과 간의 직접적인 시각적 상관관계를 파악할 수 있습니다.  건강 이벤트도 타임라인에 표시되지만, 이러한 유형의 이벤트는 반드시 성과 차트 중 하나의 급증과 일치하지는 않습니다.

.단계
. *이벤트 타임라인* 창에서 타임라인의 이벤트 점 위에 커서를 놓으면 해당 이벤트 지점의 이벤트 요약을 볼 수 있습니다.
+
팝업 대화 상자에는 이벤트 유형, 이벤트가 발생한 날짜 및 시간, 상태, 이벤트 기간에 대한 정보가 표시됩니다.

. 하나 또는 여러 이벤트에 대한 전체 이벤트 세부 정보 보기:
+
|===
| 이렇게 하려면... | 여기를 클릭하세요... 


 a| 
단일 이벤트에 대한 세부 정보 보기
 a| 
팝업 대화 상자에서 *이벤트 세부 정보 보기*를 클릭하세요.



 a| 
여러 이벤트에 대한 세부 정보 보기
 a| 
팝업 대화 상자에서 *이벤트 세부 정보 보기*를 클릭하세요.

[NOTE]
====
여러 이벤트 대화 상자에서 단일 이벤트를 클릭하면 해당 이벤트 세부 정보 페이지가 표시됩니다.

====
|===

