---
permalink: performance-checker/task_move_workloads_to_different_aggregate.html 
sidebar: sidebar 
keywords: move, workloads, different, aggregate 
summary: Unified Manager를 사용하면 현재 작업 부하가 있는 집계보다 사용량이 적은 집계를 식별한 다음 선택한 볼륨이나 LUN을 해당 집계로 이동할 수 있습니다.  고성능 워크로드를 덜 바쁜 집계나 플래시 스토리지가 활성화된 집계로 옮기면 워크로드를 더 효율적으로 수행할 수 있습니다. 
---
= 워크로드를 다른 집계로 이동
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 사용하면 현재 작업 부하가 있는 집계보다 사용량이 적은 집계를 식별한 다음 선택한 볼륨이나 LUN을 해당 집계로 이동할 수 있습니다.  고성능 워크로드를 덜 바쁜 집계나 플래시 스토리지가 활성화된 집계로 옮기면 워크로드를 더 효율적으로 수행할 수 있습니다.

.시작하기 전에
* 운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 현재 성능 문제가 있는 집계의 이름을 기록해 두어야 합니다.
* 집계에서 이벤트를 수신한 날짜와 시간을 기록해야 합니다.
* Unified Manager는 한 달 이상의 성과 데이터를 수집하고 분석해야 합니다.


이러한 단계를 통해 다음 리소스를 식별하여 고성능 워크로드를 활용도가 낮은 집계로 이동할 수 있습니다.

* 동일한 클러스터에서 활용도가 낮은 집계
* 현재 집계에서 가장 높은 성과를 보인 볼륨


.단계
. 클러스터에서 가장 활용도가 낮은 집계를 식별합니다.
+
.. *이벤트* 세부 정보 페이지에서 집계가 있는 클러스터의 이름을 클릭합니다.
+
클러스터 세부 정보는 성능/클러스터 랜딩 페이지에 표시됩니다.

.. *요약* 페이지에서 *관리되는 개체* 창의 *집계*를 클릭합니다.
+
이 클러스터의 집계 목록이 표시됩니다.

.. *활용률* 열을 클릭하면 활용률이 가장 낮은 순으로 집계가 정렬됩니다.
+
또한 가장 큰 *여유 용량*을 가진 집계를 식별할 수도 있습니다.  이는 작업 부하를 이동하려는 잠재적인 집계 목록을 제공합니다.

.. 작업 부하를 이동하려는 집계의 이름을 적어 두세요.


. 이벤트를 수신한 집계에서 성과가 좋은 볼륨을 식별합니다.
+
.. 성능 문제가 있는 집계를 클릭하세요.
+
집계 세부 정보는 성능/집계 탐색기 페이지에 표시됩니다.

.. *시간 범위* 선택기에서 *지난 30일*을 선택한 다음 *범위 적용*을 클릭합니다.
+
이를 통해 기본 72시간보다 더 긴 성과 기록 기간을 볼 수 있습니다.  지난 72시간 동안만이 아니라 지속적으로 많은 리소스를 사용하는 볼륨을 이동하려고 합니다.

.. *보기 및 비교* 컨트롤에서 *이 집계의 볼륨*을 선택합니다.
+
이 집계에 포함된 FlexVol 볼륨과 FlexGroup 구성 볼륨 목록이 표시됩니다.

.. 가장 높은 성능을 보이는 볼륨을 확인하려면 가장 높은 MB/s 순으로 볼륨을 정렬한 다음 가장 높은 IOPS 순으로 정렬하세요.
.. 다른 집계로 옮기고 싶은 볼륨의 이름을 적어 두세요.


. 성과가 좋은 볼륨을 활용도가 낮은 것으로 파악된 집계로 이동합니다.
+
ONTAP System Manager, OnCommand Workflow Automation, ONTAP 명령 또는 이러한 도구를 조합하여 이동 작업을 수행할 수 있습니다.



며칠 후에 이 노드나 집계에서 동일한 유형의 이벤트를 수신하는지 확인하세요.
