---
permalink: performance-checker/task_configure_connection_between_um_server_and_external_data_provider.html 
sidebar: sidebar 
keywords: configuring, connection, unified manager, server, external, data, provider 
summary: Unified Manager는 클러스터 성능 데이터를 외부 서버로 전송할 수 있습니다.  전송되는 통계 데이터의 유형과 데이터를 전송하는 간격을 지정할 수 있습니다. 
---
= Unified Manager 서버에서 외부 데이터 공급자로의 연결 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 클러스터 성능 데이터를 외부 서버로 전송할 수 있습니다.  전송되는 통계 데이터의 유형과 데이터를 전송하는 간격을 지정할 수 있습니다.

.시작하기 전에
* Unified Manager 서버의 유지 관리 콘솔에 로그인하려면 권한이 있는 사용자 ID가 있어야 합니다.
* 외부 데이터 공급자에 대한 다음 정보가 있어야 합니다.
+
** 서버 이름 또는 IP 주소(IPv4 또는 IPv6)
** 서버 기본 포트(기본 포트 2003을 사용하지 않는 경우)


* Unified Manager 서버에서 통계 데이터를 수신할 수 있도록 원격 서버와 타사 소프트웨어를 구성해야 합니다.
* 어떤 통계 그룹을 보내고 싶은지 알아야 합니다.
+
** PERFORMANCE_INDICATOR: 성능 모니터 통계
** RESOURCE_UTILIZATION: 리소스 활용도 및 성능 모니터 통계
** DRILL_DOWN: 모든 통계


* 통계를 전송하려는 시간 간격을 알아야 합니다: 5분, 10분 또는 15분
+
기본적으로 Unified Manager는 5분 간격으로 통계를 수집합니다.  전송 간격을 10분(또는 15분)으로 설정하면 각 전송 동안 전송되는 데이터 양은 기본 5분 간격을 사용할 때보다 2배(또는 3배) 더 많아집니다.

+
[NOTE]
====
Unified Manager 성능 수집 간격을 10분 또는 15분으로 변경하는 경우 전송 간격도 Unified Manager 수집 간격과 같거나 더 크게 변경해야 합니다.

====


하나의 Unified Manager 서버와 하나의 외부 데이터 공급자 서버 간의 연결을 구성할 수 있습니다.

.단계
. Unified Manager 서버의 유지 관리 콘솔에 유지 관리 사용자로 로그인합니다.
+
Unified Manager 유지 관리 콘솔 프롬프트가 표시됩니다.

. 유지 관리 콘솔에서 *외부 데이터 공급자* 메뉴 옵션의 번호를 입력합니다.
+
외부 서버 연결 메뉴가 표시됩니다.

. *서버 연결 추가/수정* 메뉴 옵션의 번호를 입력하세요.
+
현재 서버 연결 정보가 표시됩니다.

. 메시지가 표시되면 다음을 입력하십시오. `*y*` 계속하려면.
. 메시지가 표시되면 대상 서버의 IP 주소 또는 이름과 서버 포트 정보(기본 포트 2003과 다른 경우)를 입력합니다.
. 메시지가 표시되면 다음을 입력하십시오. `*y*` 입력한 정보가 정확한지 확인하세요.
. 외부 서버 연결 메뉴로 돌아가려면 아무 키나 누르세요.
. *서버 구성 수정* 메뉴 옵션의 번호를 입력하세요.
+
현재 서버 구성 정보가 표시됩니다.

. 메시지가 표시되면 다음을 입력하십시오. `*y*` 계속하려면.
. 메시지가 표시되면 보낼 통계 유형, 통계를 보낼 시간 간격, 지금 통계 전송을 활성화할지 여부를 입력합니다.
+
|===
| 을 위한.. | 입력하다... 


 a| 
통계 그룹 ID
 a| 
`*0*`- 성능 지표(기본값)

`*1*`- 리소스 활용

`*2*`- 드릴다운



 a| 
공급업체 태그
 a| 
외부 서버에서 통계가 저장될 폴더에 대한 설명적 이름입니다.  기본 이름은 "`netapp-performance`"이지만 다른 값을 입력할 수 있습니다.

점 표기법을 사용하면 계층적 폴더 구조를 정의할 수 있습니다.  예를 들어, 다음을 입력하여 `*stats.performance.netapp*` 통계는 *통계* > *성능* > *netapp*에서 확인할 수 있습니다.



 a| 
전송 간격
 a| 
`*5*`(기본), `*10*` , 또는 `*15*` 분



 a| 
활성화/비활성화
 a| 
`*0*`- 장애를 입히다

`*1*`- 활성화(기본값)

|===
. 메시지가 표시되면 다음을 입력하십시오. `*y*` 입력한 정보가 정확한지 확인하세요.
. 외부 서버 연결 메뉴로 돌아가려면 아무 키나 누르세요.
. 유형 `*x*` 유지 관리 콘솔을 종료합니다.


연결을 구성한 후, 선택한 성능 데이터가 지정한 시간 간격으로 대상 서버로 전송됩니다.  외부 도구에 지표가 나타나기까지는 몇 분이 걸립니다.  지표 계층 구조에서 새로운 지표를 보려면 브라우저를 새로 고쳐야 할 수도 있습니다.
