---
permalink: performance-checker/task_add_alerts.html 
sidebar: sidebar 
keywords: add, alerts 
summary: 특정 이벤트가 생성되면 알림을 받도록 알림을 구성할 수 있습니다.  단일 리소스, 리소스 그룹 또는 특정 심각도 유형의 이벤트에 대한 알림을 구성할 수 있습니다.  알림을 받을 빈도를 지정하고 알림에 스크립트를 연결할 수 있습니다. 
---
= 알림 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
특정 이벤트가 생성되면 알림을 받도록 알림을 구성할 수 있습니다.  단일 리소스, 리소스 그룹 또는 특정 심각도 유형의 이벤트에 대한 알림을 구성할 수 있습니다.  알림을 받을 빈도를 지정하고 알림에 스크립트를 연결할 수 있습니다.

.시작하기 전에
* 이벤트가 생성될 때 Active IQ Unified Manager 서버가 이러한 설정을 사용하여 사용자에게 알림을 보낼 수 있도록 사용자 이메일 주소, SMTP 서버, SNMP 트랩 호스트와 같은 알림 설정을 구성해야 합니다.
* 알림을 발생시키고자 하는 리소스와 이벤트, 그리고 알림을 보내고자 하는 사용자의 사용자 이름이나 이메일 주소를 알아야 합니다.
* 이벤트에 따라 스크립트를 실행하려면 스크립트 페이지를 사용하여 Unified Manager에 스크립트를 추가해야 합니다.
* 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.


여기에 설명된 대로 알림 설정 페이지에서 알림을 만드는 것 외에도 이벤트를 수신한 후 이벤트 세부 정보 페이지에서 직접 알림을 만들 수 있습니다.

.단계
. 왼쪽 탐색 창에서 *저장소 관리* > *알림 설정*을 클릭합니다.
. *알림 설정* 페이지에서 *추가*를 클릭합니다.
. *알림 추가* 대화 상자에서 *이름*을 클릭하고 알림의 이름과 설명을 입력합니다.
. *리소스*를 클릭하고 알림에 포함하거나 제외할 리소스를 선택합니다.
+
*이름에 포함* 필드에 텍스트 문자열을 지정하여 필터를 설정하여 리소스 그룹을 선택할 수 있습니다.  지정한 텍스트 문자열을 기준으로 사용 가능한 리소스 목록에는 필터 규칙과 일치하는 리소스만 표시됩니다.  지정하는 텍스트 문자열은 대소문자를 구분합니다.

+
리소스가 지정한 포함 및 제외 규칙을 모두 준수하는 경우 제외 규칙이 포함 규칙보다 우선하며 제외된 리소스와 관련된 이벤트에 대한 알림은 생성되지 않습니다.

. *이벤트*를 클릭하고 알림을 트리거하려는 이벤트 이름이나 이벤트 심각도 유형에 따라 이벤트를 선택합니다.
+
[TIP]
====
두 개 이상의 이벤트를 선택하려면 선택하는 동안 Ctrl 키를 누르세요.

====
. *작업*을 클릭하고 알림을 보낼 사용자를 선택하고, 알림 빈도를 선택하고, SNMP 트랩을 트랩 수신기로 보낼지 여부를 선택하고, 알림이 생성될 때 실행할 스크립트를 지정합니다.
+
[NOTE]
====
사용자에게 지정된 이메일 주소를 수정하고 편집을 위해 알림을 다시 열면 수정된 이메일 주소가 이전에 선택된 사용자에 더 이상 매핑되지 않으므로 이름 필드가 비어 있게 됩니다.  또한, 사용자 페이지에서 선택한 사용자의 이메일 주소를 수정한 경우, 수정된 이메일 주소는 선택한 사용자의 이메일 주소에 업데이트되지 않습니다.

====
+
SNMP 트랩을 통해 사용자에게 알리도록 선택할 수도 있습니다.

. *저장*을 클릭하세요.




[[example-of-adding-an-alert]]
== 알림 추가의 예

이 예제에서는 다음 요구 사항을 충족하는 알림을 만드는 방법을 보여줍니다.

* 알림 이름: HealthTest
* 리소스: 이름에 "`abc`"가 포함된 모든 볼륨을 포함하고 이름에 "`xyz`"가 포함된 모든 볼륨을 제외합니다.
* 이벤트: 모든 중요한 건강 이벤트 포함
* 작업: "+sample@domain.com+", "`테스트`" 스크립트가 포함되며 사용자는 15분마다 알림을 받아야 합니다.


알림 추가 대화 상자에서 다음 단계를 수행합니다.

. *이름*을 클릭하고 입력하세요. `*HealthTest*` *알림 이름* 필드에.
. *리소스*를 클릭하고 포함 탭의 드롭다운 목록에서 *볼륨*을 선택합니다.
+
.. 입력하다 `*abc*` *이름에 다음이 포함됨* 필드에 "`abc`"가 포함된 이름에 볼륨을 표시합니다.
.. 사용 가능한 리소스 영역에서 << *이름에 'abc'가 포함된 모든 볼륨*>>을 선택하고 선택한 리소스 영역으로 이동합니다.
.. *제외*를 클릭하고 입력하세요. `*xyz*` *이름에 포함* 필드를 입력한 다음 *추가*를 클릭합니다.


. *이벤트*를 클릭하고 이벤트 심각도 필드에서 *중요*를 선택합니다.
. 일치하는 이벤트 영역에서 *모든 중요 이벤트*를 선택하고 선택한 이벤트 영역으로 이동합니다.
. *작업*을 클릭하고 다음을 입력하세요. `*sample@domain.com*` 이 사용자에게 알림 필드에서.
. 사용자에게 15분마다 알림을 보내려면 *15분마다 알림*을 선택하세요.
+
지정된 시간 동안 수신자에게 알림을 반복적으로 보내도록 알림을 구성할 수 있습니다.  경고에 대한 이벤트 알림이 활성화되는 시간을 결정해야 합니다.

. 실행할 스크립트 선택 메뉴에서 *테스트* 스크립트를 선택합니다.
. *저장*을 클릭하세요.

