---
permalink: performance-checker/task_log_in_to_gui.html 
sidebar: sidebar 
keywords: log in, ui, unified manager 
summary: 지원되는 웹 브라우저를 사용하여 Unified Manager UI에 로그인할 수 있습니다. 
---
= UI에 로그인
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
지원되는 웹 브라우저를 사용하여 Unified Manager UI에 로그인할 수 있습니다.

.시작하기 전에
* 웹 브라우저는 최소 요구 사항을 충족해야 합니다.
+
상호 운용성 매트릭스를 참조하세요. http://mysupport.netapp.com/matrix["mysupport.netapp.com/매트릭스"] 지원되는 브라우저 버전의 전체 목록을 확인하세요.

* Unified Manager 서버의 IP 주소 또는 URL이 있어야 합니다.


1시간 동안 활동이 없으면 자동으로 세션에서 로그아웃됩니다.  이 기간은 *일반* > *기능 설정*에서 구성할 수 있습니다.

.단계
. 웹 브라우저에 URL을 입력합니다. 여기서 URL은 Unified Manager 서버의 IP 주소 또는 정규화된 도메인 이름(FQDN)입니다.
+
** IPv4의 경우: `+https://URL/+`
** IPv6의 경우: `https://[URL]/`




서버가 자체 서명된 디지털 인증서를 사용하는 경우 브라우저에 해당 인증서를 신뢰할 수 없다는 경고가 표시될 수 있습니다.  위험을 인정하고 계속 접근하거나, 서버 인증을 위해 인증 기관(CA) 서명 디지털 인증서를 설치할 수 있습니다. .  로그인 화면에서 사용자 이름과 비밀번호를 입력하세요.

Unified Manager 사용자 인터페이스에 대한 로그인이 SAML 인증을 사용하여 보호되는 경우 Unified Manager 로그인 페이지 대신 ID 공급자(IdP) 로그인 페이지에 자격 증명을 입력하게 됩니다.

대시보드 페이지가 표시됩니다.

[NOTE]
====
Unified Manager 서버가 초기화되지 않은 경우 새 브라우저 창에 첫 번째 경험 마법사가 표시됩니다.  이메일 알림을 보낼 초기 이메일 수신자, 이메일 통신을 처리할 SMTP 서버, AutoSupport Unified Manager 설치에 대한 정보를 기술 지원팀에 보낼 수 있는지 여부를 입력해야 합니다.  이 정보를 완료하면 Unified Manager UI가 나타납니다.

====