---
permalink: performance-checker/task_add_alerts_for_performance_events.html 
sidebar: sidebar 
keywords: add, alerts, performance, events 
summary: Unified Manager에서 수신한 다른 이벤트와 마찬가지로 개별 성능 이벤트에 대한 알림을 구성할 수 있습니다.  또한, 모든 성과 이벤트를 동일하게 처리하고 같은 사람에게 이메일을 보내려는 경우, 중요하거나 경고적인 성과 이벤트가 발생할 때 알려주는 단일 알림을 만들 수 있습니다. 
---
= 성능 이벤트에 대한 알림 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager에서 수신한 다른 이벤트와 마찬가지로 개별 성능 이벤트에 대한 알림을 구성할 수 있습니다.  또한, 모든 성과 이벤트를 동일하게 처리하고 같은 사람에게 이메일을 보내려는 경우, 중요하거나 경고적인 성과 이벤트가 발생할 때 알려주는 단일 알림을 만들 수 있습니다.

.시작하기 전에
애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

아래 예에서는 모든 중요 지연 시간, IOPS, MBps 이벤트에 대한 이벤트를 만드는 방법을 보여줍니다.  동일한 방법을 사용하여 모든 성능 카운터와 모든 경고 이벤트에서 이벤트를 선택할 수 있습니다.

.단계
. 왼쪽 탐색 창에서 *저장소 관리* > *알림 설정*을 클릭합니다.
. 알림 설정 페이지에서 *추가*를 클릭합니다.
. 알림 추가 대화 상자에서 *이름*을 클릭하고 알림의 이름과 설명을 입력합니다.
. *리소스* 페이지에서 어떤 리소스도 선택하지 마세요.
+
리소스가 선택되지 않았으므로 이벤트가 수신된 모든 클러스터, 집계, 볼륨 등에 알림이 적용됩니다.

. *이벤트*를 클릭하고 다음 작업을 수행하세요.
+
.. 이벤트 심각도 목록에서 *중요*를 선택합니다.
.. 이벤트 이름 포함 필드에 다음을 입력합니다. `*latency*` 그런 다음 화살표를 클릭하여 일치하는 모든 이벤트를 선택합니다.
.. 이벤트 이름 포함 필드에 다음을 입력합니다. `*iops*` 그런 다음 화살표를 클릭하여 일치하는 모든 이벤트를 선택합니다.
.. 이벤트 이름 포함 필드에 다음을 입력합니다. `*mbps*` 그런 다음 화살표를 클릭하여 일치하는 모든 이벤트를 선택합니다.


. *작업*을 클릭한 다음 *다음 사용자에게 알림* 필드에서 알림 이메일을 받을 사용자의 이름을 선택합니다.
. 이 페이지에서 SNMP 탭을 발행하고 스크립트를 실행하기 위한 다른 옵션을 구성합니다.
. *저장*을 클릭하세요.

