---
permalink: storage-mgmt/concept_assign_policies_on_workloads.html 
sidebar: sidebar 
keywords: assign, policies, workloads, single, multiple, storage, system-recommended, psls 
summary: '모든 워크로드 페이지에서 다양한 탐색 옵션을 사용하여 스토리지 워크로드에 스토리지 효율성 정책(SEP)과 성능 서비스 수준(PSL)을 할당할 수 있습니다.' 
---
= 워크로드에 정책 할당
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 워크로드 페이지에서 다양한 탐색 옵션을 사용하여 스토리지 워크로드에 스토리지 효율성 정책(SEP)과 성능 서비스 수준(PSL)을 할당할 수 있습니다.



[[assign-policies-to-a-single-workload]]
== 단일 작업 부하에 정책 할당

단일 작업 부하에 PSL이나 SEP 또는 둘 다를 할당할 수 있습니다. 다음 단계를 따르세요.

. 작업량을 선택하세요.
. 행 옆에 있는 편집 아이콘을 클릭한 다음, *편집*을 클릭합니다.
+
*할당된 성능 서비스 수준* 및 *스토리지 효율성 정책* 필드가 활성화되었습니다.

. 필요한 PSL이나 SEP, 또는 둘 다를 선택하세요.
. 변경 사항을 적용하려면 확인 아이콘을 클릭하세요.


[NOTE]
====
작업 부하를 선택하고 *추가 작업*을 클릭하여 정책을 할당할 수도 있습니다.

====


[[assign-policies-to-multiple-storage-workloads]]
== 여러 스토리지 워크로드에 정책 할당

여러 스토리지 워크로드에 PSL이나 SEP를 함께 할당할 수 있습니다. 다음 단계를 따르세요.

. 정책을 할당할 작업 부하에 대한 확인란을 선택하거나 데이터 센터의 모든 작업 부하를 선택합니다.
. *추가 작업*을 클릭하세요.
. PSL을 할당하려면 *성과 서비스 수준 할당*을 선택하세요.  SEP를 할당하려면 *스토리지 효율성 정책 할당*을 선택하세요.  정책을 선택할 수 있는 팝업이 표시됩니다.
. 적절한 정책을 선택하고 *적용*을 클릭하세요.  정책이 할당된 작업 부하의 수가 표시됩니다.  정책이 할당되지 않은 작업 부하도 원인과 함께 나열됩니다.
+
[NOTE]
====
대량의 워크로드에 정책을 적용하는 경우 선택한 워크로드 수에 따라 시간이 다소 걸릴 수 있습니다.  *백그라운드에서 실행* 버튼을 클릭하면 작업이 백그라운드에서 실행되는 동안 다른 작업을 계속할 수 있습니다.  대량 할당이 완료되면 완료 상태를 볼 수 있습니다.  여러 작업 부하에 PSL을 적용하는 경우, 이전 대량 할당 작업이 실행 중일 때는 다른 요청을 트리거할 수 없습니다.

====




[[assign-system-recommended-psls-to-workloads]]
== 워크로드에 시스템 권장 PSL 할당

데이터 센터에서 PSL이 할당되지 않았거나 할당된 PSL이 시스템 권장 사항과 일치하지 않는 스토리지 워크로드에 시스템 권장 PSL을 할당할 수 있습니다.  이 기능을 사용하려면 *시스템 권장 PSL 할당* 버튼을 클릭하세요.  특정한 작업 부하를 선택할 필요는 없습니다.

권장 사항은 시스템 분석을 통해 내부적으로 결정되며, IOPS 및 기타 매개변수가 사용 가능한 PSL의 정의와 일치하지 않는 워크로드의 경우 건너뜁니다.  스토리지 워크로드 `Waiting for I/O` 학습 상태도 제외됩니다.

[NOTE]
====
Unified Manager는 시스템 분석을 재정의하고 워크로드에 대해 다른 PSL을 권장하기 위해 워크로드 이름에서 특수 키워드를 찾습니다.  워크로드 이름에 "`ora`"라는 문자가 포함된 경우 **Extreme Performance**PSL이 권장됩니다.  그리고 워크로드 이름에 "`vm`"이라는 문자가 포함되어 있는 경우 **Performance**PSL이 권장됩니다.

====
또한 지식 기반(KB) 문서를 참조하세요. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/Performance_Service_Level'_is_not_adaptive_to_a_highly_variable_workload["ActiveIQ Unified Manager '시스템 권장 성능 서비스 수준 할당'은 매우 가변적인 작업 부하에 적응하지 않습니다."]
