---
permalink: storage-mgmt/concept_what_options_do_i_have_in_fix_it_button.html 
sidebar: sidebar 
keywords: fix it,fix all 
summary: 관리 작업 페이지에는 Unified Manager가 이벤트를 통해 알림을 받은 문제를 해결할 수 있는 수정 또는 모두 수정 버튼이 제공됩니다. 
---
= 수정 또는 모두 수정 버튼이 표시되면 어떤 옵션이 있습니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리 작업 페이지에는 Unified Manager가 이벤트를 통해 알림을 받은 문제를 해결할 수 있는 *수정* 또는 *모두 수정* 버튼이 제공됩니다.

필요한 경우, 버튼을 클릭하여 문제를 해결하는 것이 좋습니다.  하지만 Unified Manager에서 권장하는 대로 문제를 해결하고 싶지 않은 경우 다음 작업을 수행할 수 있습니다.

|===
| 당신은 무엇을 하고 싶습니까? | *행동* 


 a| 
Unified Manager를 사용하여 식별된 모든 개체의 문제를 해결하세요.
 a| 
*모두 수정* 버튼을 클릭하세요.



 a| 
지금은 식별된 개체에 대한 문제를 해결하지 말고, 이벤트가 다시 발생할 때까지 이 관리 작업을 숨기세요.
 a| 
아래쪽 화살표를 클릭하고 *모두 닫기*를 클릭하세요.



 a| 
식별된 일부 개체의 문제만 해결합니다.
 a| 
관리 작업의 이름을 클릭하면 목록이 확장되고 모든 개별 *수정* 작업이 표시됩니다. 그런 다음 개별 관리 작업을 수정하거나 해제하는 단계를 따르세요.

|===
|===
| 당신은 무엇을 하고 싶습니까? | 행동 


 a| 
Unified Manager를 이용해 문제를 해결하세요.
 a| 
*수정* 버튼을 클릭하세요.



 a| 
지금은 문제를 해결하지 말고 이벤트가 다시 발생할 때까지 이 관리 작업을 숨기세요.
 a| 
아래쪽 화살표를 클릭하고 *닫기*를 클릭하세요.



 a| 
이 이벤트에 대한 세부 정보를 표시하면 문제를 더 잘 이해할 수 있습니다.
 a| 
* *수정* 버튼을 클릭하고 나타나는 대화 상자에서 적용될 수정 사항을 검토하세요.
* 아래쪽 화살표를 클릭하고 *이벤트 세부 정보 보기*를 클릭하면 이벤트 세부 정보 페이지가 표시됩니다.


문제를 해결하려면 두 결과 페이지 중 하나에서 *수정*을 클릭하세요.



 a| 
문제를 더 잘 이해할 수 있도록 이 저장소 개체에 대한 세부 정보를 표시합니다.
 a| 
스토리지 개체의 이름을 클릭하면 성능 탐색기 또는 상태 세부 정보 페이지에 세부 정보가 표시됩니다.

|===
어떤 경우에는 수정 사항이 다음 15분 구성 폴에 반영됩니다.  다른 경우에는 구성 변경 사항을 검증하고 이벤트가 더 이상 사용되지 않도록 설정하는 데 최대 몇 시간이 걸릴 수 있습니다.

완료되었거나 진행 중인 관리 작업 목록을 보려면 필터 아이콘을 클릭하고 *완료* 또는 *진행 중*을 선택하세요.

모든 작업은 직렬 방식으로 실행되므로 *진행 중* 패널을 볼 때 일부 개체는 상태가 *진행 중*인 반면 다른 개체는 상태가 *예정*인 경우가 있습니다. 즉, 아직 구현을 기다리는 중입니다.
