---
permalink: storage-mgmt/concept_workloads_dashboard.html 
sidebar: sidebar 
keywords: workloads, overview, data center, sections 
summary: '작업 부하란 볼륨이나 LUN과 같은 저장 객체의 입출력(I/O) 작업을 나타냅니다.  저장소가 프로비저닝되는 방식은 예상되는 작업 부하 요구 사항을 기반으로 합니다.  Active IQ Unified Manager 는 스토리지 개체에 트래픽이 발생한 후에만 워크로드 통계를 추적합니다.  예를 들어, 작업 부하 IOPS와 대기 시간 값은 사용자가 데이터베이스나 이메일 애플리케이션을 사용하기 시작한 후에 사용할 수 있습니다.' 
---
= 워크로드 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
작업 부하란 볼륨이나 LUN과 같은 저장 객체의 입출력(I/O) 작업을 나타냅니다.  저장소가 프로비저닝되는 방식은 예상되는 작업 부하 요구 사항을 기반으로 합니다.  Active IQ Unified Manager 는 스토리지 개체에 트래픽이 발생한 후에만 워크로드 통계를 추적합니다.  예를 들어, 작업 부하 IOPS와 대기 시간 값은 사용자가 데이터베이스나 이메일 애플리케이션을 사용하기 시작한 후에 사용할 수 있습니다.

워크로드 페이지에는 Unified Manager가 관리하는 ONTAP 클러스터의 스토리지 워크로드 요약이 표시됩니다.  성능 서비스 수준을 준수하는 스토리지 워크로드와 준수하지 않는 스토리지 워크로드에 대한 누적된 한눈에 보는 정보를 제공합니다.  또한 이를 통해 데이터 센터 전반의 클러스터의 총 용량, 사용 가능 용량, 사용된 용량 및 성능(IOPS)을 평가할 수 있습니다.

[NOTE]
====
성능 서비스 수준에 맞지 않거나 사용할 수 없거나 관리되지 않는 스토리지 워크로드의 수를 평가하고, 적합성, 용량 사용량 및 IOPS를 보장하기 위해 필요한 조치를 취하는 것이 좋습니다.

====
워크로드 페이지에는 다음 두 섹션이 있습니다.

* 워크로드 개요: Unified Manager에서 관리하는 ONTAP 클러스터의 스토리지 워크로드 수에 대한 개요를 제공합니다.
* 데이터 센터 개요: 데이터 센터의 스토리지 워크로드 용량과 IOPS에 대한 개요를 제공합니다.  관련 데이터는 데이터 센터 수준과 개별 .별로 표시됩니다.




[[workloads-overview-section]]
== 워크로드 개요 섹션

워크로드 개요 섹션에서는 스토리지 워크로드에 대한 누적된 정보를 한눈에 볼 수 있습니다.  스토리지 작업 부하의 상태는 할당된 성능 서비스 수준과 할당되지 않은 성능 서비스 수준을 기준으로 표시됩니다.

* *할당됨*: 성능 서비스 수준이 할당된 스토리지 워크로드에 대해 다음 상태가 보고됩니다.
+
** *적합*: 스토리지 워크로드의 성능은 할당된 성능 서비스 수준을 기준으로 합니다.  스토리지 워크로드가 연관된 성능 서비스 수준에서 정의된 임계 대기 시간 내에 있는 경우 "적합"으로 표시됩니다.  적합한 작업 부하는 파란색으로 표시됩니다.
** *비준수*: 성능 모니터링 중에 스토리지 워크로드 지연 시간이 연관된 성능 서비스 수준에서 정의된 임계값 지연 시간을 초과하는 경우 스토리지 워크로드는 "비준수"로 표시됩니다.  규정에 맞지 않는 작업 부하는 주황색으로 표시됩니다.
** *사용할 수 없음*: 스토리지 워크로드가 오프라인이거나 해당 클러스터에 접근할 수 없는 경우 "`사용할 수 없음`"으로 표시됩니다.  사용할 수 없는 워크로드는 빨간색으로 표시됩니다.


* *할당되지 않음*: 성능 서비스 수준이 할당되지 않은 스토리지 워크로드는 "`할당되지 않음`"으로 보고됩니다.  숫자는 정보 아이콘을 통해 전달됩니다.


총 작업 부하 수는 할당된 작업 부하와 할당되지 않은 작업 부하의 합계입니다.

이 섹션에 표시된 총 워크로드 수를 클릭하면 워크로드 페이지에서 볼 수 있습니다.

성능 서비스 수준별 적합성 하위 섹션에는 사용 가능한 스토리지 작업 부하의 총 수가 표시됩니다.

* 각 유형의 성능 서비스 수준에 맞춰
* 할당된 성과 서비스 수준과 권장되는 성과 서비스 수준 사이에 불일치가 있는 경우




[[data-center-overview-section]]
== 데이터 센터 개요 섹션

데이터 센터 개요 섹션은 데이터 센터의 모든 클러스터에 대한 사용 가능한 용량과 사용된 용량, IOPS를 그래픽으로 나타냅니다.  이 데이터를 사용하여 스토리지 워크로드의 용량과 IOPS를 관리해야 합니다.  이 섹션에는 모든 클러스터의 스토리지 작업 부하에 대한 다음 정보도 표시됩니다.

* 데이터 센터의 모든 클러스터에 대한 총 용량, 사용 가능 용량 및 사용된 용량
* 데이터 센터의 모든 클러스터에 대한 총 IOPS, 사용 가능한 IOPS 및 사용된 IOPS
* 각 성능 서비스 수준에 따른 사용 가능한 용량 및 사용된 용량
* 각 성능 서비스 수준에 따른 사용 가능한 IOPS 및 사용된 IOPS
* 성능 서비스 수준이 할당되지 않은 작업 부하에서 사용되는 총 공간 및 IOPS


*성능 서비스 수준을 기준으로 데이터 센터 용량 및 성능을 계산하는 방법*

사용된 용량과 IOPS는 클러스터의 모든 스토리지 워크로드의 총 사용된 용량과 성능을 기준으로 검색됩니다.

사용 가능한 IOPS는 노드의 예상 지연 시간과 권장되는 성능 서비스 수준을 기반으로 계산됩니다.  여기에는 예상 지연 시간이 자체 예상 지연 시간보다 작거나 같은 모든 성능 서비스 수준에 대해 사용 가능한 IOPS가 포함됩니다.

사용 가능한 용량은 예상 지연 시간과 집계에 대한 권장 성능 서비스 수준을 기반으로 계산됩니다.  여기에는 예상 지연 시간이 자체 예상 지연 시간보다 작거나 같은 모든 성능 서비스 수준에 사용 가능한 용량이 포함됩니다.
