---
permalink: storage-mgmt/concept_monitor_vms.html 
sidebar: sidebar 
keywords: monitor, virtual, machines, view, summary, topology, expand 
summary: '가상 머신(VM) 애플리케이션에서 지연 문제가 발생하는 경우 원인을 분석하고 문제를 해결하기 위해 VM을 모니터링해야 할 수도 있습니다.  VM은 vCenter Server와 VM 스토리지를 호스팅하는 ONTAP 클러스터가 Unified Manager에 추가되면 사용할 수 있습니다.' 
---
= 가상 머신 모니터링
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
가상 머신(VM) 애플리케이션에서 지연 문제가 발생하는 경우 원인을 분석하고 문제를 해결하기 위해 VM을 모니터링해야 할 수도 있습니다.  VM은 vCenter Server와 VM 스토리지를 호스팅하는 ONTAP 클러스터가 Unified Manager에 추가되면 사용할 수 있습니다.

VM에 대한 자세한 내용은 *VMWARE* > > *가상 머신* 페이지에서 확인할 수 있습니다.  가용성, 상태, 사용 및 할당된 용량, 네트워크 지연 시간, VM, 데이터 저장소, 호스트의 IOPS 및 지연 시간과 같은 정보가 표시됩니다.  여러 데이터 저장소를 지원하는 VM의 경우 그리드는 지연 시간이 가장 긴 데이터 저장소의 메트릭을 표시하며, 별표 아이콘(*)은 추가 데이터 저장소를 나타냅니다.  아이콘을 클릭하면 추가 데이터 저장소의 메트릭이 표시됩니다.  일부 열은 정렬 및 필터링이 불가능합니다.

[NOTE]
====
VM과 해당 세부 정보를 보려면 ONTAP 클러스터의 검색(폴링 또는 메트릭 수집)이 완료되어야 합니다.  클러스터가 Unified Manager에서 제거되면 다음 검색 주기 이후에는 해당 VM을 더 이상 사용할 수 없습니다.

====
이 페이지에서는 VM의 자세한 토폴로지를 볼 수 있으며, VM과 관련된 구성 요소(예: 호스트, 가상 디스크, 연결된 데이터 저장소)를 표시합니다.  토폴로지 보기는 다음 순서로 기본 구성 요소를 해당 계층에 표시합니다. *가상 디스크* > *VM* > *호스트* > *네트워크* > *데이터 저장소* > *VMDK*.

토폴로지 측면에서 I/O 경로와 구성 요소 수준 대기 시간을 확인하고 스토리지가 성능 문제의 원인인지 확인할 수 있습니다.  토폴로지의 요약 보기에는 I/O 경로가 표시되고, IOPS 및 지연 문제가 있는 구성 요소가 강조 표시되어 문제 해결 단계를 결정할 수 있습니다.  각 구성 요소를 별도로 묘사하고 해당 구성 요소의 지연 시간을 함께 보여주는 토폴로지의 확장된 보기를 가질 수도 있습니다.  레이어를 통해 강조 표시된 I/O 경로를 결정하기 위해 구성 요소를 선택할 수 있습니다.



[[view-summary-topology]]
== 요약 토폴로지 보기

요약 토폴로지에서 VM을 보고 성능 문제를 확인하려면 다음을 수행합니다.

. *VMWARE* > *가상 머신*으로 이동합니다.
. 검색창에 VM 이름을 입력하여 검색하세요.  *필터* 버튼을 클릭하면 특정 기준에 따라 검색 결과를 필터링할 수도 있습니다.  하지만 VM을 찾을 수 없는 경우 해당 vCenter Server가 추가되어 검색되었는지 확인하세요.
+
[NOTE]
====
vCenter Server에서는 VM, 클러스터, 데이터스토어, 폴더 또는 파일과 같은 vSphere 엔터티의 이름에 특수 문자(예: %, &, *, $, #, @, !, \, /, :, *, ?, "`, <, >, |, ;, ')를 허용합니다.  VMware vCenter Server와 ESX/ESXi Server는 표시 이름에 사용된 특수 문자를 이스케이프하지 않습니다.  하지만 Unified Manager에서 이름을 처리하면 다르게 표시됩니다.  예를 들어, 다음과 같은 이름의 VM `%$VC_AIQUM_clone_191124%` vCenter Server에서는 다음과 같이 표시됩니다. `%25$VC_AIQUM_clone_191124%25` 통합 관리자에서.  특수 문자가 포함된 이름을 가진 VM을 쿼리할 때 이 문제에 대해 기록해 두어야 합니다.

====
. VM의 상태를 확인하세요.  VM 상태는 vCenter Server에서 검색됩니다.  다음과 같은 상태를 사용할 수 있습니다.  이러한 상태에 대한 자세한 내용은 VMware 설명서를 참조하세요.
+
** 정상
** 경고
** 알리다
** 모니터링되지 않음
** 알려지지 않은


. 컴퓨팅, 네트워크 및 스토리지 계층 전반의 구성 요소 토폴로지에 대한 요약 보기를 보려면 VM 옆에 있는 아래쪽 화살표를 클릭하세요.  지연 문제가 있는 노드는 강조 표시됩니다.  요약 보기에는 구성 요소의 최악의 지연 시간이 표시됩니다.  예를 들어, VM에 두 개 이상의 가상 디스크가 있는 경우 이 보기에는 모든 가상 디스크 중에서 지연 시간이 가장 긴 가상 디스크가 표시됩니다.
. 일정 기간 동안 데이터 저장소의 대기 시간과 처리량을 분석하려면 데이터 저장소 개체 아이콘 위에 있는 *워크로드 분석기* 버튼을 클릭합니다.  워크로드 분석 페이지로 이동하면 시간 범위를 선택하고 데이터 저장소의 성능 차트를 볼 수 있습니다.  워크로드 분석기에 대한 자세한 내용은 _워크로드 분석기를 사용한 워크로드 문제 해결_을 참조하세요.




[[view-expanded-topology]]
== 확장된 토폴로지 보기

VM의 확장된 토폴로지를 보면 각 구성 요소를 개별적으로 자세히 살펴볼 수 있습니다.

.단계
. 요약 토폴로지 보기에서 *토폴로지 확장*을 클릭합니다.  각 객체의 지연 시간과 함께 각 구성 요소의 자세한 토폴로지를 개별적으로 볼 수 있습니다.  예를 들어 데이터 저장소나 VMDK에 여러 노드가 있는 것처럼 한 카테고리에 여러 노드가 있는 경우 지연 시간이 가장 긴 노드는 빨간색으로 강조 표시됩니다.
. 특정 객체의 IO 경로를 확인하려면 해당 객체를 클릭하여 IO 경로와 해당 매핑을 확인하세요.  예를 들어, 가상 디스크의 매핑을 보려면 가상 디스크를 클릭하여 해당 VMDK에 대한 강조 표시된 매핑을 확인합니다.  이러한 구성 요소의 성능 지연이 발생하는 경우 ONTAP 에서 더 많은 데이터를 수집하여 문제를 해결할 수 있습니다.
+
[NOTE]
====
VMDK에 대한 메트릭은 보고되지 않습니다.  토폴로지에서는 VMDK 이름만 표시되고 메트릭은 표시되지 않습니다.

====


*관련 정보*

link:../performance-checker/concept_troubleshooting_workloads_using_workload_analyzer.html["워크로드 분석기를 사용하여 워크로드 문제 해결"]
