---
permalink: storage-mgmt/concept_mcc_svmdr_vmawareness.html 
sidebar: sidebar 
keywords: view, virtual, infrastructure, disaster, recovery, setup, datastores, metrocluster configuration 
summary: 'MetroCluster 구성이나 스토리지 가상 머신(스토리지 VM) 재해 복구(SVM DR) 설정에서 호스팅되는 데이터스토어의 구성 및 성능 측정 항목을 볼 수 있습니다.' 
---
= 재해 복구 설정에서 가상 인프라 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 구성이나 스토리지 가상 머신(스토리지 VM) 재해 복구(SVM DR) 설정에서 호스팅되는 데이터스토어의 구성 및 성능 측정 항목을 볼 수 있습니다.

Unified Manager에서는 vCenter Server에 데이터스토어로 연결된 MetroCluster 구성의 NAS 볼륨이나 LUN을 볼 수 있습니다.  MetroCluster 구성에서 호스팅되는 데이터 저장소는 표준 환경의 데이터 저장소와 동일한 토폴로지 뷰로 표현됩니다.

vCenter Server의 데이터스토어에 매핑된 스토리지 VM 재해 복구 구성의 NAS 볼륨이나 LUN도 볼 수 있습니다.



== MetroCluster 구성에서 데이터 저장소 보기

MetroCluster 구성에서 데이터 저장소를 보기 전에 다음 필수 조건을 확인하세요.

* 스위치오버 및 스위치백이 발생하는 경우 HA 쌍의 기본 및 보조 클러스터와 vCenter Server를 검색해야 합니다.
* HA 쌍의 기본 및 보조 클러스터와 vCenter Server는 Unified Manager에서 관리해야 합니다.
* 필요한 설정은 ONTAP 및 vCenter Server에서 완료해야 합니다.  자세한 내용은 ONTAP 및 vCenter 설명서를 참조하세요.
+
https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 문서 센터"]



데이터 저장소를 보려면 다음 단계를 따르세요.

. *VMWARE* > *가상 머신* 페이지에서 데이터 저장소를 호스팅하는 VM을 클릭합니다.  *워크로드 분석기* 또는 데이터 저장소 개체 링크를 클릭합니다.  볼륨이나 LUN을 호스팅하는 기본 사이트가 예상대로 작동하는 표준 시나리오에서는 기본 사이트의 vServer 클러스터 세부 정보를 볼 수 있습니다.
. 재해 발생 시 보조 사이트로 연속적으로 전환하면 데이터 저장소 링크는 보조 클러스터의 볼륨이나 LUN의 성능 지표를 가리킵니다.  이는 다음 클러스터 주기와 vServer 검색(획득)이 완료된 후에 반영됩니다.
. 성공적인 스위치백 후, 데이터스토어 링크는 다시 기본 클러스터의 볼륨이나 LUN의 성능 측정 항목을 반영합니다.  이는 다음 클러스터 주기와 vServer 검색이 완료된 후에 반영됩니다.




== 스토리지 VM 재해 복구 구성의 데이터 저장소 보기

스토리지 VM 재해 복구 구성에서 데이터 저장소를 보기 전에 다음 필수 구성 요소를 확인하세요.

* 스위치오버 및 스위치백이 발생하는 경우 HA 쌍의 기본 및 보조 클러스터와 vCenter Server를 검색해야 합니다.
* 소스 및 대상 클러스터와 스토리지 VM 피어는 모두 Unified Manager에서 관리해야 합니다.
* 필요한 설정은 ONTAP 및 vCenter Server에서 완료해야 합니다.
+
** NAS(NFS 및 VMFS) 데이터 저장소의 경우 재해 발생 시 다음 단계로 보조 저장소 VM을 시작하고, 데이터 LIF 및 경로를 확인하고, vCenter Server에서 끊어진 연결을 설정하고, VM을 시작합니다.
+
기본 사이트로 다시 전환하려면 기본 사이트에서 데이터 제공을 시작하기 전에 볼륨 간 데이터를 동기화해야 합니다.

** SAN(VMFS용 iSCSI 및 FC) 데이터 저장소의 경우 vCenter Server는 마운트된 LUN을 VMFS 형식으로 포맷합니다.  재해 발생 시, 해당 단계에는 보조 저장소 VM을 가동하고, 데이터 LIF와 경로를 검증하는 작업이 포함됩니다.  iSCSI 대상 IP가 기본 LIF와 다른 경우 수동으로 추가해야 합니다.  새로운 LUN은 호스트의 스토리지 어댑터의 iSCSI 어댑터에서 장치로 사용할 수 있어야 합니다.  그 후, 새로운 LUN이 포함된 새로운 VMFS 데이터 저장소를 생성하고, 기존 VM을 새 이름으로 등록해야 합니다.  VM이 작동 중이어야 합니다.
+
복구가 발생하는 경우 볼륨 간의 데이터를 동기화해야 합니다.  새로운 VMFS 데이터 저장소는 LUN과 새 이름으로 등록된 이전 VM을 사용하여 다시 생성해야 합니다.

+
설정에 대한 자세한 내용은 ONTAP 및 vCenter Server 설명서를 참조하세요.

+
https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 문서 센터"]





데이터 저장소를 보려면 다음 단계를 따르세요.

. *VMWARE* > *가상 머신* 페이지에서 데이터 저장소를 호스팅하는 VM 인벤토리를 클릭합니다.  데이터 저장소 개체 링크를 클릭합니다.  표준 시나리오에서는 기본 스토리지 VM의 볼륨과 LUN의 성능 데이터를 볼 수 있습니다.
. 재해 발생 시 보조 저장소 VM으로 연속적으로 전환하면 데이터 저장소 링크는 보조 저장소 VM의 볼륨이나 LUN의 성능 지표를 가리킵니다.  이는 다음 클러스터 주기와 vServer 검색(획득)이 완료된 후에 반영됩니다.
. 성공적인 스위치백 후, 데이터 저장소 링크는 다시 기본 스토리지 VM의 볼륨이나 LUN의 성능 측정 항목을 반영합니다.  이는 다음 클러스터 주기와 vServer 검색이 완료된 후에 반영됩니다.




== 지원되지 않는 시나리오

* MetroCluster 구성의 경우 다음 제한 사항을 참고하세요.
+
** 클러스터는 오직 `NORMAL` 그리고 `SWITCHOVER` 국가가 채택되었습니다.  다른 주, 예: `PARTIAL_SWITCHOVER, PARTIAL_SWITCHBACK` , 그리고 `NOT_REACHABLE` 지원되지 않습니다.
** ASO(자동 전환)가 활성화되어 있지 않으면 기본 클러스터가 다운되면 보조 클러스터를 검색할 수 없으며 토폴로지는 계속해서 기본 클러스터의 볼륨이나 LUN을 가리킵니다.


* 스토리지 VM 재해 복구 구성의 경우 다음 제한 사항에 유의하세요.
+
** SAN 스토리지 환경에서 Site Recovery Manager(SRM) 또는 Storage Replication Adapter(SRA)를 활성화한 구성은 지원되지 않습니다.



