---
permalink: storage-mgmt/concept_all_workloads.html 
sidebar: sidebar 
keywords: view, workloads, add, provision, storage, filter, analyze, performance, capacity, criteria 
summary: 모든 워크로드 보기에는 데이터 센터의 클러스터에서 사용 가능한 모든 워크로드 목록이 표시됩니다. 
---
= 워크로드 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager에 클러스터를 추가하면 각 클러스터의 스토리지 워크로드가 자동으로 검색되어 워크로드 페이지에 표시됩니다.

Unified Manager는 스토리지 워크로드에서 I/O 작업이 시작된 후에만 권장 사항(권장 PSL)을 위한 워크로드 분석을 시작합니다.

FlexGroup 볼륨과 구성 요소는 제외됩니다.



== 워크로드 개요

워크로드 개요 페이지에는 데이터 센터의 워크로드 개요와 데이터 센터의 공간 및 성능 개요가 표시됩니다.

* *작업 부하 개요* 패널: 총 작업 부하 수와 PSL이 할당된 작업 부하 수, 할당되지 않은 작업 부하 수가 표시됩니다.  각 PSL에 대한 작업 부하 수의 세부 내용도 표시됩니다.  개수를 클릭하면 필터링된 워크로드가 포함된 *모든 워크로드* 보기로 이동합니다.  *시스템 권장 PSL 할당* 버튼을 클릭하면 시스템 권장 사항을 준수하지 않는 워크로드의 수를 확인하고 해당 워크로드에 시스템 권장 PSL을 할당할 수도 있습니다.
* *데이터 센터 개요* 패널: 데이터 센터의 사용 가능한 공간(TiB)과 사용된 공간(TiB) 및 성능(IOPS)을 표시합니다.  각 PSL에 따른 모든 워크로드의 사용 가능한 공간(TiB)과 사용된 공간(TiB) 및 성능(IOPS)도 표시됩니다.




== 모든 워크로드 보기

*저장소 > 워크로드 > 모든 워크로드* 페이지에는 Unified Manager에서 관리하는 ONTAP 클러스터와 관련된 스토리지 워크로드가 나열됩니다.

I/O 작업이 발생하지 않은 새로 발견된 스토리지 워크로드의 경우 상태는 "I/O 대기 중"입니다.  스토리지 워크로드에 대한 I/O 작업이 시작된 후 Unified Manager가 분석을 시작하고 워크로드 상태가 "학습 중..."으로 변경됩니다.  분석이 완료되면(I/O 작업 시작 후 24시간 이내) 스토리지 작업 부하에 권장되는 PSL이 표시됩니다.

이 페이지에서는 스토리지 작업 부하에 스토리지 효율성 정책(SEP)과 성능 서비스 수준(PSL)을 할당할 수도 있습니다.  여러 작업을 수행할 수 있습니다.

* 스토리지 워크로드 추가 또는 프로비저닝
* 작업 부하 목록 보기 및 필터링
* 스토리지 워크로드에 PSL 할당
* 시스템에서 권장하는 PSL을 평가하고 워크로드에 할당합니다.
* 스토리지 워크로드에 SEP 할당




=== 스토리지 워크로드 추가 또는 프로비저닝

지원되는 LUN(iSCSI 및 FCP 프로토콜 모두 지원), NFS 파일 공유, SMB 공유에 스토리지 워크로드를 추가하거나 프로비저닝할 수 있습니다.

.단계
. *저장소 > 워크로드 > 모든 워크로드 > 생성*을 클릭합니다.
. 작업 부하를 생성합니다.  자세한 내용은 다음을 참조하세요.link:../storage-mgmt/concept_provision_and_manage_workloads.html["워크로드 프로비저닝 및 관리"] .




=== 워크로드 보기 및 필터링

모든 워크로드 화면에서는 데이터 센터의 모든 워크로드를 볼 수 있고, PSL이나 이름을 기준으로 특정 스토리지 워크로드를 검색할 수 있습니다.  필터 아이콘을 사용하여 검색에 대한 구체적인 조건을 입력할 수 있습니다.  호스트 클러스터나 스토리지 VM 등 다양한 필터 조건으로 검색할 수 있습니다.  *용량 총계* 옵션을 사용하면 작업 부하의 총 용량(MB)을 기준으로 필터링할 수 있습니다.  하지만 이 경우 총 용량을 바이트 수준에서 비교하기 때문에 반환되는 작업 부하의 수는 달라질 수 있습니다.

각 작업 부하에 대해 호스트 클러스터, 스토리지 VM 등의 정보가 할당된 PSL 및 SEP와 함께 표시됩니다.

이 페이지에서는 작업 부하의 성능 세부 정보를 볼 수도 있습니다.  *열 선택/정렬* 버튼을 클릭하고 보려는 특정 열을 선택하면 워크로드의 IOPS, 용량 및 지연 시간에 대한 자세한 정보를 볼 수 있습니다.  성능 보기 열에는 작업 부하에 대한 평균 및 최대 IOPS가 표시되며, 작업 부하 분석기 아이콘을 클릭하면 자세한 IOPS 분석을 볼 수 있습니다.



=== 작업 부하에 대한 성능 및 용량 기준 분석

*IOPS 분석* 팝업의 *워크로드 분석* 버튼을 클릭하면 워크로드 분석 페이지로 이동합니다. 여기서 시간 범위를 선택하고 선택한 워크로드에 대한 지연 시간, 처리량, 용량 추세를 볼 수 있습니다.  워크로드 분석기에 대한 자세한 내용은 다음을 참조하세요.link:..//performance-checker/concept_troubleshooting_workloads_using_workload_analyzer.html["워크로드 분석기를 사용하여 워크로드 문제 해결"] .

*성능 보기* 열의 막대형 차트 아이콘을 클릭하면 작업 부하에 대한 성능 정보를 보고 문제 해결에 도움을 받을 수 있습니다.  개체를 분석하기 위해 워크로드 분석 페이지에서 성능 및 용량 차트를 보려면 *워크로드 분석* 버튼을 클릭하세요.

자세한 내용은 다음을 참조하세요. link:../performance-checker/reference_what_data_does_workload_analyzer_display.html["워크로드 분석기는 어떤 데이터를 표시합니까?"].
