---
permalink: storage-mgmt/concept_manage_storage_efficiency_policies.html 
sidebar: sidebar 
keywords: manage, storage, efficiency, policies, guidelines, create, custom 
summary: 'SEP(스토리지 효율성 정책)를 사용하면 작업 부하의 스토리지 효율성 특성을 정의할 수 있습니다.  워크로드를 처음 생성할 때 또는 나중에 워크로드를 편집하여 워크로드에 SEP를 할당할 수 있습니다.' 
---
= 스토리지 효율성 정책 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SEP(스토리지 효율성 정책)를 사용하면 작업 부하의 스토리지 효율성 특성을 정의할 수 있습니다.  워크로드를 처음 생성할 때 또는 나중에 워크로드를 편집하여 워크로드에 SEP를 할당할 수 있습니다.

스토리지 효율성에는 씬 프로비저닝, 중복 제거, 데이터 압축과 같은 기술을 사용하여 스토리지 활용도를 높이고 스토리지 비용을 낮추는 것이 포함됩니다.  SEP를 만들 때 이러한 공간 절약 기술을 개별적으로 또는 함께 사용하여 최대의 보관 효율성을 달성할 수 있습니다.  정책을 스토리지 작업 부하와 연결하면 지정된 정책 설정이 해당 정책에 할당됩니다.  Unified Manager를 사용하면 시스템 정의 및 사용자 정의 SEP를 할당하여 데이터 센터의 스토리지 리소스를 최적화할 수 있습니다.

Unified Manager는 높음과 낮음의 두 가지 시스템 정의 SEP를 제공합니다.  이러한 SEP는 데이터 센터의 대부분 스토리지 워크로드에 적용할 수 있지만, 시스템에서 정의한 SEP가 요구 사항을 충족하지 못하는 경우 사용자 고유의 정책을 만들 수 있습니다.

시스템에서 정의되었거나 현재 작업 부하에 할당된 SEP는 수정할 수 없습니다.  워크로드에 할당된 SEP를 삭제할 수 없으며, 해당 SEP가 유일하게 사용 가능한 SEP인 경우에도 삭제할 수 없습니다.

스토리지 효율성 정책 페이지에는 사용 가능한 SEP가 나열되어 있으며, 이를 통해 사용자 정의 SEP를 추가, 편집, 삭제할 수 있습니다.  이 페이지에는 다음 정보가 표시됩니다.

|===
| 필드 | 설명 


 a| 
이름
 a| 
SEP의 이름.



 a| 
유형
 a| 
정책이 시스템 정의인지 사용자 정의인지 여부.



 a| 
우주 보호 구역
 a| 
볼륨이 씬 프로비저닝되었는지 아니면 씩 프로비저닝되었는지 여부.



 a| 
중복제거
 a| 
워크로드에서 중복 제거가 활성화되어 있는지 여부:

* 인라인: 작업 부하에 기록되는 동안 중복 제거가 발생합니다.
* 배경: 중복 제거는 작업 부하에서 발생합니다.
* 비활성화: 작업 부하에서 중복 제거가 비활성화됩니다.




 a| 
압축
 a| 
작업 부하에서 데이터 압축이 활성화되어 있는지 여부:

* 인라인: 작업 부하에 기록되는 동안 데이터 압축이 발생합니다.
* 배경: 데이터 압축은 작업 부하에서 발생합니다.
* 비활성화: 작업 부하에서 데이터 압축이 비활성화됩니다.




 a| 
작업 부하
 a| 
SEP에 할당된 스토리지 워크로드 수

|===


== 사용자 정의 스토리지 효율성 정책 생성을 위한 지침

기존 SEP가 스토리지 워크로드에 대한 정책 요구 사항을 충족하지 못하는 경우 사용자 지정 SEP를 만들 수 있습니다.  그러나 스토리지 작업 부하에는 시스템에서 정의한 SEP를 사용하고, 필요한 경우에만 사용자 정의 SEP를 만드는 것이 좋습니다.

모든 워크로드 페이지와 볼륨/상태 세부 정보 페이지에서 워크로드에 할당된 SEP를 볼 수 있습니다.  대시보드의 용량 패널과 용량: 모든 클러스터 보기에서 이러한 스토리지 효율성을 기반으로 한 클러스터 수준 데이터 감소 비율(스냅샷 복사본 없음)을 볼 수 있습니다.
