---
permalink: storage-mgmt/concept_monitor_and_manage_clusters_from_dashboard.html 
sidebar: sidebar 
keywords: monitor, manage, clusters, dashboard 
summary: '대시보드는 모니터링하는 ONTAP 시스템의 현재 상태에 대한 누적된 정보를 한눈에 볼 수 있도록 제공합니다.  대시보드는 모니터링 중인 클러스터의 전반적인 용량, 성능 및 보안 상태를 평가할 수 있는 "패널"을 제공합니다.' 
---
= 대시보드에서 클러스터를 모니터링하고 관리합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
대시보드는 모니터링하는 ONTAP 시스템의 현재 상태에 대한 누적된 정보를 한눈에 볼 수 있도록 제공합니다.  대시보드는 모니터링 중인 클러스터의 전반적인 용량, 성능 및 보안 상태를 평가할 수 있는 "패널"을 제공합니다.

또한 ONTAP System Manager나 ONTAP CLI를 사용하지 않고도 Unified Manager 사용자 인터페이스에서 직접 수정할 수 있는 특정 ONTAP 문제도 있습니다.

대시보드 상단에서 패널에 모니터링되는 모든 클러스터에 대한 정보를 표시할지, 아니면 개별 클러스터에 대한 정보를 표시할지 선택할 수 있습니다.  모든 클러스터의 상태를 보고 나서 자세한 정보를 보고 싶을 때 개별 클러스터로 드릴다운할 수 있습니다.

[NOTE]
====
아래 나열된 일부 패널은 구성에 따라 페이지에 나타나지 않을 수 있습니다.

====
|===
| 패널 | 설명 


 a| 
관리 조치
 a| 
Unified Manager가 문제에 대한 단일 해결책을 진단하고 결정할 수 있는 경우 해당 해결책은 *수정* 버튼과 함께 이 패널에 표시됩니다.



 a| 
용량
 a| 
로컬 계층과 클라우드 계층의 총 용량과 사용된 용량, 그리고 로컬 용량이 상한에 도달할 때까지 남은 일수를 표시합니다.



 a| 
성능 용량
 a| 
각 클러스터의 성능 용량 값과 성능 용량이 상한에 도달할 때까지 걸리는 일수를 표시합니다.



 a| 
워크로드 IOPS
 a| 
현재 특정 IOPS 범위에서 실행 중인 총 워크로드 수를 표시합니다.



 a| 
작업 부하 성능
 a| 
정의된 각 성능 서비스 수준에 할당된 적합 및 비적합 워크로드의 총 수를 표시합니다.



 a| 
보안
 a| 
규정을 준수하거나 준수하지 않는 클러스터 수, 규정을 준수하거나 준수하지 않는 SVM 수, 암호화되거나 암호화되지 않은 볼륨 수를 표시합니다.



 a| 
보호
 a| 
SVM-DR 관계로 보호되는 스토리지 VM 수, SnapMirror 관계로 보호되는 볼륨 수, Snapshot으로 보호되는 볼륨 수, MetroCluster 로 보호되는 클러스터 수를 표시합니다.



 a| 
사용 개요
 a| 
가장 높은 IOPS, 가장 높은 처리량(MBps), 가장 많이 사용된 물리적 용량을 기준으로 클러스터를 정렬하여 표시합니다.

|===