---
permalink: storage-mgmt/concept_fix_ontap_issues_directly_from_unified_manager.html 
sidebar: sidebar 
keywords: fix, ontap, issues, directly, unified manager, fix it, fix-it, remediation 
summary: 'ONTAP System Manager나 ONTAP CLI를 사용하지 않고도 Unified Manager 사용자 인터페이스에서 직접 특정 ONTAP 문제를 해결할 수 있습니다.  "관리 작업" 옵션은 Unified Manager 이벤트를 트리거한 여러 ONTAP 문제에 대한 수정 사항을 제공합니다.' 
---
= Unified Manager에서 직접 ONTAP 문제 또는 기능을 관리하세요.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager나 ONTAP CLI를 사용하지 않고도 Unified Manager 사용자 인터페이스에서 직접 특정 ONTAP 문제를 해결하거나 특정 ONTAP 기능을 관리할 수 있습니다.  "관리 작업" 옵션은 Unified Manager 이벤트를 트리거한 여러 ONTAP 문제에 대한 수정 사항을 제공합니다.

왼쪽 탐색 창에서 *관리 작업* 옵션을 선택하면 관리 작업 페이지에서 직접 문제를 해결할 수 있습니다.  관리 작업은 대시보드의 관리 작업 패널, 이벤트 세부 정보 페이지, 왼쪽 탐색 메뉴의 작업 부하 분석 선택에서도 사용할 수 있습니다.

Unified Manager는 특정 문제를 철저히 진단하고 단일 해결책을 제공할 수 있습니다.  랜섬웨어 방지 모니터링과 같은 특정 ONTAP 기능의 경우 Unified Manager는 내부 검사를 수행하고 특정 작업을 권장합니다.  해결 가능한 경우 해당 해결 방법은 관리 작업에 *수정* 버튼과 함께 표시됩니다.  문제를 해결하려면 *수정* 버튼을 클릭하세요.  애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

Unified Manager는 클러스터에 ONTAP 명령을 보내 요청된 수정을 수행합니다.  수정이 완료되면 해당 이벤트는 더 이상 사용되지 않습니다.

일부 관리 작업을 통해 *모두 수정* 버튼을 사용하여 여러 저장소 개체에서 동일한 문제를 해결할 수 있습니다.  예를 들어, "볼륨 공간 가득 참" 이벤트가 발생한 볼륨이 5개 있을 수 있는데, 이 경우 "볼륨 자동 증가 사용"에 대한 *모두 수정* 관리 작업을 클릭하면 해결할 수 있습니다.  한 번의 클릭으로 5권의 문제를 해결할 수 있습니다.

자동 수정을 사용하여 관리할 수 있는 ONTAP 문제 및 기능에 대한 정보는 다음을 참조하세요.link:../storage-mgmt/reference_what_ontap_issues_can_unified_manager_fix.html["Unified Manager가 해결할 수 있는 문제는 무엇입니까?"] .
