---
permalink: storage-mgmt/concept_manage_performance_service_levels.html 
sidebar: sidebar 
keywords: manage, performance service level, PSL, User-defined, system-defined PSL, bursty, Database PSL, extreme PSL, beyond extreme PSL 
summary: 성과 서비스 수준 계산 및 관리. 
---
= 성능 서비스 수준
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능 서비스 수준(PSL)을 사용하면 작업 부하에 대한 성능 및 스토리지 목표를 정의할 수 있습니다.  워크로드를 처음 생성할 때 또는 나중에 워크로드를 편집하여 워크로드에 PSL을 할당할 수 있습니다.

스토리지 리소스의 관리 및 모니터링은 서비스 수준 목표(SLO)를 기반으로 합니다.  SLO는 필요한 성능과 용량을 기반으로 하는 서비스 수준 계약에 의해 정의됩니다.  Unified Manager에서 SLO는 NetApp 스토리지에서 실행되는 애플리케이션의 PSL 정의를 나타냅니다.  저장 서비스는 기반 리소스의 성능과 활용도를 기준으로 차별화됩니다.  PSL은 스토리지 서비스 목표에 대한 설명입니다.  PSL을 사용하면 스토리지 공급자가 작업 부하에 대한 성능 및 용량 목표를 지정할 수 있습니다.  워크로드에 PSL을 할당하면 ONTAP 의 해당 워크로드는 성능 및 용량 목표에 따라 관리됩니다.  각 PSL은 최대 IOP, 예상 IOP, 절대 최소 IOP, 예상 지연 시간에 따라 결정됩니다.

Unified Manager에는 다음과 같은 유형의 PSL이 있습니다.

* *시스템 정의*: Unified Manager는 변경할 수 없는 몇 가지 고정 정책을 제공합니다.  미리 정의된 PSL은 다음과 같습니다.
+
** 극한의 성능
** 성능
** 가치
+
Extreme Performance, Performance, Value PSL은 데이터 센터의 대부분 일반적인 스토리지 워크로드에 적용할 수 있습니다.

+
Unified Manager는 데이터베이스 애플리케이션에 대해 세 가지 성능 서비스 수준도 제공합니다.  이러한 PSL은 버스티 IOPS를 지원하고 가장 높은 처리량 요구가 있는 데이터베이스 애플리케이션에 적합한 매우 고성능 PSL입니다.

** 데이터베이스 로그를 위한 Extreme
** 데이터베이스 공유 데이터에 대한 Extreme
** 데이터베이스 데이터를 위한 Extreme


* *사용자 정의*: 미리 정의된 성과 서비스 수준이 요구 사항을 충족하지 못하는 경우, 요구 사항을 충족하는 새로운 PSL을 만들 수 있습니다.  자세한 내용은 다음을 참조하세요.link:../storage-mgmt/task_create_and_edit_psls.html["성능 서비스 수준 생성 및 편집"] .
* *Beyond Extreme*: Beyond Extreme PSL은 Extreme보다 높은 IOPS를 요구하는 워크로드에 권장되는 시스템 PSL입니다.  워크로드는 IOPS, 용량, 지연 시간을 기준으로 내부적으로 분석되며, *저장소 > 워크로드 > 모든 워크로드* 화면에서 각 워크로드에 대해 Beyond Extreme PSL이 권장됩니다.  최적의 성능을 보장하기 위해 PSL을 워크로드에 적용할 수 있습니다.
+
워크로드에 대한 IOP 매개변수는 워크로드 동작에 따라 동적으로 생성되며 Beyond Extreme PSL의 이름에 다음 형식으로 추가됩니다. `Beyond Extreme <number-(peak IOPS/TB)> <number(expected IOPS/TB)>` .  예를 들어, 시스템이 작업 부하에 최대 및 예상 IOP가 있다고 판단하는 경우 `106345` 그리고 `37929` 각각 작업 부하에 대해 생성된 Beyond Extreme PSL은 다음과 같이 명명됩니다. `Beyond Extreme 106345 37929` .  이러한 PSL은 시스템에서 권장되지만 작업 부하에 할당하면 이러한 PSL은 다음과 같이 표시됩니다. `User-defined` 유형으로.





[[manage-workloads-by-assigning-psls]]
== PSL을 할당하여 작업 부하를 관리합니다.

*정책* > *성능 서비스 수준* 페이지와 스토리지 공급자 API를 사용하여 PSL에 액세스할 수 있습니다.  PSL을 할당하여 스토리지 작업 부하를 관리하면 개별적으로 스토리지 작업 부하를 관리할 필요가 없으므로 편리합니다.  모든 수정 사항은 개별적으로 관리하는 대신 다른 PSL을 재할당하여 관리할 수도 있습니다.  Unified Manager를 사용하면 내부 평가 및 권장 사항을 기반으로 워크로드에 PSL을 할당할 수 있습니다.

작업 부하에 시스템 권장 PSL을 할당하는 방법에 대한 자세한 내용은 다음을 참조하세요.link:..//storage-mgmt/concept_assign_policies_on_workloads.html#assign-system-recommended-psls-to-workloads["워크로드에 시스템 권장 PSL 할당"]

성과 서비스 수준 페이지에는 사용 가능한 PSL 정책이 나열되어 있으며, 이를 추가, 편집, 삭제할 수 있습니다.


NOTE: 시스템에서 정의되었거나 현재 작업 부하에 할당된 PSL은 수정할 수 없습니다.  작업 부하에 할당된 PSL을 삭제할 수 없으며, 해당 PSL이 유일하게 사용 가능한 PSL인 경우에도 삭제할 수 없습니다.

이 페이지에는 다음 정보가 표시됩니다.

|===
| 필드 | 설명 


 a| 
이름
 a| 
PSL의 이름.



 a| 
유형
 a| 
정책이 시스템 정의인지 사용자 정의인지 여부.



 a| 
예상 IOPS/TB
 a| 
LUN이나 파일 공유에서 애플리케이션이 수행할 것으로 예상되는 최소 IOPS 수입니다.  예상 IOPS는 할당된 스토리지 개체 크기를 기반으로 할당된 최소 예상 IOPS를 지정합니다.



 a| 
최대 IOPS/TB
 a| 
애플리케이션이 LUN 또는 파일 공유에서 수행할 수 있는 최대 IOPS 수입니다.  최대 IOPS는 할당된 스토리지 객체 크기 또는 사용된 스토리지 객체 크기를 기반으로 할당 가능한 최대 IOPS를 지정합니다.

최대 IOPS는 할당 정책에 따라 결정됩니다.  할당 정책은 할당된 공간 또는 사용된 공간입니다.  할당 정책이 할당된 공간으로 설정된 경우 최대 IOPS는 스토리지 개체의 크기를 기준으로 계산됩니다.  할당 정책이 사용 공간으로 설정된 경우 최대 IOPS는 스토리지 효율성을 고려하여 스토리지 개체에 저장된 데이터 양을 기준으로 계산됩니다.  기본적으로 할당 정책은 사용 공간으로 설정됩니다.



 a| 
절대 최소 IOPS
 a| 
예상 IOPS가 이 값보다 낮을 경우, 절대 최소 IOPS가 재정의로 사용됩니다.  시스템 정의 PSL의 기본값은 다음과 같습니다.

* 극한 성능: 예상 IOPS >= 6144/TB인 경우 절대 최소 IOPS = 1000
* 성능: 예상 IOPS가 2048/TB 이상, 6144/TB 미만인 경우 절대 최소 IOPS = 500
* 값: 예상 IOPS가 128/TB 이상, 2048/TB 미만인 경우 절대 최소 IOPS = 75


시스템 정의 데이터베이스 PSL의 기본값은 다음과 같습니다.

* 데이터베이스 로그의 경우 극단적: 예상 IOPS >= 22528인 경우 절대 최소 IOPS = 4000
* 데이터베이스 공유 데이터의 경우 극단적인 경우: 예상 IOPS가 16384 이상인 경우 절대 최소 IOPS는 2000입니다.
* 데이터베이스 데이터의 경우 극단적인 경우: 예상 IOPS >= 12288인 경우 절대 최소 IOPS = 2000


사용자 정의 PSL의 절대 최소 IOPS의 상위 값은 최대 75000이 될 수 있습니다.  낮은 값은 다음과 같이 계산됩니다.

1000/예상 지연 시간



 a| 
예상 지연 시간
 a| 
작업당 밀리초 단위의 스토리지 IOPS에 대한 예상 지연 시간(ms/op).



 a| 
용량
 a| 
클러스터에서 사용 가능한 총 용량과 사용된 용량입니다.



 a| 
작업 부하
 a| 
PSL에 할당된 스토리지 워크로드의 수입니다.

|===
최대 IOPS와 예상 IOPS가 ONTAP 클러스터에서 일관되고 차별화된 성능을 달성하는 데 어떻게 도움이 되는지에 대한 자세한 내용은 다음 KB 문서를 참조하세요.https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/What_is_Performance_Budgeting%3F["성과 예산이란 무엇인가요?"]



[[events-generated-for-workloads-breaching-the-threshold-defined-by-psls]]
=== PSL에서 정의한 임계값을 위반하는 작업 부하에 대해 생성된 이벤트

이전 시간 동안 작업 부하가 예상 대기 시간 값을 30% 초과하는 경우 Unified Manager는 다음 이벤트 중 하나를 생성하여 잠재적인 성능 문제를 알려줍니다.

* 성능 서비스 수준 정책에 정의된 대로 작업 부하 볼륨 대기 시간 임계값이 위반되었습니다.
* 성능 서비스 수준 정책에 정의된 대로 워크로드 LUN 지연 임계값이 위반되었습니다.


대기 시간 값이 높아지는 원인을 파악하기 위해 작업 부하를 분석하는 것이 좋습니다.

자세한 내용은 다음 링크를 참조하세요.

* link:../events/reference_volume_events.html#impact-area-performance["볼륨 이벤트"]
* link:../performance-checker/concept_what_happens_when_performance_threshold_policy_is_breached.html["성능 임계값 정책이 위반되면 어떻게 되나요?"]
* link:..//performance-checker/concept_how_unified_manager_uses_workload_response_time.html["Unified Manager가 워크로드 대기 시간을 사용하여 성능 문제를 식별하는 방법"]
* link:../performance-checker/concept_what_performance_events_are.html["어떤 성과 이벤트가 있나요?"]




[[system-defined-psls]]
=== 시스템 정의 PSL

다음 표는 시스템 정의 PSL에 대한 정보를 제공합니다.

|===
| 성능 서비스 수준 | 설명 및 사용 사례 | 예상 지연 시간(ms/op) | 최대 IOPS | 예상 IOPS | 절대 최소 IOPS 


 a| 
극한의 성능
 a| 
매우 낮은 대기 시간으로 매우 높은 처리량을 제공합니다.

지연 시간에 민감한 애플리케이션에 이상적입니다.
 a| 
1
 a| 
12288
 a| 
6144
 a| 
1000



 a| 
성능
 a| 
낮은 지연 시간으로 높은 처리량 제공

데이터베이스 및 가상화된 애플리케이션에 이상적입니다.
 a| 
2
 a| 
4096
 a| 
2048
 a| 
500



 a| 
가치
 a| 
높은 저장 용량과 적당한 지연 시간을 제공합니다.

이메일, 웹 콘텐츠, 파일 공유, 백업 대상 등 대용량 애플리케이션에 이상적입니다.
 a| 
17
 a| 
512
 a| 
128
 a| 
75



 a| 
데이터베이스 로그를 위한 Extreme
 a| 
가장 낮은 지연 시간으로 최대 처리량을 제공합니다.

데이터베이스 로그를 지원하는 데이터베이스 애플리케이션에 이상적입니다.  이 PSL은 데이터베이스 로그가 매우 폭주하고 로깅에 대한 수요가 끊임없이 있기 때문에 가장 높은 처리량을 제공합니다.
 a| 
1
 a| 
45056
 a| 
22528
 a| 
4000



 a| 
데이터베이스 공유 데이터에 대한 Extreme
 a| 
가장 낮은 지연 시간으로 매우 높은 처리량을 제공합니다.

공통 데이터 저장소에 저장되어 있지만 여러 데이터베이스에서 공유되는 데이터베이스 애플리케이션 데이터에 이상적입니다.
 a| 
1
 a| 
32768
 a| 
16384
 a| 
2000



 a| 
데이터베이스 데이터를 위한 Extreme
 a| 
가장 낮은 지연 시간으로 높은 처리량을 제공합니다.

데이터베이스 테이블 정보 및 메타데이터와 같은 데이터베이스 애플리케이션 데이터에 이상적입니다.
 a| 
1
 a| 
24576
 a| 
12288
 a| 
2000

|===