---
permalink: storage-mgmt/reference_rules_to_generate_user_and_group_quota.html 
sidebar: sidebar 
keywords: rules, generate, user, group, quota, email, address, page, area, define, add comments, syntax, command buttons 
summary: 사용자 및 그룹 할당량 이메일 주소 생성 규칙 페이지를 사용하면 클러스터, SVM, 볼륨, Q트리, 사용자 또는 사용자 그룹과 관련된 사용자 할당량을 기반으로 이메일 주소를 지정하는 규칙을 만들 수 있습니다.  할당량이 초과되면 지정된 이메일 주소로 알림이 전송됩니다. 
---
= 사용자 및 그룹 할당량 이메일 주소 생성 규칙 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용자 및 그룹 할당량 이메일 주소 생성 규칙 페이지를 사용하면 클러스터, SVM, 볼륨, Q트리, 사용자 또는 사용자 그룹과 관련된 사용자 할당량을 기반으로 이메일 주소를 지정하는 규칙을 만들 수 있습니다.  할당량이 초과되면 지정된 이메일 주소로 알림이 전송됩니다.



== 규칙 영역

할당된 이메일 주소에 대한 규칙을 정의해야 합니다.  규칙을 설명하는 주석을 추가할 수도 있습니다.



== 규칙을 정의하는 방법

실행하려는 순서대로 규칙을 입력해야 합니다.  첫 번째 규칙의 기준이 충족되면 이 규칙에 따라 이메일 주소가 생성됩니다.  만약 기준이 충족되지 않으면 다음 규칙의 기준이 고려되고, 이런 식으로 계속됩니다.  각 줄에는 별도의 규칙이 나열되어 있습니다.  기본 규칙은 목록의 마지막 규칙입니다.  규칙의 우선순위를 변경할 수 있습니다.  하지만 기본 규칙의 순서는 변경할 수 없습니다.

예를 들어, qtree1의 할당량 위반에 대한 알림을 받기 위해 이메일 주소 qtree1@xyz.com을 사용하고 다른 모든 qtree에 대해 이메일 주소 admin@xyz.com을 사용하려는 경우, 규칙을 다음 순서로 나열해야 합니다.

* $QTREE == 'qtree1'이면 qtree1@xyz.com입니다.
* $QTREE == * 이면 admin@xyz.com입니다.


지정한 규칙에 대한 기준이 하나도 충족되지 않으면 기본 규칙이 사용됩니다.

$USER_OR_GROUP == * 이면 $USER_OR_GROUP@$DOMAIN

두 명 이상의 사용자가 동일한 할당량을 가지고 있는 경우, 사용자 이름은 쉼표로 구분된 값으로 표시되며 해당 규칙은 할당량에 적용되지 않습니다.



== 댓글을 추가하는 방법

규칙을 설명하는 주석을 추가할 수 있습니다.  각 주석의 시작 부분에 #을 사용해야 하며, 각 줄에 별도의 주석을 나열해야 합니다.



== 규칙 구문

규칙의 구문은 다음 중 하나여야 합니다.

* 만약에 ( `valid variableoperator *` ) 그 다음에 `email ID@domain name`
+
if는 키워드이고 소문자입니다.  연산자는 ==입니다.  이메일 ID에는 모든 문자, 유효한 변수 $USER_OR_GROUP, $USER 또는 $GROUP이 포함될 수 있으며, 모든 문자와 유효한 변수 $USER_OR_GROUP, $USER 또는 $GROUP의 조합이 포함될 수 있습니다.  도메인 이름에는 모든 문자, 유효한 변수 $DOMAIN, 또는 모든 문자와 유효한 변수 $DOMAIN의 조합이 포함될 수 있습니다.  유효한 변수는 대문자 또는 소문자일 수 있지만 두 가지를 조합한 것은 허용되지 않습니다.  예를 들어, $domain과 $DOMAIN은 유효하지만 $Domain은 유효한 변수가 아닙니다.

* 만약에 ( `valid variableoperator `string`` ) 그 다음에 `email ID@domain name`
+
if는 키워드이고 소문자입니다.  연산자는 포함 또는 ==일 수 있습니다.  이메일 ID에는 모든 문자, 유효한 변수 $USER_OR_GROUP, $USER 또는 $GROUP이 포함될 수 있으며, 모든 문자와 유효한 변수 $USER_OR_GROUP, $USER 또는 $GROUP의 조합이 포함될 수 있습니다.  도메인 이름에는 모든 문자, 유효한 변수 $DOMAIN, 또는 모든 문자와 유효한 변수 $DOMAIN의 조합이 포함될 수 있습니다.  유효한 변수는 대문자 또는 소문자일 수 있지만 두 가지를 조합한 것은 허용되지 않습니다.  예를 들어, $domain과 $DOMAIN은 유효하지만 $Domain은 유효한 변수가 아닙니다.





== 명령 버튼

명령 단추를 사용하면 생성된 규칙을 저장, 검증 또는 취소할 수 있습니다.

* *검증*
+
생성된 규칙의 구문을 검증합니다.  검증 중에 오류가 발생하면 오류를 생성한 규칙과 오류 메시지가 표시됩니다.

* *공장 기본값으로 복원*
+
주소 규칙을 공장 기본값으로 복원할 수 있습니다.

* *구하다*
+
규칙의 구문을 검증하고 오류가 없으면 규칙을 저장합니다.  검증 중에 오류가 발생하면 오류를 생성한 규칙과 오류 메시지가 표시됩니다.


