---
permalink: storage-mgmt/reference_email_notification_format_page.html 
sidebar: sidebar 
keywords: email, notification, format, page 
summary: '이메일 알림 형식 페이지는 할당량 관련 문제(소프트 한도 위반 또는 하드 한도 도달)가 있을 때 사용자 또는 사용자 그룹에 전송되는 이메일의 규칙을 표시합니다.' 
---
= 이메일 알림 형식 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이메일 알림 형식 페이지는 할당량 관련 문제(소프트 한도 위반 또는 하드 한도 도달)가 있을 때 사용자 또는 사용자 그룹에 전송되는 이메일의 규칙을 표시합니다.

이메일 알림은 다음 사용자 또는 사용자 그룹 할당량 이벤트가 생성될 때만 전송됩니다. 사용자 또는 그룹 할당량 디스크 공간 소프트 한도 위반, 사용자 또는 그룹 할당량 파일 수 소프트 한도 위반, 사용자 또는 그룹 할당량 디스크 공간 하드 한도 도달, 사용자 또는 그룹 할당량 파일 수 하드 한도 도달.

* *에서*
+
이메일이 발송된 이메일 주소가 표시되며, 수정이 가능합니다.  기본적으로 이는 알림 페이지에 지정된 이메일 주소입니다.

* *주제*
+
알림 이메일의 제목을 표시합니다.

* *이메일 세부 정보*
+
알림 이메일의 텍스트를 표시합니다.  귀하의 요구 사항에 맞게 텍스트를 수정할 수 있습니다.  예를 들어, 할당량 속성과 관련된 정보를 제공하고 키워드 수를 줄일 수 있습니다.  하지만 키워드는 수정하면 안 됩니다.

+
유효한 키워드는 다음과 같습니다.

+
** $이벤트_이름
+
이메일 알림을 발생시킨 이벤트 이름을 지정합니다.

** 할당량_목표
+
할당량이 적용되는 qtree 또는 볼륨을 지정합니다.

** 할당량_사용_퍼센트
+
사용자 또는 사용자 그룹에서 사용하는 디스크 하드 제한, 디스크 소프트 제한, 파일 하드 제한 또는 파일 소프트 제한의 백분율을 지정합니다.

** 할당량_한도
+
사용자 또는 사용자 그룹이 도달한 디스크 하드 한도 또는 파일 하드 한도를 지정하고 다음 이벤트 중 하나가 생성됩니다.

+
*** 사용자 또는 그룹 할당량 디스크 공간 하드 한도에 도달했습니다.
*** 사용자 또는 그룹 할당량 디스크 공간 소프트 한도에 도달했습니다.
*** 사용자 또는 그룹 할당량 파일 수 하드 제한에 도달했습니다.
*** 사용자 또는 그룹 할당량 파일 수 소프트 제한에 도달했습니다.


** $QUOTA_USED
+
사용자 또는 사용자 그룹이 사용한 디스크 공간이나 생성한 파일 수를 지정합니다.

** $QUOTA_USER
+
사용자 또는 사용자 그룹 이름을 지정합니다.







[[command-buttons]]
== 명령 버튼

명령 단추를 사용하면 이메일 알림 형식에 대한 변경 사항을 미리 보고, 저장하거나 취소할 수 있습니다.

* *시사*
+
알림 이메일의 미리보기를 표시합니다.

* *공장 기본값으로 복원*
+
알림 형식을 공장 기본값으로 복원할 수 있습니다.

* *구하다*
+
알림 형식에 대한 변경 사항을 저장합니다.


