---
permalink: storage-mgmt/reference_dashboard_page.html 
sidebar: sidebar 
keywords: dashboard page, 
summary: '대시보드 페이지에는 모니터링 중인 클러스터의 높은 수준의 용량, 성능 및 보안 상태를 표시하는 "패널"이 있습니다.  이 페이지에서는 Unified Manager가 특정 이벤트를 해결하기 위해 수행할 수 있는 수정 사항을 나열하는 관리 작업 패널도 제공합니다.' 
---
= 대시보드 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
대시보드 페이지에는 모니터링 중인 클러스터의 높은 수준의 용량, 성능 및 보안 상태를 표시하는 "패널"이 있습니다.  이 페이지에서는 Unified Manager가 특정 이벤트를 해결하기 위해 수행할 수 있는 수정 사항을 나열하는 관리 작업 패널도 제공합니다.

대부분의 패널에는 해당 카테고리의 활성 이벤트 수와 지난 24시간 동안 추가된 새 이벤트 수도 표시됩니다.  이 정보는 이벤트를 해결하기 위해 추가로 분석해야 할 클러스터를 결정하는 데 도움이 됩니다.  이벤트를 클릭하면 상위 이벤트가 표시되고, 해당 카테고리에서 활성 이벤트를 표시하도록 필터링된 이벤트 관리 인벤토리 페이지로 연결되는 링크가 제공됩니다.

대시보드 상단에서 패널에 모니터링되는 모든 클러스터("모든 클러스터")에 대한 정보를 표시할지, 아니면 개별 클러스터에 대한 정보를 표시할지 선택할 수 있습니다.  모든 클러스터의 상태를 보고 나서 자세한 정보를 보고 싶을 때 개별 클러스터로 드릴다운할 수 있습니다.

[NOTE]
====
아래 나열된 패널 중 일부는 구성에 따라 대시보드에 표시됩니다.

====


== 관리 작업 패널

Unified Manager는 특정 문제를 철저히 진단하고 단일 해결책을 제공할 수 있습니다.  가능한 경우 해당 해결 방법은 *수정* 또는 *모두 수정* 버튼과 함께 이 패널에 표시됩니다.  ONTAP System Manager나 ONTAP CLI를 사용하지 않고도 Unified Manager에서 이러한 문제를 즉시 해결할 수 있습니다.  모든 문제를 보려면 보기를 클릭하세요.link:concept_fix_ontap_issues_directly_from_unified_manager.html["Unified Manager에서 직접 ONTAP 문제 해결"] 자세한 내용은.



== 용량 패널

모든 클러스터를 볼 때 이 패널에는 각 클러스터의 물리적 사용 용량(저장소 효율성 절감 적용 후)과 물리적 사용 가능 용량(잠재적 저장 효율성 절감 제외), 디스크가 가득 찰 것으로 예상되는 날짜 수, 구성된 ONTAP 저장 효율성 설정에 따른 데이터 감소율(스냅샷 복사본 없음)이 표시됩니다.  또한 구성된 클라우드 계층에 사용된 용량도 나열됩니다.  막대형 차트를 클릭하면 해당 클러스터의 집계 인벤토리 페이지로 이동합니다.  "완전히 채워질 때까지 남은 일수" 텍스트를 클릭하면 남은 용량 일수가 가장 적은 집계를 나타내는 메시지가 표시됩니다. 자세한 내용을 보려면 집계 이름을 클릭하세요.

단일 클러스터를 볼 때 이 패널에는 로컬 계층의 각 디스크 유형별로 정렬된 데이터 집계에 대한 물리적 사용 용량과 물리적 사용 가능 용량, 그리고 클라우드 계층에 대한 물리적 사용 가능 용량이 표시됩니다.  디스크 유형에 대한 막대형 차트를 클릭하면 해당 디스크 유형을 사용하는 볼륨의 볼륨 인벤토리 페이지로 이동합니다.



== 성능 용량 패널

모든 클러스터를 볼 때 이 패널에는 각 클러스터의 성능 용량 값(지난 1시간 동안의 평균)과 성능 용량이 상한에 도달할 때까지 걸리는 일수(일일 성장률 기준)가 표시됩니다.  막대형 차트를 클릭하면 해당 클러스터의 노드 인벤토리 페이지로 이동합니다.  노드 인벤토리 페이지에는 지난 72시간 동안의 평균 성능 용량이 표시됩니다.  "완전히 채워질 때까지 남은 일수" 텍스트를 클릭하면 남은 성능 용량 일수가 가장 적은 노드를 나타내는 메시지가 표시됩니다. 자세한 내용을 보려면 노드 이름을 클릭하세요.

단일 클러스터를 볼 때 이 패널에는 클러스터 성능 용량 사용 비율, 총 IOPS, 총 처리량(MB/s) 값과 이 세 가지 측정 항목이 각각 상한에 도달할 것으로 예상되는 날짜가 표시됩니다.



== 워크로드 IOPS 패널

단일 클러스터를 볼 때 이 패널에는 현재 특정 IOPS 범위에서 실행 중인 총 워크로드 수가 표시되고, 차트 위에 커서를 올려 놓으면 각 디스크 유형에 대한 숫자가 표시됩니다.



== 작업 부하 성능 패널

이 패널은 각 성능 서비스 수준(PSL) 정책에 할당된 적합 및 비적합 워크로드의 총 수를 표시합니다.  또한 PSL이 할당되지 않은 워크로드의 수도 표시됩니다.  막대형 차트를 클릭하면 작업 부하 페이지에서 해당 정책에 할당된 적합한 작업 부하로 이동합니다.  막대형 차트 뒤에 있는 숫자를 클릭하면 해당 정책에 할당된 적합 및 비적합 워크로드로 이동합니다.



== 보안 패널

보안 패널은 현재 보기에 따라 모든 클러스터 또는 단일 클러스터에 대한 높은 수준의 보안 상태를 표시합니다.  이 패널에는 다음이 표시됩니다.

* 지난 24시간 동안 수신된 보안 이벤트 목록입니다.  이벤트를 클릭하면 이벤트 세부 정보 페이지에서 세부 정보를 볼 수 있습니다.
* 클러스터 보안 상태(준수 클러스터와 비준수 클러스터 수)
* 스토리지 VM 보안 상태(규정을 준수하는 스토리지 VM과 규정을 준수하지 않는 스토리지 VM의 수)
* 볼륨 암호화 상태(암호화되었거나 암호화되지 않은 볼륨 수)
* 볼륨 랜섬웨어 방지 상태(랜섬웨어 방지가 활성화 또는 비활성화된 볼륨 수)


규정을 준수하는 클러스터와 준수하지 않는 클러스터, 스토리지 VMS, 암호화된 볼륨과 암호화되지 않은 볼륨, 볼륨 랜섬웨어 방지 상태의 막대형 차트를 클릭하면 해당 페이지로 이동하여 필터링된 클러스터, 스토리지 VM, 볼륨의 보안 세부 정보를 볼 수 있습니다.

규정 준수는 다음을 기반으로 합니다. https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf["ONTAP 9를 위한 NetApp 보안 강화 가이드"^] .  보안 페이지에서 모든 클러스터의 보안 세부 정보를 보려면 패널 상단의 오른쪽 화살표를 클릭하세요.  자세한 내용은 다음을 참조하세요.link:../health-checker/task_view_detailed_security_status_for_clusters_and_svms.html["클러스터 및 스토리지 VM에 대한 자세한 보안 상태 보기"] .



== 데이터 보호 패널

이 패널은 데이터 센터의 단일 클러스터 또는 모든 클러스터에 대한 데이터 보호 요약을 표시합니다.  ONTAP 에서 지난 24시간 동안 발생한 데이터 보호 이벤트, MetroCluster 이벤트, 활성 이벤트의 총 수를 표시합니다.  각 이벤트의 링크를 클릭하면 이벤트 세부 정보 페이지로 이동합니다.  *모두 보기* 링크를 클릭하면 이벤트 관리 인벤토리 페이지에서 모든 활성 보호 이벤트를 볼 수 있습니다.  패널에는 다음이 표시됩니다.

* 스냅샷 복사본으로 보호되는 데이터 센터의 클러스터 또는 모든 클러스터의 볼륨 수입니다.
* SnapMirror 관계로 보호되는 데이터 센터의 클러스터 또는 모든 클러스터에 있는 볼륨의 수입니다.  SnapMirror 관계의 경우 소스 클러스터의 볼륨 수가 고려됩니다.
* IP 또는 FC를 통한 MetroCluster 구성으로 보호되는 데이터 센터의 클러스터 수 또는 모든 클러스터입니다.
* SnapMirror 복구 지점 목표(RPO) 지연이 있는 볼륨 관계의 수는 지연 상태에 따라 달라집니다.


마우스를 올려 놓으면 각각의 카운트와 범례를 볼 수 있습니다.  패널 상단의 오른쪽 화살표를 클릭하면 데이터 보호 페이지에서 단일 클러스터나 모든 클러스터에 대한 세부 정보를 볼 수 있습니다.  또한, 다음을 클릭할 수 있습니다.

* 보호되지 않은 볼륨과 스냅샷 복사본으로 보호된 볼륨에 대한 막대형 차트를 통해 볼륨 페이지로 이동하여 세부 정보를 볼 수 있습니다.
* MetroCluster 구성으로 보호되거나 보호되지 않는 클러스터에 대한 막대형 차트를 통해 클러스터 페이지로 이동하여 세부 정보를 볼 수 있습니다.
* 모든 관계에 대한 막대형 차트는 관계 페이지로 이동하며, 여기서 세부 정보는 소스 클러스터를 기준으로 필터링됩니다.


자세한 내용은 다음을 참조하세요. link:../data-protection/view-protection-status.html["볼륨 보호 상태 보기"].



== 사용 개요 패널

모든 클러스터를 볼 때 가장 높은 IOPS, 가장 높은 처리량(MB/s), 가장 많이 사용된 물리적 용량을 기준으로 클러스터를 정렬하여 볼 수 있습니다.

단일 클러스터를 볼 때 가장 높은 IOPS, 가장 높은 처리량(MB/s), 가장 많이 사용된 논리적 용량을 기준으로 작업 부하를 정렬하여 볼 수 있습니다.

*관련 정보*

link:../events/task_fix_issues_using_um_automatic_remediations.html["Unified Manager 자동 수정을 사용하여 문제 해결"]

link:../performance-checker/task_display_information_about_performance_event.html["성능 이벤트에 대한 정보 표시"]

link:../performance-checker/concept_manage_performance_using_perf_capacity_available_iops.html["성능 용량 및 사용 가능한 IOPS 정보를 사용하여 성능 관리"]

link:../health-checker/reference_health_volume_details_page.html["볼륨/상태 세부 정보 페이지"]

link:../performance-checker/reference_performance_event_analysis_and_notification.html["성능 이벤트 분석 및 알림"]

link:../events/reference_description_of_event_severity_types.html["이벤트 심각도 유형에 대한 설명"]

link:../performance-checker/concept_sources_of_performance_events.html["성과 이벤트의 소스"]

link:../health-checker/concept_manage_cluster_security_objectives.html["클러스터 보안 목표 관리"]

link:../performance-checker/concept_monitor_cluster_performance_from_cluster_landing_page.html["성능 클러스터 랜딩 페이지에서 클러스터 성능을 모니터링합니다."]

link:../performance-checker/concept_monitor_performance_using_object_performance.html["성능 인벤토리 페이지를 사용하여 성능 모니터링"]
