---
permalink: storage-mgmt/reference_what_ontap_issues_can_unified_manager_fix.html 
sidebar: sidebar 
keywords: ontap issues, fix it action, automatic remediation feature, remediation events, fix-it messages, fix-it events 
summary: 이 표에서는 Unified Manager가 Unified Manager 사용자 인터페이스에서 수정 또는 모두 수정 버튼을 클릭하여 직접 해결할 수 있는 ONTAP 문제를 설명합니다. 
---
= Unified Manager가 해결할 수 있는 문제는 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager 의 자동 수정 기능을 사용하면 특정 ONTAP 문제를 해결하거나 랜섬웨어 모니터링과 같은 특정 ONTAP 기능을 Unified Manager를 통해 효과적으로 관리할 수 있습니다.

이 표에서는 Unified Manager 웹 UI의 *수정* 또는 *모두 수정* 버튼을 통해 직접 관리할 수 있는 ONTAP 문제 또는 기능에 대해 설명합니다.

|===
| 이벤트 이름 및 설명 | 관리 조치 | "수정" 작업 


 a| 
볼륨 공간 가득 참

볼륨 공간이 거의 부족하여 용량 가득 참 임계값을 초과했습니다.  이 임계값은 기본적으로 볼륨 크기의 90%로 설정됩니다.
 a| 
볼륨 자동 증가 활성화
 a| 
Unified Manager는 이 볼륨에 대해 볼륨 자동 증가가 구성되어 있지 않다고 판단하므로 필요에 따라 볼륨 용량이 증가하도록 이 기능을 활성화합니다.



 a| 
Inode가 가득 찼습니다

이 볼륨의 inode가 부족하여 새로운 파일을 수용할 수 없습니다.
 a| 
볼륨의 inode 수 증가
 a| 
볼륨의 inode 수가 2% 증가합니다.



 a| 
스토리지 계층 정책 불일치가 감지되었습니다.

볼륨에 비활성 데이터가 많고 현재 계층화 정책이 "스냅샷 전용" 또는 "없음"으로 설정되어 있습니다.
 a| 
자동 클라우드 티어링 활성화
 a| 
볼륨이 이미 FabricPool 에 있으므로 계층화 정책이 "자동"으로 변경되어 비활성 데이터가 비용이 저렴한 클라우드 계층으로 이동됩니다.



 a| 
스토리지 계층 불일치가 감지되었습니다.

볼륨에는 비활성 데이터가 많이 있지만 클라우드 지원 스토리지 계층(FabricPool)에 상주하지 않습니다.
 a| 
볼륨의 스토리지 계층 변경
 a| 
볼륨을 클라우드 지원 스토리지 계층으로 이동하고 계층화 정책을 "자동"으로 설정하여 비활성 데이터를 클라우드 계층으로 이동합니다.



 a| 
감사 로그 비활성화됨

저장소 VM에 대한 감사 로그가 활성화되지 않았습니다.
 a| 
스토리지 VM에 대한 감사 로깅 활성화
 a| 
스토리지 VM에서 감사 로깅을 활성화합니다.

스토리지 VM에는 이미 로컬 또는 원격 감사 로그 위치가 구성되어 있어야 합니다.



 a| 
로그인 배너 비활성화됨

클러스터의 로그인 배너를 활성화하여 액세스 제한을 명확히 하여 보안을 강화해야 합니다.
 a| 
클러스터에 대한 로그인 배너 설정
 a| 
클러스터 로그인 배너를 "`권한이 있는 사용자만 접근 가능`"으로 설정합니다.



 a| 
로그인 배너 비활성화됨

스토리지 VM에 대한 로그인 배너를 활성화하여 액세스 제한을 명확히 하여 보안을 강화해야 합니다.
 a| 
스토리지 VM에 대한 로그인 배너 설정
 a| 
스토리지 VM 로그인 배너를 "권한이 있는 사용자만 액세스 가능"으로 설정합니다.



 a| 
SSH가 안전하지 않은 암호를 사용하고 있습니다

접미사 "-cbc"가 붙은 암호는 안전하지 않은 것으로 간주됩니다.
 a| 
클러스터에서 안전하지 않은 암호 제거
 a| 
클러스터에서 aes192-cbc, aes128-cbc 등의 안전하지 않은 암호를 제거합니다.



 a| 
SSH가 안전하지 않은 암호를 사용하고 있습니다

접미사 "-cbc"가 붙은 암호는 안전하지 않은 것으로 간주됩니다.
 a| 
스토리지 VM에서 안전하지 않은 암호 제거
 a| 
스토리지 VM에서 aes192-cbc 및 aes128-cbc와 같은 안전하지 않은 암호를 제거합니다.



 a| 
AutoSupport HTTPS 전송이 비활성화되었습니다.

AutoSupport 메시지를 기술 지원팀에 보내는 데 사용되는 전송 프로토콜은 암호화되어야 합니다.
 a| 
AutoSupport 메시지의 전송 프로토콜로 HTTPS를 설정합니다.
 a| 
클러스터의 AutoSupport 메시지에 대한 전송 프로토콜로 HTTPS를 설정합니다.



 a| 
클러스터 부하 불균형 임계값 위반

클러스터 내 노드 간에 부하가 불균형하다는 것을 나타냅니다.  이 이벤트는 노드 간 성능 용량 사용 분산이 30%를 초과할 때 생성됩니다.
 a| 
클러스터 워크로드 균형 조정
 a| 
Unified Manager는 불균형을 줄이기 위해 한 노드에서 다른 노드로 이동할 최적의 볼륨을 식별한 다음 볼륨을 이동합니다.



 a| 
클러스터 용량 불균형 임계값 위반

클러스터 내 집계 간의 용량 불균형을 나타냅니다.  이 이벤트는 집계 간 사용된 용량 차이가 70%를 넘을 때 생성됩니다.
 a| 
클러스터 용량 균형
 a| 
Unified Manager는 불균형을 줄이기 위해 한 집계에서 다른 집계로 이동할 최적의 볼륨을 식별한 다음 볼륨을 이동합니다.



 a| 
성능 용량 사용 임계값 위반

한 개 이상의 활성 작업 부하로 사용률을 줄이지 않으면 노드의 부하가 과도하게 사용될 수 있음을 나타냅니다.  이 이벤트는 노드 성능 용량 사용 값이 12시간 이상 100% 이상일 때 생성됩니다.
 a| 
노드의 높은 부하 제한
 a| 
Unified Manager는 가장 높은 IOPS를 가진 볼륨을 식별하고 과거 예상 IOPS 수준과 최대 IOPS 수준을 사용하여 QoS 정책을 적용하여 노드의 부하를 줄입니다.



 a| 
동적 이벤트 경고 임계값 위반됨

일부 작업 부하가 비정상적으로 높아 노드가 이미 과부하 상태에서 작동하고 있음을 나타냅니다.
 a| 
노드의 과부하를 줄이세요
 a| 
Unified Manager는 가장 높은 IOPS를 가진 볼륨을 식별하고 과거 예상 IOPS 수준과 최대 IOPS 수준을 사용하여 QoS 정책을 적용하여 노드의 부하를 줄입니다.



 a| 
인수가 불가능합니다

현재 장애 조치가 비활성화되어 있으므로 중단이나 재부팅 중에는 노드 리소스에 대한 액세스가 노드를 다시 사용할 수 있을 때까지 손실됩니다.
 a| 
노드 장애 조치 활성화
 a| 
Unified Manager는 클러스터의 모든 노드에서 장애 조치를 활성화하기 위해 적절한 명령을 보냅니다.



 a| 
옵션 Cf.takeover.on_panic이 OFF로 구성되었습니다.

nodeshell 옵션 "cf.takeover.on_panic"이 *off*로 설정되어 있어 HA 구성 시스템에서 문제가 발생할 수 있습니다.
 a| 
패닉 시 인수 활성화
 a| 
Unified Manager는 클러스터에 적절한 명령을 보내 이 설정을 *켜짐*으로 변경합니다.



 a| 
nodeshell 옵션 snapmirror.enable을 비활성화합니다.

이전 nodeshell 옵션인 "snapmirror.enable"이 *on*으로 설정되어 있어 ONTAP 9.3 이상으로 업그레이드한 후 부팅하는 동안 문제가 발생할 수 있습니다.
 a| 
snapmirror.enable 옵션을 off로 설정합니다.
 a| 
Unified Manager는 클러스터에 적절한 명령을 보내 이 설정을 *off*로 변경합니다.



 a| 
Telnet 활성화됨

Telnet은 안전하지 않고 암호화되지 않은 방식으로 데이터를 전달하기 때문에 잠재적인 보안 문제가 있음을 나타냅니다.
 a| 
Telnet 비활성화
 a| 
Unified Manager는 클러스터에 적절한 명령을 보내 Telnet을 비활성화합니다.



 a| 
스토리지 VM 랜섬웨어 방지 학습 구성

랜섬웨어 방지 모니터링 라이선스가 있는 클러스터를 주기적으로 확인합니다.  해당 클러스터에서 스토리지 VM이 NFS 또는 SMB 볼륨만 지원하는지 여부를 검증합니다.
 a| 
스토리지 VM을 다음 위치에 두십시오. `learning` 랜섬웨어 방지 모니터링 모드
 a| 
Unified Manager는 랜섬웨어 방지 모니터링을 설정합니다. `learning` 클러스터 관리 콘솔을 통해 스토리지 VM의 상태를 확인합니다.  스토리지 VM에 생성된 모든 새 볼륨에 대한 랜섬웨어 방지 모니터링은 자동으로 학습 모드로 전환됩니다.  이러한 기능을 통해 ONTAP 볼륨의 활동 패턴을 학습하고 잠재적인 악의적 공격으로 인한 이상을 감지할 수 있습니다.



 a| 
볼륨 랜섬웨어 방지 학습 구성

랜섬웨어 방지 모니터링 라이선스가 있는 클러스터를 주기적으로 확인합니다.  해당 클러스터에서 볼륨이 NFS 또는 SMB 서비스만 지원하는지 여부를 검증합니다.
 a| 
볼륨을 넣어 `learning` 랜섬웨어 방지 모니터링 모드
 a| 
Unified Manager는 랜섬웨어 방지 모니터링을 설정합니다. `learning` 클러스터 관리 콘솔을 통해 볼륨에 대한 상태를 확인합니다.  이러한 기능을 통해 ONTAP 볼륨의 활동 패턴을 학습하고 잠재적인 악의적 공격으로 인한 이상을 감지할 수 있습니다.



 a| 
볼륨 랜섬웨어 방지 활성화

랜섬웨어 방지 모니터링 라이선스가 있는 클러스터를 주기적으로 확인합니다.  볼륨이 다음 위치에 있는지 감지합니다. `learning` 45일 이상 랜섬웨어 방지 모니터링 모드를 유지하고, 활성 모드로 전환할 가능성을 판단합니다.
 a| 
볼륨을 넣어 `active` 랜섬웨어 방지 모니터링 모드
 a| 
Unified Manager는 랜섬웨어 방지 모니터링을 설정합니다. `active` 클러스터 관리 콘솔을 통해 볼륨에 대해.  이러한 기능을 통해 ONTAP 볼륨의 활동 패턴을 학습하고 잠재적인 악의적 공격으로 인한 이상을 감지하며 데이터 보호 조치에 대한 알림을 생성할 수 있습니다.



 a| 
볼륨 랜섬웨어 방지 비활성화

랜섬웨어 방지 모니터링 라이선스가 있는 클러스터를 주기적으로 확인합니다.  볼륨에서 활성 랜섬웨어 모니터링 중에 반복적인 알림을 감지합니다(예: 잠재적인 랜섬웨어 공격에 대한 경고가 30일 동안 여러 번 반환됨).
 a| 
볼륨에서 랜섬웨어 방지 모니터링 비활성화
 a| 
Unified Manager는 클러스터 관리 콘솔을 통해 볼륨에 대한 랜섬웨어 방지 모니터링을 비활성화합니다.

|===