---
permalink: storage-mgmt/task_provision_fileshares.html 
sidebar: sidebar 
keywords: provision, file, share, volumes 
summary: '기존 클러스터와 스토리지 가상 머신(스토리지 VM)에서 워크로드 프로비저닝 페이지에서 CIFS/SMB 및 NFS 프로토콜을 지원하는 파일 공유 볼륨을 만들 수 있습니다.' 
---
= 파일 공유 볼륨 제공
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 클러스터와 스토리지 가상 머신(스토리지 VM)에서 워크로드 프로비저닝 페이지에서 CIFS/SMB 및 NFS 프로토콜을 지원하는 파일 공유 볼륨을 만들 수 있습니다.

.시작하기 전에
* 스토리지 VM에는 파일 공유 볼륨을 프로비저닝하기 위한 공간이 있어야 합니다.
* 스토리지 VM에서 SMB 및 NFS 서비스 중 하나 또는 둘 다를 활성화해야 합니다.
* 워크로드에 대한 성능 서비스 수준(PSL)과 스토리지 효율성 정책(SEP)을 선택하고 할당하려면 워크로드를 생성하기 전에 해당 정책이 만들어져 있어야 합니다.


.단계
. *워크로드 프로비저닝* 페이지에서 생성하려는 워크로드의 이름을 추가한 다음, 사용 가능한 목록에서 클러스터를 선택합니다.
. 선택한 클러스터를 기반으로 *저장 VM* 필드는 해당 클러스터에 사용 가능한 저장 VM을 필터링합니다.  목록에서 필요한 스토리지 VM을 선택하세요.
+
스토리지 VM에서 지원되는 SMB 및 NFS 서비스에 따라 호스트 정보 섹션에서 NAS 옵션이 활성화됩니다.

. 저장소 및 최적화 섹션에서 워크로드에 대한 저장소 용량과 PSL을 지정하고, 선택적으로 SEP를 지정합니다.
+
SEP에 대한 사양은 LUN에 할당되고 PSL에 대한 정의는 워크로드가 생성될 때 워크로드에 적용됩니다.

. 작업 부하에 할당한 PSL을 적용하려면 *성능 제한 적용* 확인란을 선택합니다.
+
워크로드에 PSL을 할당하면 워크로드가 생성된 집계가 해당 정책에 정의된 성능 및 용량 목표를 지원할 수 있습니다.  예를 들어, 워크로드에 "극한 성능" PSL이 할당된 경우, 워크로드를 프로비저닝할 집계에는 SSD 스토리지와 같이 "극한 성능" 정책의 성능 및 용량 목표를 지원할 수 있는 기능이 있어야 합니다.

+
[NOTE]
====
이 확인란을 선택하지 않으면 PSL이 작업 부하에 적용되지 않으며 대시보드에서 작업 부하 상태가 할당되지 않음으로 표시됩니다.

====
. *NAS* 옵션을 선택하세요.
+
*NAS* 옵션이 활성화되어 있지 않으면 선택한 스토리지 VM이 SMB나 NFS, 또는 둘 다를 지원하는지 확인하세요.

+
[NOTE]
====
스토리지 VM이 SMB와 NFS 서비스 모두에 대해 활성화된 경우, *NFS로 공유* 및 *SMB로 공유* 확인란을 선택하여 NFS와 SMB 프로토콜을 모두 지원하는 파일 공유를 만들 수 있습니다.  SMB 또는 CIFS 공유를 만들려면 해당 확인란만 선택하세요.

====
. NFS 파일 공유 볼륨의 경우 파일 공유 볼륨에 액세스할 호스트 또는 네트워크의 IP 주소를 지정합니다.  여러 호스트에 대해 쉼표로 구분된 값을 입력할 수 있습니다.
+
호스트 IP 주소를 추가하면 호스트 세부 정보와 스토리지 VM을 일치시키기 위한 내부 검사가 실행되고 해당 호스트에 대한 내보내기 정책이 생성되거나 기존 정책이 있는 경우 재사용됩니다.  동일한 호스트에 대해 여러 개의 NFS 공유가 생성된 경우, 일치하는 규칙이 있는 동일한 호스트에 대한 사용 가능한 내보내기 정책이 모든 파일 공유에 재사용됩니다.  API를 사용하여 NFS 공유를 프로비저닝하면 개별 정책의 규칙을 지정하거나 특정 정책 키를 제공하여 정책을 재사용하는 기능을 사용할 수 있습니다.

. SMB 공유의 경우, SMB 공유에 액세스할 수 있는 사용자 또는 사용자 그룹을 지정하고 필요한 권한을 할당합니다.  각 사용자 그룹에 대해 파일 공유를 생성하는 동안 새로운 액세스 제어 목록(ACL)이 생성됩니다.
. *저장*을 클릭하세요.
+
작업 부하가 저장소 작업 부하 목록에 추가됩니다.


