---
permalink: storage-mgmt/task_provision_luns.html 
sidebar: sidebar 
keywords: provision, luns 
summary: '기존 클러스터와 스토리지 가상 머신(스토리지 VM)에서 워크로드 프로비저닝 페이지에서 CIFS/SMB 및 NFS 프로토콜을 지원하는 LUN을 만들 수 있습니다.' 
---
= LUN 프로비저닝
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 클러스터와 스토리지 가상 머신(스토리지 VM)에서 워크로드 프로비저닝 페이지에서 CIFS/SMB 및 NFS 프로토콜을 지원하는 LUN을 만들 수 있습니다.

.시작하기 전에
* 스토리지 VM에는 LUN을 프로비저닝하기 위한 공간이 있어야 합니다.
* LUN을 생성하는 스토리지 VM에서는 iSCSI와 FCP를 모두 활성화해야 합니다.
* 워크로드에 대한 성능 서비스 수준(PSL)과 스토리지 효율성 정책(SEP)을 선택하고 할당하려면 워크로드를 생성하기 전에 해당 정책이 만들어져 있어야 합니다.


.단계
. *워크로드 프로비저닝* 페이지에서 생성하려는 워크로드의 이름을 추가한 다음, 사용 가능한 목록에서 클러스터를 선택합니다.
+
선택한 클러스터를 기반으로 *저장 VM* 필드는 해당 클러스터에 사용 가능한 저장 VM을 필터링합니다.

. iSCSI 및 FCP 서비스를 지원하는 스토리지 VM을 목록에서 선택합니다.
+
선택에 따라 호스트 정보 섹션에서 SAN 옵션이 활성화됩니다.

. *저장 및 최적화* 섹션에서 작업 부하에 대한 저장 용량과 PSL을 지정하고, 선택적으로 SEP를 지정합니다.
+
SEP에 대한 사양은 LUN에 할당되고 PSL에 대한 정의는 워크로드가 생성될 때 워크로드에 적용됩니다.

. 작업 부하에 할당된 PSL을 적용하려면 *성능 제한 적용* 확인란을 선택합니다.
+
워크로드에 PSL을 할당하면 워크로드가 생성된 집계가 해당 정책에 정의된 성능 및 용량 목표를 지원할 수 있습니다.  예를 들어, 워크로드에 "극한 성능" PSL이 할당된 경우, 워크로드를 프로비저닝할 집계에는 SSD 스토리지와 같이 "극한 성능" 정책의 성능 및 용량 목표를 지원할 수 있는 기능이 있어야 합니다.

+
[NOTE]
====
이 확인란을 선택하지 않으면 PSL이 작업 부하에 적용되지 않으며 대시보드의 작업 부하 상태가 다음과 같이 표시됩니다. `unassigned` .

====
. *SAN* 옵션을 선택하세요.  *SAN* 옵션이 활성화되어 있지 않으면 선택한 스토리지 VM이 iSCSI 및 FCP를 지원하는지 확인하세요.
. 호스트 OS를 선택하세요.
. LUN에 대한 이니시에이터의 액세스를 제어하기 위해 호스트 매핑을 지정합니다.  기존의 개시자 그룹(igroup)을 할당하거나 새로운 igroup을 정의하고 매핑할 수 있습니다.
+
[NOTE]
====
LUN을 프로비저닝하는 동안 새로운 igroup을 생성하는 경우, 다음 검색 주기(최대 15분)까지 기다려야 사용할 수 있습니다.  따라서 사용 가능한 igroup 목록에서 기존 igroup을 사용하는 것이 좋습니다.

====
+
새로운 igroup을 만들려면 *새 이니시에이터 그룹 만들기* 버튼을 선택하고 igroup에 대한 정보를 입력하세요.

. *저장*을 클릭하세요.
+
LUN이 스토리지 워크로드 목록에 추가됩니다.


