---
permalink: storage-mgmt/task_view_and_add_vcenter_servers.html 
sidebar: sidebar 
keywords: view, add, vcenter, server 
summary: '가상 머신(VM)의 성능을 보고 문제를 해결하려면 연관된 vCenter Server를 Active IQ Unified Manager 인스턴스에 추가해야 합니다.' 
---
= vCenter Server 보기 및 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
가상 머신(VM)의 성능을 보고 문제를 해결하려면 연관된 vCenter Server를 Active IQ Unified Manager 인스턴스에 추가해야 합니다.

.시작하기 전에
vCenter Server를 추가하거나 보기 전에 다음 사항을 확인하세요.

* vCenter Server 이름을 알고 있습니다.
* vCenter Server의 IP 주소를 알고 있으며 필요한 자격 증명이 있습니다.  자격 증명은 vCenter Server 관리자이거나 vCenter Server에 대한 읽기 전용 액세스 권한이 있는 루트 사용자여야 합니다.
* 추가하려는 vCenter Server는 vSphere 6.5 이상을 실행합니다.
+

NOTE: VMware ESXi 및 vCenter Server에 대한 Unified Manager 지원은 영어와 일본어로 제공됩니다.

* vCenter Server의 데이터 수집 설정은 통계 수준으로 설정됩니다. `_Level 3_` 모든 모니터링 대상에 대해 필요한 수준의 메트릭 수집을 보장합니다.  간격 기간은 다음과 같아야 합니다. `_5 minutes_` , 그리고 저장 기간은 다음과 같아야 합니다. `_1 day_` .
+
자세한 내용은 VMware 설명서의 _vSphere 모니터링 및 성능 가이드_에서 "`데이터 수집 수준`" 섹션을 참조하세요.

* vCenter Server의 대기 시간 값은 대기 시간 값을 성공적으로 계산하기 위해 마이크로초가 아닌 밀리초로 구성됩니다.
* vCenter Server에 데이터스토어를 추가하는 동안 호스트의 IP 주소나 정규화된 도메인 이름(FQDN)을 모두 사용할 수 있습니다.  FQDN을 추가하는 경우 Unified Manager 서버에서 도메인 이름을 확인할 수 있는지 확인하세요.  예를 들어 Linux 설치의 경우 도메인 이름이 추가되었는지 확인하십시오. `/etc/resolv.conf` 파일.
* vCenter Server의 현재 시간은 vCenter Server 표준 시간대와 동기화됩니다.
* 성공적인 검색을 위해 vCenter Server에 접속할 수 있습니다.
* Unified Manager에 vCenter Server를 추가하면 VMware SDK에 대한 읽기 액세스 권한이 부여됩니다.  이는 구성 폴링에 필요합니다.


추가되고 검색된 모든 vCenter Server에 대해 Unified Manager는 vCenter Server 및 ESXi 서버 세부 정보, ONTAP 매핑, 데이터 저장소 세부 정보, 호스팅된 VM 수 등의 구성 데이터를 수집합니다.  또한 구성 요소의 성능 측정 항목을 수집합니다.

.단계
. *VMWARE* > *vCenter*로 이동하여 vCenter Server가 목록에서 사용 가능한지 확인하세요.
+
[NOTE]
====
vCenter Server를 사용할 수 없는 경우 vCenter Server를 추가해야 합니다.

====
+
.. *추가*를 클릭하세요.
.. vCenter Server에 대한 올바른 IP 주소를 추가하고 장치에 접근할 수 있는지 확인하세요.
.. vCenter Server에 대한 읽기 전용 액세스 권한이 있는 관리자 또는 루트 사용자의 사용자 이름과 비밀번호를 추가합니다.
.. 기본 443이 아닌 다른 포트를 사용하는 경우 사용자 지정 포트 번호를 추가하세요.
.. *저장*을 클릭하세요.
+
성공적으로 검색되면 수락할 수 있는 서버 인증서가 표시됩니다.

+
인증서를 수락하면 vCenter Server가 사용 가능한 vCenter Server 목록에 추가됩니다.  장치를 추가해도 연결된 VM에 대한 데이터가 수집되지 않으며, 수집은 예약된 간격으로 수행됩니다.



. vCenter Server를 *vCenters* 페이지에서 사용할 수 있는 경우, *상태* 필드 위에 마우스를 올려놓으면 vCenter Server가 예상대로 수행되고 있는지, 아니면 경고나 오류가 있는지 확인할 수 있습니다.
+
[NOTE]
====
vCenter Server를 추가하면 다음 상태를 볼 수 있습니다.  하지만 vCenter Server를 추가한 후 해당 VM의 성능 및 지연 시간 데이터가 정확하게 반영되려면 최대 1시간이 걸릴 수 있습니다.

====
+
** 녹색: "정상"은 vCenter Server가 검색되었고 성능 측정 항목이 성공적으로 수집되었음을 나타냅니다.
** 노란색: "경고"(예: vCenter Server의 통계 수준이 각 개체에 대한 통계를 얻기 위해 3 이상으로 설정되지 않은 경우)
** 주황색: "오류"(예외, 구성 데이터 수집 실패 또는 vCenter Server에 접근할 수 없는 등의 내부 오류를 나타냄) 열 표시 아이콘(*표시/숨기기*)을 클릭하면 vCenter Server 상태에 대한 상태 메시지를 보고 문제를 해결할 수 있습니다.


. vCenter Server에 접근할 수 없거나 자격 증명이 변경된 경우 *vCenter* > *편집*을 선택하여 vCenter Server 세부 정보를 편집합니다.
. *VMware vCenter Server 편집* 페이지에서 필요한 변경 사항을 적용합니다.
. *저장*을 클릭하세요.


*vCenter Server 데이터 수집이 시작됩니다*

vCenter Server는 실시간으로 20초 성능 데이터 샘플을 수집하여 5분 샘플로 정리합니다.  Unified Manager의 성능 데이터 수집 일정은 vCenter Server의 기본 설정을 기반으로 합니다.  Unified Manager는 vCenter Server에서 얻은 5분 샘플을 처리하고 가상 디스크, VM 및 호스트의 IOPS와 대기 시간의 시간당 평균을 계산합니다.  데이터 저장소의 경우 Unified Manager는 ONTAP 에서 얻은 샘플을 통해 IOPS와 대기 시간의 시간당 평균을 계산합니다.  이러한 값은 매시 정각에 제공됩니다.  vCenter Server를 추가한 직후에는 성능 측정 항목을 사용할 수 없으며, 다음 시간이 시작되어야만 사용할 수 있습니다.  성능 데이터 폴링은 구성 데이터 수집 주기를 완료하면 시작됩니다.

vCenter Server 구성 데이터를 폴링하기 위해 Unified Manager는 클러스터 구성 데이터를 수집하는 경우와 동일한 일정을 따릅니다.  vCenter Server 구성 및 성능 데이터 수집 일정에 대한 자세한 내용은 "클러스터 구성 및 성능 데이터 수집 활동"을 참조하세요.

*관련 정보*

link:../performance-checker/concept_cluster_configuration_and_performance_data_collection_activity.html["클러스터 구성 및 성능 데이터 수집 활동"]
