---
permalink: storage-mgmt/task_edit_user_and_group_quota_email_addresses.html 
sidebar: sidebar 
keywords: edit, user, group, quota, email, addresses 
summary: '클러스터, 스토리지 가상 머신(SVM), 볼륨, Q트리, 사용자 또는 사용자 그룹과 관련된 사용자 할당량에 따라 이메일 주소를 수정할 수 있습니다.  사용자 및 그룹 할당량 이메일 주소 생성 규칙 대화 상자에서 지정한 규칙에 따라 생성된 이메일 주소를 재정의하려면 이메일 주소를 수정할 수 있습니다.' 
---
= 사용자 및 그룹 할당량 이메일 주소 편집
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터, 스토리지 가상 머신(SVM), 볼륨, Q트리, 사용자 또는 사용자 그룹과 관련된 사용자 할당량에 따라 이메일 주소를 수정할 수 있습니다.  사용자 및 그룹 할당량 이메일 주소 생성 규칙 대화 상자에서 지정한 규칙에 따라 생성된 이메일 주소를 재정의하려면 이메일 주소를 수정할 수 있습니다.

.시작하기 전에
* 운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 당신은 검토해야 합니다link:reference_rules_to_generate_user_and_group_quota.html["규칙 생성을 위한 지침"] .


이메일 주소를 편집하는 경우 사용자 및 그룹 할당량 이메일 주소를 생성하는 규칙이 더 이상 할당량에 적용되지 않습니다.  지정된 규칙에 따라 생성된 이메일 주소로 알림을 보내려면 이메일 주소를 삭제하고 변경 사항을 저장해야 합니다.

.단계
. 왼쪽 탐색 창에서 *저장소* > *SVM*을 클릭합니다.
. *상태: 모든 저장소 VM* 보기에서 SVM을 선택한 다음 *사용자 및 그룹 할당량* 탭을 클릭합니다.
. 탭 행 아래에 있는 *이메일 주소 편집*을 클릭하세요.
. *이메일 주소 편집* 대화 상자에서 적절한 작업을 수행합니다.
+
|===
| 만약에... | 그 다음에... 


 a| 
지정된 규칙에 의해 생성된 이메일 주소로 알림을 보내려고 합니다.
 a| 
.. *이메일 주소* 필드에서 이메일 주소를 삭제하세요.
.. *저장*을 클릭하세요.
.. F5를 눌러 브라우저를 새로 고치면 이메일 주소 편집 대화 상자가 다시 로드됩니다.  지정된 규칙에 의해 생성된 이메일 주소는 *이메일 주소* 필드에 표시됩니다.




 a| 
지정된 이메일 주소로 알림을 보내려고 합니다.
 a| 
.. *이메일 주소* 필드에서 이메일 주소를 수정하세요.
.. *저장*을 클릭하세요. 사용자 및 그룹 할당량 이메일 주소를 생성하는 규칙은 더 이상 할당량에 적용되지 않습니다.


|===

