---
permalink: storage-mgmt/task_export_storage_data_as_reports.html 
sidebar: sidebar 
keywords: export, storage, data, reports 
summary: 다양한 출력 형식으로 저장 데이터를 내보낸 다음, 내보낸 데이터를 사용하여 보고서를 작성할 수 있습니다.  예를 들어, 해결되지 않은 중요 이벤트가 10개 있는 경우 이벤트 관리 인벤토리 페이지에서 데이터를 내보내 보고서를 만든 다음, 문제를 해결할 수 있는 관리자에게 보고서를 보낼 수 있습니다. 
---
= 저장소 데이터를 보고서로 내보내기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다양한 출력 형식으로 저장 데이터를 내보낸 다음, 내보낸 데이터를 사용하여 보고서를 작성할 수 있습니다.  예를 들어, 해결되지 않은 중요 이벤트가 10개 있는 경우 이벤트 관리 인벤토리 페이지에서 데이터를 내보내 보고서를 만든 다음, 문제를 해결할 수 있는 관리자에게 보고서를 보낼 수 있습니다.

데이터를 내보낼 수 있습니다 `.csv` 파일, `.xlsx` 파일 또는 `.pdf` *저장소* 및 *네트워크* 인벤토리 페이지에서 문서를 작성하고 내보낸 데이터를 사용하여 보고서를 작성합니다.  제품에는 다른 위치만 있습니다. `.csv` 또는 `.pdf` 파일을 생성할 수 있습니다.

.단계
. 다음 작업 중 하나를 수행합니다.
+
|===
| 내보내고 싶다면... | 이렇게 하세요... 


 a| 
저장소 객체 인벤토리 세부 정보
 a| 
왼쪽 탐색 메뉴에서 *저장소* 또는 *네트워크*를 클릭한 다음, 저장소 개체를 선택합니다.  시스템에서 제공하는 보기 중 하나 또는 사용자가 만든 사용자 정의 보기를 선택하세요.



 a| 
QoS 정책 그룹 세부 정보
 a| 
왼쪽 탐색 메뉴에서 *저장소* > *QoS 정책 그룹*을 클릭합니다.



 a| 
저장 용량 및 보호 내역 세부 정보
 a| 
*저장소* > *집계* 또는 *저장소* > *볼륨*을 클릭한 다음, 단일 집계 또는 볼륨을 선택합니다.



 a| 
이벤트 세부 정보
 a| 
왼쪽 탐색 메뉴에서 *이벤트 관리*를 클릭합니다.



 a| 
스토리지 객체 상위 10개 성능 세부 정보
 a| 
*저장소* > *클러스터* > *성능: 모든 클러스터*를 클릭한 다음, 클러스터를 선택하고 *상위 성능자* 탭을 선택합니다.  그런 다음 저장소 개체와 성능 카운터를 선택합니다.

|===
. *보고서* 버튼(일부 UI 페이지에서는 *내보내기* 버튼)을 클릭합니다.
. *CSV 다운로드*, *PDF 다운로드* 또는 *Excel 다운로드*를 클릭하여 내보내기 요청을 확인하세요.
+
상위 성과자 탭에서는 보고 있는 단일 클러스터 또는 데이터 센터의 모든 클러스터에 대한 통계 보고서를 다운로드할 수 있습니다.

+
파일이 다운로드되었습니다.

. 적절한 응용프로그램에서 파일을 엽니다.


*관련 정보*

link:["상태/클러스터 인벤토리 페이지"]

link:../reporting/task_schedule_report.html["보고서 예약"]
