---
permalink: health-checker/concept_introduction_to_unified_manager_health_monitoring.html 
sidebar: sidebar 
keywords: introduction, active iq, unified manager, health, monitor 
summary: 'Active IQ Unified Manager (이전 OnCommand Unified Manager)를 사용하면 중앙 사용자 인터페이스를 통해 ONTAP 소프트웨어를 실행하는 많은 수의 시스템을 모니터링할 수 있습니다.  Unified Manager 서버 인프라는 확장성, 지원성, 향상된 모니터링 및 알림 기능을 제공합니다.' 
---
= Active IQ Unified Manager 상태 모니터링 소개
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager (이전 OnCommand Unified Manager)를 사용하면 중앙 사용자 인터페이스를 통해 ONTAP 소프트웨어를 실행하는 많은 수의 시스템을 모니터링할 수 있습니다.  Unified Manager 서버 인프라는 확장성, 지원성, 향상된 모니터링 및 알림 기능을 제공합니다.

Unified Manager의 주요 기능으로는 모니터링, 알림, 클러스터 가용성 및 용량 관리, 보호 기능 관리, 진단 데이터 번들링 및 기술 지원팀으로 전송 등이 있습니다.

Unified Manager를 사용하여 클러스터를 모니터링할 수 있습니다.  클러스터에서 문제가 발생하면 Unified Manager는 이벤트를 통해 해당 문제의 세부 정보를 알려줍니다.  일부 이벤트에서는 문제를 바로잡는 데 필요한 시정 조치도 제공합니다.  문제가 발생하면 이메일과 SNMP 트랩을 통해 알림을 받을 수 있도록 이벤트에 대한 알림을 구성할 수 있습니다.

Unified Manager를 사용하면 주석과 연결하여 환경의 스토리지 객체를 관리할 수 있습니다.  사용자 정의 주석을 만들고 규칙을 통해 클러스터, 스토리지 가상 머신(SVM), 볼륨을 주석과 동적으로 연결할 수 있습니다.

각 클러스터 개체에 대한 용량 및 상태 차트에 제공된 정보를 사용하여 클러스터 개체의 저장 요구 사항을 계획할 수도 있습니다.



[[physical-and-logical-capacity]]
== 물리적 및 논리적 용량

Unified Manager는 ONTAP 스토리지 객체에 사용되는 물리적 공간과 논리적 공간의 개념을 활용합니다.

* 물리적 용량: 물리적 공간은 볼륨에 사용되는 물리적 저장 블록을 말합니다.  "물리적 사용 용량"은 일반적으로 저장 효율성 기능(중복 제거 및 압축 등)으로 인한 데이터 감소로 인해 논리적 사용 용량보다 작습니다.
* 논리적 용량: 논리적 공간은 볼륨에서 사용 가능한 공간(논리적 블록)을 의미합니다.  논리적 공간은 중복 제거나 압축 결과를 고려하지 않고 이론적 공간을 어떻게 사용할 수 있는지를 나타냅니다.  "사용된 논리적 공간"은 사용된 물리적 공간과 구성된 저장 효율성 기능(중복 제거 및 압축 등)을 통해 절감된 공간을 합친 것입니다.  이 측정값은 실제 사용 용량보다 크게 나타나는 경우가 많은데, 이는 여기에는 데이터 압축 및 기타 물리적 공간의 감소가 반영되지 않기 때문입니다.  따라서 총 논리적 용량은 제공된 공간보다 높을 수 있습니다.




[[capacity-measurement-units]]
== 용량 측정 단위

Unified Manager는 1024(2^10^)바이트의 이진 단위를 기준으로 저장 용량을 계산합니다.  ONTAP 9.10.0 및 이전 버전에서는 이러한 단위가 KB, MB, GB, TB, PB로 표시되었습니다.  ONTAP 9.10.1부터 Unified Manager에서는 KiB, MiB, GiB, TiB, PiB로 표시됩니다.


NOTE: ONTAP 의 모든 릴리스에서 처리량에 사용되는 단위는 초당 킬로바이트(Kbps), 초당 메가바이트(Mbps), 초당 기가바이트(Gbps), 초당 테라바이트(Tbps) 등으로 계속 사용됩니다.

[cols="4*"]
|===
| ONTAP 9.10.0 및 이전 버전의 Unified Manager에 표시되는 용량 단위 | ONTAP 9.10.1용 Unified Manager에 표시되는 용량 단위 | 계산 | 바이트 단위의 값 


 a| 
KB
 a| 
키비
 a| 
1024
 a| 
1024바이트



 a| 
엠비
 a| 
미비
 a| 
1024 * 1024
 a| 
1,048,576바이트



 a| 
영국
 a| 
수코양이
 a| 
1024 * 1024 * 1024
 a| 
1,073,741,824바이트



 a| 
결핵
 a| 
티비
 a| 
1024 * 1024 * 1024 * 1024
 a| 
1,099,511,627,776바이트

|===