---
permalink: health-checker/concept_unified_manager_health_monitoring_features.html 
sidebar: sidebar 
keywords: unified manager, health, monitor, features 
summary: Unified Manager는 확장성, 지원성, 향상된 모니터링 및 알림 기능을 제공하는 서버 인프라를 기반으로 구축되었습니다.  Unified Manager는 ONTAP 소프트웨어를 실행하는 시스템의 모니터링을 지원합니다. 
---
= Unified Manager 상태 모니터링 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 확장성, 지원성, 향상된 모니터링 및 알림 기능을 제공하는 서버 인프라를 기반으로 구축되었습니다.  Unified Manager는 ONTAP 소프트웨어를 실행하는 시스템의 모니터링을 지원합니다.

Unified Manager에는 다음과 같은 기능이 포함되어 있습니다.

* ONTAP 소프트웨어가 설치된 시스템에 대한 검색, 모니터링 및 알림:
+
** 물리적 객체: 노드, 디스크, 디스크 셸프, SFO 쌍, 포트 및 플래시 캐시
** 논리적 개체: 클러스터, 스토리지 가상 머신(SVM), 집계, 볼륨, LUN, 네임스페이스, qtree, LIF, 스냅샷 복사본, 연결 경로, NFS 공유, SMB 공유, 사용자 및 그룹 할당량, QoS 정책 그룹, 개시자 그룹
** 프로토콜: CIFS, NFS, FC, iSCSI, NVMe 및 FCoE
** 스토리지 효율성: SSD 집계, Flash Pool 집계, FabricPool 집계, 중복 제거 및 압축
** 보호: SnapMirror 관계(동기 및 비동기) 및 SnapVault 관계


* 클러스터 검색 및 모니터링 상태 보기
* FC 및 IP 구성을 통한 MetroCluster : 클러스터 구성 요소의 구성, 문제 및 연결 상태를 보고 모니터링합니다.  FC 구성을 통한 MetroCluster 위한 MetroCluster 스위치 및 브리지
* 향상된 경고, 이벤트 및 임계값 인프라
* LDAP, LDAPS, SAML 인증 및 로컬 사용자 지원
* RBAC(사전 정의된 역할 집합용)
* AutoSupport 및 지원 번들
* 환경의 용량, 가용성, 보호 및 성능 상태를 보여주는 향상된 대시보드
* 볼륨 이동 상호 운용성, 볼륨 이동 기록 및 접합 경로 변경 기록
* 일부 디스크 실패, MetroCluster 집계 미러링 저하, MetroCluster 예비 디스크 남음 이벤트와 같은 이벤트에 영향을 받는 리소스를 그래픽으로 표시하는 영향 범위 영역
* MetroCluster 이벤트의 효과를 표시하는 가능한 효과 영역
* 일부 디스크 실패, MetroCluster 집계 미러링 저하, MetroCluster 예비 디스크 남음 이벤트와 같은 이벤트를 해결하기 위해 수행할 수 있는 작업을 표시하는 제안된 시정 조치 영역
* 볼륨 오프라인 이벤트, 볼륨 제한 이벤트, 씬 프로비저닝 볼륨 공간 위험 이벤트와 같은 이벤트에 영향을 받을 수 있는 리소스를 표시하는 영향을 받을 수 있는 리소스 영역
* FlexVol 또는 FlexGroup 볼륨이 있는 SVM 지원
* 노드 루트 볼륨 모니터링 지원
* 회수 가능한 공간 계산 및 스냅샷 복사본 삭제를 포함한 향상된 스냅샷 복사본 모니터링
* 저장소 객체에 대한 주석
* 물리적 및 논리적 용량, 활용도, 공간 절약, 성능 및 관련 이벤트와 같은 스토리지 객체 정보의 보고서 생성 및 관리
* OnCommand Workflow Automation 과 통합하여 워크플로 실행
+
Storage Automation Store에는 OnCommand Workflow Automation (WFA)과 함께 사용하도록 개발된 NetApp 인증 자동화 스토리지 워크플로 팩이 포함되어 있습니다.  팩을 다운로드한 후 WFA로 가져와서 실행할 수 있습니다.  자동화된 워크플로는 여기에서 사용할 수 있습니다.

+
https://automationstore.netapp.com["스토리지 자동화 스토어"]


