---
permalink: health-checker/concept_common_unified_manager_administrative_workflows_and_tasks.html 
sidebar: sidebar 
keywords: Common, unified, manager, health, workflows, tasks 
summary: 'Unified Manager와 관련된 일반적인 관리 워크플로 및 작업에는 모니터링할 스토리지 클러스터 선택, 데이터 가용성, 용량 및 보호에 부정적인 영향을 미치는 조건 진단, 손실된 데이터 복원, 볼륨 구성 및 관리, 진단 데이터를 묶어 기술 지원팀에 전송(필요한 경우) 등이 있습니다.' 
---
= 공통 Unified Manager 상태 워크플로 및 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager와 관련된 일반적인 관리 워크플로 및 작업에는 모니터링할 스토리지 클러스터 선택, 데이터 가용성, 용량 및 보호에 부정적인 영향을 미치는 조건 진단, 손실된 데이터 복원, 볼륨 구성 및 관리, 진단 데이터를 묶어 기술 지원팀에 전송(필요한 경우) 등이 있습니다.

Unified Manager를 사용하면 스토리지 관리자가 대시보드를 보고, 관리되는 스토리지 클러스터의 전체 용량, 가용성 및 보호 상태를 평가한 다음, 발생할 수 있는 특정 문제를 신속하게 식별, 찾고, 진단하고, 해결을 위해 할당할 수 있습니다.

관리되는 스토리지 개체의 스토리지 용량이나 데이터 가용성에 영향을 미치는 클러스터, 스토리지 가상 머신(SVM), 볼륨 또는 FlexGroup 볼륨과 관련된 가장 중요한 문제는 대시보드 페이지의 시스템 상태 그래프와 이벤트에 표시됩니다.  심각한 문제가 발견되면 이 페이지에서는 적절한 문제 해결 워크플로를 지원하는 링크를 제공합니다.

Unified Manager는 OnCommand Workflow Automation (WFA)과 같은 관련 관리 도구가 포함된 워크플로에 포함되어 스토리지 리소스의 직접적인 구성을 지원할 수도 있습니다.

이 문서에서는 다음 관리 작업과 관련된 일반적인 워크플로를 설명합니다.

* 가용성 문제 진단 및 관리
+
하드웨어 오류나 스토리지 리소스 구성 문제로 인해 대시보드 페이지에 데이터 가용성 이벤트가 표시되는 경우, 스토리지 관리자는 내장된 링크를 따라 영향을 받는 스토리지 리소스에 대한 연결 정보를 보고, 문제 해결 조언을 보고, 문제 해결을 다른 관리자에게 할당할 수 있습니다.

* 성능 사고 구성 및 모니터링
+
관리자는 모니터링되는 스토리지 시스템 리소스의 성능을 모니터링하고 관리할 수 있습니다.  를 참조하십시오link:../performance-checker/concept_introduction_to_unified_manager_performance_monitoring.html["Active IQ Unified Manager 성능 모니터링 소개"] 자세한 내용은.

* 볼륨 용량 문제 진단 및 관리
+
대시보드 페이지에 볼륨 저장소 용량 문제가 표시되면 저장소 관리자는 내장된 링크를 따라 영향을 받는 볼륨의 저장소 용량과 관련된 현재 및 과거 추세를 보고, 문제 해결 조언을 보고, 다른 관리자에게 문제 해결을 할당할 수 있습니다.

* 보호 관계 문제 구성, 모니터링 및 진단
+
보호 관계를 만들고 구성한 후, 스토리지 관리자는 보호 관계와 관련된 잠재적인 문제, 보호 관계의 현재 상태, 영향을 받는 관계에 대한 현재 및 과거 보호 작업 성공 정보, 문제 해결 조언을 볼 수 있습니다.  를 참조하십시오link:../data-protection/concept_create_and_monitor_protection_relationships.html["보호 관계 생성, 모니터링 및 문제 해결"] 자세한 내용은.

* 백업 파일을 생성하고 백업 파일에서 데이터를 복원합니다.
* 주석과 스토리지 객체 연결
+
스토리지 객체를 주석과 연결하면 스토리지 관리자가 스토리지 객체와 관련된 이벤트를 필터링하고 볼 수 있으며, 이를 통해 스토리지 관리자가 이벤트와 관련된 문제의 우선순위를 지정하고 해결할 수 있습니다.

* REST API를 사용하면 Unified Manager에서 수집한 상태, 용량 및 성능 정보를 보고 클러스터를 관리하는 데 도움이 됩니다. 보다link:../api-automation/concept_get_started_with_um_apis.html["Active IQ Unified Manager REST API 시작하기"] 자세한 내용은.
* 기술 지원팀에 지원 번들 보내기
+
스토리지 관리자는 유지 관리 콘솔을 사용하여 지원 번들을 검색하여 기술 지원팀에 보낼 수 있습니다.  문제에 AutoSupport 메시지에서 제공하는 것보다 더 자세한 진단 및 문제 해결이 필요한 경우 지원 번들을 기술 지원팀에 보내야 합니다.


