---
permalink: health-checker/concept_configure_destination_and_schedule_for_database_dump_backups.html 
sidebar: sidebar 
keywords: configure, destination, schedule, database dump, backups, snapshot copy, copies 
summary: Unified Manager 데이터베이스 덤프 백업 설정을 구성하여 데이터베이스 백업 경로, 보존 횟수 및 백업 일정을 설정할 수 있습니다.  매일 또는 매주 예약된 백업을 활성화할 수 있습니다.  기본적으로 예약된 백업은 비활성화되어 있지만 백업 일정을 설정해야 합니다. 
---
= 데이터베이스 덤프 백업의 대상 및 일정을 구성합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager 데이터베이스 덤프 백업 설정을 구성하여 데이터베이스 백업 경로, 보존 횟수 및 백업 일정을 설정할 수 있습니다.  매일 또는 매주 예약된 백업을 활성화할 수 있습니다.  기본적으로 예약된 백업은 비활성화되어 있지만 백업 일정을 설정해야 합니다.

.시작하기 전에
* 운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 백업 경로로 정의한 위치에는 최소 150GB의 사용 가능한 공간이 있어야 합니다.
+
Unified Manager 호스트 시스템 외부의 원격 위치를 사용하는 것이 좋습니다.

* Linux 시스템에 Unified Manager를 설치하고 MySQL 백업을 사용하는 경우 백업 디렉토리에 다음 권한과 소유권이 설정되어 있는지 확인하세요.
+
권한: 0750, 소유권: jboss:maintenance

* Unified Manager가 Windows 시스템에 설치되고 MySQL 백업을 사용하는 경우, 관리자만 백업 디렉토리에 액세스할 수 있도록 해야 합니다.


첫 번째 백업은 전체 백업이기 때문에 후속 백업보다 처음 백업을 수행할 때 더 많은 시간이 필요합니다.  전체 백업은 1GB가 넘을 수 있으며 3~4시간이 걸릴 수 있습니다.  이후 백업은 증분식으로 진행되므로 시간이 덜 걸립니다.

[NOTE]
====
* 백업에 할당한 공간에 비해 증분 백업 파일의 수가 너무 많다고 생각되면 주기적으로 전체 백업을 수행하여 이전 백업과 증분 파일을 대체할 수 있습니다.  또 다른 옵션으로 스냅샷 복사본을 사용하여 백업을 수행할 수 있습니다.
* 새로운 클러스터를 추가한 후 처음 15일 동안 수행한 백업은 과거 성능 데이터를 얻기에 충분히 정확하지 않을 수 있습니다.


====
.단계
. 왼쪽 탐색 창에서 *일반* > *데이터베이스 백업*을 클릭합니다.
. *데이터베이스 백업* 페이지에서 *백업 설정*을 클릭합니다.
. 백업 경로, 보존 횟수 및 일정에 적합한 값을 구성합니다.
+
보존 횟수의 기본값은 10입니다. 무제한 백업을 생성하려면 0을 사용할 수 있습니다.

. *매일 예약* 또는 *매주 예약* 버튼을 선택한 다음, 일정 세부 정보를 지정합니다.
. *적용*을 클릭하세요.


데이터베이스 덤프 백업 파일은 일정에 따라 생성됩니다.  사용 가능한 백업 파일은 데이터베이스 백업 페이지에서 볼 수 있습니다.
