---
permalink: health-checker/concept_what_database_restore_is.html 
sidebar: sidebar 
keywords: unified manager, database, restore 
summary: MySQL 데이터베이스 복원은 기존 Unified Manager 백업 파일을 동일하거나 다른 Unified Manager 서버로 복원하는 프로세스입니다.  Unified Manager 유지 관리 콘솔에서 복원 작업을 수행합니다. 
---
= 데이터베이스 복원이란 무엇인가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MySQL 데이터베이스 복원은 기존 Unified Manager 백업 파일을 동일하거나 다른 Unified Manager 서버로 복원하는 프로세스입니다.  Unified Manager 유지 관리 콘솔에서 복원 작업을 수행합니다.

동일한(로컬) 시스템에서 복원 작업을 수행하고 백업 파일이 모두 로컬에 저장된 경우 기본 위치를 사용하여 복원 옵션을 실행할 수 있습니다.  다른 Unified Manager 시스템(원격 시스템)에서 복원 작업을 수행하는 경우 복원 옵션을 실행하기 전에 보조 저장소에서 백업 파일을 로컬 디스크로 복사해야 합니다.

복원 프로세스 중에는 Unified Manager에서 로그아웃됩니다.  복원 프로세스가 완료되면 시스템에 로그인할 수 있습니다.

백업 이미지를 새 서버로 복원하는 경우 복원 작업이 완료된 후 새 HTTPS 보안 인증서를 생성하고 Unified Manager 서버를 다시 시작해야 합니다.  백업 이미지를 새 서버로 복원할 때 필요한 경우 SAML 인증 설정도 재구성해야 합니다.

[NOTE]
====
Unified Manager가 최신 버전의 소프트웨어로 업그레이드된 후에는 이전 백업 파일을 사용하여 이미지를 복원할 수 없습니다.  공간을 절약하기 위해 Unified Manager를 업그레이드하면 최신 파일을 제외한 모든 이전 백업 파일이 자동으로 제거됩니다.

====
*관련 정보*

link:../config/task_generate_an_https_security_certificate_ocf.html["HTTPS 보안 인증서 생성"]

link:../config/task_enable_saml_authentication_um.html["SAML 인증 활성화"]

link:../config/concept_authentication_with_active_directory_or_openldap.html["Active Directory 또는 OpenLDAP를 통한 인증"]
