---
permalink: health-checker/concept_how_group_rules_work_for_groups.html 
sidebar: sidebar 
keywords: group rules, work, groups 
summary: '그룹 규칙은 스토리지 개체(볼륨, 클러스터 또는 SVM)를 특정 그룹에 포함할 수 있도록 정의하는 기준입니다.  그룹에 대한 그룹 규칙을 정의하기 위해 조건 그룹이나 조건을 사용할 수 있습니다.' 
---
= 그룹에 대한 그룹 규칙의 작동 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그룹 규칙은 스토리지 개체(볼륨, 클러스터 또는 SVM)를 특정 그룹에 포함할 수 있도록 정의하는 기준입니다.  그룹에 대한 그룹 규칙을 정의하기 위해 조건 그룹이나 조건을 사용할 수 있습니다.

* 그룹 규칙은 그룹에 연결해야 합니다.
* 그룹 규칙에 대해서는 개체 유형을 연결해야 합니다. 그룹 규칙에 대해서는 하나의 개체 유형만 연결됩니다.
* 각 모니터링 주기가 끝나거나 규칙이 생성, 편집 또는 삭제될 때 저장소 개체가 그룹에 추가되거나 제거됩니다.
* 그룹 규칙은 하나 이상의 조건 그룹을 가질 수 있으며, 각 조건 그룹은 하나 이상의 조건을 가질 수 있습니다.
* 저장 객체는 사용자가 만든 그룹 규칙에 따라 여러 그룹에 속할 수 있습니다.




== 정황

여러 개의 조건 그룹을 만들 수 있으며, 각 조건 그룹에는 하나 이상의 조건이 포함될 수 있습니다.  그룹에 대한 그룹 규칙에서 정의된 모든 조건 그룹을 적용하여 그룹에 포함되는 스토리지 객체를 지정할 수 있습니다.

조건 그룹 내의 조건은 논리적 AND를 사용하여 실행됩니다.  조건 그룹의 모든 조건이 충족되어야 합니다.  그룹 규칙을 만들거나 수정하면 조건 그룹의 모든 조건을 충족하는 저장소 개체만 적용, 선택 및 그룹화하는 조건이 생성됩니다.  그룹에 포함할 스토리지 개체의 범위를 좁히려는 경우 조건 그룹 내에서 여러 조건을 사용할 수 있습니다.

다음 피연산자와 연산자를 사용하고 필요한 값을 지정하여 저장 객체로 조건을 생성할 수 있습니다.

[cols="2*"]
|===
| 저장 객체 유형 | 적용 가능한 피연산자 


 a| 
용량
 a| 
* 객체 이름
* 소유 클러스터 이름
* SVM 이름 소유
* 주석




 a| 
서포트 머신(SVM)
 a| 
* 객체 이름
* 소유 클러스터 이름
* 주석




 a| 
무리
 a| 
* 객체 이름
* 주석


|===
저장 객체에 대한 피연산자로 주석을 선택하면 "`Is`" 연산자를 사용할 수 있습니다.  다른 모든 피연산자의 경우 연산자로 "`Is`" 또는 "`Contains`"를 선택할 수 있습니다.

* 피연산자
+
Unified Manager의 피연산자 목록은 선택한 개체 유형에 따라 변경됩니다.  목록에는 Unified Manager에서 정의한 개체 이름, 소유 클러스터 이름, 소유 SVM 이름 및 주석이 포함됩니다.

* 연산자
+
연산자 목록은 조건에 대해 선택된 피연산자에 따라 변경됩니다.  Unified Manager에서 지원되는 연산자는 "`Is`"와 "`Contains`"입니다.

+
"`Is`" 연산자를 선택하면, 선택된 피연산자에 대해 제공된 값과 피연산자 값이 정확히 일치하는지 여부가 조건 평가에서 평가됩니다.

+
``Contains`` 연산자를 선택하면 조건이 다음 기준 중 하나를 충족하는지 평가됩니다.

+
** 피연산자 값은 선택된 피연산자에 제공된 값과 정확히 일치합니다.
** 피연산자 값에는 선택된 피연산자에 대해 제공된 값이 포함됩니다.


* 가치
+
값 필드는 선택한 피연산자에 따라 변경됩니다.





== 조건이 포함된 그룹 규칙의 예

다음 두 가지 조건을 갖춘 볼륨에 대한 조건 그룹을 고려하세요.

* 이름에 "`vol`"이 포함되어 있습니다.
* SVM 이름은 "`data_svm`"입니다.


이 조건 그룹은 이름에 "`vol`"이 포함되어 있고 이름이 "`data_svm`"인 SVM에 호스팅된 모든 볼륨을 선택합니다.



== 조건 그룹

조건 그룹은 논리적 OR을 사용하여 실행된 다음 저장소 개체에 적용됩니다.  저장 객체는 그룹에 포함되려면 조건 그룹 중 하나를 만족해야 합니다.  모든 조건 그룹의 저장 객체가 결합됩니다.  조건 그룹을 사용하면 그룹에 포함할 저장 개체의 범위를 늘릴 수 있습니다.



== 조건 그룹이 있는 그룹 규칙의 예

각 그룹에 다음 두 가지 조건이 포함된 볼륨에 대한 두 개의 조건 그룹을 고려하세요.

* 조건 그룹 1
+
** 이름에 "`vol`"이 포함되어 있습니다.
** SVM 이름은 "`data_svm`"입니다. 조건 그룹 1은 이름에 "`vol`"이 포함되어 있고 이름이 "`data_svm`"인 SVM에 호스팅된 모든 볼륨을 선택합니다.


* 조건 그룹 2
+
** 이름에 "`vol`"이 포함되어 있습니다.
** data-priority의 주석 값은 "`critical`"입니다. 조건 그룹 2는 이름에 "`vol`"이 포함되고 data-priority 주석 값이 "`critical`"로 주석이 달린 모든 볼륨을 선택합니다.




이 두 조건 그룹을 포함하는 그룹 규칙이 스토리지 개체에 적용되면 다음 스토리지 개체가 선택한 그룹에 추가됩니다.

* 이름에 "`vol`"이 포함되어 있고 이름이 "`data_svm`"인 SVM에 호스팅된 모든 볼륨입니다.
* 이름에 "`vol`"이 포함되어 있고 데이터 우선순위 주석 값 "`critical`"이 주석 처리된 모든 볼륨입니다.

