---
permalink: health-checker/concept_how_annotation_rules_work_in_unified_manager.html 
sidebar: sidebar 
keywords: annotation rules, work, unified manager 
summary: '주석 규칙은 스토리지 개체(볼륨, 클러스터 또는 스토리지 가상 머신(SVM))에 주석을 달기 위해 정의하는 기준입니다.  주석 규칙을 정의하려면 조건 그룹이나 조건을 사용할 수 있습니다.' 
---
= Unified Manager에서 주석 규칙이 작동하는 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
주석 규칙은 스토리지 개체(볼륨, 클러스터 또는 스토리지 가상 머신(SVM))에 주석을 달기 위해 정의하는 기준입니다.  주석 규칙을 정의하려면 조건 그룹이나 조건을 사용할 수 있습니다.

* 주석 규칙을 주석에 연결해야 합니다.
* 주석 규칙에 대해 개체 유형을 연결해야 합니다. 주석 규칙에 대해 하나의 개체 유형만 연결할 수 있습니다.
* Unified Manager는 각 모니터링 주기가 끝날 때마다 또는 규칙이 생성, 편집, 삭제 또는 재정렬될 때마다 스토리지 개체에 주석을 추가하거나 제거합니다.
* 주석 규칙에는 하나 이상의 조건 그룹이 있을 수 있으며, 각 조건 그룹에는 하나 이상의 조건이 있을 수 있습니다.
* 저장 객체에는 여러 개의 주석이 있을 수 있습니다.  특정 주석에 대한 주석 규칙은 규칙 조건에서 다른 주석을 사용하여 이미 주석이 달린 개체에 다른 주석을 추가할 수도 있습니다.




== 정황

여러 개의 조건 그룹을 만들 수 있으며, 각 조건 그룹에는 하나 이상의 조건이 포함될 수 있습니다.  저장소 객체에 주석을 달기 위해 주석 규칙에 정의된 모든 조건 그룹을 적용할 수 있습니다.

조건 그룹 내의 조건은 논리적 AND를 사용하여 실행됩니다.  조건 그룹의 모든 조건이 충족되어야 합니다.  주석 규칙을 만들거나 수정하면 조건 그룹의 모든 조건을 충족하는 스토리지 개체만 적용하고 선택하고 주석을 다는 조건이 생성됩니다.  저장 객체에 주석을 달 범위를 좁히려는 경우 조건 그룹 내에서 여러 조건을 사용할 수 있습니다.

다음 피연산자와 연산자를 사용하고 필요한 값을 지정하여 저장 객체로 조건을 생성할 수 있습니다.

[cols="2*"]
|===
| 저장 객체 유형 | 적용 가능한 피연산자 


 a| 
용량
 a| 
* 객체 이름
* 소유 클러스터 이름
* SVM 이름 소유
* 주석




 a| 
서포트 머신(SVM)
 a| 
* 객체 이름
* 소유 클러스터 이름
* 주석




 a| 
무리
 a| 
* 객체 이름
* 주석


|===
저장 객체에 대한 피연산자로 주석을 선택하면 "`Is`" 연산자를 사용할 수 있습니다.  다른 모든 피연산자의 경우 연산자로 "`Is`" 또는 "`Contains`"를 선택할 수 있습니다.  "`Is`" 연산자를 선택하면, 선택된 피연산자에 제공된 값과 피연산자 값이 정확히 일치하는지 여부가 조건 평가에서 평가됩니다.  ``Contains`` 연산자를 선택하면 조건이 다음 기준 중 하나를 충족하는지 평가됩니다.

* 피연산자 값은 선택한 피연산자 값과 정확히 일치합니다.
* 피연산자 값에는 선택된 피연산자에 대해 제공된 값이 포함됩니다.




== 조건이 포함된 주석 규칙의 예

다음 두 가지 조건이 있는 볼륨에 대한 하나의 조건 그룹이 있는 주석 규칙을 고려하세요.

* 이름에 "`vol`"이 포함되어 있습니다.
* SVM 이름은 "`data_svm`"입니다.


이 주석 규칙은 이름에 "`vol`"이 포함되고 이름이 "`data_svm`"인 SVM에 호스팅된 모든 볼륨에 선택한 주석과 주석 유형을 주석으로 지정합니다.



== 조건 그룹

조건 그룹은 논리적 OR을 사용하여 실행된 다음 저장소 개체에 적용됩니다.  저장 객체는 주석을 달기 위해 조건 그룹 중 하나의 요구 사항을 충족해야 합니다.  모든 조건 그룹의 조건을 충족하는 저장 객체에 주석이 달립니다.  조건 그룹을 사용하면 주석이 추가될 저장 객체의 범위를 늘릴 수 있습니다.



== 조건 그룹이 있는 주석 규칙의 예

볼륨에 대한 두 개의 조건 그룹이 있는 주석 규칙을 고려합니다. 각 그룹에는 다음 두 가지 조건이 포함되어 있습니다.

* 조건 그룹 1
+
** 이름에 "`vol`"이 포함되어 있습니다.
** SVM 이름은 "`data_svm`"입니다. 이 조건 그룹은 이름에 "`vol`"이 포함되어 있고 이름이 "`data_svm`"인 SVM에 호스팅된 모든 볼륨에 주석을 추가합니다.


* 조건 그룹 2
+
** 이름에 "`vol`"이 포함되어 있습니다.
** data-priority의 주석 값은 "`critical`"입니다. 이 조건 그룹은 이름에 "vol`"이 포함되고 data-priority 주석 값이 "`critical`"인 모든 볼륨에 주석을 추가합니다.




이 두 조건 그룹을 포함하는 주석 규칙이 스토리지 개체에 적용되면 다음 스토리지 개체에 주석이 추가됩니다.

* 이름에 "`vol`"이 포함되어 있고 SVM에서 "`data_svm`"이라는 이름으로 호스팅되는 모든 볼륨입니다.
* 이름에 "`vol`"이 포함되어 있고 데이터 우선순위 주석 값이 "`critical`"로 주석 처리된 모든 볼륨입니다.

