---
permalink: health-checker/reference_setup_autosupport_page.html 
sidebar: sidebar 
keywords: autosupport, messages, support bundles, technical support 
summary: AutoSupport 페이지를 사용하면 기술 지원팀에 미리 정의된 AutoSupport 메시지와 주문형 AutoSupport 메시지를 보내 환경이 올바르게 작동하는지 확인하고 환경의 무결성을 유지하는 데 도움을 받을 수 있습니다.  AutoSupport 기본적으로 활성화되어 있으며 NetAppActive IQ의 이점을 얻으려면 비활성화해서는 안 됩니다. 
---
= AutoSupport 메시지와 지원 번들을 기술 지원팀에 보냅니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport 페이지를 사용하면 기술 지원팀에 미리 정의된 AutoSupport 메시지와 주문형 AutoSupport 메시지를 보내 환경이 올바르게 작동하는지 확인하고 환경의 무결성을 유지하는 데 도움을 받을 수 있습니다.  AutoSupport 기본적으로 활성화되어 있으며 NetAppActive IQ의 이점을 얻으려면 비활성화해서는 안 됩니다.

필요할 때마다 Unified Manager 서버에 대한 진단 시스템 정보와 자세한 데이터를 메시지로 보낼 수 있으며, 주기적으로 메시지를 보내도록 예약하거나, 심지어 지원 번들을 생성하여 기술 지원 팀에 보낼 수도 있습니다.

[NOTE]
====
스토리지 관리자 역할을 가진 사용자는 주문형 AutoSupport 메시지와 지원 번들을 생성하여 기술 지원팀에 보낼 수 있습니다.  그러나 관리자나 유지 관리 사용자만이 주기적 AutoSupport 활성화하거나 비활성화하고 HTTP 프록시 서버 설정 섹션에 설명된 대로 HTTP 설정을 구성할 수 있습니다.  HTTP 프록시 서버를 사용해야 하는 환경에서는 스토리지 관리자가 기술 지원팀에 주문형 AutoSupport 메시지와 지원 번들을 보내기 전에 구성이 완료되어야 합니다.

====


[[send-on-demand-autosupport-messages]]
== 주문형 AutoSupport 메시지 보내기

기술 지원팀이나 지정된 이메일 수신자, 또는 두 곳 모두에 주문형 메시지를 생성하여 보낼 수 있습니다.

.단계
. *일반* > * AutoSupport*로 이동하여 다음 작업 중 하나 또는 둘 다를 수행합니다.
. AutoSupport 메시지를 기술 지원팀에 보내려면 *기술 지원팀에 보내기* 확인란을 선택하세요.
. 특정 이메일 수신자에게 AutoSupport 메시지를 보내려면 *이메일 수신자에게 보내기* 확인란을 선택하고 수신자의 이메일 주소를 입력합니다.
. *저장*을 클릭하세요.
. * AutoSupport 생성 및 보내기*를 클릭하세요.




[[enable-periodic-autosupport]]
== 주기적 AutoSupport 활성화

문제 진단 및 해결을 위해 기술 지원팀에 구체적이고 미리 정의된 메시지를 주기적으로 보낼 수 있습니다.  이 기능은 기본적으로 활성화되어 있습니다.  비활성화된 경우 관리자나 유지 관리 사용자가 설정을 활성화할 수 있습니다.

.단계
. *일반* > * AutoSupport*로 이동합니다.
. 주기적 AutoSupport 섹션에서 * Active IQ 에 AutoSupport 데이터 주기적으로 전송 활성화* 확인란을 선택합니다.
. 필요한 경우 HTTP 프록시 서버 설정 섹션에 설명된 대로 HTTP 프록시 서버의 이름, 포트 및 인증 정보를 정의합니다.
. *저장*을 클릭하세요.




[[upload-on-demand-support-bundle]]
== 주문형 지원 번들 업로드

문제 해결 요구 사항에 따라 지원 번들을 생성하여 기술 지원팀에 보낼 수 있습니다.  Unified Manager는 가장 최근에 생성된 두 개의 지원 번들만 저장합니다.  이전 지원 번들은 시스템에서 삭제됩니다.

일부 유형의 지원 데이터는 많은 양의 클러스터 리소스를 사용하거나 완료하는 데 오랜 시간이 걸릴 수 있으므로 전체 지원 번들을 선택하면 특정 데이터 유형을 포함하거나 제외하여 지원 번들 크기를 줄일 수 있습니다.  또한 30일 분의 로그와 구성 데이터베이스 기록만 포함된 가벼운 지원 번들을 만드는 옵션도 있습니다. 여기에는 성능 데이터, 인수 기록 파일, 서버 힙 덤프가 제외됩니다.

.단계
. *일반* > * AutoSupport*로 이동합니다.
. 주문형 지원 번들 섹션에서 *지원 번들 생성 및 전송*을 클릭합니다.
. 기술 지원팀에 가벼운 지원 번들을 보내려면 지원 번들 생성 및 보내기 팝업에서 **가벼운 지원 번들 생성** 확인란을 선택합니다.
. 또는 전체 지원 번들을 보내려면 *전체 지원 번들 생성* 확인란을 선택합니다.  지원 번들에 포함하거나 제외할 특정 데이터 유형을 선택합니다.
+
[NOTE]
====
어떠한 데이터 유형도 선택하지 않더라도 지원 번들은 다른 Unified Manager 데이터와 함께 생성됩니다.

====
. *번들을 기술 지원팀에 보내기* 확인란을 선택하여 번들을 생성하고 기술 지원팀에 보냅니다.  이 확인란을 선택하지 않으면 번들이 생성되어 Unified Manager 서버에 로컬로 저장됩니다.  생성된 지원 번들은 나중에 VMware 시스템의 /support 디렉토리에서 사용할 수 있습니다. `/opt/netapp/data/support/` Linux 시스템에서, 그리고 `ProgramData\NetApp\OnCommandAppData\ocum\support` Windows 시스템에서.
. *보내기*를 클릭하세요.




[[set-up-http-proxy-server]]
== HTTP 프록시 서버 설정

Unified Manager 서버에서 직접 액세스할 수 없는 환경인 경우, AutoSupport 콘텐츠를 지원팀에 보내기 위해 인터넷 액세스를 제공하는 프록시를 지정할 수 있습니다.  이 섹션은 관리자와 유지 관리 사용자만 사용할 수 있습니다.

* *HTTP 프록시 사용*
+
HTTP 프록시로 사용되는 서버를 식별하려면 이 상자를 선택하세요.

+
프록시 서버의 호스트 이름 또는 IP 주소와 서버에 연결하는 데 사용되는 포트 번호를 입력하세요.

* *인증을 사용하세요*
+
HTTP 프록시로 사용되는 서버에 액세스하기 위해 인증 정보를 제공해야 하는 경우 이 상자를 선택하세요.

+
HTTP 프록시를 인증하는 데 필요한 사용자 이름과 비밀번호를 입력하세요.



[NOTE]
====
기본 인증만 제공하는 HTTP 프록시는 지원되지 않습니다.

====