---
permalink: health-checker/reference_health_aggregate_details_page.html 
sidebar: sidebar 
keywords: unified manager, aggregate, health details page 
summary: 집계/상태 세부 정보 페이지를 사용하면 용량, 디스크 정보, 구성 세부 정보, 생성된 이벤트 등 선택한 집계에 대한 자세한 정보를 볼 수 있습니다.  해당 집계에 대한 관련 객체 및 관련 알림에 대한 정보도 볼 수 있습니다. 
---
= 집계/상태 세부 정보 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
집계/상태 세부 정보 페이지를 사용하면 용량, 디스크 정보, 구성 세부 정보, 생성된 이벤트 등 선택한 집계에 대한 자세한 정보를 볼 수 있습니다.  해당 집계에 대한 관련 객체 및 관련 알림에 대한 정보도 볼 수 있습니다.



== 명령 버튼

[NOTE]
====
FabricPool 활성화된 집계를 모니터링할 때 이 페이지의 커밋된 값과 초과 커밋된 값은 로컬 또는 성능 계층 용량에만 적용됩니다.  클라우드 계층에서 사용 가능한 공간의 양은 초과 할당 값에 반영되지 않습니다.  마찬가지로, 집계 임계값은 로컬 성능 계층에만 적용됩니다.

====
명령 단추를 사용하면 선택한 집계에 대해 다음 작업을 수행할 수 있습니다.

* *성능 보기로 전환*
+
집계/성과 세부 정보 페이지로 이동할 수 있습니다.

* *행위*
+
** 알림 추가
+
선택한 집계에 알림을 추가할 수 있습니다.

** 임계값 편집
+
선택한 집계에 대한 임계값 설정을 수정할 수 있습니다.



* *집계 보기*
+
Health: All Aggregates 보기로 이동할 수 있습니다.





== 용량 탭

용량 탭에는 선택한 집계에 대한 자세한 정보(용량, 임계값, 일일 성장률 등)가 표시됩니다.

기본적으로 루트 집계에 대한 용량 이벤트는 생성되지 않습니다.  또한 Unified Manager에서 사용하는 임계값은 노드 루트 집계에 적용할 수 없습니다.  이러한 이벤트 생성에 대한 설정을 수정할 수 있는 사람은 기술 지원 담당자뿐입니다.  기술 지원 담당자가 설정을 수정하면 임계값이 노드 루트 집계에 적용됩니다.

* *용량*
+
집계에 대한 용량 세부 정보를 표시하는 데이터 용량 그래프와 스냅샷 복사본 그래프를 표시합니다.

+
** 사용된 논리적 공간
+
ONTAP 저장 효율성 기술을 사용하여 절감한 비용을 적용하지 않고 집계된 데이터의 실제 크기입니다.

** 사용된
+
데이터가 집계하여 사용하는 물리적 용량입니다.

** 과도하게 헌신하다
+
전체 공간이 과도하게 할당된 경우 차트에는 과도하게 할당된 양이 표시된 플래그가 표시됩니다.

** 경고
+
경고 임계값이 설정된 위치에 점선을 표시합니다. 즉, 집계된 공간이 거의 가득 찼음을 의미합니다.  이 임계값을 초과하면 공간이 거의 가득 찼습니다 이벤트가 생성됩니다.

** 오류
+
오류 임계값이 설정된 위치에 실선이 표시됩니다. 즉, 집계 공간이 가득 찼음을 의미합니다.  이 임계값을 초과하면 공간 가득 참 이벤트가 생성됩니다.

** 스냅샷 복사본 그래프
+
이 그래프는 사용된 스냅샷 용량이나 스냅샷 예약이 0이 아닌 경우에만 표시됩니다.



+
두 그래프 모두 사용된 스냅샷 용량이 스냅샷 예약 용량을 초과하는 경우 스냅샷 용량이 스냅샷 예약 용량을 초과하는 용량을 표시합니다.

* *클라우드 티어*
+
FabricPool 지원 집계에 대한 클라우드 계층의 데이터가 사용하는 공간을 표시합니다.  FabricPool 라이센스가 있을 수도 있고 없을 수도 있습니다.

+
클라우드 계층이 다른 클라우드 공급자("미러 계층")에 미러링되면 두 클라우드 계층이 여기에 표시됩니다.

* *세부*
+
용량에 대한 자세한 정보를 표시합니다.

+
** 총 용량
+
전체 용량을 집계하여 표시합니다.

** 데이터 용량
+
집계에서 사용된 공간의 양(사용된 용량)과 집계에서 사용 가능한 공간의 양(여유 용량)을 표시합니다.

** 스냅샷 예약
+
집계된 스냅샷 용량과 남은 스냅샷 용량을 표시합니다.

** 초과 할당 용량
+
전체 초과 약속을 표시합니다.  집계 초과 커밋을 사용하면 현재 모든 저장 공간이 사용되지 않는 한, 주어진 집계에서 실제로 사용 가능한 것보다 더 많은 저장 공간을 제공할 수 있습니다.  씬 프로비저닝을 사용하는 경우 집계된 볼륨의 총 크기가 집계의 총 용량을 초과할 수 있습니다.

+
[NOTE]
====
집계에 과도한 용량을 할당한 경우 사용 가능한 공간을 주의 깊게 모니터링하고 필요에 따라 저장 공간을 추가해야 공간 부족으로 인한 쓰기 오류가 발생하지 않습니다.

====
** 클라우드 티어
+
FabricPool 지원 집계에 대한 클라우드 계층의 데이터가 사용하는 공간을 표시합니다.  FabricPool 라이센스가 있을 수도 있고 없을 수도 있습니다.  클라우드 계층이 다른 클라우드 공급자(미러 계층)에 미러링되면 두 클라우드 계층이 여기에 표시됩니다.

** 총 캐시 공간
+
Flash Pool 집계에 추가된 SSD(솔리드 스테이트 드라이브) 또는 할당 단위의 총 공간을 표시합니다.  집계를 위해 Flash Pool을 활성화했지만 SSD를 추가하지 않은 경우 캐시 공간이 0KB로 표시됩니다.

+
[NOTE]
====
집계에 대해 Flash Pool이 비활성화된 경우 이 필드는 숨겨집니다.

====
** 집계 임계값
+
다음의 집계 용량 임계값을 표시합니다.

+
*** 거의 가득 찬 임계값
+
집계가 거의 채워지는 비율을 지정합니다.

*** 전체 임계값
+
집계가 가득 찬 비율을 지정합니다.

*** 거의 초과 할당 임계값
+
집계가 과도하게 할당되는 비율을 지정합니다.

*** 초과 할당 임계값
+
집계가 과도하게 할당되는 비율을 지정합니다.



** 기타 세부 정보: 일일 성장률
+
마지막 두 샘플 간의 변화율이 24시간 동안 지속될 경우 집계에 사용된 디스크 공간을 표시합니다.

+
예를 들어, 집계가 오후 2시에 10GB의 디스크 공간을 사용하고 오후 6시에 12GB를 사용하는 경우 이 집계의 일일 증가율(GB)은 2GB입니다.

** 볼륨 이동
+
현재 진행 중인 볼륨 이동 작업의 수를 표시합니다.

+
*** 볼륨 아웃
+
집계에서 이동되는 볼륨의 수와 용량을 표시합니다.

+
링크를 클릭하면 볼륨 이름, 볼륨이 이동된 집계, 볼륨 이동 작업의 상태, 예상 종료 시간 등의 자세한 내용을 볼 수 있습니다.

*** 볼륨
+
집계로 이동 중인 볼륨의 수와 남은 용량을 표시합니다.

+
링크를 클릭하면 볼륨 이름, 볼륨이 이동된 집계, 볼륨 이동 작업 상태, 예상 종료 시간 등의 자세한 내용을 볼 수 있습니다.

*** 볼륨 이동 후 예상 사용 용량
+
볼륨 이동 작업이 완료된 후 사용된 공간의 추정량(백분율, KB, MB, GB 등)을 집계하여 표시합니다.





* *용량 개요 - 볼륨*
+
집계에 포함된 볼륨의 용량에 대한 정보를 제공하는 그래프를 표시합니다.  볼륨에서 사용된 공간의 양(사용된 용량)과 볼륨에서 사용 가능한 공간의 양(여유 용량)이 표시됩니다.  씬 프로비저닝된 볼륨에 대해 씬 프로비저닝된 볼륨 공간 위험 이벤트가 생성되면 볼륨에서 사용된 공간의 양(사용된 용량)과 볼륨에서 사용 가능하지만 집계 용량 문제로 인해 사용할 수 없는 공간의 양(사용 불가능 용량)이 표시됩니다.

+
드롭다운 목록에서 보고 싶은 그래프를 선택할 수 있습니다.  그래프에 표시된 데이터를 정렬하여 사용된 크기, 프로비저닝된 크기, 사용 가능한 용량, 가장 빠른 일일 성장률, 가장 느린 성장률과 같은 세부 정보를 표시할 수 있습니다.  집계된 볼륨을 포함하는 스토리지 가상 머신(SVM)을 기준으로 데이터를 필터링할 수 있습니다.  씬 프로비저닝된 볼륨에 대한 세부 정보도 볼 수 있습니다.  관심 있는 영역 위에 커서를 놓으면 그래프에서 특정 지점의 세부 정보를 볼 수 있습니다.  기본적으로 그래프는 집계된 상위 30개 필터링된 볼륨을 표시합니다.





== 디스크 정보 탭

RAID 유형 및 크기, 집계에 사용된 디스크 유형을 포함하여 선택한 집계에 있는 디스크에 대한 자세한 정보를 표시합니다.  이 탭에는 RAID 그룹과 사용된 디스크 유형(예: SAS, ATA, FCAL, SSD 또는 VMDISK)도 그래픽으로 표시됩니다.  커서를 패리티 디스크와 데이터 디스크 위에 놓으면 디스크 베이, 셸프, 회전 속도 등의 자세한 정보를 볼 수 있습니다.

* *데이터*
+
전용 데이터 디스크, 공유 데이터 디스크 또는 둘 다에 대한 세부 정보를 그래픽으로 표시합니다.  데이터 디스크에 공유 디스크가 포함되어 있는 경우 공유 디스크의 그래픽 세부 정보가 표시됩니다.  데이터 디스크에 전용 디스크와 공유 디스크가 포함된 경우 전용 데이터 디스크와 공유 데이터 디스크 모두의 그래픽 세부 정보가 표시됩니다.

+
** *RAID 세부 정보*
+
RAID 세부 정보는 전용 디스크에 대해서만 표시됩니다.

+
*** 유형
+
RAID 유형(RAID0, RAID4, RAID-DP 또는 RAID-TEC)을 표시합니다.

*** 그룹 크기
+
RAID 그룹에서 허용되는 최대 디스크 수를 표시합니다.

*** 여러 떼
+
집계된 RAID 그룹의 수를 표시합니다.



** *사용된 디스크*
+
*** 효과적인 유형
+
데이터 디스크 유형(예: ATA, SATA, FCAL, SSD 또는 VMDISK)을 전체적으로 표시합니다.

*** 데이터 디스크
+
집계에 할당된 데이터 디스크의 수와 용량을 표시합니다.  집계에 공유 디스크만 포함된 경우 데이터 디스크 세부 정보가 표시되지 않습니다.

*** 패리티 디스크
+
집계에 할당된 패리티 디스크의 수와 용량을 표시합니다.  집계에 공유 디스크만 포함된 경우 패리티 디스크 세부 정보가 표시되지 않습니다.

*** 공유 디스크
+
집계에 할당된 공유 데이터 디스크의 수와 용량을 표시합니다.  공유 디스크 세부 정보는 집계에 공유 디스크가 포함된 경우에만 표시됩니다.



** *예비 디스크*
+
선택한 집계에서 노드에 사용 가능한 예비 데이터 디스크의 유효 디스크 유형, 개수 및 용량을 표시합니다.

+
[NOTE]
====
집계가 파트너 노드로 장애 조치되면 Unified Manager는 집계와 호환되는 모든 예비 디스크를 표시하지 않습니다.

====


* *SSD 캐시*
+
전용 캐시 SSD 디스크와 공유 캐시 SSD 디스크에 대한 세부 정보를 제공합니다.

+
전용 캐시 SSD 디스크에 대한 세부 정보는 다음과 같습니다.

+
** *RAID 세부 정보*
+
*** 유형
+
RAID 유형(RAID0, RAID4, RAID-DP 또는 RAID-TEC)을 표시합니다.

*** 그룹 크기
+
RAID 그룹에서 허용되는 최대 디스크 수를 표시합니다.

*** 여러 떼
+
집계된 RAID 그룹의 수를 표시합니다.



** *사용된 디스크*
+
*** 효과적인 유형
+
집계된 캐시에 사용된 디스크가 SSD 유형임을 나타냅니다.

*** 데이터 디스크
+
캐시에 대한 집계에 할당된 데이터 디스크의 수와 용량을 표시합니다.

*** 패리티 디스크
+
캐시에 대한 집계에 할당된 패리티 디스크의 수와 용량을 표시합니다.



** *예비 디스크*
+
캐시에 대해 선택된 집계에서 노드에 사용 가능한 예비 디스크의 효과적인 유형, 개수 및 용량을 표시합니다.

+
[NOTE]
====
집계가 파트너 노드로 장애 조치되면 Unified Manager는 집계와 호환되는 모든 예비 디스크를 표시하지 않습니다.

====


+
공유 캐시에 대한 다음 세부 정보를 제공합니다.

+
** *저장 풀*
+
스토리지 풀의 이름을 표시합니다.  스토리지 풀 이름 위에 포인터를 놓으면 다음 세부 정보를 볼 수 있습니다.

+
*** 상태
+
스토리지 풀의 상태를 표시합니다. 상태는 정상 또는 비정상입니다.

*** 총 할당량
+
총 할당 단위와 스토리지 풀의 크기를 표시합니다.

*** 할당 단위 크기
+
집계에 할당할 수 있는 스토리지 풀의 최소 공간 크기를 표시합니다.

*** 디스크
+
스토리지 풀을 생성하는 데 사용된 디스크 수를 표시합니다.  스토리지 풀 열의 디스크 수와 해당 스토리지 풀의 디스크 정보 탭에 표시된 디스크 수가 일치하지 않으면 하나 이상의 디스크가 손상되어 스토리지 풀이 정상적이지 않음을 나타냅니다.

*** 사용된 할당
+
집계에서 사용되는 할당 단위의 수와 크기를 표시합니다.  집계 이름을 클릭하면 집계 세부 정보를 볼 수 있습니다.

*** 사용 가능한 할당량
+
노드에 사용 가능한 할당 단위의 수와 크기를 표시합니다.  노드 이름을 클릭하면 집계 세부 정보를 볼 수 있습니다.



** *할당된 캐시*
+
집계에서 사용되는 할당 단위의 크기를 표시합니다.

** *할당 단위*
+
집계에 사용된 할당 단위 수를 표시합니다.

** *디스크*
+
스토리지 풀에 포함된 디스크 수를 표시합니다.

** *세부*
+
*** 스토리지 풀
+
스토리지 풀의 수를 표시합니다.

*** 전체 크기
+
스토리지 풀의 총 크기를 표시합니다.





* *클라우드 티어*
+
FabricPool 활성화된 집계를 구성한 경우 클라우드 계층의 이름을 표시하고 사용된 총 공간을 보여줍니다.  클라우드 계층이 다른 클라우드 공급자(미러 계층)로 미러링되면 두 클라우드 계층에 대한 세부 정보가 여기에 표시됩니다.





== 구성 탭

구성 탭에는 클러스터 노드, 블록 유형, RAID 유형, RAID 크기, RAID 그룹 수 등 선택한 집계에 대한 세부 정보가 표시됩니다.

* *개요*
+
** 마디
+
선택한 집계를 포함하는 노드의 이름을 표시합니다.

** 블록 유형
+
집계의 블록 형식을 32비트 또는 64비트로 표시합니다.

** RAID 유형
+
RAID 유형(RAID0, RAID4, RAID-DP, RAID-TEC 또는 혼합 RAID)을 표시합니다.

** RAID 사이즈
+
RAID 그룹의 크기를 표시합니다.

** RAID 그룹
+
집계된 RAID 그룹의 수를 표시합니다.

** SnapLock 타입
+
집계의 SnapLock 유형을 표시합니다.



* *클라우드 티어*
+
이것이 FabricPool 지원 집계인 경우 클라우드 계층에 대한 세부 정보가 표시됩니다.  일부 필드는 저장소 제공업체에 따라 다릅니다.  클라우드 계층이 다른 클라우드 공급자("미러 계층")에 미러링되면 두 클라우드 계층이 여기에 표시됩니다.

+
** 공급자
+
스토리지 공급자의 이름(예: StorageGRID, Amazon S3, IBM Cloud Object Storage, Microsoft Azure Cloud, Google Cloud Storage 또는 Alibaba Cloud Object Storage)을 표시합니다.

** 이름
+
ONTAP 에서 클라우드 계층을 생성할 때 해당 클라우드 계층의 이름을 표시합니다.

** 섬기는 사람
+
클라우드 계층의 FQDN을 표시합니다.

** 포트
+
클라우드 공급자와 통신하는 데 사용되는 포트입니다.

** 액세스 키 또는 계정
+
클라우드 계층에 대한 액세스 키 또는 계정을 표시합니다.

** 컨테이너 이름
+
클라우드 계층의 버킷 또는 컨테이너 이름을 표시합니다.

** SSL
+
클라우드 계층에 SSL 암호화가 활성화되어 있는지 여부를 표시합니다.







== 역사 지역

기록 영역에는 선택한 집계의 용량에 대한 정보를 제공하는 그래프가 표시됩니다.  또한, *내보내기* 버튼을 클릭하면 현재 보고 있는 차트에 대한 CSV 형식의 보고서를 만들 수 있습니다.

기록 창 상단의 드롭다운 목록에서 그래프 유형을 선택할 수 있습니다.  1주일, 1개월, 1년 중 하나를 선택하여 특정 기간에 대한 세부 정보를 볼 수도 있습니다.  기록 그래프는 추세를 파악하는 데 도움이 됩니다. 예를 들어, 집계 사용량이 지속적으로 '거의 가득 참' 임계값을 초과하는 경우 적절한 조치를 취할 수 있습니다.

기록 그래프는 다음 정보를 표시합니다.

* *사용된 총 용량(%)*
+
세로(y)축에 사용 내역을 기준으로 집계된 용량의 사용 추세와 사용된 용량을 백분율로 선 그래프로 표시합니다.  기간은 수평(x)축에 표시됩니다.  일주일, 한 달, 또는 일년 중 원하는 기간을 선택할 수 있습니다.  그래프의 특정 지점에 대한 세부 정보를 보려면 커서를 특정 영역 위에 올려놓으세요.  해당 범례를 클릭하면 선 그래프를 숨기거나 표시할 수 있습니다.  예를 들어, 사용된 용량 범례를 클릭하면 사용된 용량 그래프 선이 숨겨집니다.

* *사용된 총 용량 대비 총 용량*
+
수직(y)축에 바이트, 킬로바이트, 메가바이트 등의 단위를 선 그래프로 표시하고, 사용 내역을 기반으로 집계 용량이 어떻게 사용되는지 추세를 표시하며, 사용된 용량과 전체 용량을 표시합니다.  기간은 수평(x)축에 표시됩니다.  일주일, 한 달, 또는 일년 중 원하는 기간을 선택할 수 있습니다.  그래프의 특정 지점에 대한 세부 정보를 보려면 커서를 특정 영역 위에 올려놓으세요.  해당 범례를 클릭하면 선 그래프를 숨기거나 표시할 수 있습니다.  예를 들어, 사용된 추세 용량 범례를 클릭하면 사용된 추세 용량 그래프 선이 숨겨집니다.

* *사용된 총 용량(%) 대비 약정된 용량(%)*
+
수직(y)축에 사용 내역과 커밋된 공간을 기준으로 집계 용량이 어떻게 사용되는지 추세를 선 그래프로 백분율로 표시합니다.  기간은 수평(x)축에 표시됩니다.  일주일, 한 달, 또는 일년 중 원하는 기간을 선택할 수 있습니다.  그래프의 특정 지점에 대한 세부 정보를 보려면 커서를 특정 영역 위에 올려놓으세요.  해당 범례를 클릭하면 선 그래프를 숨기거나 표시할 수 있습니다.  예를 들어, 할당된 공간 범례를 클릭하면 할당된 공간 그래프 선이 숨겨집니다.





== 이벤트 목록

이벤트 목록에는 새 이벤트와 확인된 이벤트에 대한 세부 정보가 표시됩니다.

* *심각성*
+
이벤트의 심각도를 표시합니다.

* *이벤트*
+
이벤트 이름을 표시합니다.

* *트리거 시간*
+
이벤트가 생성된 이후 경과된 시간을 표시합니다.  경과 시간이 일주일을 초과하면 이벤트가 생성된 타임스탬프가 표시됩니다.





== 관련 장치 창

관련 장치 창을 사용하면 집계와 관련된 클러스터 노드, 볼륨 및 디스크를 볼 수 있습니다.

* *마디*
+
집계를 포함하는 노드의 용량과 상태를 표시합니다.  용량은 사용 가능한 용량을 가용 용량으로 나눈 총 사용 가능 용량을 나타냅니다.

* *노드의 집계*
+
선택한 집계가 포함된 클러스터 노드에 있는 모든 집계의 수와 용량을 표시합니다.  또한 가장 높은 심각도 수준을 기준으로 집계의 상태도 표시됩니다.  예를 들어, 클러스터 노드에 10개의 집계가 포함되어 있고 그 중 5개가 경고 상태를 표시하고 나머지 5개가 위험 상태를 표시하는 경우 표시되는 상태는 위험입니다.

* *권수*
+
FlexVol 볼륨과 FlexGroup 볼륨의 수와 용량을 전체적으로 표시합니다. 이 수치에는 FlexGroup 구성 요소는 포함되지 않습니다.  볼륨의 상태도 가장 높은 심각도 수준을 기준으로 표시됩니다.

* *자원 풀*
+
집계와 관련된 리소스 풀을 표시합니다.

* *디스크*
+
선택한 집계에 있는 디스크의 수를 표시합니다.





== 관련 알림 창

관련 알림 창을 사용하면 선택한 집계에 대해 생성된 알림 목록을 볼 수 있습니다.  알림 추가 링크를 클릭하여 알림을 추가하거나 알림 이름을 클릭하여 기존 알림을 편집할 수도 있습니다.

*관련 정보*

link:../health-checker/task_view_storage_pool_details.html["스토리지 풀 세부 정보 보기"]
