---
permalink: health-checker/task_determine_if_volume_is_offline_because_of_broken_disks.html 
sidebar: sidebar 
keywords: determine, volume, offline, broken disks, aggregate 
summary: RAID 디스크 문제로 인해 호스트 집계가 오프라인 상태가 되어 볼륨이 오프라인 상태일 가능성을 확인하거나 제거하려면 Unified Manager 웹 UI를 사용할 수 있습니다. 
---
= 집계된 디스크가 손상되어 볼륨이 오프라인 상태인지 확인합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
RAID 디스크 문제로 인해 호스트 집계가 오프라인 상태가 되어 볼륨이 오프라인 상태일 가능성을 확인하거나 제거하려면 Unified Manager 웹 UI를 사용할 수 있습니다.

.시작하기 전에
운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

볼륨 오프라인 상태가 호스팅 집계를 오프라인으로 만드는 RAID 디스크 문제로 인해 발생하는지 확인하려면 다음 작업을 수행하세요.

.단계
. *볼륨/상태* 세부 정보 페이지의 *관련 장치* 창에서 집계 아래에 표시된 하이퍼텍스트 링크를 찾아 클릭합니다.
+
집계/상태 세부 정보 페이지에는 호스팅 집계의 온라인 또는 오프라인 상태가 표시됩니다.  집계 상태가 온라인인 경우 RAID 디스크 문제는 볼륨이 오프라인되는 원인이 아닙니다.

. 집계 상태가 오프라인인 경우 *디스크 정보*를 클릭하고 *디스크 정보* 탭의 *이벤트* 목록에서 손상된 디스크 이벤트를 찾습니다.
. 손상된 디스크를 더 자세히 식별하려면 *관련 장치* 창의 노드 아래에 표시된 하이퍼텍스트 링크를 클릭하세요.
+
클러스터/상태 세부 정보 페이지가 표시됩니다.

. *디스크*를 클릭한 다음, *필터* 창에서 *손상됨*을 선택하면 손상된 상태의 모든 디스크가 나열됩니다.
+
손상된 상태의 디스크로 인해 호스트 집계가 오프라인 상태가 된 경우, 영향을 받는 집계 열에 집계 이름이 표시됩니다.



볼륨 오프라인 상태가 손상된 RAID 디스크와 그에 따른 오프라인 호스트 집계로 인해 발생한 것인지 확인한 후, 해당 관리자나 운영자에게 연락하여 손상된 디스크를 수동으로 교체하고 집계를 다시 온라인으로 전환하세요.
