---
permalink: health-checker/task_define_schedule_for_snapshot_backups.html 
sidebar: sidebar 
keywords: define, backup, schedule, linux, windows, snapshot copy, copies 
summary: Unified Manager UI를 사용하여 Unified Manager 스냅샷 복사본이 생성되는 일정을 구성할 수 있습니다. 
---
= Linux 및 Windows에 대한 백업 일정 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager UI를 사용하여 Unified Manager 스냅샷 복사본이 생성되는 일정을 구성할 수 있습니다.

.시작하기 전에
* 운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 스냅샷이 생성될 대상을 식별하려면 유지 관리 콘솔에서 스냅샷 복사본을 생성하기 위한 설정을 구성해야 합니다.


스냅샷 복사본은 몇 분 안에 생성되고 Unified Manager 데이터베이스는 몇 초 동안만 잠깁니다.

[NOTE]
====
새로운 클러스터를 추가한 후 처음 15일 동안 수행한 백업은 과거 성능 데이터를 얻기에 충분히 정확하지 않을 수 있습니다.

====
.단계
. 왼쪽 탐색 창에서 *일반* > *데이터베이스 백업*을 클릭합니다.
. *데이터베이스 백업* 페이지에서 *백업 설정*을 클릭합니다.
. *보존 횟수* 필드에 보존하려는 스냅샷 사본의 최대 수를 입력합니다.
+
보존 횟수의 기본값은 10입니다.  스냅샷 복사본의 최대 수는 클러스터의 ONTAP 소프트웨어 버전에 따라 결정됩니다.  ONTAP 버전에 관계없이 최대값을 구현하려면 이 필드를 비워둘 수 있습니다.

. *매일 예약* 또는 *매주 예약* 버튼을 선택한 다음, 일정 세부 정보를 지정합니다.
. *적용*을 클릭하세요.


스냅샷 사본은 일정에 따라 생성됩니다.  사용 가능한 백업 파일은 데이터베이스 백업 페이지에서 볼 수 있습니다.

이 볼륨과 스냅샷의 중요성 때문에 이 볼륨에 대한 알림을 하나 또는 두 개 만들어 다음과 같은 경우 알림을 받도록 할 수 있습니다.

* 볼륨 공간이 90% 채워졌습니다.  *볼륨 공간 가득 참* 이벤트를 사용하여 알림을 설정하세요.
+
ONTAP System Manager나 ONTAP CLI를 사용하여 볼륨에 용량을 추가하면 Unified Manager 데이터베이스의 공간이 부족해지는 것을 방지할 수 있습니다.

* 스냅샷의 개수가 최대 개수에 가까워졌습니다.  *스냅샷 사본이 너무 많음* 이벤트를 사용하여 알림을 설정하세요.
+
ONTAP 시스템 관리자나 ONTAP CLI를 사용하여 이전 스냅샷을 삭제하면 항상 새로운 스냅샷 복사본을 위한 공간을 확보할 수 있습니다.



알림 설정 페이지에서 알림을 구성합니다.
