---
permalink: health-checker/task_configure_netapp_snapshot_backup_from_maintenance_console.html 
sidebar: sidebar 
keywords: configure, backup, snapshot copy, copies maintenance console 
summary: 스냅샷 복사를 사용하여 Active IQ Unified Manager 백업을 수행하려면 유지 관리 콘솔에서 몇 가지 구성 단계를 수행해야 합니다. 
---
= 유지 관리 콘솔에서 스냅샷 복사로 백업 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅샷 복사를 사용하여 Active IQ Unified Manager 백업을 수행하려면 유지 관리 콘솔에서 몇 가지 구성 단계를 수행해야 합니다.

.시작하기 전에
시스템에 대한 세부 정보는 다음과 같습니다.

* 클러스터 IP 주소
* 스토리지 VM 이름
* 볼륨 이름
* LUN 이름
* 산길
* 스토리지 시스템 자격 증명


.단계
. Unified Manager의 유지 관리 콘솔에 액세스합니다.
. *백업 복원*을 선택하려면 4를 입력하세요.
. * NetApp 스냅샷을 사용하여 백업 및 복원*을 선택하려면 2를 입력합니다.
+
[NOTE]
====
백업 구성을 변경하려면 * NetApp 스냅샷 백업 구성 업데이트*를 선택하려면 3을 입력합니다.  비밀번호만 업데이트할 수 있습니다.

====
. 메뉴에서 1을 입력하여 * NetApp 스냅샷 백업 구성*을 선택합니다.
. 필요한 정보를 제공하려면 1을 입력하세요.
. 유지 관리 콘솔에 대한 사용자 이름과 비밀번호를 제공한 다음 LUN이 호스트에 마운트되었는지 확인합니다.
+
그런 다음 프로세스에서는 사용자가 제공한 데이터 디렉터리, LUN 경로, 스토리지 VM, 볼륨, 공간 가용성, 드라이브 등이 올바른지 확인합니다.  백그라운드에서 진행되는 작업은 다음과 같습니다.

+
** 서비스가 중단되었습니다
** 데이터베이스 디렉토리가 마운트된 저장소로 이동되었습니다.
** 데이터베이스 디렉토리가 삭제되고 심볼릭 링크가 설정됩니다.
** 구성이 Active IQ Unified Manager 인터페이스에서 완료되면 백업 유형이 NetApp 스냅샷으로 수정되고 사용자 인터페이스에 데이터베이스 백업(스냅샷 기반)으로 반영됩니다.




백업 작업을 시작하기 전에 스냅샷 구성에 변경 사항이 있는지 확인해야 합니다. 변경 사항이 있으면 스냅샷이 유효하지 않게 될 수 있습니다.  G 드라이브에 백업을 구성하고 스냅샷을 찍었다고 가정해 보겠습니다.  나중에 E 드라이브에 대한 백업을 재구성했고 데이터는 새로운 구성에 따라 E 드라이브에 저장됩니다.  G 드라이브에 있는 동안 찍은 스냅샷을 복원하려고 하면 G 드라이브가 없다는 오류 메시지가 나타나서 실패합니다.
