---
permalink: health-checker/task_restore_snapshot_backup.html 
sidebar: sidebar 
keywords: restore, unified manager, snapshot copy, copies, 
summary: 데이터 손실이나 데이터 손상이 발생하는 경우 최소한의 데이터 손실로 Unified Manager를 이전의 안정적인 상태로 복원할 수 있습니다.  Unified Manager 유지 관리 콘솔을 사용하여 Unified Manager 스냅샷 데이터베이스를 로컬 또는 원격 운영 체제로 복원할 수 있습니다. 
---
= 스냅샷 복사본을 사용하여 Unified Manager 복원
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 손실이나 데이터 손상이 발생하는 경우 최소한의 데이터 손실로 Unified Manager를 이전의 안정적인 상태로 복원할 수 있습니다.  Unified Manager 유지 관리 콘솔을 사용하여 Unified Manager 스냅샷 데이터베이스를 로컬 또는 원격 운영 체제로 복원할 수 있습니다.

.시작하기 전에
* Unified Manager가 설치된 Linux 호스트에 대한 루트 사용자 자격 증명과 Windows 호스트 컴퓨터에 대한 관리자 권한이 있어야 합니다.
* Unified Manager 서버의 유지 관리 콘솔에 로그인하려면 권한이 있는 사용자 ID와 비밀번호가 있어야 합니다.


복원 기능은 플랫폼과 버전에 따라 다릅니다.  Unified Manager 백업은 동일한 버전의 Unified Manager에서만 복원할 수 있습니다.

.단계
. Unified Manager 시스템의 IP 주소 또는 정규화된 도메인 이름에 연결합니다.
+
** 리눅스: 보안 셸
** 윈도우: 파워셸


. 루트 사용자 자격 증명을 사용하여 시스템에 로그인합니다.
. 명령을 입력하세요 `maintenance_console` 그리고 Enter를 누르세요.
. 유지 관리 콘솔의 *메인 메뉴*에서 *백업 복원* 옵션에 4를 입력합니다.
. * NetApp 스냅샷을 사용하여 백업 및 복원*을 선택하려면 2를 입력합니다.
+
Unified Manager를 설치한 후에는 새 서버로 복원을 수행하는 경우 UI를 시작하거나 설치가 완료된 후 클러스터, 사용자 또는 인증 설정을 구성하지 마세요.  * NetApp 스냅샷 백업 구성*을 선택하려면 1을 입력하고 원본 시스템에 있는 대로 스냅샷 복사본에 대한 설정을 구성합니다.

. * NetApp 스냅샷을 사용하여 복원*을 선택하려면 3을 입력합니다.
. Unified Manager를 복원할 스냅샷 복사본을 선택합니다.  *Enter*를 누르세요.
. 복원 프로세스가 완료되면 Unified Manager 사용자 인터페이스에 로그인합니다.


백업을 복원한 후 Workflow Automation 서버가 작동하지 않으면 다음 단계를 수행하세요.

. Workflow Automation 서버에서 Unified Manager 서버의 IP 주소를 최신 컴퓨터를 가리키도록 변경합니다.
. Unified Manager 서버에서 1단계에서 획득에 실패하면 데이터베이스 비밀번호를 재설정합니다.

