---
permalink: health-checker/task_view_fabricpool_capacity_information.html 
sidebar: sidebar 
keywords: view, fabricPool, cloud tier, mirror tier, capacity, information 
summary: 클러스터, 집계 및 볼륨에 대한 FabricPool 용량 정보는 이러한 개체에 대한 용량 및 성능 인벤토리와 세부 정보 페이지에서 볼 수 있습니다.  이 페이지에는 미러 계층이 구성된 경우 FabricPool 미러 정보도 표시됩니다. 
---
= FabricPool 용량 정보 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터, 집계 및 볼륨에 대한 FabricPool 용량 정보는 이러한 개체에 대한 용량 및 성능 인벤토리와 세부 정보 페이지에서 볼 수 있습니다.  이 페이지에는 미러 계층이 구성된 경우 FabricPool 미러 정보도 표시됩니다.

이 페이지에는 로컬 성능 계층과 클라우드 계층에서 사용 가능한 용량, 두 계층에서 사용되는 용량, 어떤 집계가 클라우드 계층에 연결되어 있는지, 어떤 볼륨이 특정 정보를 클라우드 계층으로 이동하여 FabricPool 기능을 구현하고 있는지 등의 정보가 표시됩니다.

클라우드 계층이 다른 클라우드 공급자에 미러링되면(``미러 계층`') 두 클라우드 계층 모두 집계/상태 세부 정보 페이지에 표시됩니다.

.단계
. 다음 중 하나를 수행하세요.
+
[cols="2*"]
|===
| ...에 대한 용량 정보를 보려면 | 이렇게 하세요... 


 a| 
클러스터
 a| 
.. 용량: 모든 클러스터 보기에서 클러스터를 클릭합니다.
.. 클러스터/상태 세부 정보 페이지에서 *구성* 탭을 클릭합니다.
+
디스플레이에는 이 클러스터가 연결된 모든 클라우드 계층의 이름이 표시됩니다.





 a| 
골재
 a| 
.. 용량: 모든 집계 보기에서 유형 필드가 "`SSD(FabricPool)`" 또는 "`HDD(FabricPool)`"를 나타내는 집계를 클릭합니다.
.. 집계/상태 세부 정보 페이지에서 *용량* 탭을 클릭합니다.
+
디스플레이에는 클라우드 계층에서 사용된 총 용량이 표시됩니다.

.. *디스크 정보* 탭을 클릭합니다.
+
디스플레이에는 클라우드 계층의 이름과 사용 용량이 표시됩니다.

.. *구성* 탭을 클릭합니다.
+
디스플레이에는 클라우드 계층의 이름과 클라우드 계층에 대한 기타 자세한 정보가 표시됩니다.





 a| 
볼륨
 a| 
.. 용량: 모든 볼륨 보기에서 "계층화 정책" 필드에 정책 이름이 나타나는 볼륨을 클릭합니다.
.. 볼륨/상태 세부 정보 페이지에서 *구성* 탭을 클릭합니다.
+
디스플레이에는 볼륨에 할당된 FabricPool 계층화 정책의 이름이 표시됩니다.



|===
. *작업 부하 분석* 페이지에서 *용량 추세* 영역의 "클라우드 계층 보기"를 선택하면 지난달에 로컬 성능 계층과 클라우드 계층에서 사용된 용량을 확인할 수 있습니다.


FabricPool 집계에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/disks-aggregates/index.html["디스크 및 집계 개요"] .
