---
permalink: health-checker/task_view_node_list_and_details.html 
sidebar: sidebar 
keywords: view, node list, details 
summary: '클러스터의 노드 목록을 보려면 Health: All Nodes 보기를 사용하세요.  클러스터/상태 세부 정보 페이지를 사용하면 모니터링되는 클러스터에 속한 노드에 대한 자세한 정보를 볼 수 있습니다.' 
---
= 노드 목록 및 세부 정보 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터의 노드 목록을 보려면 Health: All Nodes 보기를 사용하세요.  클러스터/상태 세부 정보 페이지를 사용하면 모니터링되는 클러스터에 속한 노드에 대한 자세한 정보를 볼 수 있습니다.

.시작하기 전에
운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

노드 상태, 노드가 포함된 클러스터, 집계 용량 세부 정보(사용됨 및 총 용량), 원시 용량 세부 정보(사용 가능, 예비 및 총 용량)와 같은 세부 정보를 볼 수 있습니다.  HA 쌍, 디스크 쉘프, 포트에 대한 정보도 얻을 수 있습니다.

.단계
. 왼쪽 탐색 창에서 *저장소* > *노드*를 클릭합니다.
. *상태: 모든 노드* 보기에서 세부 정보를 보려는 노드를 클릭합니다.
+
선택한 노드에 대한 자세한 정보는 클러스터/상태 세부 정보 페이지에 표시됩니다.  왼쪽 창에는 HA 쌍 목록이 표시됩니다.  기본적으로 HA 세부 정보가 열려 있으며, 선택한 HA 쌍과 관련된 HA 상태 세부 정보와 이벤트가 표시됩니다.

. 노드에 대한 다른 세부 정보를 보려면 적절한 작업을 수행하세요.
+
[cols="2*"]
|===
| 보려면... | 딸깍 하는 소리... 


 a| 
디스크 선반에 대한 세부 정보
 a| 
*디스크 선반*.



 a| 
항만 관련 정보
 a| 
*항구*.

|===


자세한 내용은 다음을 참조하세요.

* link:../performance-checker/performance-view-all.html#performance-all-nodes-view["성능: 모든 노드 보기"]
* link:../performance-checker/concept_view_node_and_aggregate_available_iops_values.html["노드 및 집계 가능한 IOPS 값 보기"]
* link:../performance-checker/concept_view_node_and_aggregate_performance_capacity_used_values.html["노드 및 집계 성능 용량 사용 값 보기"]

