---
permalink: health-checker/task_edit_individual_volume_health_threshold_settings.html 
sidebar: sidebar 
keywords: edit, individual, volume, health, threshold, settings 
summary: 하나 이상의 볼륨에 대한 볼륨 용량, 성장, 할당량 및 공간 예약에 대한 상태 임계값 설정을 편집할 수 있습니다.  임계값을 넘으면 경고가 생성되고 알림을 받게 됩니다.  이러한 알림은 발생한 이벤트에 따라 예방 조치를 취하는 데 도움이 됩니다. 
---
= 개별 볼륨 상태 임계값 설정 편집
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
하나 이상의 볼륨에 대한 볼륨 용량, 성장, 할당량 및 공간 예약에 대한 상태 임계값 설정을 편집할 수 있습니다.  임계값을 넘으면 경고가 생성되고 알림을 받게 됩니다.  이러한 알림은 발생한 이벤트에 따라 예방 조치를 취하는 데 도움이 됩니다.

.시작하기 전에
애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

임계값의 변경 사항에 따라 다음 모니터링 주기에서 이벤트가 생성되거나 폐기됩니다.

볼륨에서 자동 증가가 활성화된 경우 해당 용량 임계값은 원래 볼륨 크기가 아닌 자동 증가에 의해 설정된 최대 볼륨 크기를 기준으로 위반된 것으로 간주됩니다.

[NOTE]
====
1000개의 스냅샷 복사본의 기본값은 ONTAP 버전이 9.4 이상인 경우에만 FlexVol 볼륨에 적용되고, ONTAP 버전이 9.8 이상인 경우에만 FlexGroup 볼륨에 적용됩니다.  이전 버전의 ONTAP 소프트웨어가 설치된 클러스터의 경우 볼륨당 최대 스냅샷 복사본 수는 250개입니다.  이전 버전의 경우 Unified Manager는 1000(1000~250 사이의 모든 숫자)을 250으로 해석합니다. 즉, 스냅샷 복사본 수가 250에 도달하면 계속해서 이벤트를 받게 됩니다.  이전 버전에서 이 임계값을 250 미만으로 설정하려면 여기, 상태: 모든 볼륨 보기 또는 볼륨/상태 세부 정보 페이지에서 임계값을 250 이하로 설정해야 합니다.

====
.단계
. 왼쪽 탐색 창에서 *저장소* > *볼륨*을 클릭합니다.
. *상태: 모든 볼륨* 보기에서 하나 이상의 볼륨을 선택한 다음 *임계값 편집*을 클릭합니다.
. *볼륨 임계값 편집* 대화 상자에서 용량, 스냅샷 복사본, Qtree 할당량, 증가 또는 inode 중 하나의 임계값 설정을 편집하려면 적절한 확인란을 선택한 다음 설정을 수정합니다.
. *저장*을 클릭하세요.


*관련 정보*

link:../config/task_add_users.html["사용자 추가"]
