---
permalink: health-checker/task_resolve_volume_offline_issues.html 
sidebar: sidebar 
keywords: resolve, volume, offline issues 
summary: 이 워크플로는 Unified Manager가 이벤트 관리 인벤토리 페이지에 표시할 수 있는 볼륨 오프라인 이벤트를 평가하고 해결하는 방법의 예를 제공합니다.  이 시나리오에서는 Unified Manager를 사용하여 하나 이상의 볼륨 오프라인 이벤트에 대한 문제를 해결하는 관리자입니다. 
---
= 볼륨 오프라인 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 워크플로는 Unified Manager가 이벤트 관리 인벤토리 페이지에 표시할 수 있는 볼륨 오프라인 이벤트를 평가하고 해결하는 방법의 예를 제공합니다.  이 시나리오에서는 Unified Manager를 사용하여 하나 이상의 볼륨 오프라인 이벤트에 대한 문제를 해결하는 관리자입니다.

.시작하기 전에
운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

볼륨이 오프라인으로 보고되는 데에는 여러 가지 이유가 있을 수 있습니다.

* SVM 관리자가 의도적으로 볼륨을 오프라인으로 전환했습니다.
* 볼륨의 호스팅 클러스터 노드가 다운되었고 HA 쌍 파트너에 대한 스토리지 장애 조치도 실패했습니다.
* 해당 SVM의 루트 볼륨을 호스팅하는 노드가 다운되어 볼륨을 호스팅하는 스토리지 가상 머신(SVM)이 중지되었습니다.
* 두 개의 RAID 디스크가 동시에 고장나서 볼륨의 호스팅 집계가 중단되었습니다.


이벤트 관리 인벤토리 페이지와 클러스터/상태, 스토리지 VM/상태, 볼륨/상태 세부 정보 페이지를 사용하여 이러한 가능성 중 하나 이상을 확인하거나 제거할 수 있습니다.

.단계
. 왼쪽 탐색 창에서 *이벤트 관리*를 클릭합니다.
. *이벤트 관리* 인벤토리 페이지에서 *활성 가용성 이벤트*를 선택합니다.
. 볼륨 오프라인 이벤트에 표시된 하이퍼텍스트 링크를 클릭하세요.
+
가용성 사건에 대한 이벤트 세부 정보 페이지가 표시됩니다.

. 해당 페이지에서 SVM 관리자가 해당 볼륨을 오프라인으로 전환했다는 표시가 있는지 확인하세요.
. *이벤트* 세부 정보 페이지에서 다음 작업 중 하나 이상에 대한 정보를 검토할 수 있습니다.
+
** 진단에 도움이 될 만한 정보를 얻으려면 원인 필드에 표시된 정보를 검토하세요.
+
이 예에서 원인 필드의 정보는 볼륨이 오프라인 상태라는 사실만 알려줍니다.

** SVM 관리자가 의도적으로 해당 볼륨을 오프라인으로 전환한 흔적이 있는지 메모 및 업데이트 영역을 확인하세요.
** 이벤트 소스(이 경우 오프라인으로 보고된 볼륨)를 클릭하면 해당 볼륨에 대한 자세한 정보를 얻을 수 있습니다.
** 이벤트를 관리자에게 할당합니다.
** 해당 사건을 확인하거나, 적절한 경우 해결된 것으로 표시합니다.



