---
permalink: health-checker/task_view_aggregate_list_and_details.html 
sidebar: sidebar 
keywords: view, aggregate list, details 
summary: '상태: 모든 집계 보기에서 집계 인벤토리를 모니터링할 수 있습니다.  용량: 모든 집계 보기를 사용하면 모든 클러스터의 집계 용량 및 활용도에 대한 정보를 볼 수 있습니다.' 
---
= 집계 목록 및 세부 정보 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
상태: 모든 집계 보기에서 집계 인벤토리를 모니터링할 수 있습니다.  용량: 모든 집계 보기를 사용하면 모든 클러스터의 집계 용량 및 활용도에 대한 정보를 볼 수 있습니다.

.시작하기 전에
운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

집계/상태 세부 정보 페이지에서 집계 용량 및 구성, 디스크 정보와 같은 세부 정보를 볼 수 있습니다.  필요한 경우 임계값 설정을 구성하기 전에 이러한 세부 정보를 사용할 수 있습니다.

.단계
. 왼쪽 탐색 창에서 *저장소* > *집계*를 클릭합니다.
. 다음 방법 중 하나를 선택하여 집계 세부 정보를 확인하세요.
+
** 모든 클러스터의 모든 집계 상태에 대한 정보를 보려면 보기 메뉴에서 상태: 모든 집계 보기를 선택합니다.
** 모든 클러스터의 모든 집계에 대한 용량 및 활용도에 대한 정보를 보려면 보기 메뉴에서 용량: 모든 집계 보기를 선택합니다.
** 전체 세부 정보를 보려면 집계 이름을 클릭하세요.
+
최소 세부 정보 대화 상자에서 *세부 정보 보기*를 클릭하면 전체 세부 정보를 볼 수도 있습니다.



. 최소 세부 정보 대화 상자에서 *관련 항목 보기*를 클릭하여 집계와 관련된 객체를 봅니다.


*관련 정보*

* link:../health-checker/reference_health_aggregate_details_page.html["집계/상태 세부 정보 페이지"]
* link:../performance-checker/performance-view-all.html#performance-all-aggregates-view["성능: 모든 집계 보기"]
* link:../reporting/concept_customize_aggregate_capacity_reports.html["집계 용량 보고서 사용자 정의"]

