---
permalink: health-checker/task_perform_diagnotstic_actions_for_volume_offline_conditions.html 
sidebar: sidebar 
keywords: perform, diagnostic actions, volume, offline, conditions 
summary: 오프라인으로 보고된 볼륨의 볼륨/상태 세부 정보 페이지로 이동한 후 볼륨 오프라인 상태를 진단하는 데 도움이 되는 추가 정보를 검색할 수 있습니다. 
---
= 볼륨 오프라인 조건에 대한 진단 작업 수행
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
오프라인으로 보고된 볼륨의 볼륨/상태 세부 정보 페이지로 이동한 후 볼륨 오프라인 상태를 진단하는 데 도움이 되는 추가 정보를 검색할 수 있습니다.

.시작하기 전에
운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

오프라인으로 보고된 볼륨이 의도적으로 오프라인으로 전환된 것이 아니라면, 해당 볼륨은 여러 가지 이유로 오프라인 상태일 수 있습니다.

오프라인 볼륨의 볼륨/상태 세부 정보 페이지에서 시작하여 다른 페이지와 창으로 이동하여 가능한 원인을 확인하거나 제거할 수 있습니다.

* 볼륨이 오프라인 상태인지 확인하려면 *볼륨/상태* 세부 정보 페이지 링크를 클릭하세요. 볼륨의 호스트 노드가 다운되었고 HA 쌍 파트너에 대한 스토리지 장애 조치도 실패했기 때문입니다.
+
보다link:task_determine_if_volume_offline_condition_is_by_down_cluster_node.html["볼륨 오프라인 상태가 다운 노드로 인해 발생하는지 확인"] .

* *볼륨/상태* 세부 정보 페이지 링크를 클릭하여 볼륨이 오프라인 상태이고 해당 SVM의 루트 볼륨을 호스팅하는 노드가 다운되어 호스트 스토리지 가상 머신(SVM)이 중지되었는지 확인합니다.
+
보다link:task_determine_if_volume_is_offline_and_its_svm_is_stopped.html["노드가 다운되어 볼륨이 오프라인 상태이고 SVM이 중지되었는지 확인"] .

* 호스트 집계에서 디스크가 손상되어 볼륨이 오프라인 상태인지 확인하려면 *볼륨/상태* 세부 정보 페이지 링크를 클릭하세요.
+
보다link:task_determine_if_volume_is_offline_because_of_broken_disks.html["집계된 디스크가 손상되어 볼륨이 오프라인 상태인지 확인"] .



*관련 정보*

link:../config/reference_unified_manager_roles_and_capabilities.html["Unified Manager 사용자 역할 및 기능"]
