---
permalink: health-checker/task_perform_suggested_remedial_actions_for_full_volume.html 
sidebar: sidebar 
keywords: perform, suggested, remedial actions, volume 
summary: '"볼륨 공간 가득 참" 오류 이벤트를 수신한 후 이벤트 세부 정보 페이지에서 제안된 시정 조치를 검토하고 제안된 조치 중 하나를 수행하기로 결정합니다.' 
---
= 전체 볼륨에 대해 제안된 시정 조치를 수행합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"볼륨 공간 가득 참" 오류 이벤트가 발생한 후 이벤트 세부 정보 페이지에서 제안된 시정 조치를 검토하고 제안된 조치 중 하나를 수행하기로 결정합니다.

.시작하기 전에
애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

모든 역할을 가진 사용자는 Unified Manager를 사용하여 이 워크플로의 모든 작업을 수행할 수 있습니다.

이 예에서는 Unified ManagerEvent Management 인벤토리 페이지에서 볼륨 공간 가득 참 오류 이벤트가 표시되었고 이벤트 이름을 클릭했습니다.

전체 볼륨에 대해 수행할 수 있는 가능한 시정 조치는 다음과 같습니다.

* 볼륨에서 자동 증가, 중복 제거 또는 압축 활성화
* 볼륨 크기 조정 또는 이동
* 볼륨에서 데이터 삭제 또는 이동


이러한 모든 작업은 ONTAP System Manager나 ONTAP CLI에서 수행해야 하지만 Unified Manager를 사용하면 어떤 작업을 수행해야 할지 결정하는 데 필요한 정보를 찾을 수 있습니다.

.단계
. *이벤트* 세부 정보 페이지에서 소스 필드의 볼륨 이름을 클릭하면 영향을 받은 볼륨에 대한 세부 정보를 볼 수 있습니다.
. *볼륨/상태* 세부 정보 페이지에서 *구성*을 클릭하면 볼륨에서 중복 제거 및 압축이 이미 활성화되어 있는 것을 확인할 수 있습니다.
+
볼륨 크기를 조절하기로 결정했습니다.

. *관련 장치* 창에서 호스팅 집계의 이름을 클릭하면 해당 집계가 더 큰 볼륨을 수용할 수 있는지 확인할 수 있습니다.
. *집계/상태* 세부 정보 페이지에서 전체 볼륨을 호스팅하는 집계에 커밋되지 않은 용량이 충분하다는 것을 확인했으므로 ONTAP 시스템 관리자를 사용하여 볼륨 크기를 조정하여 용량을 늘립니다.


*관련 정보*

link:../events/reference_event_details_page.html["이벤트 세부 정보 페이지"]
