---
permalink: health-checker/task_perform_corrective_action_for_storage_failover_interconnect_links.html 
sidebar: sidebar 
keywords: perform, corrective action, storage failover, interconnect links 
summary: 스토리지 장애 조치 관련 이벤트의 이벤트 세부 정보 페이지를 표시하면 페이지의 요약 정보를 검토하여 이벤트의 긴급성, 문제의 가능한 원인, 문제에 대한 가능한 해결책을 확인할 수 있습니다. 
---
= 스토리지 장애 조치 상호 연결 링크가 다운된 경우 시정 조치를 수행합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 장애 조치 관련 이벤트의 이벤트 세부 정보 페이지를 표시하면 페이지의 요약 정보를 검토하여 이벤트의 긴급성, 문제의 가능한 원인, 문제에 대한 가능한 해결책을 확인할 수 있습니다.

.시작하기 전에
운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

이 예제 시나리오에서 이벤트 세부 정보 페이지에 제공된 이벤트 요약에는 스토리지 장애 조치 상호 연결 링크 다운 조건에 대한 다음 정보가 포함되어 있습니다.

[listing]
----
Event: Storage Failover Interconnect One or More Links Down

Summary

Severity: Warning
State: New
Impact Level: Risk
Impact Area: Availability
Source: aardvark
Source Type: Node
Acknowledged By:
Resolved By:
Assigned To:
Cause: At least one storage failover interconnected link
       between the nodes aardvark and bonobo is down.
       RDMA interconnect is up (Link0 up, Link1 down)
----
예시 이벤트 정보는 HA 쌍 노드 aardvark와 bonobo 사이의 스토리지 장애 조치 상호 연결 링크 Link1이 다운되었지만 Apple과 Boy 사이의 Link0은 활성화되어 있음을 나타냅니다.  한 링크가 활성화되어 있으므로 원격 동적 메모리 액세스(RDMA)가 계속 작동하고 스토리지 장애 조치 작업이 계속 성공할 수 있습니다.

하지만 링크 장애와 스토리지 장애 조치 보호가 완전히 비활성화되는 것을 방지하기 위해 Link1이 다운된 이유를 추가로 진단하기로 결정했습니다.

.단계
. *이벤트* 세부 정보 페이지에서 소스 필드에 지정된 이벤트에 대한 링크를 클릭하면 스토리지 장애 조치 상호 연결 링크 다운 조건과 관련이 있을 수 있는 다른 이벤트에 대한 자세한 내용을 얻을 수 있습니다.
+
이 예에서 이벤트의 소스는 aardvark라는 노드입니다.  해당 노드 이름을 클릭하면 클러스터/상태 세부 정보 페이지의 노드 탭에 영향을 받은 HA 쌍인 aardvark와 bonobo에 대한 HA 세부 정보가 표시되고, 영향을 받은 HA 쌍에서 최근 발생한 다른 이벤트도 표시됩니다.

. 이벤트와 관련된 자세한 내용은 *HA 세부 정보*를 확인하세요.
+
이 예에서 관련 정보는 이벤트 테이블에 있습니다.  표에는 "저장소 장애 조치 연결 하나 이상 링크 다운" 이벤트, 이벤트가 생성된 시간, 그리고 이 이벤트가 발생한 노드가 표시됩니다.



HA 세부 정보의 노드 위치 정보를 사용하여 영향을 받는 HA 쌍 노드의 스토리지 장애 조치 문제에 대한 물리적 검사 및 수리를 요청하거나 직접 완료합니다.

*관련 정보*

link:../events/reference_event_details_page.html["이벤트 세부 정보 페이지"]

link:../config/reference_unified_manager_roles_and_capabilities.html["Unified Manager 사용자 역할 및 기능"]
