---
permalink: health-checker/task_generate_and_upload_support_bundle.html 
sidebar: sidebar 
keywords: generate, upload, support bundle 
summary: 진단 정보가 포함된 지원 번들을 생성한 후 기술 지원팀에 보내 문제 해결에 도움을 받을 수 있습니다.  유지 관리 콘솔에서 NetApp 에 ​​지원 번들을 업로드할 수도 있습니다. 
---
= 지원 번들을 생성하고 업로드합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
진단 정보가 포함된 지원 번들을 생성한 후 기술 지원팀에 보내 문제 해결에 도움을 받을 수 있습니다.

Unified Manager 9.8부터 Unified Manager 서버가 인터넷에 연결되어 있으면 유지 관리 콘솔에서 NetApp 에 ​​지원 번들을 업로드할 수도 있습니다.

.시작하기 전에
유지 관리 사용자로서 유지 관리 콘솔에 액세스할 수 있어야 합니다.

일부 유형의 지원 데이터는 많은 양의 클러스터 리소스를 사용하거나 완료하는 데 오랜 시간이 걸릴 수 있으므로 전체 지원 번들을 선택하면 포함하거나 제외할 데이터 유형을 지정하여 지원 번들 크기를 줄일 수 있습니다.  또한 30일 분의 로그와 구성 데이터베이스 기록만 포함된 가벼운 지원 번들을 만드는 옵션도 있습니다. 여기에는 성능 데이터, 인수 기록 파일, 서버 힙 덤프가 제외됩니다.

Unified Manager는 가장 최근에 생성된 두 개의 지원 번들만 저장합니다.  이전 지원 번들은 시스템에서 삭제됩니다.

.단계
. 유지 관리 콘솔의 *메인 메뉴*에서 *지원/진단*을 선택합니다.
. 지원 번들에 포함할 세부 정보 수준에 따라 *가벼운 지원 번들 생성* 또는 *지원 번들 생성*을 선택하세요.
. 전체 지원 번들을 선택하는 경우 지원 번들에 포함하거나 제외할 다음 데이터 유형을 선택하거나 선택 해제합니다.
+
** *데이터베이스 덤프*
+
MySQL 서버 데이터베이스의 덤프.

** *힙 덤프*
+
Unified Manager 서버 프로세스의 주요 상태 스냅샷입니다.  이 옵션은 기본적으로 비활성화되어 있으며 고객 지원팀에서 요청할 때만 선택해야 합니다.

** *획득 녹음*
+
Unified Manager와 모니터링되는 클러스터 간의 모든 통신을 기록합니다.



+
[NOTE]
====
모든 데이터 유형을 선택 해제하더라도 지원 번들은 다른 Unified Manager 데이터와 함께 생성됩니다.

====
. 유형 `g` 을 입력한 다음 Enter를 눌러 지원 번들을 생성합니다.
+
지원 번들 생성은 메모리를 많이 사용하는 작업이므로 이때 지원 번들을 생성할지 확인하라는 메시지가 표시됩니다.

. 유형 `y` 을 입력한 다음 Enter를 눌러 지원 번들을 생성합니다.
+
지금 지원 번들을 생성하지 않으려면 다음을 입력하십시오. `n` 를 입력한 다음 Enter를 누릅니다.

. 전체 지원 번들에 데이터베이스 덤프 파일을 포함한 경우 성능 통계를 포함할 기간을 지정하라는 메시지가 표시됩니다.  성능 통계를 포함하려면 많은 시간과 공간이 필요하므로 성능 통계를 포함하지 않고 데이터베이스를 덤프할 수도 있습니다.
+
.. 시작 날짜를 YYYYMMDD 형식으로 입력하세요.
+
예를 들어 다음을 입력하세요. `20210101` 2021년 1월 1일 기준.  입력하다 `n` 성과 통계를 포함하지 않으려면.

.. 지정된 시작 날짜의 오전 12시부터 시작하여 포함할 통계의 일 수를 입력합니다.
+
1에서 10까지의 숫자를 입력할 수 있습니다.



+
성과 통계를 포함하는 경우 시스템은 성과 통계를 수집하는 기간을 표시합니다.

. 지원 번들이 생성되면 NetApp 에 ​​업로드할지 여부를 묻는 메시지가 표시됩니다.  유형 `y` 를 입력한 다음 Enter를 누릅니다.
+
지원 사례 번호를 입력하라는 메시지가 표시됩니다.

. 이미 사건 번호가 있는 경우, 번호를 입력하고 Enter를 누르세요.  그렇지 않으면 Enter를 누르세요.
+
지원 번들은 NetApp 에 ​​업로드됩니다.



Unified Manager 서버가 인터넷에 연결되어 있지 않거나 다른 이유로 지원 번들을 업로드할 수 없는 경우, 해당 번들을 검색하여 수동으로 보낼 수 있습니다.  SFTP 클라이언트를 사용하거나 UNIX 또는 Linux CLI 명령을 사용하여 검색할 수 있습니다.  Windows 설치에서는 원격 데스크톱(RDP)을 사용하여 지원 번들을 검색할 수 있습니다.

생성된 지원 번들은 VMware 시스템의 /support 디렉토리, Linux 시스템의 /opt/netapp/data/support/ 디렉토리, Windows 시스템의 ProgramData\ NetApp\OnCommandAppData\ocum\support 디렉토리에 있습니다.

*관련 정보*

link:../config/reference_unified_manager_roles_and_capabilities.html["Unified Manager 사용자 역할 및 기능"]
