---
permalink: health-checker/task_create_volume_where_backups_are_stored.html 
sidebar: sidebar 
keywords: configure, snapshot copy, copies location 
summary: ONTAP 시스템 관리자나 ONTAP CLI를 사용하여 ONTAP 클러스터 중 하나에 스냅샷 복사본이 저장될 볼륨을 구성할 수 있습니다. 
---
= 스냅샷 복사 위치 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 시스템 관리자나 ONTAP CLI를 사용하여 ONTAP 클러스터 중 하나에 스냅샷 복사본이 저장될 볼륨을 구성할 수 있습니다.

.시작하기 전에
클러스터, 스토리지 VM 및 볼륨은 다음 요구 사항을 충족해야 합니다.

* 클러스터 요구 사항:
+
** ONTAP 9.3 이상이 설치되어 있어야 합니다.
** Unified Manager 서버와 지리적으로 가까워야 합니다.
** Unified Manager로 모니터링이 가능하지만 필수는 아닙니다.


* 스토리지 VM 요구 사항:
+
** 이름 스위치와 이름 매핑은 "`files`"를 사용하도록 설정해야 합니다.
** 클라이언트 측 사용자와 통신하기 위해 생성된 로컬 사용자
** 모든 읽기/쓰기 액세스가 선택되었는지 확인하세요.
** 내보내기 정책에서 Superuser Access가 "`any`"로 설정되어 있는지 확인하세요.
** Linux용 NetApp 스냅샷을 위한 NFS
** NFSv4는 NFS 서버에서 활성화되어야 하며 클라이언트와 스토리지 VM에 지정된 NFSv4 ID 도메인이 필요합니다.
** 볼륨은 Unified Manager/opt/netapp/data 디렉토리 크기의 최소 두 배여야 합니다.
+
du -sh /opt/netapp/data/ 명령을 사용하여 현재 크기를 확인합니다.



* 볼륨 요구 사항:
+
** 볼륨은 Unified Manager /opt/netapp/data 디렉토리 크기의 최소 두 배여야 합니다.
** 보안 스타일은 UNIX로 설정해야 합니다.
** 로컬 스냅샷 정책을 비활성화해야 합니다.
** 볼륨 자동 크기 조정을 활성화해야 합니다.
** 성능 서비스 수준은 "Extreme"과 같이 높은 IOPS와 낮은 지연 시간을 갖는 정책으로 설정되어야 합니다.




NFS 볼륨을 생성하는 자세한 단계는 다음을 참조하세요. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_configure_NFSv4_in_Cluster-Mode["ONTAP 9에서 NFSv4를 구성하는 방법"] 그리고 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-nfsv3-cg/home.html["ONTAP 9 NFS 구성 익스프레스 가이드"] .
