---
permalink: install-vapp/concept_virtual_infrastructure_or_hardware_system_requirements.html 
sidebar: sidebar 
keywords: virtual, infrastructure, hardware, system, requirements, virtual appliance 
summary: 가상 인프라나 물리적 시스템에 Unified Manager를 설치하려면 메모리, CPU, 디스크 공간에 대한 최소 요구 사항을 충족해야 합니다. 
---
= 가상 인프라 및 하드웨어 시스템 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
가상 인프라나 물리적 시스템에 Unified Manager를 설치하려면 메모리, CPU, 디스크 공간에 대한 최소 요구 사항을 충족해야 합니다.

다음 표는 메모리, CPU, 디스크 공간 리소스에 권장되는 값을 보여줍니다.  이러한 값은 Unified Manager가 허용 가능한 성능 수준을 충족하도록 검증되었습니다.

[cols="2*"]
|===
| 하드웨어 구성 | 권장 설정 


 a| 
숫양
 a| 
12GB(최소 요구 사항 8GB)



 a| 
프로세서
 a| 
4개의 CPU



 a| 
CPU 사이클 용량
 a| 
총 9572MHz(최소 요구 사항 9572MHz)



 a| 
디스크 여유 공간
 a| 
* 5GB(씬 프로비저닝)
* 152GB(두꺼운 프로비저닝)


|===
Unified Manager는 메모리 용량이 적은 시스템에도 설치할 수 있지만, 권장하는 12GB RAM을 사용하면 최적의 성능을 위해 충분한 메모리를 확보할 수 있으며, 구성이 커짐에 따라 시스템이 추가 클러스터와 스토리지 개체를 수용할 수 있습니다.  Unified Manager가 배포된 VM에 메모리 제한을 설정해서는 안 되며, 소프트웨어가 시스템에 할당된 메모리를 활용하는 것을 방해하는 기능(예: 벌루닝)을 활성화해서는 안 됩니다.

또한 Unified Manager의 두 번째 인스턴스를 설치하기 전에 Unified Manager의 단일 인스턴스가 모니터링할 수 있는 노드 수에는 제한이 있습니다. 자세한 내용은 다음을 참조하세요. link:https://www.netapp.com/pdf.html?item=/media/13504-tr4621pdf.pdf["Unified Manager 모범 사례 가이드"^].

메모리 페이지 스와핑은 시스템과 관리 애플리케이션의 성능에 부정적인 영향을 미칩니다.  전반적인 호스트 활용으로 인해 사용할 수 없는 CPU 리소스를 놓고 경쟁하면 성능이 저하될 수 있습니다.



== 전용 사용에 대한 요구 사항

Unified Manager를 설치하는 물리적 또는 가상 시스템은 Unified Manager에만 사용해야 하며 다른 애플리케이션과 공유해서는 안 됩니다.  다른 애플리케이션이 시스템 리소스를 소모하여 Unified Manager의 성능을 크게 저하시킬 수 있습니다.



== 백업을 위한 공간 요구 사항

Unified Manager 백업 및 복원 기능을 사용하려면 "`data`" 디렉터리나 디스크에 150GB의 공간을 확보하도록 추가 용량을 할당하세요.  백업은 로컬 대상이나 원격 대상에 기록될 수 있습니다.  가장 좋은 방법은 Unified Manager 호스트 시스템 외부에 있으며 최소 150GB의 공간이 있는 원격 위치를 식별하는 것입니다.



== 호스트 연결 요구 사항

Unified Manager를 설치하는 물리적 시스템이나 가상 시스템은 성공적으로 다음을 수행할 수 있도록 구성되어야 합니다. `ping` 호스트 자체의 호스트 이름입니다.  IPv6 구성의 경우 다음 사항을 확인해야 합니다. `ping6` Unified Manager 설치가 성공적으로 이루어지도록 호스트 이름이 성공적으로 지정되었습니다.

호스트 이름(또는 호스트 IP 주소)을 사용하여 제품 웹 UI에 액세스할 수 있습니다.  배포 중에 네트워크에 대한 정적 IP 주소를 구성한 경우 네트워크 호스트에 대한 이름을 지정했습니다.  DHCP를 사용하여 네트워크를 구성한 경우 DNS에서 호스트 이름을 얻어야 합니다.

정규화된 도메인 이름(FQDN)이나 IP 주소 대신 짧은 이름을 사용하여 사용자가 Unified Manager에 액세스하도록 허용하려는 경우 네트워크 구성에서 이 짧은 이름을 유효한 FQDN으로 확인해야 합니다.
