---
permalink: install-vapp/qsg-vapp.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, VMWare QSG, vApp QSG, quick installation 
summary: VMWare vSphere 플랫폼의 Unified Manager에 대한 빠른 시작 가이드입니다. 
---
= VMware 설치를 위한 빠른 시작 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다운로드할 수 있습니다 `.tar` 루트 인증서가 포함된 파일 `README` 파일 및 `OVA` 파일을 만들고 Unified Manager를 가상 어플라이언스로 배포합니다.



== 시스템 요구 사항

* 운영 체제: VMware ESXi 8.0
* 램: 12GB
* CPU: 총 9572MHz
* 여유 디스크 공간: 5GB(씬 프로비저닝), 152GB(씩 프로비저닝)


자세한 시스템 요구 사항은 다음을 참조하세요.link:../install-vapp/concept_requirements_for_installing_unified_manager.html["Unified Manager 설치 요구 사항"] 그리고link:http://mysupport.netapp.com/matrix["상호 운용성 매트릭스"] .



== Active IQ Unified Manager 설치



=== 설치 프로그램을 다운로드하세요

. 다운로드 `.tar` 루트 인증서가 포함된 파일 `README` 파일 및 `OVA` 파일.
. vSphere Client에서 액세스할 수 있는 로컬 디렉토리나 네트워크 디렉토리에 파일을 저장합니다.
. 다운로드한 디렉토리에서 `.tar` 파일을 입력하세요 `tar -xvzf ActiveIQUnifiedManager-<version>.tar.gz` 명령.  + 필요한 `OVA` 파일, 루트 인증서 및 `README` 파일이 대상 디렉토리에 압축 해제됩니다.




=== 무결성 확인

당신은의 무결성을 확인할 수 있습니다 `OVA` 제공된 단계에 따라 파일을 `README` 파일.



=== Unified Manager 설치

. vSphere Client에서 *파일 > OVF 템플릿 배포*를 클릭합니다.
. OVA 파일을 찾아 마법사를 사용하여 ESXi 서버에 가상 어플라이언스를 배포합니다.
. 검토 세부 정보 페이지의 게시자 섹션에서 메시지 `Entrust Code Signing - OVCS2 (Trusted certificate)` 다운로드한 파일의 무결성을 확인합니다 `OVA` 파일.  메시지에 대하여 `Entrust Code Signing - OVCS2 (Invalid certificate)` VMware vCenter Server를 7.0U3E 이상 버전으로 업그레이드하세요.
. 사용자 지정 템플릿 페이지의 속성 탭에서 수행 중인 설치 유형에 따라 필요한 필드를 채웁니다.
+
** 정적 구성의 경우 모든 필드에 필요한 정보를 입력하세요.  *보조 DNS* 필드에 대한 정보를 추가할 필요는 없습니다.
** IPv4를 사용하는 DHCP의 경우, 어떤 필드에도 정보를 추가하지 마세요.
** IPv6를 사용하는 DHCP의 경우 "자동 IPv6 주소 지정 사용" 상자를 선택합니다.  다른 필드에는 어떠한 정보도 추가하지 마세요.


. VM의 전원을 켭니다.
. 콘솔 탭을 클릭하면 초기 부팅 프로세스를 볼 수 있습니다.
. 시간대를 구성합니다.
. Unified Manager 유지 관리 사용자 이름과 비밀번호를 입력하세요.


설치가 끝나면 Unified Manager 웹 UI에 연결하기 위한 정보가 표시됩니다.
