---
permalink: install-vapp/reference_vmware_software_and_installation_requirements.html 
sidebar: sidebar 
keywords: vmware, software, installation, requirements 
summary: Unified Manager를 설치하는 VMware vSphere 시스템에는 특정 버전의 운영 체제와 특정 버전의 지원 소프트웨어가 필요합니다. 
---
= VMware 소프트웨어 및 설치 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 설치하는 VMware vSphere 시스템에는 특정 버전의 운영 체제와 특정 버전의 지원 소프트웨어가 필요합니다.



[[operating-system-software]]
== 운영 체제 소프트웨어

지원되는 운영 체제는 VMware ESXi 8.0입니다.

[NOTE]
====
VMware vSphere 시스템의 Unified Manager OVA는 내부적으로 Debian OS 12(bookworm)를 실행합니다.  지원되는 ESXi 서버 버전이 지원할 수 있는 가상 머신 하드웨어 버전에 대한 자세한 내용은 VMware 설명서를 참조하세요.

====
다음 vSphere 버전이 지원됩니다.

* VMware vCenter Server 7.0 및 8.0


지원되는 ESXi 버전의 전체 및 최신 목록은 상호 운용성 매트릭스를 참조하세요.

http://mysupport.netapp.com/matrix["mysupport.netapp.com/매트릭스"]

가상 어플라이언스가 올바르게 작동하려면 VMware ESXi 서버 시간이 NTP 서버 시간과 동일해야 합니다.  VMware ESXi 서버 시간을 NTP 서버 시간과 동기화하면 시간 오류가 방지됩니다.



[[installation-requirements]]
== 설치 요구 사항

Unified Manager 가상 어플라이언스에 대한 VMware 고가용성이 지원됩니다.

ONTAP 소프트웨어를 실행하는 스토리지 시스템에 NFS 데이터 저장소를 배포하는 경우 VMware VAAI용 NetApp NFS 플러그인을 사용하여 두꺼운 프로비저닝을 사용하세요.

고가용성 지원 환경에서 리소스가 부족하여 배포에 실패하는 경우 VM 재시작 우선 순위를 비활성화하고 호스트 격리 응답을 켜둔 상태로 두어 클러스터 기능 가상 머신 옵션을 수정해야 할 수 있습니다.


NOTE: Unified Manager를 설치하거나 업그레이드하는 동안 필요한 타사 소프트웨어와 보안 패치가 VMware vSphere 시스템에 자동으로 설치되거나 업그레이드됩니다.  Unified Manager 설치 및 업그레이드 프로세스가 이러한 구성 요소를 제어하므로 타사 구성 요소의 독립 실행형 설치 또는 업그레이드를 시도해서는 안 됩니다.
