---
permalink: install-vapp/task_deploy_unified_manager_vapp.html 
sidebar: sidebar 
keywords: deploy, unified manager 
summary: Unified Manager를 배포하려면 소프트웨어 다운로드, 가상 어플라이언스 배포, 유지 관리 사용자 이름과 비밀번호 생성, 웹 UI에서 초기 설정 수행이 필요합니다. 
---
= Unified Manager 배포
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 배포하려면 소프트웨어 다운로드, 가상 어플라이언스 배포, 유지 관리 사용자 이름과 비밀번호 생성, 웹 UI에서 초기 설정 수행이 필요합니다.

.시작하기 전에
* 배포를 위해 시스템 요구 사항을 확인하고 완료해야 합니다.
+
보다link:concept_requirements_for_installing_unified_manager.html["시스템 요구 사항"] .

* 다음 정보가 있는지 확인하세요.
+
** NetApp 지원 사이트에 대한 로그인 자격 증명
** VMware vCenter Server 및 vSphere Web Client에 액세스하기 위한 자격 증명
** Unified Manager 가상 어플라이언스를 배포하는 ESXi 서버의 IP 주소
** 데이터 저장소의 저장 공간 및 메모리 요구 사항 등 데이터 센터에 대한 세부 정보
** IPv6 주소 지정을 사용하려면 호스트에서 IPv6를 활성화해야 합니다.




VMware ESXi 서버에서 Unified Manager를 가상 어플라이언스로 배포할 수 있습니다.

SSH를 사용해서가 아니라 VMware 콘솔을 사용하여 유지 관리 콘솔에 액세스해야 합니다.

[NOTE]
====
Unified Manager 9.8부터 VMware Tools가 Open VM Tools로 대체되었습니다. `open-vm-tools` ).  더 이상 설치의 일부로 VMware Tools를 설치할 필요가 없습니다. `open-vm-tools` Unified Manager 설치 패키지에 포함되어 있습니다.

====
배포 및 초기 설정을 완료한 후에는 유지 관리 콘솔에서 클러스터를 추가하거나 추가 네트워크 설정을 구성한 다음 웹 UI에 액세스할 수 있습니다.

.단계
. 다음 단계를 따르세요link:task_download_unified_manager_ova_file.html["Unified Manager 다운로드"] .
. 또한 다음 단계를 따르세요.link:task_deploy_unified_manager_virtual_appliance_vapp.html["Unified Manager 가상 어플라이언스 배포"] .

