---
permalink: install-vapp/task_upgrade_unified_manager_virtual_appliance_vapp.html 
sidebar: sidebar 
keywords: upgrade, unified manager, virtual, appliance 
summary: Unified Manager 가상 어플라이언스를 업그레이드할 수 있습니다. 
---
= Unified Manager 가상 어플라이언스 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager 가상 어플라이언스를 릴리스 9.13 또는 9.14에서 9.16로 업그레이드할 수 있습니다.

.시작하기 전에
다음 사항을 확인하세요.

* NetApp 지원 사이트에서 업그레이드 파일과 ISO 이미지를 다운로드했습니다.
* Unified Manager를 업그레이드하는 시스템은 시스템 및 소프트웨어 요구 사항을 충족합니다.
+
보다link:concept_virtual_infrastructure_or_hardware_system_requirements.html["가상 인프라 요구 사항"] .

+
보다link:reference_vmware_software_and_installation_requirements.html["VMware 소프트웨어 및 설치 요구 사항"] .

* vSphere 6.5 이상 사용자의 경우 VMware Remote Console(VMRC)을 설치했습니다.
* 업그레이드하는 동안 성능 데이터를 13개월 동안 보관하는 기존 기본 설정을 유지할지, 아니면 6개월로 변경할지 묻는 메시지가 표시될 수 있습니다.  확인 후, 과거 성과 데이터는 6개월 후에 삭제됩니다.
* 다음 정보가 있습니다.
+
** NetApp 지원 사이트에 대한 로그인 자격 증명
** VMware vCenter Server 및 vSphere Web Client에 액세스하기 위한 자격 증명
** Unified Manager 유지 관리 사용자에 대한 자격 증명




업그레이드 프로세스 중에는 Unified Manager를 사용할 수 없습니다.  Unified Manager를 업그레이드하기 전에 실행 중인 모든 작업을 완료해야 합니다.

Workflow Automation과 Unified Manager를 페어링한 경우 Workflow Automation에서 호스트 이름을 수동으로 업데이트해야 합니다.

.단계
. vSphere Client에서 *홈* > *인벤토리* > *VM 및 템플릿*을 클릭합니다.
. Unified Manager 가상 어플라이언스가 설치된 가상 머신(VM)을 선택합니다.
. Unified Manager VM이 실행 중이면 *요약* > *명령* > *게스트 종료*로 이동합니다.
. Unified Manager VM의 스냅샷이나 복제본과 같은 백업 사본을 만들어 애플리케이션과 일관된 백업을 만듭니다.
. vSphere Client에서 Unified Manager VM의 전원을 켭니다.
. VMware 원격 콘솔을 실행합니다.
. *CDROM* 아이콘을 클릭하고 *디스크 이미지 파일(.iso)에 연결*을 선택합니다.
. 선택하세요 `ActiveIQUnifiedManager-<version>-virtual-update.iso` 파일을 클릭하고 *열기*를 클릭합니다.
. *콘솔* 탭을 클릭합니다.
. Unified Manager 유지 관리 콘솔에 로그인합니다.
. 메인 메뉴에서 *업그레이드*를 선택하세요.
+
업그레이드 프로세스 중에는 Unified Manager를 사용할 수 없으며, 완료되면 다시 시작된다는 메시지가 표시됩니다.

. 유형 `y` 계속하려면.
+
가상 어플라이언스가 있는 가상 머신을 백업하라는 경고가 표시됩니다.

. 유형 `y` 계속하려면.
+
업그레이드 프로세스와 Unified Manager 서비스 재시작은 완료하는 데 몇 분 정도 걸릴 수 있습니다.

. 계속하려면 아무 키나 누르세요.
+
유지 관리 콘솔에서 자동으로 로그아웃됩니다.

. *선택 사항:* 유지 관리 콘솔에 로그인하고 Unified Manager 버전을 확인하세요.


지원되는 웹 브라우저에서 새 창으로 웹 UI를 실행하고 로그인하여 Unified Manager 업그레이드 버전을 사용할 수 있습니다.  UI에서 작업을 수행하기 전에 검색 프로세스가 완료될 때까지 기다려야 합니다.
