---
permalink: install-windows/qsg-windows.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, Windows QSG, quick installation, Windows installer 
summary: Windows 플랫폼에서 Unified Manager를 사용하는 빠른 시작 가이드입니다. 
---
= Windows 설치를 위한 빠른 시작 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
설치 패키지를 다운로드하고 Unified Manager를 설치하여 데이터 저장 용량, 가용성, 성능 및 보호 문제를 모니터링하고 해결할 수 있습니다.



[[system-requirements]]
== 시스템 요구 사항

* 운영 체제
+
** Microsoft Windows Server 2019 Standard 및 Datacenter Edition
** Microsoft Windows Server 2022 Standard 및 Datacenter Edition
+
Unified Manager는 다음 언어에 대해 64비트 Windows 운영 체제에서 지원됩니다.

** 영어
** 일본어
** 간체 중국어


* 램: 12GB
* CPU: 총 9572MHz
* 여유 디스크 공간: 설치 디렉토리용 100GB 디스크 공간, MySQL 데이터 디렉토리용 50GB 디스크 공간


자세한 시스템 요구 사항은 다음을 참조하세요.link:../install-windows/concept_requirements_for_installing_unified_manager.html["Unified Manager 설치 요구 사항"] 그리고link:http://mysupport.netapp.com/matrix["상호 운용성 매트릭스"^] .



[[install-active-iq-unified-manager]]
== Active IQ Unified Manager 설치



[[download-the-installer]]
=== 설치 프로그램을 다운로드하세요

. 다운로드 `ActiveIQUnifiedManager-<version>.exe` 설치 패키지.
. 설치 파일을 대상 시스템의 디렉토리에 복사합니다.




[[install-unified-manager]]
=== Unified Manager 설치

Unified Manager를 설치하려면 Microsoft .NET 4.5.2 이상 버전이 설치되어 있는지 확인하세요.  Unified Manager는 설치 과정의 일부로 필요에 따라 다른 타사 패키지를 설치합니다.  종속 소프트웨어 패키지에 대한 자세한 내용은 다음을 참조하세요.link:../install-windows/reference_windows_software_and_installation_requirements.html["Windows 소프트웨어 및 설치 요구 사항"] .

. 기본 로컬 관리자 계정을 사용하여 Windows에 로그인합니다.
. 설치 파일을 다운로드한 디렉토리에서 마우스 오른쪽 버튼을 클릭하고 Unified Manager 실행 파일(.exe)을 관리자 권한으로 실행합니다.
. 메시지가 표시되면 사용자 이름과 비밀번호를 입력하여 Unified Manager 유지 관리 사용자를 만듭니다.
. 데이터베이스 연결 마법사에서 MySQL 루트 비밀번호를 입력합니다.
. 나머지 메시지에 따라 설치를 완료하세요.
. 설치가 끝나면 *마침*을 클릭하면 Unified Manager 웹 UI가 표시됩니다.

