---
permalink: install-windows/task_upgrade_to_unified_manager_on_microsoft_windows.html 
sidebar: sidebar 
keywords: upgrade, unified manager 
summary: Windows 플랫폼에서 설치 파일을 다운로드하여 실행하면 Unified Manager를 업그레이드할 수 있습니다. 
---
= Unified Manager 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows 플랫폼에서 설치 파일을 다운로드하여 실행하면 Unified Manager 9.13 또는 9.14을 9.16로 업그레이드할 수 있습니다.

.시작하기 전에
* Unified Manager를 업그레이드하는 시스템은 시스템 및 소프트웨어 요구 사항을 충족해야 합니다.
+
보다link:concept_virtual_infrastructure_or_hardware_system_requirements.html["하드웨어 시스템 요구 사항"] .

+
보다link:reference_windows_software_and_installation_requirements.html["Windows 소프트웨어 및 설치 요구 사항"] .

+
[NOTE]
====
Unified Manager 9.5부터 OpenJDK가 설치 패키지에 포함되어 자동으로 설치됩니다.  Unified Manager 9.5부터 Oracle Java가 지원되지 않습니다.

====
+
[NOTE]
====
업그레이드를 시작하기 전에 Microsoft .NET 4.5.2 이상이 시스템에 설치되어 있는지 확인하세요.

====
* MySQL Community Edition은 Unified Manager 업그레이드 중에 자동으로 업그레이드됩니다.  시스템에 설치된 MySQL 버전이 8.4.4 이전인 경우 Unified Manager 업그레이드 프로세스는 자동으로 MySQL을 8.4.4로 업그레이드합니다.  이전 버전의 MySQL을 8.4.4로 독립 실행형 업그레이드를 실행해서는 안 됩니다.
* ASA r2 시스템을 제외한 모든 클러스터가 지원됩니다.
* Windows 관리자 권한이 있어야 합니다.  사용자 이름이 느낌표 "`로 시작하지 않는지 확인하세요.!`". Installation of Unified Manager might fail if the user name of user running the installation begins with "` !`".
* NetApp 지원 사이트에 로그인하려면 유효한 자격 증명이 있어야 합니다.
* 데이터 손실을 방지하려면 업그레이드 중에 문제가 발생할 경우를 대비해 Unified Manager 컴퓨터의 백업을 만들어야 합니다.
* 업그레이드를 수행하려면 충분한 디스크 공간이 있어야 합니다.
+
설치 드라이브의 사용 가능한 공간은 데이터 디렉터리 크기보다 2.5GB 더 커야 합니다.  충분한 여유 공간이 없으면 업그레이드가 중지되고 추가할 공간의 양을 알려주는 오류 메시지가 표시됩니다.

* 업그레이드하는 동안 성능 데이터를 13개월 동안 보관하는 기존 기본 설정을 유지할지, 아니면 6개월로 변경할지 묻는 메시지가 표시될 수 있습니다.  확인 후, 6개월 이후의 과거 실적 데이터는 삭제됩니다.
* 업그레이드하기 전에 _<InstallDir>\JDK_ 및 _MySQL Data Directory_에 있는 열려 있는 파일이나 폴더를 모두 닫아야 합니다.
* Windows 시스템에 활성 바이러스 백신 소프트웨어가 설치되어 있는 경우 Unified Manager 업그레이드가 실패할 수 있습니다.  Unified Manager를 업그레이드하기 전에 시스템의 모든 바이러스 검사 소프트웨어를 비활성화해야 합니다.


업그레이드 프로세스 중에는 Unified Manager를 사용할 수 없습니다.  Unified Manager를 업그레이드하기 전에 실행 중인 모든 작업을 완료해야 합니다.

Unified Manager가 OnCommand Workflow Automation 인스턴스와 페어링되어 있고 두 제품 모두에 사용 가능한 소프트웨어의 새 버전이 있는 경우, 업그레이드를 수행한 후 두 제품의 연결을 해제한 다음 새 Workflow Automation 연결을 설정해야 합니다.  제품 중 하나만 업그레이드하는 경우 업그레이드 후 Workflow Automation에 로그인하여 Unified Manager에서 여전히 데이터를 수집하고 있는지 확인해야 합니다.

.단계
. NetApp 지원 사이트에 로그인하고 Unified Manager 다운로드 페이지로 이동합니다.
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["NetApp 지원 사이트"^].

. 필요한 Unified Manager 버전을 선택하고 최종 사용자 라이선스 계약(EULA)에 동의합니다.
. Unified Manager Windows 설치 파일이나 zip 파일을 Windows 시스템의 대상 디렉토리에 다운로드합니다.  필요한 경우 zip 파일을 추출하고 설치 파일이 있는 디렉토리로 이동합니다.  Unified Manager 설치 프로그램 실행 파일(.exe)을 마우스 오른쪽 버튼으로 클릭하고 관리자 권한으로 실행합니다.
+
Unified Manager에서 다음 메시지가 표시됩니다.

+
[listing]
----
This setup will perform an upgrade of Unified Manager. Do you want to continue?
----
. *예*를 클릭한 후, *다음*을 클릭합니다.
. 설치 중에 설정한 MySQL84 루트 비밀번호를 입력하고 *다음*을 클릭합니다.
. 지원되는 웹 브라우저에서 새 창으로 웹 UI를 실행하고 로그인하여 Unified Manager 업그레이드 버전을 사용하세요.
. Windows 시스템에 활성 바이러스 백신 소프트웨어가 설치되어 있는 경우 업그레이드가 완료된 후 바이러스 백신 검사에서 다음 경로를 수동으로 제외해야 합니다.
+
** Unified Manager 데이터 디렉토리
** Unified Manager 설치 디렉토리
** MySQL 데이터 디렉토리




[NOTE]
====
Unified Manager의 자동 업그레이드를 수행하려면 다음 명령을 실행하세요.
`ActiveIQUnifiedManager-<version\>.exe /s /v"MYSQL_PASSWORD=<password> /qn /l*v <system_drive>:\install.log"`

====