---
permalink: install-windows/task_unattended_installation_of_unified_manager.html 
sidebar: sidebar 
keywords: perform, unattended, installation, unified manager 
summary: 명령줄 인터페이스를 사용하면 사용자 개입 없이 Unified Manager를 설치할 수 있습니다.  키-값 쌍으로 매개변수를 전달하여 무인 설치를 완료할 수 있습니다. 
---
= Unified Manager의 무인 설치 수행
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
명령줄 인터페이스를 사용하면 사용자 개입 없이 Unified Manager를 설치할 수 있습니다.  키-값 쌍으로 매개변수를 전달하여 무인 설치를 완료할 수 있습니다.

.단계
. 기본 로컬 관리자 계정을 사용하여 Windows 명령줄 인터페이스에 로그인합니다.
. Unified Manager를 설치할 위치로 이동하고 다음 옵션 중 하나를 선택하세요.
+
[cols="4a,4a"]
|===
| 옵션 | 지침 


 a| 
타사 패키지가 사전 설치된 경우
 a| 
`ActiveIQUnifiedManager-x.y.exe /V"MYSQL_PASSWORD=mysql_password INSTALLDIR=\"Installation directory\" MYSQL_DATA_DIR=\"MySQL data directory\" MAINTENANCE_PASSWORD=maintenance_password MAINTENANCE_USERNAME=maintenance_username /qn /l*v CompletePathForLogFile"`

*예:*

`ActiveIQUnifiedManager.exe /s /v"MYSQL_PASSWORD=netapp21! INSTALLDIR=\"C:\Program Files\NetApp\" MYSQL_DATA_DIR=\"C:\ProgramData\MYSQL\MySQLServer\" MAINTENANCE_PASSWORD=******* MAINTENANCE_USERNAME=admin /qn /l*v C:\install.log"`



 a| 
타사 패키지가 설치되지 않은 경우
 a| 
`ActiveIQUnifiedManager-x.y.exe /V"MYSQL_PASSWORD=mysql_password INSTALLDIR=\"Installation directory\" MYSQL_DATA_DIR=\"MySQL data directory\" MAINTENANCE_PASSWORD=maintenance_password MAINTENANCE_USERNAME=maintenance_username /qr /l*v CompletePathForLogFile"`

*예:*

`ActiveIQUnifiedManager.exe /s /v"MYSQL_PASSWORD=netapp21! INSTALLDIR=\"C:\Program Files\NetApp\" MYSQL_DATA_DIR=\"C:\ProgramData\MYSQL\MySQLServer\" MAINTENANCE_PASSWORD=******* MAINTENANCE_USERNAME=admin /qr /l*v C:\install.log"`

|===
+
그만큼 `/qr` 이 옵션을 선택하면 사용자 인터페이스가 축소된 조용한 모드가 활성화됩니다.  설치 진행 상황을 보여주는 기본 사용자 인터페이스가 표시됩니다.  입력하라는 메시지가 표시되지 않습니다.  JRE, MySQL, 7zip 등의 타사 패키지가 사전 설치되어 있지 않은 경우 다음을 사용해야 합니다. `/qr` 옵션.  설치가 실패하면 `/qn` 이 옵션은 타사 패키지가 설치되지 않은 서버에서 사용됩니다.

+
그만큼 `/qn` 이 옵션을 사용하면 사용자 인터페이스 없이 조용한 모드를 사용할 수 있습니다.  설치 중에는 사용자 인터페이스나 세부 정보가 표시되지 않습니다.  당신은 사용해서는 안됩니다 `/qn` 타사 패키지가 설치되지 않은 경우의 옵션입니다.

. 다음 URL을 사용하여 Unified Manager 웹 사용자 인터페이스에 로그인하세요.
+
`\https://IP address`


