---
permalink: config/concept_install_https_certificate_generated_using_external_tools.html 
sidebar: sidebar 
keywords: install, HTTPS, certificate, generated from external tools 
summary: OpenSSL, BoringSSL, LetsEncrypt와 같은 외부 도구를 사용하여 생성된 자체 서명 또는 CA 서명 인증서를 설치할 수 있습니다. 
---
= 외부 도구를 사용하여 생성된 HTTPS 인증서 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OpenSSL, BoringSSL, LetsEncrypt와 같은 외부 도구를 사용하여 생성된 자체 서명 또는 CA 서명 인증서를 설치할 수 있습니다.

이러한 인증서는 외부에서 생성된 공개-개인 키 쌍이므로 인증서 체인과 함께 개인 키를 로드해야 합니다.  허용되는 키 쌍 알고리즘은 "`RSA`"와 "`EC`"입니다.  *HTTPS 인증서 설치* 옵션은 일반 섹션의 HTTPS 인증서 페이지에서 사용할 수 있습니다.  업로드하는 파일은 다음 입력 형식이어야 합니다.

. Active IQ Unified Manager 호스트에 속하는 서버의 개인 키
. 개인키와 일치하는 서버의 인증서
. 위 인증서에 서명하는 데 사용되는 루트까지의 역방향 CA 인증서




== EC 키 쌍으로 인증서를 로드하기 위한 형식

허용되는 곡선은 "`prime256v1`"과 "`secp384r1`"입니다.  외부에서 생성된 EC 쌍이 포함된 인증서 샘플:

[listing]
----
 -----BEGIN EC PRIVATE KEY-----
<EC private key of Server>
-----END EC PRIVATE KEY-----
----
[listing]
----
 -----BEGIN CERTIFICATE-----
 <Server certificate>
 -----END CERTIFICATE-----
 -----BEGIN CERTIFICATE-----
 <Intermediate certificate #1 (if present)>
 -----END CERTIFICATE-----
 -----BEGIN CERTIFICATE-----
 <Intermediate certificate #2 (if present)>
 -----END CERTIFICATE-----
 -----BEGIN CERTIFICATE-----
 <Root signing certificate>
 -----END CERTIFICATE-----
----


== RSA 키 쌍으로 인증서를 로드하기 위한 형식

호스트 인증서에 속한 RSA 키 쌍에 허용되는 키 크기는 2048, 3072 및 4096입니다. 외부에서 생성된 *RSA 키 쌍*이 있는 인증서:

[listing]
----
-----BEGIN RSA PRIVATE KEY-----
 <RSA private key of Server>
 -----END RSA PRIVATE KEY-----
 -----BEGIN CERTIFICATE-----
 <Server certificate>
 -----END CERTIFICATE-----
 -----BEGIN CERTIFICATE-----
 <Intermediate certificate #1 (if present)>
 -----END CERTIFICATE-----
 -----BEGIN CERTIFICATE-----
 <Intermediate certificate #2 (if present)>
 -----END CERTIFICATE-----
 -----BEGIN CERTIFICATE-----
 <Root signing certificate>
 -----END CERTIFICATE-----
----
인증서를 업로드한 후 변경 사항을 적용하려면 Active IQ Unified Manager 인스턴스를 다시 시작해야 합니다.



== 외부에서 생성된 인증서를 업로드하는 동안 확인

시스템은 외부 도구를 사용하여 생성된 인증서를 업로드하는 동안 검사를 수행합니다.  검사 중 하나라도 실패하면 인증서가 거부됩니다.  제품 내 CSR에서 생성된 인증서와 외부 도구를 사용하여 생성된 인증서에 대한 검증도 포함됩니다.

* 입력의 개인 키는 입력의 호스트 인증서와 대조하여 검증됩니다.
* 호스트 인증서의 일반 이름(CN)은 호스트의 FQDN과 비교됩니다.
* 호스트 인증서의 일반 이름(CN)은 비어 있거나 공백이어서는 안 되며, localhost로 설정해서는 안 됩니다.
* 유효 시작일은 미래일 수 없으며, 인증서의 유효 만료일은 과거일 수 없습니다.
* 중간 CA 또는 CA가 존재하는 경우 인증서의 유효 시작 날짜는 미래가 아니어야 하며, 유효 만료 날짜도 과거가 아니어야 합니다.


[NOTE]
====
입력된 개인 키는 암호화되어서는 안 됩니다.  암호화된 개인 키가 있는 경우 시스템에서 해당 키가 거부됩니다.

====
예제 1

[listing]
----
----BEGIN ENCRYPTED PRIVATE KEY-----
<Encrypted private key>
-----END ENCRYPTED PRIVATE KEY-----
----
예제 2

[listing]
----
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
<content here>
-----END RSA PRIVATE KEY-----
----
예제 3

[listing]
----
-----BEGIN EC PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
<content here>
-----END EC PRIVATE KEY-----
----
인증서 설치에 실패하면 기술 자료(KB) 문서를 참조하세요.https://kb.netapp.com/mgmt/AIQUM/AIQUM_fails_to_install_externally_generated_certificate["ActiveIQ Unified Manager가 외부에서 생성된 인증서를 설치하지 못했습니다."^]
