---
permalink: config/concept_audit_logging.html 
sidebar: sidebar 
keywords: audit, logging 
summary: 감사 로그를 사용하면 감사 로그가 손상되었는지 감지할 수 있습니다.  사용자가 수행하는 모든 활동은 모니터링되어 감사 로그에 기록됩니다.  감사는 Active IQ Unified Manager 의 모든 사용자 인터페이스와 공개적으로 노출된 API 기능에 대해 수행됩니다. 
---
= 감사 로깅
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
감사 로그를 사용하면 감사 로그가 손상되었는지 감지할 수 있습니다.  사용자가 수행하는 모든 활동은 모니터링되어 감사 로그에 기록됩니다.  감사는 Active IQ Unified Manager 의 모든 사용자 인터페이스와 공개적으로 노출된 API 기능에 대해 수행됩니다.

*감사 로그: 파일 보기*를 사용하면 Active IQ Unified Manager 에서 사용 가능한 모든 감사 로그 파일을 보고 액세스할 수 있습니다.  감사 로그: 파일 보기의 파일은 생성 날짜를 기준으로 나열됩니다.  이 보기에서는 시스템에 설치 또는 업그레이드한 이후 현재까지 캡처된 모든 감사 로그에 대한 정보가 표시됩니다.  Unified Manager에서 작업을 수행할 때마다 정보가 업데이트되어 로그에서 사용할 수 있습니다.  각 로그 파일의 상태는 "파일 무결성 상태" 속성을 사용하여 캡처되며, 이 속성은 로그 파일의 변조 또는 삭제를 감지하기 위해 적극적으로 모니터링됩니다.  감사 로그가 시스템에서 사용 가능한 경우 감사 로그는 다음 상태 중 하나를 가질 수 있습니다.

[cols="2*"]
|===
| 상태 | 설명 


 a| 
활동적인
 a| 
현재 로그가 기록되고 있는 파일입니다.



 a| 
정상
 a| 
비활성화되어 압축되어 시스템에 저장된 파일입니다.



 a| 
변조됨
 a| 
사용자가 수동으로 파일을 편집하여 손상된 파일입니다.



 a| 
수동 삭제
 a| 
권한이 있는 사용자에 의해 삭제된 파일입니다.



 a| 
롤오버 삭제
 a| 
롤링 구성 정책에 따라 롤링 오프로 인해 삭제된 파일입니다.



 a| 
예상치 못한 삭제
 a| 
알 수 없는 이유로 삭제된 파일입니다.

|===
감사 로그 페이지에는 다음과 같은 명령 단추가 포함되어 있습니다.

* 구성
* 삭제
* 다운로드


*삭제* 버튼을 사용하면 감사 로그 보기에 나열된 감사 로그를 삭제할 수 있습니다.  감사 로그를 삭제할 수 있으며, 선택적으로 파일을 삭제하는 이유를 제공할 수 있습니다. 이는 나중에 유효한 삭제를 판별하는 데 도움이 됩니다.  REASON 열에는 삭제 작업을 수행한 사용자의 이름과 이유가 나열됩니다.

[NOTE]
====
로그 파일을 삭제하면 시스템에서 파일이 삭제되지만 DB 테이블의 항목은 삭제되지 않습니다.

====
감사 로그 섹션의 *다운로드* 버튼을 사용하여 Active IQ Unified Manager 에서 감사 로그를 다운로드하고 감사 로그 파일을 내보낼 수 있습니다.  "`NORMAL`" 또는 "`TAMPERED`"로 표시된 파일은 압축 파일로 다운로드됩니다. `.gzip` 체재.

감사 로그 파일은 주기적으로 보관되며 참조를 위해 데이터베이스에 저장됩니다.  보관하기 전에 감사 로그는 보안과 무결성을 유지하기 위해 디지털 서명됩니다.

전체 AutoSupport 번들이 생성되면 지원 번들에는 보관된 감사 로그 파일과 활성 감사 로그 파일이 모두 포함됩니다.  하지만 가벼운 지원 번들이 생성되면 활성 감사 로그만 포함됩니다.  보관된 감사 로그는 포함되지 않습니다.
