---
permalink: config/concept_security_dashboard.html 
sidebar: sidebar 
keywords: security compliance settings, security feature settings, ONTAP hardening guide, AutoSupport settings, authentication settings 
summary: Unified Manager에서 규정 준수 모니터링을 위해 보안 매개변수를 활성화하거나 비활성화할 수 있습니다. 
---
= 규정 준수를 위한 보안 설정 활성화 및 비활성화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기능 설정 페이지의 *보안 대시보드* 패널에서 *사용자 지정* 버튼을 사용하면 Unified Manager에서 규정 준수 모니터링을 위한 보안 매개변수를 활성화하거나 비활성화할 수 있습니다.

이 페이지에서 활성화 또는 비활성화되는 설정은 Unified Manager의 클러스터 및 스토리지 VM의 전반적인 규정 준수 상태를 관리합니다.  선택 사항에 따라 해당 열은 클러스터 인벤토리 페이지의 *보안: 모든 클러스터* 보기와 스토리지 VM 인벤토리 페이지의 *보안: 모든 스토리지 VM* 보기에 표시됩니다.

[NOTE]
====
관리자 역할을 가진 사용자만 이러한 설정을 편집할 수 있습니다.

====
ONTAP 클러스터, 스토리지 VM 및 볼륨에 대한 보안 기준은 다음에 정의된 권장 사항에 따라 평가됩니다.link:https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf["NetApp ONTAP 9 보안 강화 가이드"] .  대시보드의 보안 패널과 보안 페이지에는 클러스터, 스토리지 VM 및 볼륨의 기본 보안 준수 상태가 표시됩니다.  보안 위반 사항이 있는 클러스터와 스토리지 VM에 대해 보안 이벤트가 생성되고 관리 작업이 활성화됩니다.



== 보안 설정 사용자 정의

ONTAP 환경에 맞게 규정 준수 모니터링 설정을 사용자 지정하려면 다음 단계를 따르세요.

.단계
. *일반 > 기능 설정 > 보안 대시보드 > 사용자 지정*을 클릭합니다.  *보안 대시보드 설정 사용자 정의* 팝업이 나타납니다.
+
[NOTE]
====
활성화하거나 비활성화하는 보안 준수 매개변수는 클러스터 및 스토리지 VM 화면의 기본 보안 보기, 보고서 및 예약된 보고서에 직접적인 영향을 미칠 수 있습니다.  보안 매개변수를 수정하기 전에 이 화면에서 엑셀 보고서를 업로드했다면, 다운로드한 엑셀 보고서에 오류가 있을 수 있습니다.

====
. ONTAP 클러스터에 대한 사용자 정의 설정을 활성화하거나 비활성화하려면 *클러스터*에서 필요한 일반 설정을 선택합니다.  클러스터 규정 준수를 사용자 정의하기 위한 옵션에 대한 정보는 다음을 참조하세요.link:../health-checker/reference_cluster_compliance_categories.html["클러스터 규정 준수 범주"] .
. 스토리지 VM에 대한 사용자 지정 설정을 활성화하거나 비활성화하려면 *스토리지 VM*에서 필요한 일반 설정을 선택하세요.  스토리지 VM 규정 준수를 사용자 정의하기 위한 옵션에 대한 정보는 다음을 참조하세요.link:../health-checker/reference_svm_compliance_categories.html["스토리지 VM 규정 준수 범주"] .




== AutoSupport 및 인증 설정 사용자 지정

* AutoSupport 설정* 섹션에서 ONTAP 에서 AutoSupport 메시지를 보내는 데 HTTPS 전송을 사용할지 여부를 지정할 수 있습니다.

*인증 설정* 섹션에서 기본 ONTAP 관리자 사용자에 대해 Unified Manager 경고가 발생하도록 설정할 수 있습니다.

'''