---
permalink: config/concept_api_gateway.html 
sidebar: sidebar 
keywords: api gateway 
summary: API Gateway 기능을 사용하면 Active IQ Unified Manager 단일 제어 평면으로 사용하여 개별적으로 로그인하지 않고도 여러 ONTAP 클러스터를 관리할 수 있습니다. 
---
= API 게이트웨이 활성화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
API Gateway 기능을 사용하면 Active IQ Unified Manager 단일 제어 평면으로 사용하여 개별적으로 로그인하지 않고도 여러 ONTAP 클러스터를 관리할 수 있습니다.

Unified Manager에 처음 로그인하면 나타나는 구성 페이지에서 이 기능을 활성화할 수 있습니다.  또는 *일반* > *기능 설정* > *API 게이트웨이*에서 이 기능을 활성화하거나 비활성화할 수 있습니다.

Unified Manager REST API는 ONTAP REST API와 다르며, Unified Manager REST API를 사용하여 ONTAP REST API의 모든 기능을 활용할 수 있는 것은 아닙니다.  하지만 Unified Manager에 공개되지 않은 특정 기능을 관리하기 위해 ONTAP API에 액세스해야 하는 특정 비즈니스 요구 사항이 있는 경우 API Gateway 기능을 활성화하고 ONTAP API를 실행할 수 있습니다.  게이트웨이는 ONTAP API와 동일한 형식으로 헤더와 본문 요청을 유지하여 API 요청을 터널링하는 프록시 역할을 합니다.  Unified Manager 자격 증명을 사용하고 특정 API를 실행하여 개별 클러스터 자격 증명을 전달하지 않고도 ONTAP 클러스터에 액세스하고 관리할 수 있습니다.  Unified Manager는 Unified Manager 인스턴스에서 관리하는 ONTAP 클러스터 전반에서 API를 실행하기 위한 단일 관리 지점 역할을 합니다.  API에서 반환된 응답은 ONTAP 에서 직접 실행된 해당 ONTAP REST API에서 반환된 응답과 동일합니다.

이 기능을 활성화한 후, *메뉴 모음* > *도움말 버튼* > *API 문서* > *게이트웨이* 카테고리에서 Unified Manager REST API를 실행할 수 있습니다.  또는 호스트 이름 또는 IP 주소와 REST API 페이지에 액세스하기 위한 URL을 다음 형식으로 입력할 수 있습니다. `https://<hostname>/docs/api/`

API에 대한 자세한 내용은 다음을 참조하세요.link:../api-automation/concept_get_started_with_um_apis.html["Active IQ Unified Manager REST API 시작하기"] .
