---
permalink: config/reference_definitions_of_user_types.html 
sidebar: sidebar 
keywords: definitions, user types 
summary: 사용자 유형은 사용자가 보유한 계정의 종류를 지정하며 여기에는 원격 사용자, 원격 그룹, 로컬 사용자, 데이터베이스 사용자, 유지 관리 사용자가 포함됩니다.  각 유형에는 고유한 역할이 있으며, 이 역할은 관리자 역할을 가진 사용자가 지정합니다. 
---
= 사용자 유형의 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용자 유형은 사용자가 보유한 계정의 종류를 지정하며 여기에는 원격 사용자, 원격 그룹, 로컬 사용자, 데이터베이스 사용자, 유지 관리 사용자가 포함됩니다.  각 유형에는 고유한 역할이 있으며, 이 역할은 관리자 역할을 가진 사용자가 지정합니다.

Unified Manager 사용자 유형은 다음과 같습니다.

* *유지관리 사용자*
+
Unified Manager의 초기 구성 중에 생성되었습니다.  그런 다음 유지 관리 사용자는 추가 사용자를 만들고 역할을 할당합니다.  유지 관리 사용자는 유지 관리 콘솔에 액세스할 수 있는 유일한 사용자이기도 합니다.  Unified Manager가 Red Hat Enterprise Linux 시스템에 설치되면 유지 관리 사용자에게 "`umadmin`"이라는 사용자 이름이 지정됩니다.

* *로컬 사용자*
+
Unified Manager UI에 액세스하고 유지 관리 사용자 또는 애플리케이션 관리자 역할이 있는 사용자가 제공한 역할에 따라 기능을 수행합니다.

* *원격 그룹*
+
인증 서버에 저장된 자격 증명을 사용하여 Unified Manager UI에 액세스하는 사용자 그룹입니다.  이 계정의 이름은 인증 서버에 저장된 그룹 이름과 일치해야 합니다.  원격 그룹 내의 모든 사용자는 개별 사용자 자격 증명을 사용하여 Unified Manager UI에 액세스할 수 있습니다.  원격 그룹은 할당된 역할에 따라 기능을 수행할 수 있습니다.

* *원격 사용자*
+
인증 서버에 저장된 자격 증명을 사용하여 Unified Manager UI에 액세스합니다.  원격 사용자는 유지 관리 사용자 또는 애플리케이션 관리자 역할이 있는 사용자가 부여한 역할에 따라 기능을 수행합니다.

* *데이터베이스 사용자*
+
Unified Manager 데이터베이스의 데이터에 대한 읽기 전용 액세스 권한이 있으며, Unified Manager 웹 인터페이스나 유지 관리 콘솔에 대한 액세스 권한이 없으며, API 호출을 실행할 수 없습니다.


