---
permalink: config/reference_identity_provider_requirements_um.html 
sidebar: sidebar 
keywords: identity, provider, requirements 
summary: '모든 원격 사용자에 대한 SAML 인증을 수행하기 위해 ID 공급자(IdP)를 사용하도록 Unified Manager를 구성하는 경우 Unified Manager에 대한 연결이 성공하려면 몇 가지 필수 구성 설정을 알고 있어야 합니다.' 
---
= ID 공급자 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 원격 사용자에 대한 SAML 인증을 수행하기 위해 ID 공급자(IdP)를 사용하도록 Unified Manager를 구성하는 경우 Unified Manager에 대한 연결이 성공하려면 몇 가지 필수 구성 설정을 알고 있어야 합니다.

Unified Manager URI와 메타데이터를 IdP 서버에 입력해야 합니다.  Unified ManagerSAML 인증 페이지에서 이 정보를 복사할 수 있습니다.  Unified Manager는 SAML(Security Assertion Markup Language) 표준에서 서비스 공급자(SP)로 간주됩니다.



== 지원되는 암호화 표준

* 고급 암호화 표준(AES): AES-128 및 AES-256
* 보안 해시 알고리즘(SHA): SHA-1 및 SHA-256




== 검증된 ID 공급자

* 표어
* Active Directory 페더레이션 서비스(ADFS)




== ADFS 구성 요구 사항

* Unified Manager가 이 신뢰 당사자 신뢰 항목에 대한 ADFS SAML 응답을 구문 분석하는 데 필요한 세 가지 클레임 규칙을 다음 순서대로 정의해야 합니다.
+
[cols="2*"]
|===
| 청구 규칙 | 가치 


 a| 
SAM 계정 이름
 a| 
이름 ID



 a| 
SAM 계정 이름
 a| 
항아리:oid:0.9.2342.19200300.100.1.1



 a| 
토큰 그룹 -- 비정규 이름
 a| 
항아리:oid:1.3.6.1.4.1.5923.1.5.1.1

|===
* 인증 방법을 "양식 인증"으로 설정해야 합니다. 그렇지 않으면 사용자가 Unified Manager에서 로그아웃할 때 오류가 발생할 수 있습니다. 다음 단계를 따르세요.
+
.. ADFS 관리 콘솔을 엽니다.
.. 왼쪽 트리 보기에서 인증 정책 폴더를 클릭합니다.
.. 오른쪽의 작업에서 글로벌 기본 인증 정책 편집을 클릭합니다.
.. 기본 "Windows 인증" 대신 "폼 인증"으로 인트라넷 인증 방법을 설정합니다.


* 어떤 경우에는 Unified Manager 보안 인증서에 CA 서명이 있는 경우 IdP를 통한 로그인이 거부됩니다.  이 문제를 해결하는 방법은 두 가지가 있습니다.
+
** 링크에 명시된 지침에 따라 체인된 CA 인증서와 관련된 신뢰 당사자에 대한 ADFS 서버에서 해지 확인을 비활성화합니다.
+
http://www.torivar.com/2016/03/22/adfs-3-0-disable-revocation-check-windows-2012-r2/["신뢰 당사자 신뢰에 따른 해지 확인 비활성화"]

** Unified Manager 서버 인증서 요청에 서명하려면 CA 서버가 ADFS 서버 내에 있어야 합니다.






== 기타 구성 요구 사항

* Unified Manager 클록 오차는 5분으로 설정되어 있으므로 IdP 서버와 Unified Manager 서버 간의 시간 차이는 5분을 넘을 수 없으며, 5분을 넘으면 인증이 실패합니다.

