---
permalink: config/reference_remote_authentication_page.html 
sidebar: sidebar 
keywords: remote authentication, page 
summary: 원격 인증 페이지를 사용하여 Unified Manager가 인증 서버와 통신하여 Unified Manager 웹 UI에 로그인을 시도하는 원격 사용자를 인증하도록 구성할 수 있습니다. 
---
= 원격 인증 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
원격 인증 페이지를 사용하여 Unified Manager가 인증 서버와 통신하여 Unified Manager 웹 UI에 로그인을 시도하는 원격 사용자를 인증하도록 구성할 수 있습니다.

애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

원격 인증 사용 확인란을 선택하면 인증 서버를 사용하여 원격 인증을 사용할 수 있습니다.

* *인증 서비스*
+
Active Directory, OpenLDAP 등의 디렉터리 서비스 공급자에서 사용자를 인증하도록 관리 서버를 구성하거나 고유한 인증 메커니즘을 지정할 수 있습니다.  원격 인증을 활성화한 경우에만 인증 서비스를 지정할 수 있습니다.

+
** *액티브 디렉토리*
+
*** 관리자 이름
+
인증 서버의 관리자 이름을 지정합니다.

*** 비밀번호
+
인증 서버에 접근하기 위한 비밀번호를 지정합니다.

*** 기본 고유 이름
+
인증 서버에서 원격 사용자의 위치를 지정합니다.  예를 들어, 인증 서버의 도메인 이름이 +ou@domain.com+이면 기본 고유 이름은 *cn=ou,dc=domain,dc=com*입니다.

*** 중첩된 그룹 조회 비활성화
+
중첩 그룹 조회 옵션을 활성화할지 비활성화할지 지정합니다.  기본적으로 이 옵션은 비활성화되어 있습니다.  Active Directory를 사용하는 경우 중첩 그룹에 대한 지원을 비활성화하여 인증 속도를 높일 수 있습니다.

*** 보안 연결 사용
+
인증 서버와 통신하는 데 사용되는 인증 서비스를 지정합니다.



** *오픈LDAP*
+
*** 고유 이름 바인딩
+
인증 서버에서 원격 사용자를 찾기 위해 기본 고유 이름과 함께 사용되는 바인드 고유 이름을 지정합니다.

*** 바인드 비밀번호
+
인증 서버에 접근하기 위한 비밀번호를 지정합니다.

*** 기본 고유 이름
+
인증 서버에서 원격 사용자의 위치를 지정합니다.  예를 들어, 인증 서버의 도메인 이름이 +ou@domain.com+이면 기본 고유 이름은 *cn=ou,dc=domain,dc=com*입니다.

*** 보안 연결 사용
+
LDAP 인증 서버와 통신하는 데 보안 LDAP가 사용됨을 지정합니다.



** *기타*
+
*** 고유 이름 바인딩
+
구성한 인증 서버에서 원격 사용자를 찾기 위해 기본 고유 이름과 함께 사용되는 바인드 고유 이름을 지정합니다.

*** 바인드 비밀번호
+
인증 서버에 접근하기 위한 비밀번호를 지정합니다.

*** 기본 고유 이름
+
인증 서버에서 원격 사용자의 위치를 지정합니다.  예를 들어, 인증 서버의 도메인 이름이 +ou@domain.com+이면 기본 고유 이름은 *cn=ou,dc=domain,dc=com*입니다.

*** 프로토콜 버전
+
인증 서버에서 지원하는 LDAP(Lightweight Directory Access Protocol) 버전을 지정합니다.  프로토콜 버전을 자동으로 감지할지 아니면 버전을 2 또는 3으로 설정할지 지정할 수 있습니다.

*** 사용자 이름 속성
+
관리 서버에서 인증할 사용자 로그인 이름이 포함된 인증 서버의 속성 이름을 지정합니다.

*** 그룹 멤버십 속성
+
사용자 인증 서버에 지정된 속성과 값을 기반으로 원격 사용자에게 관리 서버 그룹 멤버십을 할당하는 값을 지정합니다.

*** 우지드
+
원격 사용자가 인증 서버의 GroupOfUniqueNames 개체의 멤버로 포함된 경우, 이 옵션을 사용하면 해당 GroupOfUniqueNames 개체의 지정된 속성을 기반으로 원격 사용자에게 관리 서버 그룹 멤버십을 할당할 수 있습니다.

*** 중첩된 그룹 조회 비활성화
+
중첩 그룹 조회 옵션을 활성화할지 비활성화할지 지정합니다.  기본적으로 이 옵션은 비활성화되어 있습니다.  Active Directory를 사용하는 경우 중첩 그룹에 대한 지원을 비활성화하여 인증 속도를 높일 수 있습니다.

*** 회원
+
인증 서버가 그룹의 개별 멤버에 대한 정보를 저장하는 데 사용하는 속성 이름을 지정합니다.

*** 사용자 객체 클래스
+
원격 인증 서버에서 사용자의 개체 클래스를 지정합니다.

*** 그룹 객체 클래스
+
원격 인증 서버의 모든 그룹의 개체 클래스를 지정합니다.

+

NOTE: _Member_, _User Object Class_, _Group Object Class_ 특성에 입력한 값은 Active Directory, OpenLDAP, LDAP 구성에 추가된 값과 동일해야 합니다.  그렇지 않으면 인증이 실패할 수 있습니다.

*** 보안 연결 사용
+
인증 서버와 통신하는 데 사용되는 인증 서비스를 지정합니다.





+
[NOTE]
====
인증 서비스를 수정하려면 기존 인증 서버를 삭제하고 새 인증 서버를 추가해야 합니다.

====




== 인증 서버 영역

인증 서버 영역에는 관리 서버가 원격 사용자를 찾아 인증하기 위해 통신하는 인증 서버가 표시됩니다.  원격 사용자 또는 그룹의 자격 증명은 인증 서버에서 유지 관리됩니다.

* *명령 버튼*
+
인증 서버를 추가, 편집 또는 삭제할 수 있습니다.

+
** 추가하다
+
인증 서버를 추가할 수 있습니다.

+
추가하려는 인증 서버가 고가용성 쌍(동일한 데이터베이스 사용)의 일부인 경우 파트너 인증 서버도 추가할 수 있습니다.  이를 통해 인증 서버 중 하나에 연결할 수 없을 때 관리 서버가 파트너와 통신할 수 있습니다.

** 편집하다
+
선택한 인증 서버의 설정을 편집할 수 있습니다.

** 삭제
+
선택한 인증 서버를 삭제합니다.



* *이름 또는 IP 주소*
+
관리 서버에서 사용자를 인증하는 데 사용되는 인증 서버의 호스트 이름이나 IP 주소를 표시합니다.

* *포트*
+
인증 서버의 포트 번호를 표시합니다.

* *테스트 인증*
+
이 버튼은 원격 사용자나 그룹을 인증하여 인증 서버 구성을 검증합니다.

+
테스트 시 사용자 이름만 지정하면 관리 서버는 인증 서버에서 원격 사용자를 검색하지만 사용자를 인증하지는 않습니다.  사용자 이름과 비밀번호를 모두 지정하면 관리 서버는 원격 사용자를 검색하고 인증합니다.

+
원격 인증이 비활성화된 경우 인증을 테스트할 수 없습니다.


