---
permalink: config/reference_system_configuration_menu.html 
sidebar: sidebar 
keywords: system, configuration, menu 
summary: 시스템 구성 메뉴를 사용하면 서버 상태 보기, 가상 머신 재부팅 및 종료 등 다양한 옵션을 제공하여 가상 어플라이언스를 관리할 수 있습니다. 
---
= 시스템 구성 메뉴
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템 구성 메뉴를 사용하면 서버 상태 보기, 가상 머신 재부팅 및 종료 등 다양한 옵션을 제공하여 가상 어플라이언스를 관리할 수 있습니다.

[NOTE]
====
Linux 또는 Microsoft Windows 시스템에 Unified Manager가 설치된 경우 이 메뉴에서는 "Unified Manager 백업에서 복원" 옵션만 사용할 수 있습니다.

====
다음과 같은 메뉴 선택이 가능합니다.

* *서버 상태 표시*
+
현재 서버 상태를 표시합니다.  상태 옵션에는 실행 중 및 실행 중이 아님이 있습니다.

+
서버가 실행되고 있지 않으면 기술 지원팀에 문의해야 할 수도 있습니다.

* *가상 머신 재부팅*
+
가상 머신을 재부팅하고 모든 서비스를 중지합니다.  재부팅 후 가상 머신과 서비스가 다시 시작됩니다.

* *가상 머신 종료*
+
가상 머신을 종료하고 모든 서비스를 중지합니다.

+
이 옵션은 가상 머신 콘솔에서만 선택할 수 있습니다.

* *<로그인한 사용자> 사용자 비밀번호 변경*
+
현재 로그인한 사용자의 비밀번호를 변경합니다. 이 비밀번호는 유지 관리 사용자만 변경할 수 있습니다.

* *데이터 디스크 크기 늘리기*
+
가상 머신의 데이터 디스크(디스크 3) 크기를 늘립니다.

* *스왑 디스크 크기 늘리기*
+
가상 머신의 스왑 디스크(디스크 2) 크기를 늘립니다.

* *시간대 변경*
+
시간대를 해당 지역의 시간대로 변경합니다.

* *NTP 서버 변경*
+
IP 주소나 정규화된 도메인 이름(FQDN)과 같은 NTP 서버 설정을 변경합니다.

* *NTP 서비스 변경*
+
사이를 전환합니다 `ntp` 그리고 `systemd-timesyncd` 서비스.

* *Unified Manager 백업에서 복원*
+
이전에 백업된 버전에서 Unified Manager 데이터베이스와 구성 설정을 복원합니다.

* *서버 인증서 재설정*
+
서버 보안 인증서를 재설정합니다.

* *호스트 이름 변경*
+
가상 어플라이언스가 설치된 호스트의 이름을 변경합니다.

* *뒤쪽에*
+
시스템 구성 메뉴를 종료하고 주 메뉴로 돌아갑니다.

* *출구*
+
유지 관리 콘솔 메뉴를 종료합니다.


