---
permalink: config/reference_regenerate_https_certificate_dialog_box.html 
sidebar: sidebar 
keywords: regenerate, https certificate, dialog, box 
summary: HTTPS 인증서 재생성 대화 상자를 사용하면 보안 정보를 사용자 지정한 다음 해당 정보로 새 HTTPS 인증서를 생성할 수 있습니다. 
---
= HTTPS 인증서 재생성 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
HTTPS 인증서 재생성 대화 상자를 사용하면 보안 정보를 사용자 지정한 다음 해당 정보로 새 HTTPS 인증서를 생성할 수 있습니다.

현재 인증서 정보는 이 페이지에 표시됩니다.

"현재 인증서 속성을 사용하여 다시 생성" 및 "현재 인증서 속성 업데이트" 선택을 사용하면 현재 정보로 인증서를 다시 생성하거나 새 정보로 인증서를 생성할 수 있습니다.

* *일반 이름*
+
필수의. 보호하려는 정규화된 도메인 이름(FQDN)입니다.

+
Unified Manager 고가용성 구성에서는 가상 IP 주소를 사용합니다.

* *이메일*
+
선택 과목. 귀하의 조직에 연락할 이메일 주소입니다. 일반적으로 인증 관리자나 IT 부서의 이메일 주소입니다.

* *회사*
+
선택 과목. 일반적으로 회사의 법인명입니다.

* *부서*
+
선택 과목. 회사 내 부서의 이름입니다.

* *도시*
+
선택 과목. 회사의 도시 위치입니다.

* *상태*
+
선택 과목. 회사의 주 또는 도 소재지를 약어로 표기하지 마십시오.

* *국가*
+
선택 과목. 회사의 국가 위치.  이는 일반적으로 국가의 두 글자 ISO 코드입니다.

* *대체 이름*
+
필수의. 기존 로컬호스트나 다른 네트워크 주소 외에도 이 서버에 접속하는 데 사용할 수 있는 기본이 아닌 추가 도메인 이름입니다.  각 대체 이름은 쉼표로 구분합니다.

+
인증서의 대체 이름 필드에서 로컬 식별 정보를 제거하려면 "로컬 식별 정보 제외(예: 로컬호스트)" 확인란을 선택합니다.  이 확인란을 선택하면 필드에 입력한 내용만 대체 이름 필드에 사용됩니다.  이 필드를 비워 두면 인증서에 대체 이름 필드가 전혀 없습니다.

* *키 크기(키 알고리즘: RSA)*
+
키 알고리즘은 RSA로 설정됩니다.  2048, 3072 또는 4096비트 중 하나의 키 크기를 선택할 수 있습니다.  기본 키 크기는 2048비트로 설정됩니다.

* *유효기간*
+
기본 유효 기간은 397일입니다.  이전 버전에서 업그레이드한 경우 이전 인증서의 유효성이 변경되지 않은 것으로 보일 수 있습니다.



자세한 내용은 다음을 참조하세요. link:../config/task_generate_an_https_security_certificate_ocf.html["HTTPS 인증서 생성"].
