---
permalink: config/reference_network_configuration_menu.html 
sidebar: sidebar 
keywords: network configuration menu 
summary: 네트워크 구성 메뉴를 사용하면 네트워크 설정을 관리할 수 있습니다.  Unified Manager 사용자 인터페이스를 사용할 수 없는 경우 이 메뉴를 사용해야 합니다. 
---
= 네트워크 구성 메뉴
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
네트워크 구성 메뉴를 사용하면 네트워크 설정을 관리할 수 있습니다.  Unified Manager 사용자 인터페이스를 사용할 수 없는 경우 이 메뉴를 사용해야 합니다.

[NOTE]
====
Red Hat Enterprise Linux 또는 Microsoft Windows에 Unified Manager가 설치된 경우 이 메뉴를 사용할 수 없습니다.

====
다음과 같은 메뉴 선택이 가능합니다.

* *IP 주소 설정 표시*
+
IP 주소, 네트워크, 브로드캐스트 주소, 넷마스크, 게이트웨이, DNS 서버를 포함하여 가상 어플라이언스의 현재 네트워크 설정을 표시합니다.

* *IP 주소 설정 변경*
+
IP 주소, 넷마스크, 게이트웨이 또는 DNS 서버를 포함하여 가상 어플라이언스의 네트워크 설정을 변경할 수 있습니다.  유지 관리 콘솔을 사용하여 네트워크 설정을 DHCP에서 정적 네트워킹으로 전환하는 경우 호스트 이름을 편집할 수 없습니다.  변경 사항을 적용하려면 *변경 사항 적용*을 선택해야 합니다.

* *도메인 이름 검색 설정 표시*
+
호스트 이름을 확인하는 데 사용되는 도메인 이름 검색 목록을 표시합니다.

* *도메인 이름 검색 설정 변경*
+
호스트 이름을 확인할 때 검색할 도메인 이름을 변경할 수 있습니다.  변경 사항을 적용하려면 *변경 사항 적용*을 선택해야 합니다.

* *정적 경로 표시*
+
현재의 정적 네트워크 경로를 표시합니다.

* *정적 경로 변경*
+
정적 네트워크 경로를 추가하거나 삭제할 수 있습니다.  변경 사항을 적용하려면 *변경 사항 적용*을 선택해야 합니다.

+
** *경로 추가*
+
정적 경로를 추가할 수 있습니다.

** *경로 삭제*
+
정적 경로를 삭제할 수 있습니다.

** *뒤쪽에*
+
*메인 메뉴*로 돌아갑니다.

** *출구*
+
유지 관리 콘솔을 종료합니다.



* *네트워크 인터페이스 비활성화*
+
사용 가능한 모든 네트워크 인터페이스를 비활성화합니다.  사용 가능한 네트워크 인터페이스가 하나뿐인 경우 비활성화할 수 없습니다.  변경 사항을 적용하려면 *변경 사항 적용*을 선택해야 합니다.

* *네트워크 인터페이스 활성화*
+
사용 가능한 네트워크 인터페이스를 활성화합니다.  변경 사항을 적용하려면 *변경 사항 적용*을 선택해야 합니다.

* *변경 사항 커밋*
+
가상 어플라이언스의 네트워크 설정에 대한 모든 변경 사항을 적용합니다.  변경 사항을 적용하려면 이 옵션을 선택해야 하며, 그렇지 않으면 변경 사항이 발생하지 않습니다.

* *호스트에 핑 보내기*
+
IP 주소 변경이나 DNS 구성을 확인하기 위해 대상 호스트에 ping을 보냅니다.

* *기본 설정으로 복원*
+
모든 설정을 공장 기본값으로 재설정합니다.  변경 사항을 적용하려면 *변경 사항 적용*을 선택해야 합니다.

* *뒤쪽에*
+
*메인 메뉴*로 돌아갑니다.

* *출구*
+
유지 관리 콘솔을 종료합니다.


