---
permalink: config/task_add_space_to_data_directory_of_um_linux_host.html 
sidebar: sidebar 
keywords: add, space, data directory, linux, host 
summary: '디스크 공간을 충분히 할당하지 않은 경우 `/opt/netapp/data` Linux 호스트를 처음 설정한 후 Unified Manager를 설치한 경우 Unified Manager를 지원하는 디렉토리에서 디스크 공간을 늘려 설치 후 디스크 공간을 추가할 수 있습니다. `/opt/netapp/data` 예배 규칙서.' 
---
= Linux 호스트의 데이터 디렉토리에 공간 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
디스크 공간을 충분히 할당하지 않은 경우 `/opt/netapp/data` Linux 호스트를 처음 설정한 후 Unified Manager를 설치한 경우 Unified Manager를 지원하는 디렉토리에서 디스크 공간을 늘려 설치 후 디스크 공간을 추가할 수 있습니다. `/opt/netapp/data` 예배 규칙서.

.시작하기 전에
Unified Manager가 설치된 Red Hat Enterprise Linux 시스템에 루트 사용자 액세스 권한이 있어야 합니다.

데이터 디렉터리 크기를 늘리기 전에 Unified Manager 데이터베이스를 백업하는 것이 좋습니다.

.단계
. 디스크 공간을 추가하려는 Linux 컴퓨터에 루트 사용자로 로그인합니다.
. 표시된 순서대로 Unified Manager 서비스와 관련 MySQL 소프트웨어를 중지합니다.
+
`systemctl stop ocieau ocie mysqld`

. 임시 백업 폴더를 만듭니다(예: `/backup-data` ) 현재 데이터를 포함할 수 있는 충분한 디스크 공간이 있음 `/opt/netapp/data` 예배 규칙서.
. 기존의 콘텐츠 및 권한 구성을 복사합니다. `/opt/netapp/data` 백업 데이터 디렉토리로의 디렉토리:
+
`cp -arp /opt/netapp/data/* /backup-data`

. SE Linux가 활성화된 경우:
+
.. 기존 폴더에 대한 SE Linux 유형을 가져옵니다. `/opt/netapp/data` 접는 사람:
+
`se_type= ls -Z /opt/netapp/data | awk '{print $4}' | awk -F: '{print $3}' | head -1`

+
시스템은 다음과 유사한 확인 메시지를 반환합니다.

+
[listing]
----
echo $se_type
mysqld_db_t
----
.. chcon 명령을 실행하여 백업 디렉토리의 SE Linux 유형을 설정합니다.
+
`chcon -R --type=mysqld_db_t /backup-data`



. 내용을 제거하세요 `/opt/netapp/data` 예배 규칙서:
+
.. `cd /opt/netapp/data`
.. `rm -rf *`


. 크기를 확장하세요 `/opt/netapp/data` LVM 명령을 통해 또는 추가 디스크를 추가하여 디렉토리를 최소 150GB로 늘릴 수 있습니다.
+
[NOTE]
====
당신이 만든 경우 `/opt/netapp/data` 디스크에서 마운트를 시도해서는 안 됩니다. `/opt/netapp/data` NFS 또는 CIFS 공유로.  왜냐하면 이 경우 디스크 공간을 확장하려고 하면 다음과 같은 일부 LVM 명령이 `resize` 그리고 `extend` 예상대로 작동하지 않을 수도 있습니다.

====
. 확인해주세요 `/opt/netapp/data` 디렉토리 소유자(mysql)와 그룹(root)은 변경되지 않습니다.
+
`ls -ltr /opt/netapp/ | grep data`

+
시스템은 다음과 유사한 확인 메시지를 반환합니다.

+
[listing]
----
drwxr-xr-x.  17 mysql root  4096 Aug 28 13:08 data
----
. SE Linux가 활성화된 경우 컨텍스트를 확인하십시오. `/opt/netapp/data` 디렉토리는 여전히 mysqld_db_t로 설정되어 있습니다.
+
.. `touch /opt/netapp/data/abc`
.. `ls -Z /opt/netapp/data/abc`
+
시스템은 다음과 유사한 확인 메시지를 반환합니다.

+
[listing]
----
-rw-r--r--. root root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/abc
----


. 이 외부 파일로 인해 향후 데이터베이스 오류가 발생하지 않도록 abc 파일을 삭제하세요.
. 백업 데이터의 내용을 확장된 파일로 다시 복사합니다. `/opt/netapp/data` 예배 규칙서:
+
`cp -arp /backup-data/* /opt/netapp/data/`

. SE Linux가 활성화된 경우 다음 명령을 실행하세요.
+
`chcon -R --type=mysqld_db_t /opt/netapp/data`

. MySQL 서비스를 시작합니다:
+
`systemctl start mysqld`

. MySQL 서비스가 시작된 후, 표시된 순서대로 ocie 및 ocieau 서비스를 시작합니다.
+
`systemctl start ocie ocieau`

. 모든 서비스가 시작된 후 백업 폴더를 삭제하세요. `/backup-data` :
+
`rm -rf /backup-data`


