---
permalink: config/task_add_users.html 
sidebar: sidebar 
keywords: add, users 
summary: 사용자 페이지를 사용하여 로컬 사용자나 데이터베이스 사용자를 추가할 수 있습니다.  인증 서버에 속한 원격 사용자나 그룹을 추가할 수도 있습니다.  이러한 사용자에게 역할을 할당할 수 있으며, 역할의 권한에 따라 사용자는 Unified Manager를 사용하여 저장소 개체와 데이터를 관리하거나 데이터베이스의 데이터를 볼 수 있습니다. 
---
= 사용자 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용자 페이지를 사용하여 로컬 사용자나 데이터베이스 사용자를 추가할 수 있습니다.  인증 서버에 속한 원격 사용자나 그룹을 추가할 수도 있습니다.  이러한 사용자에게 역할을 할당할 수 있으며, 역할의 권한에 따라 사용자는 Unified Manager를 사용하여 저장소 개체와 데이터를 관리하거나 데이터베이스의 데이터를 볼 수 있습니다.

.시작하기 전에
* 애플리케이션 관리자 역할이 있어야 합니다.
* 원격 사용자 또는 그룹을 추가하려면 원격 인증을 활성화하고 인증 서버를 구성해야 합니다.
* 그래픽 인터페이스에 액세스하는 사용자를 ID 공급자(IdP)가 인증하도록 SAML 인증을 구성하려는 경우 이러한 사용자가 "`원격`" 사용자로 정의되어 있는지 확인하세요.
+
SAML 인증이 활성화된 경우 "`local`" 또는 "`maintenance`" 유형의 사용자는 UI에 액세스할 수 없습니다.



Windows Active Directory에서 그룹을 추가하는 경우 중첩된 하위 그룹이 비활성화되지 않는 한 모든 직접 구성원과 중첩된 하위 그룹이 Unified Manager에 인증할 수 있습니다.  OpenLDAP 또는 다른 인증 서비스에서 그룹을 추가하는 경우 해당 그룹의 직접 구성원만 Unified Manager에 인증할 수 있습니다.

.단계
. 왼쪽 탐색 창에서 *일반* > *사용자*를 클릭합니다.
. 사용자 페이지에서 *추가*를 클릭합니다.
. 사용자 추가 대화 상자에서 추가하려는 사용자 유형을 선택하고 필요한 정보를 입력합니다.
+
필수 사용자 정보를 입력할 때 해당 사용자에게 고유한 이메일 주소를 지정해야 합니다.  여러 사용자가 공유하는 이메일 주소는 지정하지 마세요.

. *추가*를 클릭하세요.

