---
permalink: config/task_enable_remote_logging_of_audit_logs.html 
sidebar: sidebar 
keywords: enable, remote, logging, audit, logs 
summary: 원격 감사 로깅을 활성화하려면 감사 로그 구성 대화 상자에서 원격 로깅 활성화 확인란을 선택할 수 있습니다.  이 기능을 사용하면 감사 로그를 원격 Syslog 서버로 전송할 수 있습니다.  이를 통해 공간 제약이 있을 때에도 감사 로그를 관리할 수 있습니다. 
---
= 감사 로그의 원격 로깅 활성화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
원격 감사 로깅을 활성화하려면 감사 로그 구성 대화 상자에서 *원격 로깅 활성화* 확인란을 선택하세요.  이 기능을 사용하면 감사 로그를 원격 Syslog 서버로 전송할 수 있습니다.  이를 통해 공간 제약이 있을 때에도 감사 로그를 관리할 수 있습니다.

감사 로그의 원격 로깅은 Active IQ Unified Manager 서버의 감사 로그 파일이 변조된 경우 변조 방지 백업을 제공합니다.

.단계
. *감사 로그 구성* 대화 상자에서 *원격 로깅 사용* 확인란을 선택합니다.
+
원격 로깅을 구성하기 위한 추가 필드가 표시됩니다.

. 연결하려는 원격 서버의 *호스트 이름*과 *포트*를 입력하세요.
. *서버 CA 인증서* 필드에서 *찾아보기*를 클릭하여 대상 서버의 공개 인증서를 선택합니다.
+
인증서는 다음에 업로드되어야 합니다. `.pem` 체재.  이 인증서는 대상 Syslog 서버에서 얻어야 하며 만료되어서는 안 됩니다.  인증서에는 선택된 "`호스트 이름`"이 포함되어야 합니다. `SubjectAltName` (SAN) 속성.

. 다음 필드에 값을 입력하세요: *CHARSET*, *CONNECTION TIMEOUT*, *RECONNECTION DELAY*.
+
이러한 필드의 값은 밀리초 단위여야 합니다.

. *FORMAT* 및 *PROTOCOL* 필드에서 필요한 Syslog 형식과 TLS 프로토콜 버전을 선택합니다.
. 대상 Syslog 서버에 인증서 기반 인증이 필요한 경우 *클라이언트 인증 사용* 확인란을 선택합니다.
+
감사 로그 구성을 저장하기 전에 클라이언트 인증 인증서를 다운로드하여 Syslog 서버에 업로드해야 합니다. 그렇지 않으면 연결이 실패합니다.  Syslog 서버 유형에 따라 클라이언트 인증 인증서 해시를 만들어야 할 수도 있습니다.

+
예: syslog-ng는 다음 명령을 사용하여 인증서의 <해시>를 생성해야 합니다. `openssl x509 -noout -hash -in cert.pem` 그런 다음 클라이언트 인증 인증서를 <hash> .0 ...

. *저장*을 클릭하여 서버와의 연결을 구성하고 원격 로깅을 활성화하세요.
+
감사 로그 페이지로 리디렉션됩니다.

+
[NOTE]
====
*연결 시간 초과* 값은 구성에 영향을 줄 수 있습니다.  정의된 값보다 구성에 응답하는 데 시간이 오래 걸리는 경우 연결 오류로 인해 구성이 실패할 수 있습니다.  연결을 성공적으로 설정하려면 *연결 시간 초과* 값을 늘리고 구성을 다시 시도하세요.

====

