---
permalink: config/task_access_maintenance_console.html 
sidebar: sidebar 
keywords: access, maintenance console 
summary: Unified Manager 사용자 인터페이스가 작동하지 않거나 사용자 인터페이스에서 사용할 수 없는 기능을 수행해야 하는 경우 유지 관리 콘솔에 액세스하여 Unified Manager 시스템을 관리할 수 있습니다. 
---
= 유지 관리 콘솔에 액세스하세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager 사용자 인터페이스가 작동하지 않거나 사용자 인터페이스에서 사용할 수 없는 기능을 수행해야 하는 경우 유지 관리 콘솔에 액세스하여 Unified Manager 시스템을 관리할 수 있습니다.

.시작하기 전에
Unified Manager를 설치하고 구성해야 합니다.

15분 동안 아무런 활동이 없으면 유지 관리 콘솔에서 로그아웃됩니다.

[NOTE]
====
VMware에 설치하는 경우 VMware 콘솔을 통해 유지 관리 사용자로 이미 로그인한 경우 Secure Shell을 사용하여 동시에 로그인할 수 없습니다.

====
.단계
. 유지 관리 콘솔에 액세스하려면 다음 단계를 따르세요.
+
[cols="2*"]
|===
| 이 운영체제에서는... | 다음 단계를 따르세요... 


 a| 
VMware
 a| 
.. Secure Shell을 사용하여 Unified Manager 가상 어플라이언스의 IP 주소 또는 정규화된 도메인 이름에 연결합니다.
.. 유지 관리 사용자 이름과 비밀번호를 사용하여 유지 관리 콘솔에 로그인합니다.




 a| 
리눅스
 a| 
.. Secure Shell을 사용하여 Unified Manager 시스템의 IP 주소 또는 정규화된 도메인 이름에 연결합니다.
.. 유지 관리 사용자(umadmin) 이름과 비밀번호로 시스템에 로그인합니다.
.. 명령을 입력하세요 `maintenance_console` 그리고 Enter를 누르세요.




 a| 
Windows
 a| 
.. 관리자 자격 증명을 사용하여 Unified Manager 시스템에 로그인합니다.
.. Windows 관리자 권한으로 PowerShell을 실행합니다.
.. 명령을 입력하세요 `maintenance_console` 그리고 Enter를 누르세요.


|===
+
Unified Manager 유지 관리 콘솔 메뉴가 표시됩니다.


