---
permalink: config/task_generate_an_https_security_certificate_ocf.html 
sidebar: sidebar 
keywords: generate, https, security, certificate 
summary: Active IQ Unified Manager 처음 설치하면 기본 HTTPS 인증서가 설치됩니다.  기존 인증서를 대체하는 새로운 HTTPS 보안 인증서를 생성할 수 있습니다. 
---
= HTTPS 보안 인증서 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager 처음 설치하면 기본 HTTPS 인증서가 설치됩니다.  기존 인증서를 대체하는 새로운 HTTPS 보안 인증서를 생성할 수 있습니다.

.시작하기 전에
애플리케이션 관리자 역할이 있어야 합니다.

DN(고유 이름)에 더 나은 값을 원하거나, 더 큰 키 크기나 더 긴 만료 기간을 원하거나, 현재 인증서가 만료된 경우 등 인증서를 다시 생성하는 데에는 여러 가지 이유가 있을 수 있습니다.

Unified Manager 웹 UI에 액세스할 수 없는 경우 유지 관리 콘솔을 사용하여 동일한 값으로 HTTPS 인증서를 다시 생성할 수 있습니다.  인증서를 재생성하는 동안 키 크기와 키 유효 기간을 정의할 수 있습니다.  당신이 사용하는 경우 `Reset Server Certificate` 유지 관리 콘솔에서 옵션을 선택하면 397일 동안 유효한 새로운 HTTPS 인증서가 생성됩니다.  이 인증서에는 2048비트 크기의 RSA 키가 있습니다.

.단계
. 왼쪽 탐색 창에서 *일반* > *HTTPS 인증서*를 클릭합니다.
. *HTTPS 인증서 재생성*을 클릭합니다.
+
HTTPS 인증서 재생성 대화 상자가 표시됩니다.

. 인증서를 생성하려는 방법에 따라 다음 옵션 중 하나를 선택하세요.
+
[cols="2*"]
|===
| 만약 당신이 원한다면... | 이렇게 하세요... 


 a| 
현재 값으로 인증서를 다시 생성합니다.
 a| 
*현재 인증서 속성을 사용하여 다시 생성* 옵션을 클릭합니다.



 a| 
다른 값을 사용하여 인증서 생성
 a| 
*현재 인증서 속성 업데이트* 옵션을 클릭합니다.

새 값을 입력하지 않으면 일반 이름 및 대체 이름 필드는 기존 인증서의 값을 사용합니다.  ``일반 이름``은 호스트의 FQDN으로 설정해야 합니다.  다른 필드에는 값이 필요하지 않지만, 인증서에 값을 채우려는 경우 이메일, 회사, 부서, 도시, 주, 국가 등의 값을 입력할 수 있습니다.  사용 가능한 키 크기(키 알고리즘은 "`RSA`")와 유효 기간 중에서 선택할 수도 있습니다.

[NOTE]
====
** 키 크기에 허용되는 값은 다음과 같습니다. `2048` , `3072` 그리고 `4096` .
** 유효기간은 최소 1일부터 최대 36,500일까지입니다.
+
유효기간은 36,500일이 허용되지만, 397일 또는 13개월을 넘지 않는 유효기간을 사용하는 것이 좋습니다.  유효 기간을 397일 이상으로 선택하고 이 인증서에 대한 CSR을 내보내고 잘 알려진 CA에서 서명을 받으려고 하는 경우, CA에서 반환한 서명된 인증서의 유효 기간은 397일로 줄어듭니다.

** 인증서의 대체 이름 필드에서 로컬 식별 정보를 제거하려면 "로컬 식별 정보 제외(예: 로컬호스트)" 확인란을 선택할 수 있습니다.  이 확인란을 선택하면 필드에 입력한 내용만 대체 이름 필드에 사용됩니다.  이 필드를 비워 두면 인증서에 대체 이름 필드가 전혀 없습니다.


====
|===
. *예*를 클릭하여 인증서를 다시 생성합니다.
. 새 인증서가 적용되도록 Unified Manager 서버를 다시 시작합니다.
. HTTPS 인증서를 확인하여 새로운 인증서 정보를 확인하세요.

