---
permalink: config/task_set_up_authentication_services.html 
sidebar: sidebar 
keywords: set up, authentication, services 
summary: '인증 서비스를 사용하면 Unified Manager에 대한 액세스 권한을 제공하기 전에 인증 서버에서 원격 사용자 또는 원격 그룹을 인증할 수 있습니다.  사전 정의된 인증 서비스(Active Directory 또는 OpenLDAP 등)를 사용하거나 고유한 인증 메커니즘을 구성하여 사용자를 인증할 수 있습니다.' 
---
= 인증 서비스 설정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
인증 서비스를 사용하면 Unified Manager에 대한 액세스 권한을 제공하기 전에 인증 서버에서 원격 사용자 또는 원격 그룹을 인증할 수 있습니다.  사전 정의된 인증 서비스(Active Directory 또는 OpenLDAP 등)를 사용하거나 고유한 인증 메커니즘을 구성하여 사용자를 인증할 수 있습니다.

.시작하기 전에
* 원격 인증을 활성화해야 합니다.
* 애플리케이션 관리자 역할이 있어야 합니다.


.단계
. 왼쪽 탐색 창에서 *일반* > *원격 인증*을 클릭합니다.
. 다음 인증 서비스 중 하나를 선택하세요.
+
[cols="2*"]
|===
| ...을 선택하면 | 그러면 이렇게 하세요... 


 a| 
액티브 디렉토리
 a| 
.. 관리자 이름과 비밀번호를 입력하세요.
.. 인증 서버의 기본 고유 이름을 지정합니다.
+
예를 들어, 인증 서버의 도메인 이름이 +ou@domain.com+이면 기본 고유 이름은 *cn=ou,dc=domain,dc=com*입니다.





 a| 
오픈LDAP
 a| 
.. 바인드 고유 이름과 바인드 비밀번호를 입력하세요.
.. 인증 서버의 기본 고유 이름을 지정합니다.
+
예를 들어, 인증 서버의 도메인 이름이 +ou@domain.com+이면 기본 고유 이름은 *cn=ou,dc=domain,dc=com*입니다.





 a| 
기타
 a| 
.. 바인드 고유 이름과 바인드 비밀번호를 입력하세요.
.. 인증 서버의 기본 고유 이름을 지정합니다.
+
예를 들어, 인증 서버의 도메인 이름이 +ou@domain.com+이면 기본 고유 이름은 *cn=ou,dc=domain,dc=com*입니다.

.. 인증 서버에서 지원하는 LDAP 프로토콜 버전을 지정합니다.
.. 사용자 이름, 그룹 멤버십, 사용자 그룹 및 멤버 속성을 입력합니다.


|===
+
[NOTE]
====
인증 서비스를 수정하려면 기존 인증 서버를 삭제한 다음 새 인증 서버를 추가해야 합니다.

====
. *저장*을 클릭하세요.

