---
permalink: config/task_add_clusters.html 
sidebar: sidebar 
keywords: add cluster 
summary: 클러스터를 모니터링할 수 있도록 Active IQ Unified Manager 에 클러스터를 추가할 수 있습니다.  여기에는 클러스터의 상태, 용량, 성능, 구성 등의 클러스터 정보를 얻는 기능이 포함되어 있어 발생할 수 있는 문제를 찾아 해결할 수 있습니다. 
---
= 클러스터 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터를 모니터링할 수 있도록 Active IQ Unified Manager 에 클러스터를 추가할 수 있습니다.  여기에는 클러스터의 상태, 용량, 성능, 구성 등의 클러스터 정보를 얻는 기능이 포함되어 있어 발생할 수 있는 문제를 찾아 해결할 수 있습니다.

.시작하기 전에
* 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 다음 정보가 필요합니다.
+
** Unified Manager는 온프레미스 ONTAP 클러스터, ONTAP Select, Cloud Volumes ONTAP 지원합니다.
** 호스트 이름 또는 클러스터 관리 IP 주소
+
호스트 이름은 Unified Manager가 클러스터에 연결하는 데 사용하는 FQDN 또는 약어입니다.  호스트 이름은 클러스터 관리 IP 주소로 확인되어야 합니다.

+
클러스터 관리 IP 주소는 관리 스토리지 가상 머신(SVM)의 클러스터 관리 LIF여야 합니다.  노드 관리 LIF를 사용하면 작업이 실패합니다.

** 클러스터는 ONTAP 버전 9.1 이상 소프트웨어를 실행해야 합니다.
** ONTAP 관리자 사용자 이름 및 비밀번호
+
이 계정에는 _admin_ 역할이 있어야 하며 애플리케이션 액세스 권한이 _ontapi_, _console_, _http_로 설정되어 있어야 합니다.

** HTTPS 프로토콜을 사용하여 클러스터에 연결할 포트 번호(일반적으로 포트 443)
** 귀하에게 필요한 인증서가 있습니다.
+
*SSL(HTTPS) 인증서*: 이 인증서는 Unified Manager의 소유입니다.  Unified Manager를 새로 설치하면 기본 자체 서명 SSL(HTTPS) 인증서가 생성됩니다.  NetApp 보안을 강화하기 위해 CA 서명 인증서로 업그레이드할 것을 권장합니다.  서버 인증서가 만료된 경우 인증서를 다시 생성하고 Unified Manager를 다시 시작하여 서비스에 새 인증서를 적용해야 합니다.  SSL 인증서 재생성에 대한 자세한 내용은 다음을 참조하세요.link:../config/task_generate_an_https_security_certificate_ocf.html["HTTPS 보안 인증서 생성"] .

+
*EMS 인증서*: 이 인증서는 Unified Manager의 소유입니다.  ONTAP 에서 수신한 EMS 알림에 대한 인증 과정에서 사용됩니다.

+
*상호 TLS 통신을 위한 인증서*: Unified Manager와 ONTAP 간 상호 TLS 통신 중에 사용됩니다.  인증서 기반 인증은 ONTAP 버전을 기반으로 클러스터에 대해 활성화됩니다.  ONTAP 버전을 실행하는 클러스터가 9.5보다 낮은 경우 인증서 기반 인증이 활성화되지 않습니다.

+
Unified Manager의 이전 버전을 업데이트하는 경우, 클러스터에 대해 인증서 기반 인증이 자동으로 활성화되지 않습니다.  하지만 클러스터 세부 정보를 수정하고 저장하면 해당 기능을 활성화할 수 있습니다.  인증서가 만료된 경우 새 인증서를 통합하기 위해 인증서를 다시 생성해야 합니다.  인증서 보기 및 재생성에 대한 자세한 내용은 다음을 참조하세요.link:../storage-mgmt/task_edit_clusters.html["클러스터 편집"] .

+
[NOTE]
====
*** 웹 UI에서 클러스터를 추가할 수 있으며, 인증서 기반 인증이 자동으로 활성화됩니다.
*** Unified Manager CLI를 통해 클러스터를 추가할 수 있으며, 인증서 기반 인증은 기본적으로 활성화되어 있지 않습니다.  Unified Manager CLI를 사용하여 클러스터를 추가하는 경우 Unified Manager UI를 사용하여 클러스터를 편집해야 합니다.  당신은 볼 수 있습니다link:https://docs.netapp.com/us-en/active-iq-unified-manager/events/reference_supported_unified_manager_cli_commands.html["지원되는 Unified Manager CLI 명령"] Unified Manager CLI를 사용하여 클러스터를 추가합니다.
*** 클러스터에 대해 인증서 기반 인증이 활성화되어 있고 서버에서 Unified Manager 백업을 가져와 호스트 이름이나 IP 주소가 변경된 다른 Unified Manager 서버로 복원하는 경우 클러스터 모니터링이 실패할 수 있습니다.  실패를 방지하려면 클러스터 세부 정보를 편집하고 저장하세요.  클러스터 세부 정보 편집에 대한 자세한 내용은 다음을 참조하세요.link:../storage-mgmt/task_edit_clusters.html["클러스터 편집"] .


====
+
*클러스터 인증서*: 이 인증서는 ONTAP 의 소유입니다.  만료된 인증서로는 Unified Manager에 클러스터를 추가할 수 없습니다. 인증서가 이미 만료된 경우 클러스터를 추가하기 전에 인증서를 다시 생성해야 합니다.  인증서 생성에 대한 정보는 지식 기반(KB) 문서를 참조하세요. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_renew_an_SSL_certificate_in_ONTAP_9["System Manager 사용자 인터페이스에서 ONTAP 자체 서명 인증서를 갱신하는 방법"^] .



* Unified Manager 서버에 충분한 공간이 있어야 합니다.  데이터베이스 디렉터리의 공간이 90% 이상 사용된 경우 서버에 클러스터를 추가할 수 없습니다.


MetroCluster 구성의 경우 로컬 클러스터와 원격 클러스터를 모두 추가해야 하며, 클러스터를 올바르게 구성해야 합니다.

.단계
. 왼쪽 탐색 창에서 *저장소 관리* > *클러스터 설정*을 클릭합니다.
. 클러스터 설정 페이지에서 *추가*를 클릭합니다.
. 클러스터 추가 대화 상자에서 클러스터의 호스트 이름이나 IP 주소, 사용자 이름, 비밀번호, 포트 번호 등 필요한 값을 지정합니다.
+
클러스터 관리 IP 주소를 IPv6에서 IPv4로 또는 IPv4에서 IPv6로 변경할 수 있습니다.  다음 모니터링 주기가 완료된 후 새로운 IP 주소가 클러스터 그리드와 클러스터 구성 페이지에 반영됩니다.

. *제출*을 클릭하세요.
. 호스트 승인 대화 상자에서 *인증서 보기*를 클릭하여 클러스터에 대한 인증서 정보를 확인합니다.
. *예*를 클릭하세요.
+
클러스터 세부 정보를 저장한 후 클러스터의 상호 TLS 통신에 대한 인증서를 볼 수 있습니다.

+
인증서 기반 인증이 활성화되어 있지 않으면 Unified Manager는 클러스터가 처음 추가될 때만 인증서를 확인합니다.  Unified Manager는 ONTAP 에 대한 각 API 호출에 대한 인증서를 확인하지 않습니다.



새 클러스터의 모든 개체가 검색된 후 Unified Manager는 지난 15일 동안의 과거 성능 데이터를 수집하기 시작합니다.  이러한 통계는 데이터 연속성 수집 기능을 사용하여 수집됩니다.  이 기능을 사용하면 클러스터가 추가된 직후부터 2주 이상에 걸친 성능 정보를 바로 확인할 수 있습니다.  데이터 연속성 수집 주기가 완료되면 기본적으로 5분마다 실시간 클러스터 성능 데이터가 수집됩니다.

[NOTE]
====
15일간의 성능 데이터를 수집하는 데 CPU가 많이 사용되므로, 너무 많은 클러스터에서 동시에 데이터 연속성 수집 폴링이 실행되지 않도록 새 클러스터를 추가하는 작업을 단계적으로 수행하는 것이 좋습니다.  또한 데이터 연속성 수집 기간 동안 Unified Manager를 다시 시작하면 수집이 중단되고 누락된 기간의 성능 차트에 간격이 표시됩니다.

====
[TIP]
====
클러스터를 추가할 수 없다는 오류 메시지가 나타나면 두 시스템의 시계가 동기화되지 않았는지, Unified Manager HTTPS 인증서 시작 날짜가 클러스터의 날짜보다 이후인지 확인하세요.  NTP나 유사한 서비스를 사용하여 시계가 동기화되었는지 확인해야 합니다.

====
*관련 정보*

link:../config/task_install_ca_signed_and_returned_https_certificate.html#example-certificate-chain["CA 서명 및 반환된 HTTPS 인증서 설치"]
