---
permalink: config/task_change_ports_um_uses_for_http_and_https_protocols.html 
sidebar: sidebar 
keywords: change, ports, unified manager, uses, http, https, protocols 
summary: Unified Manager가 HTTP 및 HTTPS 프로토콜에 사용하는 기본 포트는 보안을 위해 필요한 경우 설치 후 변경할 수 있습니다.  HTTP의 기본 포트는 80이고 HTTPS의 기본 포트는 443입니다. 
---
= Unified Manager가 HTTP 및 HTTPS 프로토콜에 사용하는 포트를 변경합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager가 HTTP 및 HTTPS 프로토콜에 사용하는 기본 포트는 보안을 위해 필요한 경우 설치 후 변경할 수 있습니다.  HTTP의 기본 포트는 80이고 HTTPS의 기본 포트는 443입니다.

.시작하기 전에
Unified Manager 서버의 유지 관리 콘솔에 로그인하려면 권한이 있는 사용자 ID와 비밀번호가 있어야 합니다.

[NOTE]
====
Mozilla Firefox나 Google Chrome 브라우저를 사용할 때 안전하지 않은 것으로 간주되는 포트가 몇 가지 있습니다.  HTTP 및 HTTPS 트래픽에 대한 새로운 포트 번호를 할당하기 전에 브라우저를 확인하세요.  안전하지 않은 포트를 선택하면 시스템에 접근할 수 없게 되므로 해결을 위해 고객 지원에 문의해야 합니다.

====
포트를 변경하면 Unified Manager 인스턴스가 자동으로 다시 시작되므로 이때 잠시 시스템을 종료하는 것이 좋습니다.

. SSH를 사용하여 Unified Manager 호스트에 유지 관리 사용자로 로그인합니다.
+
Unified Manager 유지 관리 콘솔 프롬프트가 표시됩니다.

. *애플리케이션 포트 보기/변경*이라고 표시된 메뉴 옵션의 번호를 입력한 다음 Enter를 누릅니다.
. 메시지가 표시되면 유지 관리 사용자 비밀번호를 다시 입력하세요.
. HTTP 및 HTTPS 포트에 대한 새 포트 번호를 입력한 다음 Enter를 누릅니다.
+
포트 번호를 비워 두면 프로토콜의 기본 포트가 할당됩니다.

+
포트를 변경하고 지금 Unified Manager를 다시 시작할지 묻는 메시지가 표시됩니다.

. *y*를 입력하여 포트를 변경하고 Unified Manager를 다시 시작합니다.
. 유지 관리 콘솔을 종료합니다.


이 변경 후 사용자는 Unified Manager 웹 UI에 액세스하기 위해 URL에 새 포트 번호를 포함해야 합니다(예: https://host.company.com:1234+ , https://12.13.14.15:1122+ 또는 https://[2001:db8:0:1]:2123+).
