---
permalink: config/task_install_ca_signed_and_returned_https_certificate.html 
sidebar: sidebar 
keywords: install, ca signed, returned, https, certificate 
summary: 인증 기관에서 서명하고 반환한 후에 보안 인증서를 업로드하고 설치할 수 있습니다.  업로드하고 설치하는 파일은 기존 자체 서명 인증서의 서명된 버전이어야 합니다.  CA 서명 인증서는 중간자 공격을 방지하는 데 도움이 되며 자체 서명 인증서보다 더 나은 보안을 제공합니다. 
---
= CA 서명 및 반환된 HTTPS 인증서 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
인증 기관에서 서명하고 반환한 후에 보안 인증서를 업로드하고 설치할 수 있습니다.  업로드하고 설치하는 파일은 기존 자체 서명 인증서의 서명된 버전이어야 합니다.  CA 서명 인증서는 중간자 공격을 방지하는 데 도움이 되며 자체 서명 인증서보다 더 나은 보안을 제공합니다.

*무엇을 시작하기 전에

다음 작업을 완료했어야 합니다.

* 인증서 서명 요청 파일을 다운로드하고 인증 기관에서 서명을 받았습니다.
* PEM 형식으로 인증서 체인을 저장했습니다.
* Unified Manager 서버 인증서부터 루트 서명 인증서까지 체인의 모든 인증서가 포함되었으며 현재 존재하는 모든 중간 인증서도 포함됩니다.


애플리케이션 관리자 역할이 있어야 합니다.

[NOTE]
====
CSR이 생성된 인증서의 유효 기간이 397일을 초과하는 경우 CA는 인증서에 서명하고 반환하기 전에 유효 기간을 397일로 줄입니다.

====
.단계
. 왼쪽 탐색 창에서 *일반* > *HTTPS 인증서*를 클릭합니다.
. *HTTPS 인증서 설치*를 클릭합니다.
. 표시되는 대화 상자에서 *파일 선택...*을 클릭하여 업로드할 파일을 찾습니다.
. 파일을 선택한 후 *설치*를 클릭하여 파일을 설치합니다.
+
자세한 내용은 다음을 참조하세요.link:concept_install_https_certificate_generated_using_external_tools.html["외부 도구를 사용하여 생성된 HTTPS 인증서 설치"] .





== 인증서 체인 예시

다음 예에서는 인증서 체인 파일이 어떻게 나타나는지 보여줍니다.

[listing]
----
-----BEGIN CERTIFICATE-----
<*Server certificate*>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<*Intermediate certificate \#1 (if present)*>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<*Intermediate certificate \#2 (if present)*>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<*Root signing certificate*>
-----END CERTIFICATE-----
----