---
permalink: config/task_change_um_host_name_on_rhel.html 
sidebar: sidebar 
keywords: change, unified manager, host name, linux systems 
summary: 어느 시점에서 Unified Manager를 설치한 Red Hat Enterprise Linux 시스템의 호스트 이름을 변경하고 싶을 수도 있습니다.  예를 들어, Linux 컴퓨터를 나열할 때 Unified Manager 서버를 유형, 작업 그룹 또는 모니터링되는 클러스터 그룹별로 더 쉽게 식별할 수 있도록 호스트 이름을 바꿀 수 있습니다. 
---
= Linux 시스템에서 Unified Manager 호스트 이름 변경
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
어느 시점에서 Unified Manager를 설치한 Red Hat Enterprise Linux 시스템의 호스트 이름을 변경하고 싶을 수도 있습니다.  예를 들어, Linux 컴퓨터를 나열할 때 Unified Manager 서버를 유형, 작업 그룹 또는 모니터링되는 클러스터 그룹별로 더 쉽게 식별할 수 있도록 호스트 이름을 바꿀 수 있습니다.

.시작하기 전에
Unified Manager가 설치된 Linux 시스템에 루트 사용자 액세스 권한이 있어야 합니다.

호스트 이름(또는 호스트 IP 주소)을 사용하여 Unified Manager 웹 UI에 액세스할 수 있습니다.  배포 중에 네트워크에 대한 정적 IP 주소를 구성한 경우 네트워크 호스트에 대한 이름을 지정했을 것입니다.  DHCP를 사용하여 네트워크를 구성한 경우 호스트 이름은 DNS 서버에서 가져와야 합니다.

호스트 이름이 어떻게 할당되었는지에 관계없이 호스트 이름을 변경하고 새 호스트 이름을 사용하여 Unified Manager 웹 UI에 액세스하려는 경우 새 보안 인증서를 생성해야 합니다.

호스트 이름 대신 서버의 IP 주소를 사용하여 웹 UI에 액세스하는 경우 호스트 이름을 변경해도 새 인증서를 생성할 필요가 없습니다.  하지만 인증서를 업데이트하여 인증서의 호스트 이름이 실제 호스트 이름과 일치하도록 하는 것이 가장 좋은 방법입니다.  새로운 인증서는 Linux 컴퓨터를 다시 시작할 때까지 적용되지 않습니다.

Unified Manager에서 호스트 이름을 변경하는 경우 OnCommand Workflow Automation (WFA)에서 호스트 이름을 수동으로 업데이트해야 합니다.  WFA에서는 호스트 이름이 자동으로 업데이트되지 않습니다.

.단계
. 수정하려는 Unified Manager 시스템에 루트 사용자로 로그인합니다.
. 다음 명령을 입력하여 Unified Manager 소프트웨어와 관련 MySQL 소프트웨어를 중지합니다.
+
`systemctl stop ocieau ocie mysqld`

. Linux를 사용하여 호스트 이름 변경 `hostnamectl` 명령:
+
`hostnamectl set-hostname new_FQDN`

+
`hostnamectl set-hostname nuhost.corp.widget.com`

. 서버에 대한 HTTPS 인증서를 다시 생성합니다.
+
`/opt/netapp/essentials/bin/cert.sh create`

. 네트워크 서비스를 다시 시작합니다.
+
`systemctl restart NetworkManager.service`

. 서비스를 다시 시작한 후 새 호스트 이름이 자기 자신을 ping할 수 있는지 확인하세요.
+
`ping new_hostname`

+
`ping nuhost`

+
이 명령은 원래 호스트 이름에 대해 이전에 설정된 것과 동일한 IP 주소를 반환해야 합니다.

. 호스트 이름 변경을 완료하고 확인한 후 다음 명령을 입력하여 Unified Manager를 다시 시작합니다.
+
`systemctl start mysqld ocie ocieau`


