---
permalink: config/task_enable_remote_authentication.html 
sidebar: sidebar 
keywords: enable, remote, authentication 
summary: Unified Manager 서버가 인증 서버와 통신할 수 있도록 원격 인증을 활성화할 수 있습니다.  인증 서버 사용자는 Unified Manager 그래픽 인터페이스에 액세스하여 저장소 개체와 데이터를 관리할 수 있습니다. 
---
= 원격 인증 활성화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager 서버가 인증 서버와 통신할 수 있도록 원격 인증을 활성화할 수 있습니다.  인증 서버 사용자는 Unified Manager 그래픽 인터페이스에 액세스하여 저장소 개체와 데이터를 관리할 수 있습니다.

.시작하기 전에
애플리케이션 관리자 역할이 있어야 합니다.

[NOTE]
====
Unified Manager 서버는 인증 서버에 직접 연결되어야 합니다.  SSSD(시스템 보안 서비스 데몬) 또는 NSLCD(이름 서비스 LDAP 캐싱 데몬)와 같은 로컬 LDAP 클라이언트를 비활성화해야 합니다.

====
Open LDAP 또는 Active Directory를 사용하여 원격 인증을 활성화할 수 있습니다.  원격 인증이 비활성화된 경우 원격 사용자는 Unified Manager에 액세스할 수 없습니다.

원격 인증은 LDAP 및 LDAPS(보안 LDAP)를 통해 지원됩니다.  Unified Manager는 보안되지 않은 통신의 경우 기본 포트로 389를 사용하고, 보안된 통신의 경우 기본 포트로 636을 사용합니다.

[NOTE]
====
사용자를 인증하는 데 사용되는 인증서는 X.509 형식을 준수해야 합니다.

====
.단계
. 왼쪽 탐색 창에서 *일반* > *원격 인증*을 클릭합니다.
. *원격 인증 사용...* 상자를 체크하세요.
. 인증 서비스 필드에서 서비스 유형을 선택하고 인증 서비스를 구성합니다.
+
[cols="2*"]
|===
| 인증 유형의 경우... | 다음 정보를 입력하세요... 


 a| 
액티브 디렉토리
 a| 
** 다음 형식 중 하나로 된 인증 서버 관리자 이름:
+
*** `domainname\username`
*** `username@domainname`
*** `Bind Distinguished Name`(적절한 LDAP 표기법 사용)


** 관리자 비밀번호
** 기본 고유 이름(적절한 LDAP 표기법 사용)




 a| 
LDAP를 엽니다
 a| 
** 적절한 LDAP 표기법으로 고유 이름을 바인딩합니다.
** 비밀번호 바인딩
** 기본 고유 이름


|===
+
Active Directory 사용자 인증에 시간이 오래 걸리거나 시간 초과가 발생하는 경우, 인증 서버에서 응답하는 데 시간이 오래 걸리는 것일 수 있습니다.  Unified Manager에서 중첩 그룹에 대한 지원을 비활성화하면 인증 시간이 줄어들 수 있습니다.

+
인증 서버에 대해 보안 연결 사용 옵션을 선택하면 Unified Manager는 SSL(Secure Sockets Layer) 프로토콜을 사용하여 인증 서버와 통신합니다.

. *선택 사항:* 인증 서버를 추가하고 인증을 테스트합니다.
. *저장*을 클릭하세요.

