---
permalink: config/task_enable_saml_authentication_um.html 
sidebar: sidebar 
keywords: enable, saml, authentication 
summary: '원격 사용자가 Unified Manager 웹 UI에 액세스하기 전에 보안 ID 공급자(IdP)를 통해 인증을 받을 수 있도록 SAML(Security Assertion Markup Language) 인증을 활성화할 수 있습니다.' 
---
= SAML 인증 활성화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
원격 사용자가 Unified Manager 웹 UI에 액세스하기 전에 보안 ID 공급자(IdP)를 통해 인증을 받을 수 있도록 SAML(Security Assertion Markup Language) 인증을 활성화할 수 있습니다.

.시작하기 전에
* 원격 인증을 구성하고 성공했는지 확인해야 합니다.
* 애플리케이션 관리자 역할이 있는 원격 사용자 또는 원격 그룹을 하나 이상 만들어야 합니다.
* ID 공급자(IdP)는 Unified Manager에서 지원되어야 하며 구성되어야 합니다.
* IdP URL과 메타데이터가 있어야 합니다.
* IdP 서버에 액세스할 수 있어야 합니다.


Unified Manager에서 SAML 인증을 활성화한 후에는 IdP가 Unified Manager 서버 호스트 정보로 구성될 때까지 사용자는 그래픽 사용자 인터페이스에 액세스할 수 없습니다.  따라서 구성 과정을 시작하기 전에 연결의 두 부분을 모두 완료할 준비가 되어 있어야 합니다.  IdP는 Unified Manager를 구성하기 전이나 후에 구성할 수 있습니다.

SAML 인증이 활성화된 후에는 원격 사용자만 Unified Manager 그래픽 사용자 인터페이스에 액세스할 수 있습니다.  로컬 사용자와 유지 관리 사용자는 UI에 액세스할 수 없습니다.  이 구성은 유지 관리 콘솔, Unified Manager 명령 또는 ZAPI에 액세스하는 사용자에게 영향을 미치지 않습니다.

[NOTE]
====
이 페이지에서 SAML 구성을 완료하면 Unified Manager가 자동으로 다시 시작됩니다.

====
.단계
. 왼쪽 탐색 창에서 *일반* > *SAML 인증*을 클릭합니다.
. *SAML 인증 사용* 확인란을 선택합니다.
+
IdP 연결을 구성하는 데 필요한 필드가 표시됩니다.

. Unified Manager 서버를 IdP 서버에 연결하는 데 필요한 IdP URI와 IdP 메타데이터를 입력합니다.
+
Unified Manager 서버에서 IdP 서버에 직접 액세스할 수 있는 경우 IdP URI를 입력한 후 *IdP 메타데이터 가져오기* 버튼을 클릭하면 IdP 메타데이터 필드가 자동으로 채워집니다.

. Unified Manager 호스트 메타데이터 URI를 복사하거나 호스트 메타데이터를 XML 텍스트 파일에 저장합니다.
+
이때 이 정보를 사용하여 IdP 서버를 구성할 수 있습니다.

. *저장*을 클릭하세요.
+
구성을 완료하고 Unified Manager를 다시 시작할 것인지 확인하는 메시지 상자가 표시됩니다.

. *확인 및 로그아웃*을 클릭하면 Unified Manager가 다시 시작됩니다.


다음에 권한이 있는 원격 사용자가 Unified Manager 그래픽 인터페이스에 액세스하려고 하면 Unified Manager 로그인 페이지 대신 IdP 로그인 페이지에 자격 증명을 입력하게 됩니다.

아직 완료되지 않았다면 IdP에 액세스하여 Unified Manager 서버 URI와 메타데이터를 입력하여 구성을 완료하세요.

[NOTE]
====
ADFS를 ID 공급자로 사용하는 경우 Unified Manager GUI는 ADFS 시간 초과를 준수하지 않으며 Unified Manager 세션 시간 초과에 도달할 때까지 계속 작동합니다.  *일반* > *기능 설정* > *비활성 시간 초과*를 클릭하면 GUI 세션 시간 초과를 변경할 수 있습니다.

====