---
permalink: config/task_configure_unified_manager_to_send_alert_notifications.html 
sidebar: sidebar 
keywords: configure, unified manager, send, alert, notifications 
summary: Unified Manager를 구성하여 사용자 환경에서 발생하는 이벤트에 대한 알림을 보낼 수 있습니다.  알림을 보내려면 먼저 여러 가지 Unified Manager 옵션을 구성해야 합니다. 
---
= Unified Manager를 구성하여 알림 알림을 보냅니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 구성하여 사용자 환경에서 발생하는 이벤트에 대한 알림을 보낼 수 있습니다.  알림을 보내려면 먼저 여러 가지 Unified Manager 옵션을 구성해야 합니다.

.시작하기 전에
애플리케이션 관리자 역할이 있어야 합니다.

Unified Manager를 배포하고 초기 구성을 완료한 후에는 이벤트 수신에 따라 경고를 트리거하고 알림 이메일이나 SNMP 트랩을 생성하도록 환경을 구성하는 것을 고려해야 합니다.

.단계
. link:task_configure_event_notification_settings.html["이벤트 알림 설정 구성"].
+
사용자 환경에서 특정 이벤트가 발생할 때 경고 알림을 보내려면 SMTP 서버를 구성하고 경고 알림을 보낼 이메일 주소를 제공해야 합니다.  SNMP 트랩을 사용하려면 해당 옵션을 선택하고 필요한 정보를 제공하면 됩니다.

. link:task_enable_remote_authentication.html["원격 인증 활성화"].
+
원격 LDAP 또는 Active Directory 사용자가 Unified Manager 인스턴스에 액세스하여 알림을 받을 수 있도록 하려면 원격 인증을 활성화해야 합니다.

. link:task_add_authentication_servers.html["인증 서버 추가"].
+
인증 서버를 추가하면 인증 서버 내의 원격 사용자가 Unified Manager에 액세스할 수 있습니다.

. link:task_add_users.html["사용자 추가"].
+
여러 유형의 로컬 또는 원격 사용자를 추가하고 특정 역할을 할당할 수 있습니다.  알림을 만들 때 알림을 받을 사용자를 지정합니다.

. link:task_add_alerts.html["알림 추가"].
+
알림을 보낼 이메일 주소를 추가하고, 알림을 받을 사용자를 추가하고, 네트워크 설정을 구성하고, 환경에 필요한 SMTP 및 SNMP 옵션을 구성한 후에 알림을 할당할 수 있습니다.


