---
permalink: install-linux/qsg-linux.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, Linux QSG, RHEL QSG, quick installation 
summary: Linux 플랫폼에서 Unified Manager를 사용하기 위한 빠른 시작 가이드입니다. 
---
= Linux 설치를 위한 빠른 시작 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
설치 패키지를 다운로드하여 물리적 또는 가상 Red Hat Enterprise Linux 플랫폼에 Unified Manager를 설치할 수 있습니다.



[[system-requirements]]
== 시스템 요구 사항

* 운영 체제: x86_64 아키텍처를 기반으로 하는 Red Hat Enterprise Linux 버전 8.x 및 9.4, OS 설치 프로그램의 *소프트웨어 선택* 옵션에서 "GUI가 있는 서버" 기반 환경을 사용하여 설치됨
* RAM: 12GB, CPU: 총 9572MHz
* 여유 디스크 공간: 100GB의 디스크 공간 `/opt/netapp/data` 디렉토리, 루트 파티션에 50GB.  별도로 장착 `/opt` 그리고 `/var/log` 디렉토리를 확인하십시오 `/opt` 15GB가 있습니다 `/var/log` 16GB가 있고 `/tmp` 10GB의 여유 공간이 있습니다.


보안 사이트에 제품을 설치하는 방법에 대한 자세한 시스템 요구 사항과 정보는 다음을 참조하세요.link:../install-linux/concept_requirements_for_install_unified_manager.html["Unified Manager 설치 요구 사항"] 그리고link:http://mysupport.netapp.com/matrix["상호 운용성 매트릭스"] .



[[install-active-iq-unified-manager]]
== Active IQ Unified Manager 설치



[[download-the-installer]]
=== 설치 프로그램을 다운로드하세요

. 다운로드 `ActiveIQUnifiedManager-<version>.zip` 코드 서명 인증서와 함께 제공되는 설치 패키지(`.pem` ) 및 디지털 서명(`.sig` ) .
. 설치 파일을 다운로드한 디렉토리에서 다음을 실행하세요.
+
`# unzip ActiveIQUnifiedManager-<version>.zip`





[[verify-integrity]]
=== 무결성 확인

다음 명령을 실행하여 설치 프로그램 패키지의 무결성을 확인하세요.

* 달리다 `openssl x509 -pubkey -noout -in AIQUM-RHEL-CLIENT-INTER-ROOT.pem > <public_key_file_name>` 코드 서명 인증서의 공개 키로 파일을 생성합니다.
* 달리다 `openssl dgst -sha256 -verify <public_key_file_name> -signature <signature_file_name> ActiveIQUnifiedManager-<version>.zip` 설치 프로그램 패키지의 서명을 확인하세요.




[[verify-repository-configuration]]
=== 저장소 구성 확인

Red Hat Enterprise Linux 저장소를 구성하는 절차는 사이트마다 다릅니다.  당신은 사용할 수 있습니다 `pre_install_check.sh` 설치 패키지에 포함된 스크립트를 사용하여 운영 체제의 구성을 확인합니다.  시스템이 인터넷에 연결되어 있으면 Red Hat Enterprise Linux 저장소를 설정하기 위한 지침이 자동으로 전송됩니다.

`# sudo ./pre_install_check.sh`



[[install-unified-manager]]
=== Unified Manager 설치

Unified Manager는 다음을 사용합니다. `yum` 소프트웨어와 그에 종속된 소프트웨어를 설치하는 유틸리티입니다.  Red Hat Enterprise Linux의 이미지가 다양하기 때문에 설치되는 패키지는 이미지에 있는 소프트웨어에 따라 달라집니다.  그만큼 `yum` 유틸리티는 설치를 위한 종속 소프트웨어 패키지를 결정합니다.  종속 소프트웨어 패키지에 대한 자세한 정보가 필요한 경우 다음을 참조하세요.link:../install-linux/reference_red_hat_software_and_installation_requirements.html["Linux 소프트웨어 및 설치 요구 사항"] .

Unified Manager를 설치하려면 루트 사용자로 또는 다음을 사용하여 다음 명령을 실행하세요. `sudo` 설치 파일이 압축 해제된 디렉토리에서:

`# yum install netapp-um<version>.x86_64.rpm`

또는

`% sudo yum install netapp-um<version>.x86_64.rpm`

설치가 끝나면 Unified Manager 웹 UI에 연결하기 위한 정보가 표시됩니다.  웹 UI에 접속이 불가능한 경우 다음을 참조하세요. `README` 포트 443 제한에 대한 자세한 내용은 소프트웨어와 함께 제공되는 파일을 참조하세요.
