---
permalink: install-linux/reference_red_hat_software_and_installation_requirements.html 
sidebar: sidebar 
keywords: linux software, installation requirements, system, authorization,  requirements 
summary: Unified Manager를 설치하는 Linux 시스템에는 특정 버전의 운영 체제와 지원 소프트웨어가 필요합니다. 
---
= Linux 소프트웨어 및 설치 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 설치하는 Linux 시스템에는 특정 버전의 운영 체제와 지원 소프트웨어가 필요합니다.



== 운영 체제 소프트웨어

Linux 시스템에는 다음 버전의 운영 체제와 지원 소프트웨어가 설치되어 있어야 합니다.

* x86_64 아키텍처를 기반으로 하는 Red Hat Enterprise Linux 버전 8.x 및 9.4.


지원되는 Red Hat Enterprise Linux 버전의 전체 및 최신 목록은 상호 운용성 매트릭스를 참조하세요.

http://mysupport.netapp.com/matrix["mysupport.netapp.com/매트릭스"^]

서버는 Unified Manager를 실행하는 데 전용되어야 합니다.  서버에 다른 애플리케이션을 설치하면 안 됩니다.  회사 규정으로 인해 Qualys와 같은 취약성 스캐너가 Linux 시스템에 설치되었을 수 있습니다.  설치가 실패하는 것을 방지하려면 Unified Manager를 설치하기 전에 취약점 스캐너를 비활성화해야 합니다.


NOTE: 취약점 스캐너(예: Qualys)는 가상 머신(VM)을 내부적으로(Unified Manager와 취약점 스캐너가 동일한 VM에 설치된 경우) 또는 외부적으로(Unified Manager와 취약점 스캐너가 두 개의 다른 서버에 설치되어 있고 취약점 스캐너가 Unified Manager가 설치된 VM을 스캔하는 경우) 스캔할 때 CPU 사용량이 높아질 수 있습니다.  이 문제는 종종 VM이 응답하지 않는 결과를 초래하고 Unified Manager 서비스에 영향을 미칩니다.  따라서 NetApp Unified Manager가 설치된 VM에서 취약점 스캐너를 비활성화할 것을 권장합니다.  스캐너를 비활성화하는 것이 불가능한 경우, 업무 시간 외에 VM을 스캔하고 스캔이 완료된 후 서비스를 다시 시작하세요.



== 타사 소프트웨어

Unified Manager는 WildFly 웹 서버에 배포됩니다.  WildFly 26.1.3은 Unified Manager와 함께 번들로 제공됩니다.

다음 타사 패키지는 필요하지만 Unified Manager에 포함되어 있지 않습니다.  이러한 패키지는 자동으로 설치됩니다. `yum` 다음 섹션에 언급된 대로 저장소를 구성했다면 설치 중에 설치 프로그램을 사용할 수 있습니다.

* MySQL Community Edition 버전 8.4.4(MySQL 저장소에서)
* OpenJDK 버전 11.0.25(Red Hat Extra Enterprise Linux 서버 저장소에서)
* Python 3.9.x(Red Hat Extra Enterprise Linux 서버 저장소에서)
* p7zip 버전 16.02 이상(Red Hat Extra Packages for Enterprise Linux 저장소에서)


[NOTE]
====
타사 소프트웨어를 업그레이드하기 전에 실행 중인 Unified Manager 인스턴스를 종료해야 합니다.  타사 소프트웨어 설치가 완료되면 Unified Manager를 다시 시작할 수 있습니다.

====


== 사용자 권한 요구 사항

Linux 시스템에 Unified Manager를 설치하는 작업은 루트 사용자 또는 루트가 아닌 사용자가 다음을 사용하여 수행할 수 있습니다. `sudo` 명령.

또한 기본 Unified Manager 설치에는 sudoers 파일에 umadmin 사용자(기본 유지 관리 사용자)와 jboss 사용자가 포함됩니다.(`ocum_sudoers` 그리고 `ocie_sudoers` )에서 `/etc/sudoers.d/` 예배 규칙서.  보안 정책이나 보안 모니터링 도구로 인해 환경에서 이 콘텐츠를 제거한 경우 다시 추가해야 합니다.  일부 Unified Manager 작업에는 sudo 권한이 필요하므로 sudoers 구성을 보존해야 합니다.



== 설치 요구 사항

시스템에 Red Hat Enterprise Linux와 관련 저장소를 설치하는 모범 사례는 아래와 같습니다.  다르게 설치 또는 구성된 시스템이나 오프프레미스(클라우드)에 배포된 시스템의 경우 추가 단계가 필요할 수 있으며, 이러한 배포에서는 Unified Manager가 제대로 실행되지 않을 수 있습니다.

* Red Hat 모범 사례에 따라 Red Hat Enterprise Linux를 설치해야 하며, 다음과 같은 기본 옵션을 선택해야 합니다. 이를 위해서는 "GUI가 있는 서버" 기반 환경을 선택해야 합니다.
* Red Hat Enterprise Linux에 Unified Manager를 설치하는 동안 시스템은 적절한 저장소에 액세스할 수 있어야 합니다. 이를 통해 설치 프로그램이 모든 필수 소프트웨어 종속성에 액세스하여 설치할 수 있습니다.
* 를 위해 `yum` Red Hat Enterprise Linux 저장소에서 종속 소프트웨어를 찾으려면 설치 프로그램을 사용하려면 Red Hat Enterprise Linux 설치 중이나 나중에 유효한 Red Hat 구독을 사용하여 시스템을 등록해야 합니다.
+
Red Hat Subscription Manager에 대한 자세한 내용은 Red Hat 설명서를 참조하세요.

* 시스템에 필요한 타사 유틸리티를 성공적으로 설치하려면 EPEL(Enterprise Linux용 추가 패키지) 저장소를 활성화해야 합니다.
+
시스템에 EPEL 저장소가 구성되어 있지 않으면 저장소를 수동으로 다운로드하여 구성해야 합니다.

+
보다link:task_manually_configure_epel_repository.html["EPEL 저장소 수동 구성"] .

* 올바른 버전의 MySQL이 설치되지 않은 경우 MySQL 저장소를 활성화해야 시스템에 MySQL 소프트웨어를 성공적으로 설치할 수 있습니다.
+
시스템에 MySQL 저장소가 구성되어 있지 않으면 저장소를 수동으로 다운로드하여 구성해야 합니다.

+
보다link:task_manually_configure_mysql_repository.html["MySQL 저장소 수동 구성"] .

* Unified Manager 호스트에는 Java 버전을 하나만 설치해야 합니다. 그렇지 않으면 시스템에서 사용할 버전을 결정하지 못할 수 있습니다. 보다 https://kb.netapp.com/data-mgmt/AIQUM/AIQUM_Kbs/After_updating_Java_on_the_Active_IQ_Unified_Manager_host_services_will_not_start["Active IQ Unified Manager 호스트에서 Java를 업데이트한 후 서비스가 시작되지 않습니다."] .


시스템에 인터넷 접속이 없고, 인터넷에 연결된 시스템에서 연결되지 않은 시스템으로 저장소가 미러링되지 않은 경우, 설치 지침에 따라 시스템의 외부 소프트웨어 종속성을 확인해야 합니다.  그런 다음 필요한 소프트웨어를 인터넷에 연결된 시스템에 다운로드하고 복사할 수 있습니다. `.rpm` Unified Manager를 설치하려는 시스템에 파일을 추가합니다.  아티팩트와 패키지를 다운로드하려면 다음을 사용해야 합니다. `yum install` 명령.  두 시스템이 동일한 운영 체제 버전을 실행하고 있는지, 그리고 구독 라이선스가 적절한 Red Hat Enterprise Linux에 대한 것인지 확인해야 합니다.

[NOTE]
====
여기에 나열된 저장소 이외의 다른 저장소에서 필요한 타사 소프트웨어를 설치해서는 안 됩니다.  Red Hat 저장소에서 설치된 소프트웨어는 Red Hat Enterprise Linux용으로 명확하게 설계되었으며 Red Hat 모범 사례(디렉토리 레이아웃, 권한 등)를 준수합니다.  다른 위치의 소프트웨어는 이러한 지침을 따르지 않을 수 있으며, 이로 인해 Unified Manager 설치가 실패하거나 향후 업그레이드 시 문제가 발생할 수 있습니다.

====


== 포트 443 요구 사항

Red Hat Enterprise Linux의 일반 이미지는 포트 443에 대한 외부 액세스를 차단할 수 있습니다.  이러한 제한으로 인해 Unified Manager를 설치한 후 관리자 웹 UI에 연결하지 못할 수 있습니다.  다음 명령을 실행하면 일반 Red Hat Enterprise Linux의 모든 외부 사용자와 애플리케이션이 포트 443에 액세스할 수 있습니다.

`# firewall-cmd --zone=public --add-port=443/tcp --permanent; firewall-cmd --reload`

"GUI가 있는 서버" 기반 환경에 Red Hat Enterprise Linux를 설치해야 합니다.  Unified Manager 설치 지침에서 사용되는 명령을 제공합니다.  다른 기반 환경에서는 설치를 검증하거나 완료하기 위해 추가 명령을 설치해야 할 수도 있습니다.  만약 `firewall-cmd` 시스템에서 사용할 수 없는 경우 다음 명령을 실행하여 설치해야 합니다.

`# sudo yum install firewalld`

보안 정책에 따라 다른 절차가 필요한지 확인하려면 명령을 실행하기 전에 IT 부서에 문의하세요.

[NOTE]
====
Red Hat 시스템에서는 THP(Transparent Huge Pages)를 비활성화해야 합니다.  이 기능을 활성화하면 특정 프로세스가 메모리를 너무 많이 사용하여 종료될 때 Unified Manager가 종료될 수 있습니다.

====