---
permalink: install-linux/task_selinux_requirements_for_mounting_opt_netapp.html 
sidebar: sidebar 
keywords: unified manager, selinux requirements, mounting, nfs, cifs, share 
summary: NAS 또는 SAN 장치에 /opt/netapp 또는 /opt/netapp/data를 마운트할 계획이고 SELinux가 활성화된 경우 다음 사항을 고려해야 합니다. 
---
= NFS 및 CIFS 공유에 대한 SELinux 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
마운트를 계획하고 있다면 `/opt/netapp` 또는 `/opt/netapp/data` NAS 또는 SAN 장치에서 SELinux를 활성화한 경우 몇 가지 고려 사항을 알아야 합니다.

마운트를 계획하고 있다면 `/opt/netapp` 또는 `/opt/netapp/data` 루트 파일 시스템이 아닌 다른 곳에서, 환경에서 SELinux를 활성화한 경우, 마운트된 디렉토리에 대한 올바른 컨텍스트를 설정해야 합니다.  사용자 환경에 적용되는 시나리오에 따라 올바른 SELinux 컨텍스트를 설정하고 확인하기 위한 다음 단계를 따르세요.



[[configure-the-selinux-context-when-optnetappdata-is-mounted]]
== SELinux 컨텍스트를 구성합니다. `/opt/netapp/data` 마운트되어 있습니다

마운트한 경우 `/opt/netapp/data` 시스템에서 SELinux가 설정되어 있습니다. `Enforcing` , SELinux 컨텍스트 유형을 확인하십시오. `/opt/netapp/data` 로 설정됩니다 `mysqld_db_t` 이는 데이터베이스 파일의 위치에 대한 기본 컨텍스트 요소입니다.

. 컨텍스트를 확인하려면 다음 명령을 실행하세요.
+
`ls -dZ /opt/netapp/data`

+
샘플 출력:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:default_t:s0 /opt/netapp/data
----
+

NOTE: 이 출력에서 컨텍스트는 다음과 같습니다. `default_t` .  이 컨텍스트를 다음으로 변경해야 합니다. `mysqld_db_t` .

. 마운트한 방식에 따라 컨텍스트를 설정하려면 다음 단계를 수행하십시오. `/opt/netapp/data` .
+
.. 다음 명령을 실행하여 컨텍스트를 설정하세요. `mysqld_db_t` :
`semanage fcontext -a -t mysqld_db_t "/opt/netapp/data"
`restorecon -R -v /opt/netapp/data`
.. 구성한 경우 `/opt/netapp/data` ~에 `/etc/fstab` , 편집해야 합니다 `/etc/fstab` 파일.  를 위해 `/opt/netapp/data/` 마운트 옵션에서 MySQL 레이블을 다음과 같이 추가합니다.
+
`context=system_u:object_r:mysqld_db_t:s0`

.. 언마운트하고 다시 마운트 `/opt/netapp/data/` 맥락을 활성화하기 위해.
.. 직접 NFS 마운트가 있는 경우 다음 명령을 실행하여 컨텍스트를 설정합니다. `mysqld_db_t` :
+
`mount <nfsshare>:/<mountpoint> /opt/netapp/data -o context=system_u:object_r:mysqld_db_t:s0`



. 컨텍스트가 올바르게 설정되었는지 확인하세요.


`ls -dZ /opt/netapp/data/`

샘플 출력:

[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/
----


[[configure-the-selinux-context-when-optnetapp-is-mounted-and-optnetappdata-is-also-mounted-separately]]
== SELinux 컨텍스트를 구성합니다. `/opt/netapp` 마운트되어 있으며 `/opt/netapp/data/` 또한 별도로 장착됩니다

이 시나리오에서는 먼저 컨텍스트를 설정해야 합니다. `/opt/netapp/data/` 이전 섹션에서 설명한 대로.  올바른 컨텍스트를 설정한 후 `/opt/netapp/data/` , 부모 디렉토리를 확인하세요 `/opt/netapp` SELinux 컨텍스트가 설정되어 있지 않습니다. `file_t` .

.단계
. 컨텍스트를 확인하려면 다음 명령을 실행하세요.
+
`ls -dZ /opt/netapp`

+
샘플 출력:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:file_t:s0 /opt/netapp
----
+
이 출력에서 컨텍스트는 다음과 같습니다. `file_t` 바뀌어야 합니다.  다음 명령은 컨텍스트를 설정합니다. `usr_t` .  컨텍스트를 다른 값으로 설정할 수 있습니다. `file_t` 귀하의 보안 요구 사항에 따라.

. 마운트한 방식에 따라 컨텍스트를 설정하려면 다음 단계를 수행하십시오. `/opt/netapp` .
+
.. 다음 명령을 실행하여 컨텍스트를 설정하세요.




[listing]
----
semanage fcontext -a -t usr_t "/opt/netapp"
restorecon -v /opt/netapp
----
. 구성한 경우 `/opt/netapp` ~에 `/etc/fstab` , 편집해야 합니다 `/etc/fstab` 파일.  를 위해 `/opt/netapp` 마운트 옵션에서 MySQL 레이블을 다음과 같이 추가합니다.
+
`context=system_u:object_r:usr_t:s0`

. 언마운트 후 다시 마운트 `/opt/netapp` 맥락을 활성화하기 위해.
. 직접 NFS 마운트가 있는 경우 다음 명령을 실행하여 컨텍스트를 설정합니다.
+
`mount <nfsshare>:/<mountpoint> /opt/netapp -o context=system_u:object_r:usr_t:s0`

+
.. 컨텍스트가 올바르게 설정되었는지 확인하세요.
+
`ls -dZ /opt/netapp`

+
샘플 출력





[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:usr_t:s0 /opt/netapp
----


[[configure-the-selinux-context-when-optnetapp-is-mounted-and-optnetappdata-is-not-mounted-separately]]
== SELinux 컨텍스트를 구성합니다. `/opt/netapp` 마운트되어 있으며 `/opt/netapp/data/` 별도로 마운트되지 않습니다

마운트한 경우 `/opt/netapp` 시스템에서 SELinux가 설정되어 있습니다. `Enforcing` , SELinux 컨텍스트 유형을 확인하십시오. `/opt/netapp` 로 설정됩니다 `mysqld_db_t` 이는 데이터베이스 파일의 위치에 대한 기본 컨텍스트 요소입니다.

.단계
. 컨텍스트를 확인하려면 다음 명령을 실행하세요.
+
`ls -dZ /opt/netapp`

+
샘플 출력:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:default_t:s0 /opt/netapp
----
+

NOTE: 이 출력에서 컨텍스트는 다음과 같습니다. `default_t` .  이 컨텍스트를 다음으로 변경해야 합니다. `mysqld_db_t` .

. 마운트 방법에 따라 컨텍스트를 설정하려면 다음 단계를 수행하십시오. `/opt/netapp` .
+
.. 다음 명령을 실행하여 컨텍스트를 설정하세요. `mysqld_db_t` :
`semanage fcontext -a -t mysqld_db_t "/opt/netapp"
`restorecon -R -v /opt/netapp`
.. 구성한 경우 `/opt/netapp` ~에 `/etc/fstab` , 편집하다 `/etc/fstab` 파일.  를 위해 `/opt/netapp/` 마운트 옵션에서 MySQL 레이블을 다음과 같이 추가합니다.
`context=system_u:object_r:mysqld_db_t:s0`
.. 언마운트 후 다시 마운트 `/opt/netapp/` 맥락을 활성화하기 위해.
.. 직접 NFS 마운트가 있는 경우 다음 명령을 실행하여 컨텍스트를 설정합니다. `mysqld_db_t` :
`mount <nfsshare>:/<mountpoint> /opt/netapp -o context=system_u:object_r:mysqld_db_t:s0`


. 컨텍스트가 올바르게 설정되었는지 확인하세요.


`ls -dZ /opt/netapp/`

샘플 출력:

[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/
----
'''