---
permalink: install-linux/task_create_custom_user_home_directory_and_umadmin.html 
sidebar: sidebar 
keywords: create, custom, user, home, directory, umadmin, password, prior, installation 
summary: Unified Manager를 설치하기 전에 사용자 정의 홈 디렉토리를 만들고 umadmin 사용자 비밀번호를 정의할 수 있습니다.  이 작업은 선택 사항이지만 일부 사이트에서는 Unified Manager 설치 기본 설정을 재정의하는 유연성이 필요할 수 있습니다. 
---
= 설치 전에 사용자 정의 사용자 홈 디렉토리와 umadmin 비밀번호를 만드세요.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 설치하기 전에 사용자 정의 홈 디렉토리를 만들고 umadmin 사용자 비밀번호를 정의할 수 있습니다.  이 작업은 선택 사항이지만 일부 사이트에서는 Unified Manager 설치 기본 설정을 재정의하는 유연성이 필요할 수 있습니다.

.시작하기 전에
* 시스템은 다음에 설명된 요구 사항을 충족해야 합니다.link:concept_virtual_infrastructure_or_hardware_system_requirements.html["하드웨어 시스템 요구 사항"] .
* Red Hat Enterprise Linux 시스템에 루트 사용자로 로그인할 수 있어야 합니다.


기본 Unified Manager 설치는 다음 작업을 수행합니다.

* umadmin 사용자를 생성합니다. `/home/umadmin` 홈 디렉토리로 사용.
* umadmin 사용자에게 기본 비밀번호 "`admin`"을 할당합니다.


일부 설치 환경은 액세스를 제한하기 때문에 `/home` , 설치가 실패합니다.  다른 위치에 홈 디렉토리를 만들어야 합니다.  또한, 일부 사이트에는 비밀번호 복잡성에 대한 규칙이 있거나 설치 프로그램에서 설정하는 대신 로컬 관리자가 비밀번호를 설정하도록 요구하는 경우도 있습니다.

설치 환경에서 이러한 설치 기본 설정을 재정의해야 하는 경우 다음 단계에 따라 사용자 지정 홈 디렉토리를 만들고 umadmin 사용자의 비밀번호를 정의하세요.

이 정보가 설치 전에 정의되어 있으면 설치 스크립트가 이러한 설정을 검색하여 설치 기본 설정 대신 정의된 값을 사용합니다.

또한 기본 Unified Manager 설치에는 sudoers 파일에 umadmin 사용자가 포함됩니다.(`ocum_sudoers` 그리고 `ocie_sudoers` )에서 `/etc/sudoers.d/` 예배 규칙서.  보안 정책이나 일부 보안 모니터링 도구로 인해 환경에서 이 콘텐츠를 제거한 경우 다시 추가해야 합니다.  일부 Unified Manager 작업에는 sudo 권한이 필요하므로 sudoers 구성을 보존해야 합니다.

사용자 환경의 보안 정책은 Unified Manager 유지 관리 사용자의 sudo 권한을 제한해서는 안 됩니다.  권한이 제한되면 일부 Unified Manager 작업이 실패할 수 있습니다.  설치가 성공적으로 완료된 후 umadmin 사용자로 로그인하여 다음 sudo 명령을 실행할 수 있는지 확인하세요.

`sudo systemctl  status ocie`

이 명령은 오류 없이 ocie 서비스의 적절한 상태를 반환해야 합니다.

.단계
. 서버에 루트 사용자로 로그인합니다.
. "`maintenance`"라는 umadmin 그룹 계정을 만듭니다.
+
`groupadd maintenance`

. 원하는 홈 디렉토리 아래의 유지 관리 그룹에 "`umadmin`" 사용자 계정을 만듭니다.
+
`adduser --home <home_directory\> -g maintenance umadmin`

. umadmin 비밀번호를 정의합니다:
+
`passwd umadmin`

+
시스템에서 umadmin 사용자에 대한 새 비밀번호 문자열을 입력하라는 메시지가 표시됩니다.



Unified Manager를 설치한 후에는 umadmin 사용자 로그인 셸을 지정해야 합니다.
