---
permalink: install-linux/task_change_jboss_password.html 
sidebar: sidebar 
keywords: change, jboss password 
summary: 설치 중에 설정된 인스턴스별 JBoss 비밀번호를 재설정할 수 있습니다.  사이트에 Unified Manager 설치 설정을 재정의하기 위해 이 보안 기능이 필요한 경우 선택적으로 비밀번호를 재설정할 수 있습니다.  이 작업은 JBoss가 MySQL에 액세스하는 데 사용하는 비밀번호도 변경합니다. 
---
= JBoss 비밀번호 변경
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
설치 중에 설정된 인스턴스별 JBoss 비밀번호를 재설정할 수 있습니다.  사이트에 Unified Manager 설치 설정을 재정의하기 위해 이 보안 기능이 필요한 경우 선택적으로 비밀번호를 재설정할 수 있습니다.  이 작업은 JBoss가 MySQL에 액세스하는 데 사용하는 비밀번호도 변경합니다.

* Unified Manager가 설치된 Red Hat Enterprise Linux 시스템에 루트 사용자 액세스 권한이 있어야 합니다.
* NetApp 에서 제공하는 서비스에 액세스할 수 있어야 합니다. `password.sh` 디렉토리의 스크립트 `/opt/netapp/essentials/bin` .


.단계
. 시스템에 루트 사용자로 로그인합니다.
. 다음 명령을 표시된 순서대로 입력하여 Unified Manager 서비스를 중지합니다.
+
`systemctl stop ocieau`

+
`systemctl stop ocie`

+
연관된 MySQL 소프트웨어를 중지하지 마세요.

. 비밀번호 변경 프로세스를 시작하려면 다음 명령을 입력하세요.
+
`/opt/netapp/essentials/bin/password.sh resetJBossPassword`

. 메시지가 표시되면 새로운 JBoss 비밀번호를 입력한 다음 확인을 위해 두 번째로 비밀번호를 입력합니다.
+
비밀번호는 8~16자여야 하며, 숫자, 대문자, 소문자, 그리고 다음 특수 문자 중 하나 이상을 포함해야 합니다.

+
`+!@%^*-_+=[]:<>.?/~+`

. 스크립트가 완료되면 다음 명령을 표시된 순서대로 입력하여 Unified Manager 서비스를 시작합니다.
+
`systemctl start ocie`

+
`systemctl start ocieau`

. 모든 서비스가 시작된 후 Unified Manager UI에 로그인할 수 있습니다.

