---
permalink: install-linux/task_upgrade_unified_manager.html 
sidebar: sidebar 
keywords: upgrade, unified manager 
summary: Linux 플랫폼에서 설치 파일을 다운로드하여 실행하면 Unified Manager를 업그레이드할 수 있습니다. 
---
= Unified Manager 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Linux 플랫폼에서 설치 파일을 다운로드하여 실행하면 Unified Manager 9.13 또는 9.14에서 9.16로 업그레이드할 수 있습니다.

.시작하기 전에
* Unified Manager를 업그레이드하는 시스템은 시스템 및 소프트웨어 요구 사항을 충족해야 합니다.
+
보다link:concept_virtual_infrastructure_or_hardware_system_requirements.html["하드웨어 시스템 요구 사항"] .

+
보다link:reference_red_hat_software_and_installation_requirements.html["Linux 소프트웨어 및 설치 요구 사항"] .

* Red Hat Enterprise Linux Subscription Manager 구독이 필요합니다.
* Unified Manager를 업그레이드하기 전에 올바른 버전의 OpenJDK를 설치하거나 업그레이드해야 합니다.
+
보다link:task_upgrade_openjdk_on_linux_ocum.html["Linux에서 JRE 업그레이드"] .

* 데이터 손실을 방지하려면 업그레이드 중에 문제가 발생할 경우를 대비해 Unified Manager 데이터베이스의 백업을 만들어야 합니다.  NetApp 백업 파일을 다음에서 이동할 것을 권장합니다. `/opt/netapp/data` 외부 위치로의 디렉토리.
* 업그레이드하는 동안 성능 데이터를 13개월 동안 보관하는 기존 기본 설정을 유지할지, 아니면 6개월로 변경할지 묻는 메시지가 표시될 수 있습니다.  확인 후, 과거 성과 데이터는 6개월 후에 삭제됩니다.
* 업그레이드 프로세스 중에는 Unified Manager를 사용할 수 없으므로 실행 중인 모든 작업을 완료했어야 합니다.
* MySQL Community Edition은 Unified Manager 업그레이드 중에 자동으로 업그레이드됩니다.  시스템에 설치된 MySQL 버전이 8.4.4 이전인 경우 Unified Manager 업그레이드 프로세스는 자동으로 MySQL을 8.4.4로 업그레이드합니다.


.단계
. 대상 Red Hat Enterprise Linux 서버에 로그인합니다.
. Unified Manager 번들을 서버에 다운로드합니다.
+
보다link:task_download_unified_manager.html["Linux용 Unified Manager 다운로드"] .

. 대상 디렉토리로 이동하여 Unified Manager 번들을 확장합니다.
+
`unzip ActiveIQUnifiedManager-<version>.zip`

+
Unified Manager에 필요한 RPM 모듈이 대상 디렉토리에 압축 해제됩니다.

. 다음 모듈이 디렉토리에 있는지 확인하세요.
+
`ls *.rpm`

+
`netapp-um<version>.x86_64.rpm`

. 사전 설치 스크립트를 실행하여 업그레이드와 충돌할 수 있는 시스템 구성 설정이나 설치된 소프트웨어가 없는지 확인하세요.
+
`sudo ./pre_install_check.sh`

+
사전 설치 스크립트는 시스템에 유효한 Red Hat Enterprise Linux 구독이 있는지, 그리고 필요한 소프트웨어 저장소에 액세스할 수 있는지 확인합니다.  스크립트에서 문제가 발견되면 문제를 해결하고 업그레이드를 계속 진행해야 합니다.

+
누락된 패키지가 감지된 경우 다음 단계를 수행하십시오.link:../install-linux/task_upgrade_unified_manager.html#additional-steps-to-perform-for-missing-packages["누락된 패키지에 대해 수행해야 할 추가 단계"] .  누락된 패키지가 없으면 다음 단계로 넘어가세요.

. 다음 스크립트를 사용하여 Unified Manager를 업그레이드하세요.
+
`upgrade.sh`

+
이 스크립트는 RPM 모듈을 자동으로 실행하여 필요한 지원 소프트웨어와 해당 모듈에서 실행되는 Unified Manager 모듈을 업그레이드합니다.  또한 업그레이드 스크립트는 업그레이드와 충돌할 수 있는 시스템 구성 설정이나 설치된 소프트웨어가 있는지 확인합니다.  스크립트에서 문제가 발견되면 Unified Manager를 업그레이드하기 전에 해당 문제를 해결해야 합니다.  Unified Manager를 업그레이드하기 전에 _net-snmp_와 같은 패키지를 이미 설치한 경우, MySQL 종속성으로 인해 업그레이드 중에 해당 패키지가 제거될 수 있습니다.  계속해서 사용하려면 패키지를 다시 수동으로 설치해야 합니다.

. 업그레이드가 완료되면 Unified Manager 웹 UI의 IP 주소 또는 URL, 유지 관리 사용자 이름(umadmin), 기본 비밀번호가 표시된 메시지가 나타날 때까지 메시지를 뒤로 스크롤합니다.
+
메시지는 다음과 비슷합니다.

+
[listing]
----
Active IQ Unified Manager upgraded successfully.
Use a web browser and one of the following URLs to access the Unified Manager GUI:

https://default_ip_address/    (if using IPv4)
https://[default_ip_address]/  (if using IPv6)
https://fully_qualified_domain_name/
----


지원되는 웹 브라우저의 새 창에 지정된 IP 주소 또는 URL을 입력하여 Unified Manager 웹 UI를 시작한 다음, 이전에 설정한 동일한 유지 관리 사용자 이름(umadmin)과 비밀번호를 사용하여 로그인합니다.



== 누락된 패키지에 대해 수행해야 할 추가 단계

업그레이드 중에 사이트에서 누락된 패키지가 감지되거나, 시스템이 인터넷에 연결되어 있지 않거나, Red Hat Enterprise Linux 저장소를 사용하지 않는 경우, 다음 단계를 수행하여 필요한 패키지가 누락되었는지 확인하고 해당 패키지를 다운로드하세요.


NOTE: 이러한 단계는 주요 절차의 _5_단계 이후에 수행되어야 합니다.  이 절차를 통해 Unified Manager가 업그레이드되므로 업그레이드를 위해 추가 단계를 실행할 필요가 없습니다.

. 사용 가능한 패키지와 사용할 수 없는 패키지 목록을 확인하세요.
+
`yum install netapp-um<version>.x86_64.rpm --assumeno`

+
"`설치 중:`" 섹션의 항목은 현재 디렉토리에서 사용 가능한 패키지이고, "`종속성을 위한 설치:`" 섹션의 항목은 시스템에서 누락된 패키지입니다.

. 인터넷에 접속할 수 있는 다른 시스템에서 다음 명령을 실행하여 누락된 패키지를 다운로드합니다.
+
`yum install package_name --downloadonly --downloaddir=.`

+
패키지는 지정된 디렉토리에 다운로드됩니다. `--downloaddir=` .

+
Red Hat Enterprise Linux 시스템에서는 "`yum-plugin-downloadonly`" 플러그인이 항상 활성화되어 있지 않으므로 패키지를 설치하지 않고도 다운로드하는 기능을 활성화해야 할 수도 있습니다.

+
`yum install yum-plugin-downloadonly`

. 다운로드한 패키지를 설치 시스템에서 Unified Manager 번들을 압축 해제한 디렉토리에 복사합니다.
. 해당 디렉토리로 디렉토리를 변경하고 다음 명령을 실행하여 누락된 패키지와 해당 종속성을 설치합니다.
+
`yum install *.rpm`

. Unified Manager 서버를 시작합니다.  다음 명령을 실행하세요:
+
`systemctl start ocie`

+
`systemctl start ocieau`



이 프로세스를 통해 Unified Manager 업그레이드 프로세스가 완료됩니다.  지원되는 웹 브라우저의 새 창에 지정된 IP 주소 또는 URL을 입력하여 Unified Manager 웹 UI를 시작한 다음, 이전에 설정한 동일한 유지 관리 사용자 이름(umadmin)과 비밀번호를 사용하여 로그인합니다.
