---
permalink: events/concept_guidelines_for_adding_alerts.html 
sidebar: sidebar 
keywords: guidelines, adding, alerts 
summary: 클러스터, 노드, 집계 또는 볼륨과 같은 리소스와 특정 심각도 유형의 이벤트를 기반으로 알림을 추가할 수 있습니다.  가장 좋은 방법은 개체가 속한 클러스터를 추가한 후 중요한 개체에 대한 알림을 추가하는 것입니다. 
---
= 알림 추가 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터, 노드, 집계 또는 볼륨과 같은 리소스와 특정 심각도 유형의 이벤트를 기반으로 알림을 추가할 수 있습니다.  가장 좋은 방법은 개체가 속한 클러스터를 추가한 후 중요한 개체에 대한 알림을 추가하는 것입니다.

다음 지침과 고려 사항을 사용하여 시스템을 효과적으로 관리하기 위한 알림을 만들 수 있습니다.

* 경고 설명
+
알림을 효과적으로 추적할 수 있도록 알림에 대한 설명을 제공해야 합니다.

* 리소스
+
어떤 물리적 또는 논리적 리소스에 알림이 필요한지 결정해야 합니다.  필요에 따라 리소스를 포함하거나 제외할 수 있습니다.  예를 들어, 알림을 구성하여 집계를 면밀히 모니터링하려면 리소스 목록에서 필요한 집계를 선택해야 합니다.

+
예를 들어 리소스 범주를 선택하는 경우, *+<<All User or Group Quotas>> +*를 선택하면 해당 카테고리에 속한 모든 객체에 대한 알림을 받게 됩니다.

+
[NOTE]
====
클러스터를 리소스로 선택하더라도 해당 클러스터 내의 스토리지 개체가 자동으로 선택되지는 않습니다.  예를 들어, 모든 클러스터의 모든 중요 이벤트에 대한 알림을 생성하면 클러스터 중요 이벤트에 대한 알림만 받게 됩니다.  노드, 집계 등의 중요 이벤트에 대한 알림은 받지 않습니다.

====
* 이벤트 심각도
+
지정된 심각도 유형(중요, 오류, 경고)의 이벤트가 알림을 트리거해야 하는지 여부와, 트리거한다면 어떤 심각도 유형을 사용해야 하는지 결정해야 합니다.

* 선택된 이벤트
+
생성된 이벤트 유형에 따라 알림을 추가하는 경우, 어떤 이벤트에 알림이 필요한지 결정해야 합니다.

+
이벤트 심각도를 선택했지만 개별 이벤트를 선택하지 않은 경우("선택한 이벤트" 열을 비워둔 경우) 해당 범주의 모든 이벤트에 대한 알림을 받게 됩니다.

* 행위
+
알림을 받는 사용자의 사용자 이름과 이메일 주소를 제공해야 합니다.  SNMP 트랩을 알림 모드로 지정할 수도 있습니다.  경고가 생성될 때 스크립트가 실행되도록 경고에 스크립트를 연결할 수 있습니다.

* 알림 빈도
+
지정된 시간 동안 수신자에게 반복적으로 알림을 보내도록 알림을 구성할 수 있습니다.  경고에 대한 이벤트 알림이 활성화되는 시간을 결정해야 합니다.  이벤트가 확인될 때까지 이벤트 알림을 반복하려면 알림을 얼마나 자주 반복할지 결정해야 합니다.

* 스크립트 실행
+
스크립트를 알림과 연결할 수 있습니다.  알림이 생성되면 스크립트가 실행됩니다.


