---
permalink: events/concept_what_event_management_system_events_are.html 
sidebar: sidebar 
keywords: event management, system, 
summary: '이벤트 관리 시스템(EMS)은 ONTAP 커널의 다양한 부분에서 이벤트 데이터를 수집하고 이벤트 전달 메커니즘을 제공합니다.  이러한 ONTAP 이벤트는 Unified Manager에서 EMS 이벤트로 보고될 수 있습니다.  중앙 집중식 모니터링 및 관리를 통해 중요한 EMS 이벤트 구성과 이러한 EMS 이벤트에 따른 경고 알림이 용이해집니다.' 
---
= 이벤트 관리 시스템 이벤트란 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이벤트 관리 시스템(EMS)은 ONTAP 커널의 다양한 부분에서 이벤트 데이터를 수집하고 이벤트 전달 메커니즘을 제공합니다.  이러한 ONTAP 이벤트는 Unified Manager에서 EMS 이벤트로 보고될 수 있습니다.  중앙 집중식 모니터링 및 관리를 통해 중요한 EMS 이벤트 구성과 이러한 EMS 이벤트에 따른 경고 알림이 용이해집니다.

Unified Manager에 클러스터를 추가하면 Unified Manager 주소가 클러스터에 알림 대상으로 추가됩니다.  EMS 이벤트는 클러스터에서 이벤트가 발생하자마자 보고됩니다.

Unified Manager에서 EMS 이벤트를 수신하는 방법에는 두 가지가 있습니다.

* 일정 수의 중요한 EMS 이벤트가 자동으로 보고됩니다.
* 개별 EMS 이벤트를 수신하도록 구독할 수 있습니다.


Unified Manager에서 생성된 EMS 이벤트는 이벤트가 생성된 방법에 따라 다르게 보고됩니다.

|===
| 기능성 | 자동 EMS 메시지 | 구독된 EMS 메시지 


 a| 
이용 가능한 EMS 이벤트
 a| 
EMS 이벤트의 하위 집합
 a| 
모든 EMS 이벤트



 a| 
트리거 시 EMS 메시지 이름
 a| 
Unified Manager 이벤트 이름(EMS 이벤트 이름에서 변환됨)
 a| 
"EMS 수신 오류" 형식은 구체적이지 않습니다.  자세한 메시지는 실제 EMS 이벤트의 점 표기 형식을 제공합니다.



 a| 
수신된 메시지
 a| 
클러스터가 발견되자마자
 a| 
Unified Manager에 필요한 각 EMS 이벤트를 추가한 후 다음 15분 폴링 주기가 지난 후



 a| 
이벤트 수명 주기
 a| 
다른 Unified Manager 이벤트와 동일: 새 항목, 확인됨, 해결됨 및 사용되지 않음 상태
 a| 
EMS 이벤트는 이벤트가 생성된 후 15분 후 클러스터가 새로 고쳐지면 더 이상 사용되지 않습니다.



 a| 
Unified Manager 가동 중지 시간 동안 이벤트를 캡처합니다.
 a| 
예, 시스템이 시작되면 각 클러스터와 통신하여 누락된 이벤트를 수집합니다.
 a| 
아니요



 a| 
이벤트 세부 정보
 a| 
제안된 시정 조치는 일관된 해결책을 제공하기 위해 ONTAP 에서 직접 가져옵니다.
 a| 
이벤트 세부 정보 페이지에서 시정 조치를 사용할 수 없습니다.

|===
[NOTE]
====
새로운 자동 EMS 이벤트 중 일부는 이전 이벤트가 해결되었음을 나타내는 정보 이벤트입니다.  예를 들어, "FlexGroup 구성 요소 공간 상태 모두 정상" 정보 이벤트는 "FlexGroup 구성 요소에 공간 문제가 있습니다" 오류 이벤트가 해결되었음을 나타냅니다.  정보 이벤트는 다른 이벤트 심각도 유형과 동일한 이벤트 수명 주기를 사용하여 관리할 수 없습니다. 그러나 동일한 볼륨에서 다른 "공간 문제" 오류 이벤트가 수신되면 해당 이벤트는 자동으로 폐기됩니다.

====