---
permalink: events/reference_metrocluster_connectivity_events.html 
sidebar: sidebar 
keywords: metrocluster, connectivity, events, impact area, availability 
summary: 연결 이벤트는 클러스터 구성 요소 간 연결과 MetroCluster 구성의 클러스터 간 연결에 대한 정보를 제공하여 잠재적인 문제를 모니터링할 수 있도록 해줍니다.  이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형, 심각도가 포함됩니다. 
---
= MetroCluster 연결 이벤트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
연결 이벤트는 클러스터 구성 요소 간 연결과 FC를 통한 MetroCluster 및 IP 구성을 통한 MetroCluster 의 MetroCluster 간 연결에 대한 정보를 제공하므로 잠재적인 문제를 모니터링할 수 있습니다.  이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형, 심각도가 포함됩니다.



== 두 구성 모두에서 공통적인 이벤트

이러한 연결 이벤트는 FC를 통한 MetroCluster 와 IP를 통한 MetroCluster 구성 모두에서 공통적으로 발생합니다.



=== 영향 영역: 가용성

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
MetroCluster 파트너 간 모든 링크가 다운되었습니다(ocumEvtMetroClusterAllLinksBetweenPartnersDown)
 a| 
사건
 a| 
MetroCluster 관계
 a| 
비판적인



 a| 
피어링 네트워크를 통해 MetroCluster 파트너에 접근할 수 없음(ocumEvtMetroClusterPartnersNotReachableOverPeeringNetwork)
 a| 
사건
 a| 
MetroCluster 관계
 a| 
비판적인



 a| 
MetroCluster 재해 복구 기능 영향(ocumEvtMetroClusterDRStatusImpacted)
 a| 
위험
 a| 
MetroCluster 관계
 a| 
비판적인



 a| 
MetroCluster 구성이 전환되었습니다(ocumEvtMetroClusterDRStatusImpacted)
 a| 
위험
 a| 
MetroCluster 관계
 a| 
경고

|===


== FC 구성을 통한 MetroCluster

이러한 이벤트는 FC 구성을 통한 MetroCluster 와 관련이 있습니다.



=== 영향 영역: 가용성

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
모든 스위치 간 링크 다운(ocumEvtMetroClusterAllISLBetweenSwitchesDown)
 a| 
사건
 a| 
MetroCluster 스위치 간 연결
 a| 
비판적인



 a| 
FC-SAS 브리지 투 스토리지 스택 링크 다운(ocumEvtBridgeSasPortDown)
 a| 
사건
 a| 
MetroCluster 브리지 스택 연결
 a| 
비판적인



 a| 
MetroCluster 구성이 부분적으로 전환됨(ocumEvtMetroClusterDRStatusPartiallyImpacted)
 a| 
위험
 a| 
MetroCluster 관계
 a| 
오류



 a| 
노드에서 FC로의 모든 FC-VI 상호 연결 링크 차단(ocumEvtMccNodeSwitchFcviLinksDown)
 a| 
사건
 a| 
MetroCluster 노드 스위치 연결
 a| 
비판적인



 a| 
노드에서 FC로 전환 하나 이상의 FC-Initiator 링크 다운(ocumEvtMccNodeSwitchFcLinksOneOrMoreDown)
 a| 
위험
 a| 
MetroCluster 노드 스위치 연결
 a| 
경고



 a| 
노드에서 FC로 모든 FC 이니시에이터 링크를 전환합니다(ocumEvtMccNodeSwitchFcLinksDown)
 a| 
사건
 a| 
MetroCluster 노드 스위치 연결
 a| 
비판적인



 a| 
FC-SAS 브리지 FC 링크 다운(ocumEvtMccSwitchBridgeFcLinksDown)으로 전환
 a| 
사건
 a| 
MetroCluster 스위치 브리지 연결
 a| 
비판적인



 a| 
노드 간 모든 FC VI InterConnect 링크 다운(ocumEvtMccInterNodeLinksDown)
 a| 
사건
 a| 
노드 간 연결
 a| 
비판적인



 a| 
노드 간 하나 이상의 FC VI InterConnect 링크가 끊어짐(ocumEvtMccInterNodeLinksOneOrMoreDown)
 a| 
위험
 a| 
노드 간 연결
 a| 
경고



 a| 
노드-브리지 링크 다운(ocumEvtMccNodeBridgeLinksDown)
 a| 
사건
 a| 
노드 브리지 연결
 a| 
비판적인



 a| 
노드에서 스토리지 스택으로의 모든 SAS 링크가 다운됨(ocumEvtMccNodeStackLinksDown)
 a| 
사건
 a| 
노드 스택 연결
 a| 
비판적인



 a| 
노드에서 스토리지 스택으로 하나 이상의 SAS 링크가 다운됨(ocumEvtMccNodeStackLinksOneOrMoreDown)
 a| 
위험
 a| 
노드 스택 연결
 a| 
경고

|===


== IP 구성을 통한 MetroCluster

이러한 이벤트는 IP 구성을 통한 MetroCluster 와 관련이 있습니다.



=== 영향 영역: 가용성

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
MetroCluster IP 사이트 간 연결 상태가 다운되었습니다(mccIntersiteconnectivityStatusDown)
 a| 
위험
 a| 
MetroCluster 관계
 a| 
비판적인



 a| 
MetroCluster-IP 노드에서 스위치로의 연결 오프라인(mccIpPortStatusOffline)
 a| 
위험
 a| 
마디
 a| 
오류

|===