---
permalink: events/reference_edit_alert_dialog_box.html 
sidebar: sidebar 
keywords: edit, alert, dialog box, name, resources, events, actions 
summary: 알림과 연관된 리소스, 이벤트, 스크립트, 알림 옵션 등의 알림 속성을 편집할 수 있습니다. 
---
= 알림 편집 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
알림과 연관된 리소스, 이벤트, 스크립트, 알림 옵션 등의 알림 속성을 편집할 수 있습니다.



== 이름

이 영역에서는 알림의 이름과 설명을 편집할 수 있습니다.

* *경고 이름*
+
알림 이름을 편집할 수 있습니다.

* *경고 설명*
+
알림에 대한 설명을 지정할 수 있습니다.

* *경보 상태*
+
알림을 활성화하거나 비활성화할 수 있습니다.





== 리소스

이 영역에서는 알림을 트리거하려는 동적 규칙에 따라 개별 리소스를 선택하거나 리소스를 그룹화할 수 있습니다.  드롭다운 목록에서 리소스 유형을 선택하여 리소스를 검색할 수도 있고, 정확한 리소스 이름을 지정하여 특정 리소스를 표시할 수도 있습니다.

* *포함하다*
+
알림을 트리거할 리소스를 포함할 수 있습니다.  문자열을 지정하여 문자열과 일치하는 리소스를 그룹화하고 이 그룹을 선택하여 알림에 포함할 수 있습니다.  예를 들어, 이름에 "`vol0`" 문자열이 포함된 모든 볼륨을 그룹화할 수 있습니다.

* *들어오지 못하게 하다*
+
알림을 발생시키지 않으려는 리소스를 제외할 수 있습니다.  예를 들어, 이름에 "`xyz`" 문자열이 포함된 모든 볼륨을 제외할 수 있습니다.

+
[NOTE]
====
제외 탭은 특정 리소스 유형의 모든 리소스를 선택한 경우에만 표시됩니다. 예: +<<All Volumes>> + 또는 +<<All Volumes whose name contains 'xyz'>> +.

====




== 이벤트

이 영역에서는 알림을 트리거할 이벤트를 선택할 수 있습니다.  특정 심각도 또는 일련의 이벤트에 따라 이벤트에 대한 알림을 트리거할 수 있습니다.

* *이벤트 심각도*
+
심각도 유형(중요, 오류 또는 경고)에 따라 이벤트를 선택할 수 있습니다.

* *이벤트 이름에 포함됨*
+
이름에 지정된 문자가 포함된 이벤트를 선택할 수 있습니다.





== 행위

이 영역에서는 알림 방법과 알림 빈도를 지정할 수 있습니다.

* *이러한 사용자에게 경고*
+
이메일 주소나 사용자 이름을 편집하거나, 알림을 받을 새 이메일 주소나 사용자 이름을 지정할 수 있습니다.

* *알림 빈도*
+
이벤트가 확인되거나 해결되거나 더 이상 유효하지 않은 상태로 이동될 때까지 관리 서버가 알림을 보내는 빈도를 편집할 수 있습니다.

+
다음 알림 방법을 선택할 수 있습니다.

+
** 한 번만 알림
** 지정된 빈도로 알림
** 지정된 시간 범위 내에서 지정된 빈도로 알림


* *SNMP 트랩 발행*
+
SNMP 트랩을 전역적으로 구성된 SNMP 호스트로 보낼지 여부를 지정할 수 있습니다.

* *스크립트 실행*
+
알림과 스크립트를 연결할 수 있습니다.  이 스크립트는 알림이 생성되면 실행됩니다.





== 명령 버튼

* *구하다*
+
변경 사항을 저장하고 대화 상자를 닫습니다.

* *취소*
+
변경 사항을 취소하고 대화 상자를 닫습니다.


