---
permalink: events/reference_cluster_events.html 
sidebar: sidebar 
keywords: cluster events, impact, area, availability, capacity, configuration, performance, security 
summary: 클러스터 이벤트는 클러스터 상태에 대한 정보를 제공하므로 클러스터를 모니터링하여 잠재적인 문제를 파악할 수 있습니다.  이벤트는 영향 영역별로 그룹화되며 이벤트 이름, 트랩 이름, 영향 수준, 소스 유형 및 심각도가 포함됩니다. 
---
= 클러스터 이벤트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 이벤트는 클러스터 상태에 대한 정보를 제공하므로 클러스터를 모니터링하여 잠재적인 문제를 파악할 수 있습니다.  이벤트는 영향 영역별로 그룹화되며 이벤트 이름, 트랩 이름, 영향 수준, 소스 유형 및 심각도가 포함됩니다.



== 영향 영역: 가용성

별표(*)는 Unified Manager 이벤트로 변환된 EMS 이벤트를 식별합니다.

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
클러스터에 예비 디스크가 없습니다(ocumEvtDisksNoSpares)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
클러스터에 도달할 수 없음(ocumEvtClusterUnreachable)
 a| 
위험
 a| 
무리
 a| 
오류



 a| 
클러스터 모니터링 실패(ocumEvtClusterMonitoringFailed)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
클러스터 FabricPool 라이선스 용량 제한 위반(ocumEvtExternalCapacityTierSpaceFull)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
NVMe-oF 유예 기간 시작 *(nvmfGracePeriodStart)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
NVMe-oF 유예 기간 활성화 *(nvmfGracePeriodActive)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
NVMe-oF 유예 기간 만료 *(nvmfGracePeriodExpired)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
객체 유지 관리 창 시작됨(objectMaintenanceWindowStarted)
 a| 
이벤트
 a| 
무리
 a| 
비판적인



 a| 
객체 유지 관리 기간이 종료되었습니다(objectMaintenanceWindowEnded)
 a| 
이벤트
 a| 
무리
 a| 
정보



 a| 
MetroCluster 남은 스페어 디스크(ocumEvtSpareDiskLeftBehind)
 a| 
위험
 a| 
무리
 a| 
오류



 a| 
MetroCluster 자동 계획되지 않은 전환 비활성화(ocumEvtMccAutomaticUnplannedSwitchOverDisabled)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
클러스터 사용자 비밀번호가 변경되었습니다. *(cluster.passwd.changed)
 a| 
이벤트
 a| 
무리
 a| 
정보

|===


== 영향 영역: 용량

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
클러스터 용량 불균형 임계값 위반(ocumConformanceNodeImbalanceWarning)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
클러스터 클라우드 계층 계획(clusterCloudTierPlanningWarning)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
FabricPool 미러 복제 재동기화 완료 *(waflCaResyncComplete)
 a| 
이벤트
 a| 
무리
 a| 
경고



 a| 
FabricPool 공간이 거의 가득 찼습니다 *(fabricpoolNearlyFull)
 a| 
위험
 a| 
무리
 a| 
오류

|===


== 영향 영역: 구성

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
노드 추가됨(해당 없음)
 a| 
이벤트
 a| 
무리
 a| 
정보



 a| 
노드 제거됨(해당 없음)
 a| 
이벤트
 a| 
무리
 a| 
정보



 a| 
클러스터 제거됨(해당 없음)
 a| 
이벤트
 a| 
무리
 a| 
정보



 a| 
클러스터 추가 실패(해당 없음)
 a| 
이벤트
 a| 
무리
 a| 
오류



 a| 
클러스터 이름이 변경되었습니다(해당 없음)
 a| 
이벤트
 a| 
무리
 a| 
정보



 a| 
긴급 EMS 수신 (해당 없음)
 a| 
이벤트
 a| 
무리
 a| 
비판적인



 a| 
중요 EMS 수신됨(해당 없음)
 a| 
이벤트
 a| 
무리
 a| 
비판적인



 a| 
EMS 알림 수신됨(해당 없음)
 a| 
이벤트
 a| 
무리
 a| 
오류



 a| 
EMS 수신 오류 (해당 없음)
 a| 
이벤트
 a| 
무리
 a| 
경고



 a| 
경고 EMS 수신됨 (해당 없음)
 a| 
이벤트
 a| 
무리
 a| 
경고



 a| 
디버그 EMS 수신됨(해당 없음)
 a| 
이벤트
 a| 
무리
 a| 
경고



 a| 
EMS 수신 알림 (해당 없음)
 a| 
이벤트
 a| 
무리
 a| 
경고



 a| 
정보 EMS 수신됨(해당 없음)
 a| 
이벤트
 a| 
무리
 a| 
경고

|===
ONTAP EMS 이벤트는 세 가지 Unified Manager 이벤트 심각도 수준으로 분류됩니다.

|===


| Unified Manager 이벤트 심각도 수준 | ONTAP EMS 이벤트 심각도 수준 


 a| 
비판적인
 a| 
비상

비판적인



 a| 
오류
 a| 
알리다



 a| 
경고
 a| 
오류

경고

디버그

알아채다

정보 제공

|===


== 영향 영역: 성능

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
클러스터 부하 불균형 임계값 위반()
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
클러스터 IOPS 중요 임계값 위반(ocumClusterIopsIncident)
 a| 
사건
 a| 
무리
 a| 
비판적인



 a| 
클러스터 IOPS 경고 임계값 위반(ocumClusterIopsWarning)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
클러스터 MB/s 중요 임계값 위반(ocumClusterMbpsIncident)
 a| 
사건
 a| 
무리
 a| 
비판적인



 a| 
클러스터 MB/s 경고 임계값 위반(ocumClusterMbpsWarning)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
클러스터 동적 임계값 위반(ocumClusterDynamicEventWarning)
 a| 
위험
 a| 
무리
 a| 
경고

|===


== 영향 영역: 보안

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
AutoSupport HTTPS 전송 비활성화(ocumClusterASUPHttpsConfiguredDisabled)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
로그 전달이 암호화되지 않음(ocumClusterAuditLogUnencrypted)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
기본 로컬 관리자 사용자 활성화(ocumClusterDefaultAdminEnabled)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
FIPS 모드 비활성화(ocumClusterFipsDisabled)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
로그인 배너 비활성화(ocumClusterLoginBannerDisabled)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
로그인 배너가 변경되었습니다(ocumClusterLoginBannerChanged)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
로그 전달 대상 변경됨(ocumLogForwardDestinationsChanged)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
NTP 서버 이름이 변경되었습니다(ocumNtpServerNamesChanged)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
NTP 서버 수가 적습니다(securityConfigNTPServerCountLowRisk)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
클러스터 피어 통신이 암호화되지 않았습니다(ocumClusterPeerEncryptionDisabled)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
SSH가 안전하지 않은 암호를 사용하고 있습니다(ocumClusterSSHInsecure)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
Telnet 프로토콜 활성화(ocumClusterTelnetEnabled)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
일부 ONTAP 사용자 계정의 비밀번호는 보안 수준이 낮은 MD5 해시 함수(ocumClusterMD5PasswordHashUsed)를 사용합니다.
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
클러스터는 자체 서명 인증서(ocumClusterSelfSignedCertificate)를 사용합니다.
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
클러스터 원격 셸이 활성화되었습니다(ocumClusterRshDisabled)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
클러스터 인증서 만료 임박(ocumEvtClusterCertificateAboutToExpire)
 a| 
위험
 a| 
무리
 a| 
경고



 a| 
클러스터 인증서가 만료되었습니다(ocumEvtClusterCertificateExpired)
 a| 
위험
 a| 
무리
 a| 
오류

|===