---
permalink: events/reference_notifications_page.html 
sidebar: sidebar 
keywords: notifications page, email, smtp, server, snmp 
summary: 이벤트가 생성되거나 사용자에게 할당될 때 Unified Manager 서버가 알림을 보내도록 구성할 수 있습니다.  알림 메커니즘을 구성할 수도 있습니다.  예를 들어, 알림은 이메일이나 SNMP 트랩으로 전송될 수 있습니다. 
---
= 알림 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이벤트가 생성되거나 사용자에게 할당될 때 Unified Manager 서버가 알림을 보내도록 구성할 수 있습니다.  알림 메커니즘을 구성할 수도 있습니다.  예를 들어, 알림은 이메일이나 SNMP 트랩으로 전송될 수 있습니다.

애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.



== 이메일

이 영역에서는 알림에 대한 다음 이메일 설정을 구성할 수 있습니다.

* *발신자 주소*
+
경고 알림이 전송되는 이메일 주소를 지정합니다.  이 값은 보고서가 공유될 때 발신자 주소로도 사용됩니다.  보낸 사람 주소에 "ActiveIQUnifiedManager@localhost.com"이라는 주소가 미리 입력되어 있는 경우 모든 이메일 알림이 성공적으로 전달되도록 실제로 작동하는 이메일 주소로 변경해야 합니다.





== SMTP 서버

이 영역에서는 다음 SMTP 서버 설정을 구성할 수 있습니다.

* *호스트 이름 또는 IP 주소*
+
지정된 수신자에게 경고 알림을 보내는 데 사용되는 SMTP 호스트 서버의 호스트 이름을 지정합니다.

* *사용자 이름*
+
SMTP 사용자 이름을 지정합니다.  SMTP 사용자 이름은 SMTP 서버에서 SMTPAUTH가 활성화된 경우에만 필요합니다.

* *비밀번호*
+
SMTP 비밀번호를 지정합니다.  SMTP 사용자 이름은 SMTP 서버에서 SMTPAUTH가 활성화된 경우에만 필요합니다.

* *포트*
+
SMTP 호스트 서버가 경고 알림을 보내는 데 사용하는 포트를 지정합니다.

+
기본값은 25입니다.

* *START/TLS 사용*
+
이 상자를 선택하면 TLS/SSL 프로토콜(start_tls 및 StartTLS라고도 함)을 사용하여 SMTP 서버와 관리 서버 간의 안전한 통신이 제공됩니다.

* *SSL을 사용하세요*
+
이 상자를 선택하면 SSL 프로토콜을 사용하여 SMTP 서버와 관리 서버 간의 안전한 통신이 제공됩니다.





== SNMP

이 영역에서는 다음 SNMP 트랩 설정을 구성할 수 있습니다.

* *버전*
+
필요한 보안 유형에 따라 사용할 SNMP 버전을 지정합니다.  옵션으로는 버전 1, 버전 3, 인증이 포함된 버전 3, 인증 및 암호화가 포함된 버전 3이 있습니다.  기본값은 버전 1입니다.

* *트랩 대상 호스트*
+
관리 서버에서 보낸 SNMP 트랩을 수신하는 호스트 이름 또는 IP 주소(IPv4 또는 IPv6)를 지정합니다.  여러 개의 트랩 대상을 지정하려면 각 호스트를 쉼표로 구분하세요.

+
[NOTE]
====
"버전" 및 "아웃바운드 포트"와 같은 기타 모든 SNMP 설정은 목록에 있는 모든 호스트에서 동일해야 합니다.

====
* *아웃바운드 트랩 포트*
+
SNMP 서버가 관리 서버에서 보낸 트랩을 수신하는 포트를 지정합니다.

+
기본값은 162입니다.

* *지역 사회*
+
호스트에 접근하기 위한 커뮤니티 문자열입니다.

* *엔진 ID*
+
SNMP 에이전트의 고유 식별자를 지정하며 관리 서버에서 자동으로 생성됩니다.  엔진 ID는 SNMP 버전 3, 인증 기능이 있는 SNMP 버전 3, 인증 및 암호화 기능이 있는 SNMP 버전 3에서 사용할 수 있습니다.

* *사용자 이름*
+
SNMP 사용자 이름을 지정합니다.  사용자 이름은 SNMP 버전 3, 인증 기능이 있는 SNMP 버전 3, 인증 및 암호화 기능이 있는 SNMP 버전 3에서 사용할 수 있습니다.

* *인증 프로토콜*
+
사용자를 인증하는 데 사용되는 프로토콜을 지정합니다.  프로토콜 옵션에는 MD5와 SHA가 있습니다.  기본값은 MD5입니다.  인증 프로토콜은 인증 기능이 있는 SNMP 버전 3 및 인증 및 암호화 기능이 있는 SNMP 버전 3에서 사용할 수 있습니다.

* *인증 비밀번호*
+
사용자를 인증할 때 사용되는 비밀번호를 지정합니다.  인증 암호는 인증 기능이 있는 SNMP 버전 3 및 인증 및 암호화 기능이 있는 SNMP 버전 3에서 사용할 수 있습니다.

* *개인정보보호 프로토콜*
+
SNMP 메시지를 암호화하는 데 사용되는 개인정보 보호 프로토콜을 지정합니다.  프로토콜 옵션에는 AES 128과 DES가 포함됩니다.  기본값은 AES 128입니다.  SNMP 버전 3에서는 인증 및 암호화 기능을 갖춘 개인정보 보호 프로토콜을 사용할 수 있습니다.

* *개인정보 비밀번호*
+
개인정보 보호 프로토콜을 사용할 때 비밀번호를 지정합니다.  개인 정보 보호 암호는 인증 및 암호화 기능이 있는 SNMP 버전 3에서 사용할 수 있습니다.



SNMP 개체 및 트랩에 대한 자세한 내용은 다음을 다운로드할 수 있습니다.link:https://mysupport.netapp.com/site/tools/tool-eula/aiqum-mib["Active IQ Unified Manager MIB"^] NetApp 지원 사이트에서.
