---
permalink: events/reference_supported_unified_manager_cli_commands.html 
sidebar: sidebar 
keywords: supported, unified manager, cli, commands, cmd, um cli, um run, 
summary: '스토리지 관리자는 CLI 명령을 사용하여 스토리지 개체(예: 클러스터, 집계, 볼륨, Q트리, LUN)에 대한 쿼리를 수행할 수 있습니다.' 
---
= 지원되는 Unified Manager CLI 명령
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 관리자는 CLI 명령을 사용하여 스토리지 개체(예: 클러스터, 집계, 볼륨, Q트리, LUN)에 대한 쿼리를 수행할 수 있습니다.  CLI 명령을 사용하여 Unified Manager 내부 데이터베이스와 ONTAP 데이터베이스를 쿼리할 수 있습니다.  작업의 시작이나 끝에서 실행되거나 경고가 발생할 때 실행되는 스크립트에서 CLI 명령을 사용할 수도 있습니다.

모든 명령은 다음 명령으로 시작해야 합니다. `um cli login` 인증을 위해 유효한 사용자 이름과 비밀번호가 필요합니다.


NOTE: _um run_ 명령을 실행하려면 계정에 _console_ 애플리케이션 액세스 권한이 있는지 확인하세요.

|===
| CLI 명령 | 설명 | 산출 


 a| 
`um cli login -u <username> [-p <password>]`
 a| 
CLI에 로그인합니다.  보안 문제 때문에 "-u" 옵션 뒤에는 사용자 이름만 입력해야 합니다.  이 방법을 사용하면 비밀번호를 입력하라는 메시지가 표시되며, 비밀번호는 기록이나 프로세스 테이블에 저장되지 않습니다.  세션은 로그인 후 3시간 후에 만료되며, 그 후 사용자는 다시 로그인해야 합니다.
 a| 
해당 메시지를 표시합니다.



 a| 
`um cli logout`
 a| 
CLI에서 로그아웃합니다.
 a| 
해당 메시지를 표시합니다.



 a| 
`um help`
 a| 
모든 첫 번째 레벨 하위 명령을 표시합니다.
 a| 
모든 첫 번째 레벨 하위 명령을 표시합니다.



 a| 
`um run cmd [ -t <timeout> ] <cluster> <command>`
 a| 
하나 이상의 호스트에서 명령을 실행하는 가장 간단한 방법입니다.  주로 ONTAP 에서 작업을 수행하거나 가져오기 위한 경고 스크립팅에 사용됩니다.  선택적인 timeout 인수는 클라이언트에서 명령이 완료되는 데 걸리는 최대 시간 제한(초)을 설정합니다.  기본값은 0(영원히 대기)입니다.
 a| 
ONTAP 에서 받은 내용입니다.



 a| 
`um run query <sql command>`
 a| 
SQL 쿼리를 실행합니다.  데이터베이스에서 읽는 쿼리만 허용됩니다.  모든 업데이트, 삽입 또는 삭제 작업은 지원되지 않습니다.
 a| 
결과는 표 형식으로 표시됩니다.  빈 집합이 반환되거나 구문 오류 또는 잘못된 요청이 있는 경우 해당 오류 메시지가 표시됩니다.



 a| 
`um datasource add -u <username> -P <password> [ -t <protocol> ] [ -p <port> ] <hostname-or-ip>`
 a| 
관리되는 스토리지 시스템 목록에 데이터 소스를 추가합니다.  데이터 소스는 저장 시스템에 대한 연결이 어떻게 이루어지는지 설명합니다.  데이터 소스를 추가할 때는 -u(사용자 이름) 및 -P(비밀번호) 옵션을 지정해야 합니다.  -t(프로토콜) 옵션은 클러스터와 통신하는 데 사용되는 프로토콜(http 또는 https)을 지정합니다.  프로토콜을 지정하지 않으면 두 프로토콜이 모두 시도됩니다. -p(포트) 옵션은 클러스터와 통신하는 데 사용되는 포트를 지정합니다.  포트가 지정되지 않으면 적절한 프로토콜의 기본값이 시도됩니다.  이 명령은 스토리지 관리자만 실행할 수 있습니다.
 a| 
사용자에게 인증서를 수락하라는 메시지를 표시하고 해당 메시지를 인쇄합니다.



 a| 
`um datasource list [ <datasource-id>]`
 a| 
관리형 스토리지 시스템의 데이터 소스를 표시합니다.
 a| 
다음 값을 표 형식으로 표시합니다. `ID Address Port, Protocol Acquisition Status, Analysis Status, Communication status, Acquisition Message, and Analysis Message` .



 a| 
`um datasource modify [ -h <hostname-or-ip> ] [ -u <username> ] [ -P <password> ] [ -t <protocol> ] [ -p <port> ] <datasource-id>`
 a| 
하나 이상의 데이터 소스 옵션을 수정합니다.  저장소 관리자만 실행할 수 있습니다.
 a| 
해당 메시지를 표시합니다.



 a| 
`um datasource remove <datasource-id>`
 a| 
Unified Manager에서 데이터 소스(클러스터)를 제거합니다.
 a| 
해당 메시지를 표시합니다.



 a| 
`um option list [ <option> .. ]`
 a| 
set 명령을 사용하여 구성할 수 있는 모든 옵션을 나열합니다.
 a| 
다음 값을 표 형식으로 표시합니다. `Name, Value, Default Value, and Requires Restart.`



 a| 
`um option set <option-name>=<option-value> [ <option-name>=<option-value> ... ]`
 a| 
하나 이상의 옵션을 설정합니다.  해당 명령은 스토리지 관리자만 실행할 수 있습니다.
 a| 
해당 메시지를 표시합니다.



 a| 
`um version`
 a| 
Unified Manager 소프트웨어 버전을 표시합니다.
 a| 
`Version ("9.6")`



 a| 
`um lun list [-q] [ -ObjectType <object-id>]`
 a| 
지정된 객체를 필터링한 후 LUN을 나열합니다.  -q는 모든 명령에 헤더를 표시하지 않도록 설정합니다.  ObjectType은 lun, qtree, cluster, volume, quota 또는 svm일 수 있습니다.

예를 들어:

*`um lun list -cluster 1`*

이 예에서 "-cluster"는 objectType이고 "1"은 objectId입니다.  이 명령은 클러스터 내의 ID가 1인 모든 LUN을 나열합니다.
 a| 
다음 값을 표 형식으로 표시합니다. `ID and LUN path.`



 a| 
`um svm list [-q] [ -ObjectType <object-id>]`
 a| 
지정된 객체를 필터링한 후 스토리지 VM을 나열합니다.  ObjectType은 lun, qtree, cluster, volume, quota 또는 svm이 될 수 있습니다.

예를 들어:

*`um svm list -cluster 1`*

이 예에서 "-cluster"는 objectType이고 "1"은 objectId입니다.  이 명령은 ID가 1인 클러스터 내의 모든 스토리지 VM을 나열합니다.
 a| 
다음 값을 표 형식으로 표시합니다. `Name and Cluster ID.`



 a| 
`um qtree list [-q] [ -ObjectType <object-id>]`
 a| 
지정된 객체를 필터링한 후 qtree를 나열합니다.  -q는 모든 명령에 헤더를 표시하지 않도록 설정합니다.  ObjectType은 lun, qtree, cluster, volume, quota 또는 svm일 수 있습니다.

예를 들어:

*`um qtree list -cluster 1`*

이 예에서 "-cluster"는 objectType이고 "1"은 objectId입니다.  이 명령은 ID가 1인 클러스터 내의 모든 qtree를 나열합니다.
 a| 
다음 값을 표 형식으로 표시합니다. `Qtree ID and Qtree Name.`



 a| 
`um disk list [-q] [-ObjectType <object-id>]`
 a| 
지정된 객체를 필터링한 후 디스크를 나열합니다.  ObjectType은 disk, aggr, node 또는 cluster가 될 수 있습니다.

예를 들어:

*`um disk list -cluster 1`*

이 예에서 "-cluster"는 objectType이고 "1"은 objectId입니다.  이 명령은 클러스터 내에서 ID가 1인 모든 디스크를 나열합니다.
 a| 
다음 값을 표 형식으로 표시합니다. `ObjectType and object-id` .



 a| 
`um cluster list [-q] [-ObjectType <object-id>]`
 a| 
지정된 객체를 필터링한 후 클러스터를 나열합니다.  ObjectType은 disk, aggr, node, cluster, lun, qtree, volume, quota 또는 svm일 수 있습니다.

예를 들어:

*`um cluster list -aggr 1`*

이 예에서 "-aggr"은 objectType이고 "1"은 objectId입니다.  이 명령은 ID 1의 집계가 속한 클러스터를 나열합니다.
 a| 
다음 값을 표 형식으로 표시합니다. `Name, Full Name, Serial Number, Datasource Id, Last Refresh Time, and Resource Key` .



 a| 
`um cluster node list [-q] [-ObjectType <object-id>]`
 a| 
지정된 객체를 필터링한 후 클러스터 노드를 나열합니다.  ObjectType은 disk, aggr, node 또는 cluster가 될 수 있습니다.

예를 들어:

*`um cluster node list -cluster 1`*

이 예에서 "-cluster"는 objectType이고 "1"은 objectId입니다.  이 명령은 ID가 1인 클러스터 내의 모든 노드를 나열합니다.
 a| 
다음 값을 표 형식으로 표시합니다. `Name and Cluster ID` .



 a| 
`um volume list [-q] [-ObjectType <object-id>]`
 a| 
지정된 객체를 필터링한 후 볼륨을 나열합니다.  ObjectType은 lun, qtree, cluster, volume, quota, svm 또는 aggregate가 될 수 있습니다.

예를 들어:

*`um volume list -cluster 1`*

이 예에서 "-cluster"는 objectType이고 "1"은 objectId입니다.  이 명령은 ID가 1인 클러스터 내의 모든 볼륨을 나열합니다.
 a| 
다음 값을 표 형식으로 표시합니다. `Volume ID and Volume Name` .



 a| 
`um quota user list [-q] [-ObjectType <object-id>]`
 a| 
지정된 객체를 필터링한 후 할당량 사용자를 나열합니다.  ObjectType은 qtree, cluster, volume, quota 또는 svm이 될 수 있습니다.

예를 들어:

*`um quota user list -cluster 1`*

이 예에서 "-cluster"는 objectType이고 "1"은 objectId입니다.  이 명령은 클러스터 내에서 ID가 1인 모든 할당량 사용자를 나열합니다.
 a| 
다음 값을 표 형식으로 표시합니다. `ID, Name, SID and Email` .



 a| 
`um aggr list [-q] [-ObjectType <object-id>]`
 a| 
지정된 객체를 필터링한 후 집계를 나열합니다.  ObjectType은 disk, aggr, node, cluster 또는 volume이 될 수 있습니다.

예를 들어:

*`um aggr list -cluster 1`*

이 예에서 "-cluster"는 objectType이고 "1"은 objectId입니다.  이 명령은 ID가 1인 클러스터 내의 모든 집계를 나열합니다.
 a| 
다음 값을 표 형식으로 표시합니다. `Aggr ID, and Aggr Name` .



 a| 
`um event ack <event-ids>`
 a| 
하나 이상의 이벤트를 확인합니다.
 a| 
해당 메시지를 표시합니다.



 a| 
`um event resolve <event-ids>`
 a| 
하나 이상의 이벤트를 해결합니다.
 a| 
해당 메시지를 표시합니다.



 a| 
`um event assign -u <username> <event-id>`
 a| 
사용자에게 이벤트를 할당합니다.
 a| 
해당 메시지를 표시합니다.



 a| 
`um event list [ -s <source> ] [ -S <event-state-filter-list>.. ] [ <event-id> .. ]`
 a| 
시스템이나 사용자가 생성한 이벤트를 나열합니다.  소스, 상태, ID를 기준으로 이벤트를 필터링합니다.
 a| 
다음 값을 표 형식으로 표시합니다. `Source, Source type, Name, Severity, State, User and Timestamp` .



 a| 
`um backup restore -f <backup_file_path_and_name>`
 a| 
.7z 파일을 사용하여 MySQL 데이터베이스 백업을 복원합니다.
 a| 
해당 메시지를 표시합니다.

|===