---
permalink: events/reference_event_setup_page.html 
sidebar: sidebar 
keywords: event, setup, page, command, buttons, list, view 
summary: 이벤트 설정 페이지에는 비활성화된 이벤트 목록이 표시되고, 연관된 개체 유형 및 이벤트의 심각도와 같은 정보가 제공됩니다.  이벤트를 전역적으로 비활성화하거나 활성화하는 등의 작업을 수행할 수도 있습니다. 
---
= 이벤트 설정 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이벤트 설정 페이지에는 비활성화된 이벤트 목록이 표시되고, 연관된 개체 유형 및 이벤트의 심각도와 같은 정보가 제공됩니다.  이벤트를 전역적으로 비활성화하거나 활성화하는 등의 작업을 수행할 수도 있습니다.

애플리케이션 관리자 또는 스토리지 관리자 역할이 있는 경우에만 이 페이지에 액세스할 수 있습니다.



[[command-buttons]]
== 명령 버튼

명령 단추를 사용하면 선택한 이벤트에 대해 다음 작업을 수행할 수 있습니다.

* *장애를 입히다*
+
이벤트를 비활성화하는 데 사용할 수 있는 이벤트 비활성화 대화 상자를 실행합니다.

* *할 수 있게 하다*
+
이전에 비활성화하기로 선택한 이벤트를 선택하여 활성화합니다.

* *업로드 규칙*
+
외부 네트워크 접속이 없는 사이트에서 Active IQ 규칙 파일을 수동으로 Unified Manager에 업로드할 수 있는 업로드 규칙 대화 상자를 실행합니다.  규칙은 Active IQ 플랫폼에서 정의한 시스템 구성, 케이블링, 모범 사례 및 가용성에 대한 이벤트를 생성하기 위해 클러스터 AutoSupport 메시지에 대해 실행됩니다.

* *EMS 이벤트 구독*
+
모니터링하고 있는 클러스터에서 특정 EMS(이벤트 관리 시스템) 이벤트를 수신하도록 구독할 수 있는 EMS 이벤트 구독 대화 상자를 실행합니다.  EMS는 클러스터에서 발생하는 이벤트에 대한 정보를 수집합니다.  구독된 EMS 이벤트에 대한 알림을 받으면 적절한 심각도에 따라 Unified Manager 이벤트가 생성됩니다.





[[list-view]]
== 목록 보기

목록 보기는 비활성화된 이벤트에 대한 정보를 (표 형식으로) 표시합니다.  열 필터를 사용하면 표시되는 데이터를 사용자 지정할 수 있습니다.

* *이벤트*
+
비활성화된 이벤트의 이름을 표시합니다.

* *심각성*
+
이벤트의 심각도를 표시합니다.  심각도는 '중요', '오류', '경고' 또는 '정보'일 수 있습니다.

* *소스 유형*
+
이벤트가 생성된 소스 유형을 표시합니다.


