---
permalink: events/reference_logical_interface_events.html 
sidebar: sidebar 
keywords: 'network, interface, (lif) events, impact area, availability, configuration, performance' 
summary: '네트워크 인터페이스 이벤트는 네트워크 인터페이스(LIF) 상태에 대한 정보를 제공하므로 잠재적인 문제를 모니터링할 수 있습니다.  이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형, 심각도가 포함됩니다.' 
---
= 네트워크 인터페이스(LIF) 이벤트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
네트워크 인터페이스 이벤트는 네트워크 인터페이스(LIF) 상태에 대한 정보를 제공하므로 잠재적인 문제를 모니터링할 수 있습니다.  이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형, 심각도가 포함됩니다.



[[impact-area-availability]]
== 영향 영역: 가용성

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
네트워크 인터페이스 상태 다운(ocumEvtLifStatusDown)
 a| 
위험
 a| 
인터페이스
 a| 
오류



 a| 
FC/FCoE 네트워크 인터페이스 상태 다운(ocumEvtFCLifStatusDown)
 a| 
위험
 a| 
인터페이스
 a| 
오류



 a| 
네트워크 인터페이스 장애 조치가 불가능합니다(ocumEvtLifFailoverNotPossible)
 a| 
위험
 a| 
인터페이스
 a| 
경고



 a| 
네트워크 인터페이스가 홈 포트에 없음(ocumEvtLifNotAtHomePort)
 a| 
위험
 a| 
인터페이스
 a| 
경고

|===


[[impact-area-configuration]]
== 영향 영역: 구성

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
네트워크 인터페이스 경로가 구성되지 않았습니다(해당 없음)
 a| 
이벤트
 a| 
인터페이스
 a| 
정보

|===


[[impact-area-performance]]
== 영향 영역: 성능

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
네트워크 인터페이스 MB/s 위험 임계값 위반(ocumNetworkLifMbpsIncident)
 a| 
사건
 a| 
인터페이스
 a| 
비판적인



 a| 
네트워크 인터페이스 MB/s 경고 임계값 위반(ocumNetworkLifMbpsWarning)
 a| 
위험
 a| 
인터페이스
 a| 
경고



 a| 
FC 네트워크 인터페이스 MB/s 위험 임계값 위반(ocumFcpLifMbpsIncident)
 a| 
사건
 a| 
인터페이스
 a| 
비판적인



 a| 
FC 네트워크 인터페이스 MB/s 경고 임계값 위반(ocumFcpLifMbpsWarning)
 a| 
위험
 a| 
인터페이스
 a| 
경고



 a| 
NVMf FC 네트워크 인터페이스 MB/s 중요 임계값 위반(ocumNvmfFcLifMbpsIncident)
 a| 
사건
 a| 
인터페이스
 a| 
비판적인



 a| 
NVMf FC 네트워크 인터페이스 MB/s 경고 임계값 위반(ocumNvmfFcLifMbpsWarning)
 a| 
위험
 a| 
인터페이스
 a| 
경고

|===