---
permalink: events/reference_snapmirror_and_vault_relationship_events.html 
sidebar: sidebar 
keywords: asynchronous, mirror, vault, relationship, events, impact area, protection 
summary: 비동기 미러 및 볼트 관계 이벤트는 비동기 SnapMirror 및 볼트 관계의 상태에 대한 정보를 제공하여 잠재적인 문제를 모니터링할 수 있도록 해줍니다.  비동기 미러 및 볼트 관계 이벤트는 볼륨 및 스토리지 VM 보호 관계 모두에서 지원됩니다.  하지만 저장소 VM 재해 복구에는 Vault 관계만 지원되지 않습니다.  이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형, 심각도가 포함됩니다. 
---
= 비동기 미러 및 볼트 관계 이벤트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
비동기 미러 및 볼트 관계 이벤트는 비동기 SnapMirror 및 볼트 관계의 상태에 대한 정보를 제공하여 잠재적인 문제를 모니터링할 수 있도록 해줍니다.  비동기 미러 및 볼트 관계 이벤트는 볼륨 및 스토리지 VM 보호 관계 모두에서 지원됩니다.  하지만 저장소 VM 재해 복구에는 Vault 관계만 지원되지 않습니다.  이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형, 심각도가 포함됩니다.



[[impact-area-protection]]
== 영향 영역: 보호

[NOTE]
====
SnapMirror 및 Vault 관계 이벤트는 Storage VM 재해 복구로 보호되는 Storage VM에 대해서도 생성되지만 구성 개체 관계에 대해서는 생성되지 않습니다.

====
|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
비동기 미러 및 볼트가 비정상입니다(ocumEvtMirrorVaultRelationshipUnhealthy)
 a| 
위험
 a| 
SnapMirror 관계
 a| 
경고



 a| 
비동기 미러 및 볼트가 끊어짐(ocumEvtMirrorVaultRelationshipStateBrokenoff)
 a| 
위험
 a| 
SnapMirror 관계
 a| 
오류



 a| 
비동기 미러 및 볼트 초기화 실패(ocumEvtMirrorVaultRelationshipInitializeFailed)
 a| 
위험
 a| 
SnapMirror 관계
 a| 
오류



 a| 
비동기 미러 및 볼트 업데이트 실패(ocumEvtMirrorVaultRelationshipUpdateFailed)
 a| 
위험
 a| 
SnapMirror 관계
 a| 
오류



 a| 
비동기 미러 및 볼트 지연 오류(ocumEvtMirrorVaultRelationshipLagError)
 a| 
위험
 a| 
SnapMirror 관계
 a| 
오류



 a| 
비동기 미러 및 볼트 지연 경고(ocumEvtMirrorVaultRelationshipLagWarning)
 a| 
위험
 a| 
SnapMirror 관계
 a| 
경고



 a| 
비동기 미러 및 볼트 재동기화 실패(ocumEvtMirrorVaultRelationshipResyncFailed)
 a| 
위험
 a| 
SnapMirror 관계
 a| 
오류

|===
[NOTE]
====
"SnapMirror 업데이트 실패" 이벤트는 Active IQ 포털(Config Advisor)에서 발생합니다.

====