---
permalink: events/reference_lun_events.html 
sidebar: sidebar 
keywords: lun, events, impact area, availability, capacity, configuration, performance 
summary: LUN 이벤트는 LUN 상태에 대한 정보를 제공하므로 잠재적인 문제를 모니터링할 수 있습니다.  이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형, 심각도가 포함됩니다. 
---
= LUN 이벤트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LUN 이벤트는 LUN 상태에 대한 정보를 제공하므로 잠재적인 문제를 모니터링할 수 있습니다.  이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형, 심각도가 포함됩니다.



[[impact-area-availability]]
== 영향 영역: 가용성

별표(*)는 Unified Manager 이벤트로 변환된 EMS 이벤트를 식별합니다.

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
LUN 오프라인(ocumEvtLunOffline)
 a| 
사건
 a| 
LUN
 a| 
비판적인



 a| 
LUN 파괴됨 *(lunDestroy)
 a| 
이벤트
 a| 
LUN
 a| 
정보



 a| 
igroup에서 지원되지 않는 운영 체제로 LUN이 매핑되었습니다(igroupUnsupportedOsType)
 a| 
사건
 a| 
LUN
 a| 
경고



 a| 
LUN에 액세스하기 위한 단일 활성 경로(ocumEvtLunSingleActivePath)
 a| 
위험
 a| 
LUN
 a| 
경고



 a| 
LUN에 액세스할 활성 경로가 없습니다(ocumEvtLunNotReachable)
 a| 
사건
 a| 
LUN
 a| 
비판적인



 a| 
LUN에 액세스하기 위한 최적화된 경로가 없습니다(ocumEvtLunOptimizedPathInactive)
 a| 
위험
 a| 
LUN
 a| 
경고



 a| 
HA 파트너에서 LUN에 액세스할 경로가 없습니다(ocumEvtLunHaPathInactive)
 a| 
위험
 a| 
LUN
 a| 
경고



 a| 
HA 쌍의 한 노드에서 LUN에 액세스할 경로가 없습니다(ocumEvtLunNodePathStatusDown)
 a| 
위험
 a| 
LUN
 a| 
오류

|===


[[impact-area-capacity]]
== 영향 영역: 용량

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
LUN 스냅샷 복사를 위한 공간이 부족합니다(ocumEvtLunSnapshotNotPossible)
 a| 
위험
 a| 
용량
 a| 
경고

|===


[[impact-area-configuration]]
== 영향 영역: 구성

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
igroup에서 지원되지 않는 운영 체제로 LUN이 매핑되었습니다(igroupUnsupportedOsType)
 a| 
위험
 a| 
LUN
 a| 
경고

|===


[[impact-area-performance]]
== 영향 영역: 성능

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
LUN IOPS 위험 임계값 위반(ocumLunIopsIncident)
 a| 
사건
 a| 
LUN
 a| 
비판적인



 a| 
LUN IOPS 경고 임계값 위반(ocumLunIopsWarning)
 a| 
위험
 a| 
LUN
 a| 
경고



 a| 
LUN MB/s 중요 임계값 위반(ocumLunMbpsIncident)
 a| 
사건
 a| 
LUN
 a| 
비판적인



 a| 
LUN MB/s 경고 임계값 위반(ocumLunMbpsWarning)
 a| 
위험
 a| 
LUN
 a| 
경고



 a| 
LUN 대기 시간(ms/op) 위험 임계값 위반(ocumLunLatencyIncident)
 a| 
사건
 a| 
LUN
 a| 
비판적인



 a| 
LUN 대기 시간(ms/op) 경고 임계값 위반(ocumLunLatencyWarning)
 a| 
위험
 a| 
LUN
 a| 
경고



 a| 
LUN 지연 시간 및 IOPS 위험 임계값 위반(ocumLunLatencyIopsIncident)
 a| 
사건
 a| 
LUN
 a| 
비판적인



 a| 
LUN 지연 시간 및 IOPS 경고 임계값 위반(ocumLunLatencyIopsWarning)
 a| 
위험
 a| 
LUN
 a| 
경고



 a| 
LUN 지연 시간 및 MB/s 중요 임계값 위반(ocumLunLatencyMbpsIncident)
 a| 
사건
 a| 
LUN
 a| 
비판적인



 a| 
LUN 지연 시간 및 MB/s 경고 임계값 위반(ocumLunLatencyMbpsWarning)
 a| 
위험
 a| 
LUN
 a| 
경고



 a| 
LUN 지연 시간 및 집계 성능 사용 용량 중요 임계값 위반(ocumLunLatencyAggregatePerfCapacityUsedIncident)
 a| 
사건
 a| 
LUN
 a| 
비판적인



 a| 
LUN 지연 시간 및 총 성능 용량 사용 경고 임계값 위반(ocumLunLatencyAggregatePerfCapacityUsedWarning)
 a| 
위험
 a| 
LUN
 a| 
경고



 a| 
LUN 지연 시간 및 집계 사용률 중요 임계값 위반(ocumLunLatencyAggregateUtilizationIncident)
 a| 
사건
 a| 
LUN
 a| 
비판적인



 a| 
LUN 지연 시간 및 집계 사용률 경고 임계값 위반(ocumLunLatencyAggregateUtilizationWarning)
 a| 
위험
 a| 
LUN
 a| 
경고



 a| 
LUN 지연 시간 및 노드 성능 사용 용량 위험 임계값 위반(ocumLunLatencyNodePerfCapacityUsedIncident)
 a| 
사건
 a| 
LUN
 a| 
비판적인



 a| 
LUN 지연 시간 및 노드 성능 사용 용량 경고 임계값 위반(ocumLunLatencyNodePerfCapacityUsedWarning)
 a| 
위험
 a| 
LUN
 a| 
경고



 a| 
LUN 지연 시간 및 노드 성능 사용 용량 - 인수 위험 임계값 위반(ocumLunLatencyAggregatePerfCapacityUsedTakeoverIncident)
 a| 
사건
 a| 
LUN
 a| 
비판적인



 a| 
LUN 지연 시간 및 노드 성능 사용 용량 - 인수 경고 임계값 위반(ocumLunLatencyAggregatePerfCapacityUsedTakeoverWarning)
 a| 
위험
 a| 
LUN
 a| 
경고



 a| 
LUN 지연 시간 및 노드 사용률 위험 임계값 위반(ocumLunLatencyNodeUtilizationIncident)
 a| 
사건
 a| 
LUN
 a| 
비판적인



 a| 
LUN 지연 시간 및 노드 사용률 경고 임계값 위반(ocumLunLatencyNodeUtilizationWarning)
 a| 
위험
 a| 
LUN
 a| 
경고



 a| 
QoS LUN 최대 IOPS 경고 임계값 위반(ocumQosLunMaxIopsWarning)
 a| 
위험
 a| 
LUN
 a| 
경고



 a| 
QoS LUN 최대 MB/s 경고 임계값 위반(ocumQosLunMaxMbpsWarning)
 a| 
위험
 a| 
LUN
 a| 
경고



 a| 
성능 서비스 수준 정책(ocumConformanceLatencyWarning)에 정의된 대로 워크로드 LUN 대기 시간 임계값이 위반되었습니다.
 a| 
위험
 a| 
LUN
 a| 
경고

|===