---
permalink: events/reference_event_details_page.html 
sidebar: sidebar 
keywords: event, details, page 
summary: 이벤트 세부 정보 페이지에서는 이벤트 심각도, 영향 수준, 영향 영역, 이벤트 소스 등 선택한 이벤트의 세부 정보를 볼 수 있습니다.  문제를 해결하기 위한 가능한 해결책에 대한 추가 정보도 볼 수 있습니다. 
---
= 이벤트 세부 정보 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이벤트 세부 정보 페이지에서는 이벤트 심각도, 영향 수준, 영향 영역, 이벤트 소스 등 선택한 이벤트의 세부 정보를 볼 수 있습니다.  문제를 해결하기 위한 가능한 해결책에 대한 추가 정보도 볼 수 있습니다.

* *이벤트 이름*
+
이벤트 이름과 이벤트가 마지막으로 확인된 시간입니다.

+
비성능 이벤트의 경우 이벤트가 새 이벤트 또는 확인된 상태인 동안에는 마지막으로 확인된 정보를 알 수 없으므로 숨겨집니다.

* *이벤트 설명*
+
이벤트에 대한 간략한 설명입니다.

+
어떤 경우에는 이벤트가 발생한 이유가 이벤트 설명에 제공됩니다.

* *경쟁의 구성 요소*
+
동적 성능 이벤트의 경우 이 섹션에는 클러스터의 논리적 및 물리적 구성 요소를 나타내는 아이콘이 표시됩니다.  구성 요소가 경합 중이면 해당 아이콘이 빨간색으로 동그라미로 표시됩니다.

+
여기에 표시된 구성 요소에 대한 설명은 _클러스터 구성 요소와 이들이 경합할 수 있는 이유_를 참조하세요.



이벤트 정보, 시스템 진단 및 제안된 작업 섹션은 다른 항목에서 설명합니다.



[[command-buttons]]
== 명령 버튼

명령 버튼을 사용하면 다음 작업을 수행할 수 있습니다.

* *노트 아이콘*
+
이벤트에 대한 메모를 추가하거나 업데이트하고, 다른 사용자가 남긴 메모를 모두 검토할 수 있습니다.



*작업 메뉴*

* *나에게 할당*
+
이벤트를 당신에게 할당합니다.

* *다른 사람에게 할당*
+
이벤트를 다른 사용자에게 할당하거나 재할당할 수 있는 소유자 할당 대화 상자를 엽니다.

+
사용자에게 이벤트를 할당하면 해당 사용자의 이름과 이벤트가 할당된 시간이 선택한 이벤트의 이벤트 목록에 추가됩니다.

+
소유권 필드를 비워두면 이벤트 할당을 해제할 수도 있습니다.

* *인정하다*
+
선택한 이벤트를 확인하여 반복적인 알림 알림을 더 이상 받지 않도록 합니다.

+
이벤트를 확인하면 사용자 이름과 이벤트를 확인한 시간이 선택한 이벤트의 이벤트 목록(확인자)에 추가됩니다.  어떤 사건을 인정하면, 그 사건을 관리할 책임을 맡게 됩니다.

* *해결됨으로 표시*
+
이벤트 상태를 해결됨으로 변경할 수 있습니다.

+
이벤트를 해결하면 사용자 이름과 이벤트를 해결한 시간이 선택한 이벤트의 이벤트 목록(해결자)에 추가됩니다.  이벤트에 대한 시정 조치를 취한 후에는 이벤트를 해결됨으로 표시해야 합니다.

* *알림 추가*
+
선택한 이벤트에 대한 알림을 추가할 수 있는 알림 추가 대화 상자가 표시됩니다.


