---
permalink: events/reference_node_events.html 
sidebar: sidebar 
keywords: node, events, impact area, availability, capacity, configuration, performance, security 
summary: 노드 이벤트는 노드 상태에 대한 정보를 제공하므로 잠재적인 문제를 모니터링할 수 있습니다.  이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형, 심각도가 포함됩니다. 
---
= 노드 이벤트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드 이벤트는 노드 상태에 대한 정보를 제공하므로 잠재적인 문제를 모니터링할 수 있습니다.  이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형, 심각도가 포함됩니다.

별표(*)는 Unified Manager 이벤트로 변환된 EMS 이벤트를 식별합니다.



[[impact-area-availability]]
== 영향 영역: 가용성

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
노드 루트 볼륨 공간이 거의 가득 찼습니다(ocumEvtClusterNodeRootVolumeSpaceNearlyFull)
 a| 
위험
 a| 
마디
 a| 
경고



 a| 
클라우드 AWS MetaDataConnFail *(ocumCloudAwsMetadataConnFail)
 a| 
위험
 a| 
마디
 a| 
오류



 a| 
클라우드 AWS IAMCredsExpired *(ocumCloudAwsIamCredsExpired)
 a| 
위험
 a| 
마디
 a| 
오류



 a| 
클라우드 AWS IAMCredsInvalid *(ocumCloudAwsIamCredsInvalid)
 a| 
위험
 a| 
마디
 a| 
오류



 a| 
클라우드 AWS IAMCredsNotFound *(ocumCloudAwsIamCredsNotFound)
 a| 
위험
 a| 
마디
 a| 
오류



 a| 
클라우드 AWS IAMCredsNotInitialized *(ocumCloudAwsIamCredsNotInitialized)
 a| 
이벤트
 a| 
마디
 a| 
정보



 a| 
클라우드 AWS IAMRoleInvalid *(ocumCloudAwsIamRoleInvalid)
 a| 
위험
 a| 
마디
 a| 
오류



 a| 
클라우드 AWS IAMRoleNotFound *(ocumCloudAwsIamRoleNotFound)
 a| 
위험
 a| 
마디
 a| 
오류



 a| 
클라우드 계층 호스트를 확인할 수 없음 *(ocumObjstoreHostUnresolvable)
 a| 
위험
 a| 
마디
 a| 
오류



 a| 
클라우드 계층 클러스터 간 네트워크 인터페이스 다운 *(ocumObjstoreInterClusterLifDown)
 a| 
위험
 a| 
마디
 a| 
오류



 a| 
NFSv4 풀 중 하나가 소진되었습니다. *(nbladeNfsv4PoolEXhaust)
 a| 
사건
 a| 
마디
 a| 
비판적인



 a| 
요청 불일치 클라우드 계층 서명 *(oscSignatureMismatch)
 a| 
위험
 a| 
마디
 a| 
오류

|===


[[impact-area-capacity]]
== 영향 영역: 용량

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
QoS 모니터 메모리 최대화 *(ocumQosMonitorMemoryMaxed)
 a| 
위험
 a| 
마디
 a| 
오류



 a| 
QoS 모니터 메모리 감소 *(ocumQosMonitorMemoryAbated)
 a| 
이벤트
 a| 
마디
 a| 
정보

|===


[[impact-area-configuration]]
== 영향 영역: 구성

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
노드 이름이 변경됨(해당 없음)
 a| 
이벤트
 a| 
마디
 a| 
정보

|===


[[impact-area-performance]]
== 영향 영역: 성능

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
노드 IOPS 위험 임계값 위반(ocumNodeIopsIncident)
 a| 
사건
 a| 
마디
 a| 
비판적인



 a| 
노드 IOPS 경고 임계값 위반(ocumNodeIopsWarning)
 a| 
위험
 a| 
마디
 a| 
경고



 a| 
노드 MB/s 중요 임계값 위반(ocumNodeMbpsIncident)
 a| 
사건
 a| 
마디
 a| 
비판적인



 a| 
노드 MB/s 경고 임계값 위반(ocumNodeMbpsWarning)
 a| 
위험
 a| 
마디
 a| 
경고



 a| 
노드 대기 시간 ms/op 중요 임계값 위반(ocumNodeLatencyIncident)
 a| 
사건
 a| 
마디
 a| 
비판적인



 a| 
노드 지연 ms/op 경고 임계값 위반(ocumNodeLatencyWarning)
 a| 
위험
 a| 
마디
 a| 
경고



 a| 
노드 성능 용량 사용 임계 임계값 위반(ocumNodePerfCapacityUsedIncident)
 a| 
사건
 a| 
마디
 a| 
비판적인



 a| 
노드 성능 용량 사용 경고 임계값 위반(ocumNodePerfCapacityUsedWarning)
 a| 
위험
 a| 
마디
 a| 
경고



 a| 
노드 성능 용량 사용 - 인수 위험 임계값 위반(ocumNodePerfCapacityUsedTakeoverIncident)
 a| 
사건
 a| 
마디
 a| 
비판적인



 a| 
노드 성능 용량 사용 - 인수 경고 임계값 위반(ocumNodePerfCapacityUsedTakeoverWarning)
 a| 
위험
 a| 
마디
 a| 
경고



 a| 
노드 사용률 위험 임계값 위반(ocumNodeUtilizationIncident)
 a| 
사건
 a| 
마디
 a| 
비판적인



 a| 
노드 사용률 경고 임계값 위반(ocumNodeUtilizationWarning)
 a| 
위험
 a| 
마디
 a| 
경고



 a| 
노드 HA 쌍 과다 사용 임계값 위반(ocumNodeHaPairOverUtilizedInformation)
 a| 
이벤트
 a| 
마디
 a| 
정보



 a| 
노드 디스크 조각화 임계값 위반(ocumNodeDiskFragmentationWarning)
 a| 
위험
 a| 
마디
 a| 
경고



 a| 
성능 용량 사용 임계값 위반(ocumNodeOverUtilizedWarning)
 a| 
위험
 a| 
마디
 a| 
경고



 a| 
노드 동적 임계값 위반(ocumNodeDynamicEventWarning)
 a| 
위험
 a| 
마디
 a| 
경고

|===


[[impact-area-security]]
== 영향 영역: 보안

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
권고 ID: NTAP-<__권고 ID__>(ocumx)
 a| 
위험
 a| 
마디
 a| 
비판적인

|===