---
permalink: events/reference_nvme_namespace_events.html 
sidebar: sidebar 
keywords: nvme, namespace, events, impact area, availability, performance 
summary: NVMe 네임스페이스 이벤트는 네임스페이스의 상태에 대한 정보를 제공하므로 잠재적인 문제를 모니터링할 수 있습니다.  이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형, 심각도가 포함됩니다. 
---
= NVMe 네임스페이스 이벤트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVMe 네임스페이스 이벤트는 네임스페이스의 상태에 대한 정보를 제공하므로 잠재적인 문제를 모니터링할 수 있습니다.  이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형, 심각도가 포함됩니다.

별표(*)는 Unified Manager 이벤트로 변환된 EMS 이벤트를 식별합니다.



== 영향 영역: 가용성

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
NVMeNS 오프라인 *(nvmeNamespaceStatusOffline)
 a| 
이벤트
 a| 
네임스페이스
 a| 
정보



 a| 
NVMeNS 온라인 *(nvmeNamespaceStatusOnline)
 a| 
이벤트
 a| 
네임스페이스
 a| 
정보



 a| 
NVMeNS 공간 부족 *(nvmeNamespaceSpaceOutOfSpace)
 a| 
위험
 a| 
네임스페이스
 a| 
경고



 a| 
NVMeNS 파괴 *(nvmeNamespaceDestroy)
 a| 
이벤트
 a| 
네임스페이스
 a| 
정보

|===


== 영향 영역: 성능

|===
| 이벤트 이름(트랩 이름) | 영향 수준 | 소스 유형 | 심각성 


 a| 
NVMe 네임스페이스 IOPS 중요 임계값 위반(ocumNvmeNamespaceIopsIncident)
 a| 
사건
 a| 
네임스페이스
 a| 
비판적인



 a| 
NVMe 네임스페이스 IOPS 경고 임계값 위반(ocumNvmeNamespaceIopsWarning)
 a| 
위험
 a| 
네임스페이스
 a| 
경고



 a| 
NVMe 네임스페이스 MB/s 중요 임계값 위반(ocumNvmeNamespaceMbpsIncident)
 a| 
사건
 a| 
네임스페이스
 a| 
비판적인



 a| 
NVMe 네임스페이스 MB/s 경고 임계값 위반(ocumNvmeNamespaceMbpsWarning)
 a| 
위험
 a| 
네임스페이스
 a| 
경고



 a| 
NVMe 네임스페이스 대기 시간(ms/op) 중요 임계값 위반(ocumNvmeNamespaceLatencyIncident)
 a| 
사건
 a| 
네임스페이스
 a| 
비판적인



 a| 
NVMe 네임스페이스 대기 시간 ms/op 경고 임계값 위반(ocumNvmeNamespaceLatencyWarning)
 a| 
위험
 a| 
네임스페이스
 a| 
경고



 a| 
NVMe 네임스페이스 지연 시간 및 IOPS 중요 임계값 위반(ocumNvmeNamespaceLatencyIopsIncident)
 a| 
사건
 a| 
네임스페이스
 a| 
비판적인



 a| 
NVMe 네임스페이스 지연 및 IOPS 경고 임계값 위반(ocumNvmeNamespaceLatencyIopsWarning)
 a| 
위험
 a| 
네임스페이스
 a| 
경고



 a| 
NVMe 네임스페이스 지연 시간 및 MB/s 중요 임계값 위반(ocumNvmeNamespaceLatencyMbpsIncident)
 a| 
사건
 a| 
네임스페이스
 a| 
비판적인



 a| 
NVMe 네임스페이스 지연 시간 및 MB/s 경고 임계값 위반(ocumNvmeNamespaceLatencyMbpsWarning)
 a| 
위험
 a| 
네임스페이스
 a| 
경고

|===