---
permalink: events/reference_dynamic_performance_event_chart_details.html 
sidebar: sidebar 
keywords: dynamic, performance, event, chart, details 
summary: 동적 성능 이벤트의 경우 이벤트 세부 정보 페이지의 시스템 진단 섹션에는 경쟁 중인 클러스터 구성 요소의 대기 시간이나 사용량이 가장 높은 상위 워크로드가 나열됩니다.  성능 통계는 성능 이벤트가 감지된 시간부터 이벤트가 마지막으로 분석된 시간까지의 시간을 기준으로 합니다.  차트에는 경쟁 중인 클러스터 구성 요소에 대한 과거 성능 통계도 표시됩니다. 
---
= 동적 성능 이벤트 차트 세부 정보
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
동적 성능 이벤트의 경우 이벤트 세부 정보 페이지의 시스템 진단 섹션에는 경쟁 중인 클러스터 구성 요소의 대기 시간이나 사용량이 가장 높은 상위 워크로드가 나열됩니다.

성능 통계는 성능 이벤트가 감지된 시간부터 이벤트가 마지막으로 분석된 시간까지의 시간을 기준으로 합니다.  차트에는 경쟁 중인 클러스터 구성 요소에 대한 과거 성능 통계도 표시됩니다.

예를 들어, 구성 요소의 활용도가 높은 워크로드를 식별하여 활용도가 낮은 구성 요소로 어떤 워크로드를 옮겨야 할지 결정할 수 있습니다.  작업 부하를 이동하면 현재 구성 요소의 작업량이 줄어들어 해당 구성 요소가 경쟁에서 벗어날 수 있습니다.  이 섹션의 맨 위에는 이벤트가 감지되어 마지막으로 분석된 시간과 날짜 범위가 표시됩니다.  활성 이벤트(새 이벤트 또는 확인된 이벤트)의 경우 마지막으로 분석된 시간이 업데이트됩니다.

대기 시간 및 활동 차트에는 차트 위에 커서를 올려 놓으면 가장 많은 작업 부하의 이름이 표시됩니다.  차트 오른쪽에 있는 작업 유형 메뉴를 클릭하면 이벤트에서의 역할(상어, 괴롭힘, 피해자 등)에 따라 작업 부하를 정렬할 수 있으며, 경쟁 중인 클러스터 구성 요소에서의 대기 시간과 사용량에 대한 세부 정보가 표시됩니다.  실제 값과 예상 값을 비교하면 작업 부하가 예상 대기 시간 또는 사용량 범위를 벗어난 경우를 확인할 수 있습니다.  자세한 내용은 다음을 참조하세요.link:..//performance-checker/concept_types_of_workloads_monitored_by_unified_manager.html["Unified Manager에서 모니터링하는 작업 유형"] .

[NOTE]
====
대기 시간의 최대 편차를 기준으로 정렬할 경우 시스템에서 정의한 작업 부하가 표에 표시되지 않습니다. 대기 시간은 사용자 정의 작업 부하에만 적용되기 때문입니다.  대기 시간 값이 매우 낮은 작업 부하는 표에 표시되지 않습니다.

====
동적 성능 임계값에 대한 자세한 내용은 다음을 참조하세요.link:../performance-checker/concept_analyze_events_from_dynamic_performance_thresholds.html["동적 성능 임계값에서 이벤트 분석"] .

Unified Manager가 작업 부하를 순위 지정하고 정렬 순서를 결정하는 방법에 대한 자세한 내용은 다음을 참조하세요.link:../performance-checker/concept_how_um_determines_performance_impact_for_incident.html["Unified Manager가 이벤트의 성능 영향을 결정하는 방법"] .

그래프의 데이터는 이벤트가 마지막으로 분석되기 전 24시간 동안의 성능 통계를 보여줍니다.  각 워크로드에 대한 실제 값과 예상 값은 워크로드가 이벤트에 관련된 시간을 기준으로 합니다.  예를 들어, 이벤트가 감지된 후에 워크로드가 이벤트에 관련될 수 있으므로, 해당 워크로드의 성능 통계가 이벤트 감지 시점의 값과 일치하지 않을 수 있습니다.  기본적으로 작업 부하는 지연 시간의 최대(가장 높은) 편차를 기준으로 정렬됩니다.

[NOTE]
====
Unified Manager는 최대 30일 동안 5분 단위의 과거 성능 및 이벤트 데이터를 보관하므로 이벤트가 30일을 넘으면 성능 데이터가 표시되지 않습니다.

====
* *작업량 정렬 열*
+
** *지연 차트*
+
마지막 분석 시 워크로드 지연에 대한 이벤트의 영향을 표시합니다.

** *구성요소 사용 열*
+
경합 중인 클러스터 구성 요소의 작업 부하 사용에 대한 세부 정보를 표시합니다.  그래프에서 실제 사용량은 파란색 선으로 표시됩니다.  빨간색 막대는 감지 시간부터 마지막 분석 시간까지의 이벤트 기간을 강조 표시합니다. 자세한 내용은 다음을 참조하세요. link:../performance-checker/reference_workload_performance_measurement_values.html["작업 부하 성능 측정 값"].

+
[NOTE]
====
네트워크 구성 요소의 경우 네트워크 성능 통계가 클러스터 외부 활동에서 나오므로 이 열은 표시되지 않습니다.

====
** *구성요소 사용*
+
네트워크 처리, 데이터 처리 및 집계 구성 요소에 대한 활용 내역(백분율)이나 QoS 정책 그룹 구성 요소에 대한 활동 내역(백분율)을 표시합니다.  네트워크 또는 상호 연결 구성 요소에 대한 차트는 표시되지 않습니다.  특정 시점의 사용 통계를 보려면 통계를 가리킬 수 있습니다.

** *총 쓰기 MB/s 기록*
+
MetroCluster 리소스 구성 요소에만 해당하며, MetroCluster 구성에서 파트너 클러스터에 미러링되는 모든 볼륨 작업 부하에 대한 총 쓰기 처리량을 초당 메가바이트(MBps) 단위로 표시합니다.

** *이벤트 내역*
+
경쟁 중인 구성 요소의 이전 이벤트를 나타내기 위해 빨간색 음영 처리된 선을 표시합니다.  더 이상 발생하지 않은 이벤트의 경우, 차트에는 선택한 이벤트가 감지되기 전과 해결된 후에 발생한 이벤트가 표시됩니다.




