---
permalink: events/reference_add_alert_dialog_box.html 
sidebar: sidebar 
keywords: add, alert, dialog, box, name, resources, events, actions, command buttons 
summary: 특정 이벤트가 생성되면 알림을 생성하여 문제를 신속하게 해결하고 환경에 미치는 영향을 최소화할 수 있습니다.  단일 리소스나 리소스 세트에 대한 알림을 만들 수 있으며, 특정 심각도 유형의 이벤트에 대해서도 알림을 만들 수 있습니다.  또한 알림 방법과 알림 빈도를 지정할 수 있습니다. 
---
= 알림 추가 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
특정 이벤트가 생성되면 알림을 생성하여 문제를 신속하게 해결하고 환경에 미치는 영향을 최소화할 수 있습니다.  단일 리소스나 리소스 세트에 대한 알림을 만들 수 있으며, 특정 심각도 유형의 이벤트에 대해서도 알림을 만들 수 있습니다.  또한 알림 방법과 알림 빈도를 지정할 수 있습니다.

애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.



[[name]]
== 이름

이 영역에서는 알림의 이름과 설명을 지정할 수 있습니다.

* *경고 이름*
+
알림 이름을 지정할 수 있습니다.

* *경고 설명*
+
알림에 대한 설명을 지정할 수 있습니다.





[[resources]]
== 리소스

이 영역에서는 알림을 트리거하려는 동적 규칙에 따라 개별 리소스를 선택하거나 리소스를 그룹화할 수 있습니다.  _동적 규칙_은 사용자가 지정한 텍스트 문자열을 기준으로 필터링되는 리소스 집합입니다.  드롭다운 목록에서 리소스 유형을 선택하여 리소스를 검색할 수도 있고, 정확한 리소스 이름을 지정하여 특정 리소스를 표시할 수도 있습니다.

저장소 개체 세부 정보 페이지에서 알림을 생성하는 경우 저장소 개체가 자동으로 알림에 포함됩니다.

* *포함하다*
+
알림을 트리거할 리소스를 포함할 수 있습니다.  문자열을 지정하여 문자열과 일치하는 리소스를 그룹화하고 이 그룹을 선택하여 알림에 포함할 수 있습니다.  예를 들어, 이름에 "abc" 문자열이 포함된 모든 볼륨을 그룹화할 수 있습니다.

* *들어오지 못하게 하다*
+
알림을 발생시키지 않으려는 리소스를 제외할 수 있습니다.  예를 들어, 이름에 "xyz" 문자열이 포함된 모든 볼륨을 제외할 수 있습니다.

+
제외 탭은 특정 리소스 유형의 모든 리소스를 선택한 경우에만 표시됩니다. 예: +<<All Volumes>> 또는<<All Volumes whose name contains 'xyz'>> +.

+
리소스가 지정한 포함 및 제외 규칙을 모두 준수하는 경우 제외 규칙이 포함 규칙보다 우선하며 이벤트에 대한 알림은 생성되지 않습니다.





[[events]]
== 이벤트

이 영역에서는 알림을 생성할 이벤트를 선택할 수 있습니다.  특정 심각도나 일련의 이벤트에 따라 이벤트에 대한 알림을 만들 수 있습니다.

두 개 이상의 이벤트를 선택하려면 선택하는 동안 Ctrl 키를 누르고 있어야 합니다.

* *이벤트 심각도*
+
심각도 유형(중요, 오류 또는 경고)에 따라 이벤트를 선택할 수 있습니다.

* *이벤트 이름에 포함됨*
+
이름에 지정된 문자가 포함된 이벤트를 선택할 수 있습니다.





[[actions]]
== 행위

이 영역에서는 알림이 발생했을 때 알림을 받을 사용자를 지정할 수 있습니다.  또한 알림 방법과 알림 빈도를 지정할 수 있습니다.

* *이러한 사용자에게 경고*
+
알림을 받을 사용자의 이메일 주소나 사용자 이름을 지정할 수 있습니다.

+
사용자에게 지정된 이메일 주소를 수정하고 편집을 위해 알림을 다시 열면 수정된 이메일 주소가 이전에 선택된 사용자에 더 이상 매핑되지 않으므로 이름 필드가 비어 있게 됩니다.  또한, 사용자 페이지에서 선택한 사용자의 이메일 주소를 수정한 경우, 수정된 이메일 주소는 선택한 사용자의 이메일 주소에 업데이트되지 않습니다.

* *알림 빈도*
+
이벤트가 확인되거나 해결되거나 더 이상 유효하지 않은 상태로 이동될 때까지 관리 서버가 알림을 보내는 빈도를 지정할 수 있습니다.

+
다음 알림 방법을 선택할 수 있습니다.

+
** 한 번만 알림
** 지정된 빈도로 알림
** 지정된 시간 범위 내에서 지정된 빈도로 알림


* *SNMP 트랩 발행*
+
이 상자를 선택하면 SNMP 트랩을 전역적으로 구성된 SNMP 호스트로 보낼지 여부를 지정할 수 있습니다.

* *스크립트 실행*
+
알림에 사용자 정의 스크립트를 추가할 수 있습니다.  이 스크립트는 알림이 생성되면 실행됩니다.

+
[NOTE]
====
사용자 인터페이스에서 이 기능을 사용할 수 없는 경우 관리자가 해당 기능을 비활성화했기 때문입니다.  필요한 경우 *저장소 관리* > *기능 설정*에서 이 기능을 활성화할 수 있습니다.

====




[[command-buttons]]
== 명령 버튼

* *구하다*
+
알림을 만들고 대화 상자를 닫습니다.

* *취소*
+
변경 사항을 취소하고 대화 상자를 닫습니다.


