---
permalink: events/task_exclude_disaster_recovery_destination_volumes_from_alerts.html 
sidebar: sidebar 
keywords: exclude, disaster, recovery, destination, volumes, generate, alerts 
summary: 볼륨 알림을 구성할 때 알림 대화 상자에서 볼륨이나 볼륨 그룹을 식별하는 문자열을 지정할 수 있습니다.  하지만 SVM에 대한 재해 복구를 구성한 경우 소스 볼륨과 대상 볼륨의 이름이 같으므로 두 볼륨 모두에 대한 알림을 받게 됩니다. 
---
= 재해 복구 대상 볼륨을 경고 생성에서 제외합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨 알림을 구성할 때 알림 대화 상자에서 볼륨이나 볼륨 그룹을 식별하는 문자열을 지정할 수 있습니다.  하지만 SVM에 대한 재해 복구를 구성한 경우 소스 볼륨과 대상 볼륨의 이름이 같으므로 두 볼륨 모두에 대한 알림을 받게 됩니다.

.시작하기 전에
애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

대상 SVM의 이름을 가진 볼륨을 제외하여 재해 복구 대상 볼륨에 대한 알림을 비활성화할 수 있습니다.  이는 볼륨 이벤트 식별자에 SVM 이름과 볼륨 이름이 모두 "<svm_name>:/<volume_name>" 형식으로 포함되어 있기 때문에 가능합니다.

아래 예에서는 기본 SVM "vs1"에서 볼륨 "vol1"에 대한 알림을 생성하는 방법을 보여 주지만, SVM "vs1-dr"에서 동일한 이름의 볼륨에 대한 알림이 생성되지 않도록 제외합니다.

알림 추가 대화 상자에서 다음 단계를 수행합니다.

.단계
. *이름*을 클릭하고 알림의 이름과 설명을 입력합니다.
. *리소스*를 클릭한 다음 *포함* 탭을 선택합니다.
+
.. 드롭다운 목록에서 *볼륨*을 선택한 다음 입력하세요.*`vol1` *이름에 "vol1"이 포함된 볼륨을 표시하려면 *이름에 다음이 포함됨* 필드를 사용합니다.
.. *+를 선택하세요<<All Volumes whose name contains 'vol1'>> +* *사용 가능한 리소스* 영역에서 *선택한 리소스* 영역으로 이동합니다.


. *제외* 탭을 선택하고 *볼륨*을 선택한 후 다음을 입력합니다.*`vs1-dr` *이름에 *포함*을 입력한 다음 *추가*를 클릭합니다.
+
이렇게 하면 SVM "vs1-dr"의 볼륨 "vol1"에 대한 경고가 생성되지 않습니다.

. *이벤트*를 클릭하고 볼륨에 적용할 이벤트를 선택합니다.
. *작업*을 클릭한 다음 *다음 사용자에게 알림* 필드에서 알림 이메일을 받을 사용자의 이름을 선택합니다.
. 이 페이지에서 SNMP 트랩을 발행하고 스크립트를 실행하기 위한 다른 옵션을 구성한 다음 *저장*을 클릭합니다.

