---
permalink: events/task_subscribe_to_ontap_ems_events.html 
sidebar: sidebar 
keywords: subscribe, ontap, ems events 
summary: 'ONTAP 소프트웨어가 설치된 시스템에서 생성되는 이벤트 관리 시스템(EMS) 이벤트를 수신하도록 구독할 수 있습니다.  일부 EMS 이벤트는 Unified Manager에 자동으로 보고되지만, 추가 EMS 이벤트는 해당 이벤트를 구독한 경우에만 보고됩니다.' 
---
= ONTAP EMS 이벤트 구독하기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 소프트웨어가 설치된 시스템에서 생성되는 이벤트 관리 시스템(EMS) 이벤트를 수신하도록 구독할 수 있습니다.  일부 EMS 이벤트는 Unified Manager에 자동으로 보고되지만, 추가 EMS 이벤트는 해당 이벤트를 구독한 경우에만 보고됩니다.

.시작하기 전에
동일한 문제에 대해 두 개의 이벤트를 수신하게 되면 혼란이 생길 수 있으므로 Unified Manager에 자동으로 추가된 EMS 이벤트는 구독하지 마세요.

원하는 수의 EMS 이벤트에 가입할 수 있습니다.  구독한 모든 이벤트가 검증되고, 검증된 이벤트만 Unified Manager에서 모니터링하는 클러스터에 적용됩니다.  _ONTAP 9 EMS 이벤트 카탈로그_는 ONTAP 9 소프트웨어의 특정 버전에 대한 모든 EMS 메시지에 대한 자세한 정보를 제공합니다.  해당 이벤트 목록을 보려면 ONTAP 9 제품 설명서 페이지에서 _EMS 이벤트 카탈로그_의 적절한 버전을 찾으세요.

https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["ONTAP 9 제품 라이브러리"]

구독한 ONTAP EMS 이벤트에 대한 알림을 구성할 수 있으며, 이러한 이벤트에 대해 실행할 사용자 정의 스크립트를 만들 수 있습니다.

[NOTE]
====
구독한 ONTAP EMS 이벤트를 받지 못하는 경우 클러스터의 DNS 구성에 문제가 있어 클러스터가 Unified Manager 서버에 도달하지 못할 수 있습니다.  이 문제를 해결하려면 클러스터 관리자가 클러스터의 DNS 구성을 수정한 다음 Unified Manager를 다시 시작해야 합니다.  이렇게 하면 보류 중인 EMS 이벤트가 Unified Manager 서버로 플러시됩니다.

====
.단계
. 왼쪽 탐색 창에서 *저장소 관리* > *이벤트 설정*을 클릭합니다.
. 이벤트 설정 페이지에서 *EMS 이벤트 구독* 버튼을 클릭합니다.
. EMS 이벤트 구독 대화 상자에서 구독하려는 ONTAP EMS 이벤트의 이름을 입력합니다.
+
ONTAP 클러스터 셸에서 구독할 수 있는 EMS 이벤트의 이름을 보려면 다음을 사용할 수 있습니다. `event route show` 명령( ONTAP 9 이전) 또는 `event catalog show` 명령(ONTAP 9 이상).

+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_configure_and_receive_alerts_from_ONTAP_EMS_Event_Subscription_in_Active_IQ_Unified_Manager["Active IQ Unified Manager 에서 ONTAP EMS 이벤트 구독에 대한 알림을 구성하고 수신하는 방법"]

. *추가*를 클릭하세요.
+
EMS 이벤트가 구독된 EMS 이벤트 목록에 추가되지만, 클러스터에 적용 가능 열에는 추가한 EMS 이벤트의 상태가 "`알 수 없음`"으로 표시됩니다.

. *저장 및 닫기*를 클릭하여 클러스터에 EMS 이벤트 구독을 등록합니다.
. *EMS 이벤트 구독*을 다시 클릭하세요.
+
추가한 EMS 이벤트의 적용 가능 클러스터 열에 상태 "`예`"가 나타납니다.

+
상태가 "예"가 아닌 경우 ONTAP EMS 이벤트 이름의 철자를 확인하세요.  이름을 잘못 입력한 경우 잘못된 이벤트를 삭제한 후 이벤트를 다시 추가해야 합니다.



ONTAP EMS 이벤트가 발생하면 이벤트 페이지에 이벤트가 표시됩니다.  이벤트 세부 정보 페이지에서 이벤트를 선택하면 EMS 이벤트에 대한 세부 정보를 볼 수 있습니다.  이벤트 처리를 관리하거나 이벤트에 대한 알림을 생성할 수도 있습니다.
