---
permalink: data-protection/concept_types_of_snapmirror_protection.html 
sidebar: sidebar 
keywords: types, snapmirror, protection, consistency group, SnapMirror active sync 
summary: 데이터 스토리지 토폴로지의 배포에 따라 Unified Manager를 사용하면 여러 유형의 SnapMirror 보호 관계를 구성할 수 있습니다.  SnapMirror 보호의 모든 변형은 장애 조치 재해 복구 보호 기능을 제공하지만 성능, 버전 유연성 및 다중 백업 사본 보호 측면에서 제공하는 기능이 다릅니다. 
---
= SnapMirror 보호 유형
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 스토리지 토폴로지의 배포에 따라 Unified Manager를 사용하면 여러 유형의 SnapMirror 보호 관계를 구성할 수 있습니다.  SnapMirror 보호의 모든 변형은 장애 조치 재해 복구 보호 기능을 제공하지만 성능, 버전 유연성 및 다중 백업 사본 보호 측면에서 제공하는 기능이 다릅니다.



[[traditional-snapmirror-asynchronous-protection-relationships]]
== 기존 SnapMirror 비동기 보호 관계

기존 SnapMirror 비동기 보호는 소스 볼륨과 대상 볼륨 간에 블록 복제 미러 보호 기능을 제공합니다.

기존 SnapMirror 관계에서는 미러 작업이 블록 복제를 기반으로 하기 때문에 대체 SnapMirror 관계보다 미러 작업이 더 빠르게 실행됩니다.  그러나 기존 SnapMirror 보호 기능을 사용하려면 대상 볼륨이 동일한 주요 릴리스 내의 소스 볼륨과 동일하거나 그 이후의 ONTAP 소프트웨어 마이너 버전(예: 버전 8.x에서 8.x로 또는 9.x에서 9.x로)에서 실행되어야 합니다.  대상에서 이전 주요 버전이 실행되고 있기 때문에 9.1 소스에서 9.0 대상으로의 복제는 지원되지 않습니다.



[[snapmirror-asynchronous-protection-with-version-flexible-replication]]
== SnapMirror 비동기 보호 및 버전 유연한 복제

SnapMirror 비동기 보호 기능과 버전 유연한 복제 기능은 소스 볼륨과 대상 볼륨 간에 논리적 복제 미러 보호 기능을 제공하며, 해당 볼륨이 서로 다른 ONTAP 8.3 이상 소프트웨어 버전(예: 버전 8.3에서 8.3.1, 8.3에서 9.1, 9.2.2에서 9.2)에서 실행되는 경우에도 마찬가지입니다.

버전에 따라 유연한 복제가 가능한 SnapMirror 관계에서는 미러 작업이 기존 SnapMirror 관계에서보다 빠르게 실행되지 않습니다.

SnapMirror 의 버전 유연한 복제 보호 기능은 실행 속도가 느리기 때문에 다음 두 가지 상황에서는 구현하기에 적합하지 않습니다.

* 소스 객체에는 보호해야 할 파일이 1,000만 개 이상 포함되어 있습니다.
* 보호된 데이터의 복구 지점 목표는 2시간 이하입니다.  (즉, 대상에는 항상 소스의 데이터보다 2시간 이상 오래되지 않은 미러링되고 복구 가능한 데이터가 포함되어 있어야 합니다.)


나열된 두 가지 상황 모두에서 기본 SnapMirror 보호의 더 빠른 블록 복제 기반 실행이 필요합니다.



[[snapmirror-asynchronous-protection-with-version-flexible-replication-and-backup-option]]
== SnapMirror 비동기 보호, 버전에 따라 유연한 복제 및 백업 옵션 제공

SnapMirror 비동기 보호 기능과 버전에 유연한 복제 및 백업 옵션은 소스 볼륨과 대상 볼륨 간의 미러 보호 기능을 제공하고 대상에 미러링된 데이터의 여러 사본을 저장하는 기능을 제공합니다.

스토리지 관리자는 어떤 스냅샷 복사본을 소스에서 대상으로 미러링할지 지정할 수 있으며, 소스에서 복사본이 삭제된 경우에도 대상에서 해당 복사본을 얼마나 오랫동안 보관할지 지정할 수 있습니다.

버전에 따라 유연한 복제 및 백업 옵션이 제공되는 SnapMirror 관계에서는 미러 작업이 기존 SnapMirror 관계에서보다 빠르게 실행되지 않습니다.



[[snapmirror-unified-replication-mirror-and-vault]]
== SnapMirror 통합 복제(미러 및 볼트)

SnapMirror 통합 복제를 사용하면 동일한 대상 볼륨에서 재해 복구와 보관을 구성할 수 있습니다.  SnapMirror 와 마찬가지로 통합 데이터 보호 기능은 처음 호출할 때 기준 전송을 수행합니다.  기본 통합 데이터 보호 정책인 "MirrorAndVault"에 따른 기준선 전송은 소스 볼륨의 스냅샷 복사본을 만든 다음 해당 복사본과 참조하는 데이터 블록을 대상 볼륨으로 전송합니다.  SnapVault 와 마찬가지로 통합 데이터 보호에는 기준선에 이전 스냅샷 사본이 포함되지 않습니다.



[[snapmirror-synchronous-protection-with-strict-synchronization]]
== SnapMirror 엄격한 동기화를 통한 동기 보호

SnapMirror "strict" 동기화를 통한 동기 보호 기능은 기본 볼륨과 보조 볼륨이 항상 서로의 정확한 사본이 되도록 보장합니다.  보조 볼륨에 데이터를 쓰려고 할 때 복제 실패가 발생하면 기본 볼륨에 대한 클라이언트 I/O가 중단됩니다.



[[snapmirror-synchronous-protection-with-regular-synchronization]]
== SnapMirror 정기 동기화를 통한 동기 보호

"일반" 동기화를 통한 SnapMirror 동기 보호는 기본 볼륨과 보조 볼륨이 항상 서로의 정확한 사본일 필요가 없으므로 기본 볼륨의 가용성을 보장합니다.  보조 볼륨에 데이터를 쓰려고 할 때 복제 오류가 발생하면 기본 볼륨과 보조 볼륨이 동기화되지 않고 클라이언트 I/O는 기본 볼륨으로 계속 진행됩니다.

[NOTE]
====
동기식 보호 관계를 모니터링하는 경우 [상태: 모든 볼륨] 보기나 [볼륨/상태 세부 정보] 페이지에서 복원 버튼과 관계 작업 버튼을 사용할 수 없습니다.

====


[[snapmirror-active-sync]]
== SnapMirror 액티브 싱크

SnapMirror Active Sync 기능은 ONTAP 9.8 이상에서 사용할 수 있으며, LUN을 사용하여 애플리케이션을 보호하고 애플리케이션이 투명하게 장애 조치되도록 하여 재해 발생 시에도 비즈니스 연속성을 보장할 수 있습니다.

Unified Manager에서 클러스터 및 스토리지 가상 머신에 사용 가능한 일관성 그룹(CG)에 대한 동기식 SnapMirror 관계를 검색하고 모니터링할 수 있습니다.  SnapMirror 액티브 동기화는 AFF 클러스터 또는 모든 SAN 어레이(ASA) 클러스터에서 지원되며, 여기서 기본 및 보조 클러스터는 AFF 또는 ASA 가 될 수 있습니다.  SnapMirror Active Sync는 iSCSI 또는 FCP LUN을 사용하여 애플리케이션을 보호합니다.

SnapMirror 활성 동기화 관계로 보호되는 볼륨과 LUN을 볼 때 보호 관계, 볼륨 인벤토리의 일관성 그룹, 일관성 그룹 관계에 대한 보호 토폴로지 보기, 최대 1년 동안의 일관성 그룹 관계에 대한 기록 데이터 보기에 대한 통합된 보기를 얻을 수 있습니다.  보고서를 다운로드할 수도 있습니다.  일관성 그룹 관계 요약을 보고, 일관성 그룹 관계에 대한 지원을 검색하고, 일관성 그룹으로 보호되는 볼륨에 대한 정보를 얻을 수도 있습니다.

관계 페이지에서는 일관성 그룹으로 보호되는 소스 및 대상 저장소 개체와 해당 개체의 관계에 대한 보호를 정렬, 필터링하고 확장할 수도 있습니다.

SnapMirror Active Sync에 대해 자세히 알아보려면 다음을 참조하세요.link:https://docs.netapp.com/us-en/ontap/smbc/index.html["Snapmirror Active Sync(이전 SM-BC)에 대한 ONTAP 9 설명서"] .
