---
permalink: data-protection/concept_storage_virtual_machine_and_resource_pool_requirements.html 
sidebar: sidebar 
keywords: svm, resource pool requirements, support, storage services 
summary: 스토리지 서비스에 특정한 일부 SVM 연결 및 리소스 풀 요구 사항을 준수하면 파트너 애플리케이션에서의 적합성을 더 잘 보장할 수 있습니다. 예를 들어, 파트너 애플리케이션에서 제공하는 스토리지 서비스에서 보호 토폴로지를 지원하기 위해 Unified Manager에서 SVM을 연결하고 리소스 풀을 만드는 경우입니다. 
---
= 스토리지 서비스를 지원하기 위한 SVM 및 리소스 풀 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 서비스에 특정한 일부 SVM 연결 및 리소스 풀 요구 사항을 준수하면 파트너 애플리케이션에서의 적합성을 더 잘 보장할 수 있습니다. 예를 들어, 파트너 애플리케이션에서 제공하는 스토리지 서비스에서 보호 토폴로지를 지원하기 위해 Unified Manager에서 SVM을 연결하고 리소스 풀을 만드는 경우입니다.

일부 애플리케이션은 Unified Manager 서버와 협력하여 소스 볼륨과 2차 또는 3차 위치의 보호 볼륨 간에 SnapMirror 또는 SnapVault 백업 보호를 자동으로 구성하고 실행하는 서비스를 제공합니다.  이러한 보호 스토리지 서비스를 지원하려면 Unified Manager를 사용하여 필요한 SVM 연결 및 리소스 풀을 구성해야 합니다.

SnapMirror 소스 또는 SnapVault 기본 볼륨에서 대상 SnapMirror 또는 2차 또는 3차 위치에 있는 SnapVault 백업 볼륨으로의 복제를 포함하여 스토리지 서비스 단일 홉 또는 계단식 보호를 지원하려면 다음 요구 사항을 준수하세요.

* SnapMirror 소스 또는 SnapVault 기본 볼륨이 포함된 SVM과 보조 볼륨 또는 3차 볼륨이 있는 모든 SVM 간에 SVM 연결을 구성해야 합니다.
+
** 예를 들어, 소스 볼륨 Vol_A가 SVM_1에 있고 SnapMirror 보조 대상 볼륨 Vol_B가 SVM_2에 있고 3차 SnapVault 백업 볼륨 Vol_C가 SVM_3에 있는 보호 토폴로지를 지원하려면 Unified Manager 웹 UI를 사용하여 SVM_1과 SVM_2 간의 SnapMirror 연결과 SVM_1과 SVM_3 간의 SnapVault 백업 연결을 구성해야 합니다.
+
이 예에서 SVM_2와 SVM_3 간의 SnapMirror 연결이나 SnapVault 백업 연결은 필요하지 않으며 사용되지 않습니다.

** 소스 볼륨 Vol_A와 SnapMirror 대상 볼륨 Vol_B가 모두 SVM_1에 있는 보호 토폴로지를 지원하려면 SVM_1과 SVM_1 간에 SnapMirror 연결을 구성해야 합니다.


* 리소스 풀에는 연관된 SVM에서 사용할 수 있는 클러스터 집계 리소스가 포함되어야 합니다.
+
Unified Manager 웹 UI를 통해 리소스 풀을 구성한 다음 파트너 애플리케이션을 통해 스토리지 서비스 2차 대상과 3차 대상 노드를 할당합니다.


