---
permalink: data-protection/reference_create_snapvault_policy_dialog_box.html 
sidebar: sidebar 
keywords: create, snapvault, policy, dialog box 
summary: SnapVault 정책 만들기 대화 상자를 사용하면 SnapVault 전송의 우선 순위를 설정하는 정책을 만들 수 있습니다.  정책을 사용하여 1차 볼륨에서 2차 볼륨으로의 전송 효율성을 극대화합니다. 
---
= SnapVault 정책 만들기 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapVault 정책 만들기 대화 상자를 사용하면 SnapVault 전송의 우선 순위를 설정하는 정책을 만들 수 있습니다.  정책을 사용하여 1차 볼륨에서 2차 볼륨으로의 전송 효율성을 극대화합니다.

* *목적지 클러스터*
+
보호 구성 대화 상자의 SnapVault 탭에서 선택한 클러스터의 이름입니다.

* *대상 SVM*
+
보호 구성 대화 상자의 SnapVault 탭에서 선택한 SVM의 이름입니다.

* *정책명*
+
새 정책에 제공하는 이름입니다.  정책 이름은 A~Z, a~z, 0~9, 마침표(.), 하이픈(-), 밑줄(_)로 구성될 수 있습니다.

* *전송 우선권*
+
전송이 실행되는 우선 순위입니다.  보통 또는 낮음 중에서 선택할 수 있습니다.  일반 전송 우선순위를 지정하는 정책이 있는 전송 관계는 낮은 전송 우선순위를 지정하는 정책이 있는 전송 관계보다 먼저 실행됩니다.  기본 설정은 일반입니다.

* *논평*
+
SnapVault 정책에 대해 최대 255자까지 의견을 추가할 수 있는 선택 필드입니다.

* *접속 시간 무시*
+
액세스 시간만 변경된 파일에 대해 증분 전송을 무시할지 여부를 지정합니다.

* *복제 라벨*
+
ONTAP 에서 선택한 스냅샷 복사본과 관련된 규칙을 표로 나열하고, 정책에 특정 복제 레이블이 있는 복사본을 나열합니다.  다음 정보와 작업도 이용할 수 있습니다.

+
** 명령 버튼
+
명령 단추를 사용하면 다음 작업을 수행할 수 있습니다.

+
*** 추가하다
+
스냅샷 사본 레이블과 보존 횟수를 생성할 수 있습니다.

*** 보존 횟수 편집
+
기존 스냅샷 복사 레이블의 보존 횟수를 변경할 수 있습니다.  보존 횟수는 1~251 사이의 숫자여야 합니다.  모든 규칙에 대한 모든 보존 횟수의 합계는 251을 초과할 수 없습니다.

*** 삭제
+
기존 스냅샷 복사 레이블을 삭제할 수 있습니다.



** 스냅샷 복사 라벨
+
스냅샷 복사 레이블을 표시합니다.  동일한 로컬 스냅샷 복사 정책이 있는 볼륨을 하나 이상 선택하면 정책의 각 레이블에 대한 항목이 표시됩니다.  두 개 이상의 로컬 스냅샷 복사 정책이 있는 여러 볼륨을 선택하는 경우 테이블에는 모든 정책의 모든 레이블이 표시됩니다.

** 일정
+
각 스냅샷 복사 레이블과 연관된 일정을 표시합니다.  레이블에 두 개 이상의 일정이 연결된 경우 해당 레이블의 일정은 쉼표로 구분된 목록으로 표시됩니다.  동일한 라벨이지만 일정이 다른 여러 볼륨을 선택하는 경우 일정에 "`다양함`"이 표시되어 선택한 볼륨에 두 개 이상의 일정이 연결되어 있음을 나타냅니다.

** 목적지 보존 횟수
+
SnapVault 보조 저장소에 보관된 지정된 레이블이 있는 스냅샷 복사본의 수를 표시합니다.  여러 일정이 있는 레이블의 보존 횟수는 각 레이블과 일정 쌍의 보존 횟수 합계를 표시합니다.  두 개 이상의 로컬 스냅샷 복사 정책이 있는 여러 볼륨을 선택하는 경우 보존 횟수는 비어 있습니다.




