---
permalink: data-protection/reference_initialize_update_relationship_dialog_box.html 
sidebar: sidebar 
keywords: initialize, update, dialog box 
summary: 초기화/업데이트 대화 상자를 사용하면 새 보호 관계에 대한 최초의 기준 전송을 수행하거나, 이미 초기화된 관계를 업데이트하고 예약되지 않은 수동 증분 업데이트를 수행할 수 있습니다. 
---
= 초기화/업데이트 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
초기화/업데이트 대화 상자를 사용하면 새 보호 관계에 대한 최초의 기준 전송을 수행하거나, 이미 초기화된 관계를 업데이트하고 예약되지 않은 수동 증분 업데이트를 수행할 수 있습니다.



== 전송 옵션 탭

전송 옵션 탭을 사용하면 전송의 초기화 우선순위를 변경하고 전송 중에 사용되는 대역폭을 변경할 수 있습니다.

* *전송 우선권*
+
전송이 실행되는 우선 순위입니다.  보통 또는 낮음 중에서 선택할 수 있습니다.  일반 전송 우선순위를 지정하는 정책과의 관계는 낮은 전송 우선순위를 지정하는 정책과의 관계보다 먼저 실행됩니다.  기본적으로 일반이 선택되어 있습니다.

* *최대 전송 속도*
+
네트워크를 통해 클러스터 간에 데이터가 전송되는 최대 속도를 지정합니다.  최대 전송 속도를 사용하지 않기로 선택하면 관계 간 기준 전송은 무제한입니다.  서로 다른 최대 전송 속도를 가진 두 개 이상의 관계를 선택하는 경우 다음 최대 전송 속도 설정 중 하나를 지정할 수 있습니다.

+
** 개별 관계 설정 또는 편집 중에 지정된 값을 사용합니다.
+
이 옵션을 선택하면 초기화 및 업데이트 작업에서 각 관계를 만들거나 편집할 때 지정된 최대 전송 속도가 사용됩니다.  이 필드는 서로 다른 전송 속도를 가진 여러 관계가 초기화되거나 업데이트되는 경우에만 사용할 수 있습니다.

** 제한 없는
+
관계 간 전송에 대역폭 제한이 없음을 나타냅니다.  이 필드는 서로 다른 전송 속도를 가진 여러 관계가 초기화되거나 업데이트되는 경우에만 사용할 수 있습니다.

** 대역폭을 제한합니다
+
이 옵션을 선택하면 네트워크 대역폭이 지정한 값으로 제한됩니다.  숫자 값을 입력한 다음 초당 킬로바이트(KBps), 초당 메가바이트(MBps), 초당 기가바이트(GBps), 초당 테라바이트(TBps)를 선택할 수 있습니다.  지정하는 최대 전송 속도는 1KBps보다 크고 4TBps보다 작아야 합니다.







== 소스 스냅샷 복사본 탭

소스 스냅샷 복사본 탭에는 기준 전송에 사용되는 소스 스냅샷 복사본에 대한 다음 정보가 표시됩니다.

* *소스 볼륨*
+
해당 소스 볼륨의 이름을 표시합니다.

* *목적지 볼륨*
+
선택한 대상 볼륨의 이름을 표시합니다.

* *소스 유형*
+
볼륨 유형을 표시합니다.  유형은 읽기/쓰기 또는 데이터 보호가 될 수 있습니다.

* *스냅샷 사본*
+
데이터 전송에 사용되는 스냅샷 복사본을 표시합니다.  스냅샷 복사 값을 클릭하면 소스 스냅샷 복사 선택 대화 상자가 표시됩니다. 이 대화 상자에서는 보호 관계 유형과 수행하는 작업에 따라 전송할 특정 스냅샷 복사를 선택할 수 있습니다.  데이터 보호 유형 소스에는 다른 스냅샷 복사본을 지정하는 옵션을 사용할 수 없습니다.





== 명령 버튼

명령 버튼을 사용하면 다음 작업을 수행할 수 있습니다.

* *취소*
+
선택 사항을 취소하고 초기화/업데이트 대화 상자를 닫습니다.

* *제출하다*
+
선택 사항을 저장하고 초기화 또는 업데이트 작업을 시작합니다.


