---
permalink: data-protection/reference_relationship_last_1_month_transfer_rate_view.html 
sidebar: sidebar 
keywords: relationship, 1 month, transfer rate, view 
summary: '관계: 지난 1개월 전송률 보기를 사용하면 비동기 관계의 볼륨에 대해 매일 전송되는 데이터 볼륨의 양을 분석할 수 있습니다.  이 페이지에서는 일일 전송에 대한 세부 정보와 볼륨 및 스토리지 VM에 대한 전송 작업을 완료하는 데 필요한 시간에 대한 정보도 제공합니다.' 
---
= 관계: 지난 1개월 전송률 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관계: 지난 1개월 전송률 보기를 사용하면 비동기 관계의 볼륨에 대해 매일 전송되는 데이터 볼륨의 양을 분석할 수 있습니다.  이 페이지에서는 일일 전송에 대한 세부 정보와 볼륨 및 스토리지 VM에 대한 전송 작업을 완료하는 데 필요한 시간에 대한 정보도 제공합니다.

페이지 상단의 컨트롤을 사용하면 특정 객체를 찾기 위한 검색을 수행하고, 표시되는 데이터 목록을 좁히기 위한 필터를 만들고 적용하고, 페이지에서 열을 추가/제거/재정렬하고, 페이지의 데이터를 .csv, .pdf 또는 .xlsx 파일로 내보낼 수 있습니다.  페이지를 사용자 지정한 후 결과를 사용자 지정 보기로 저장한 다음 이 데이터에 대한 보고서를 생성하여 정기적으로 이메일로 전송하도록 예약할 수 있습니다.  예를 들어, 볼륨 관계를 보려면 *저장소* > *볼륨* > *관계: 최근 1개월 전송률* 메뉴에 액세스하거나 *보호* > *관계* > *관계: 최근 1개월 전송률* 메뉴에 액세스하고 *필터*를 사용하여 볼륨에 대한 데이터만 볼 수 있습니다.

* *총 전송 크기*
+
볼륨 전송의 총 크기를 기가바이트 단위로 표시합니다.

* *낮*
+
볼륨 전송이 시작된 날짜를 표시합니다.

* *종말 시간*
+
볼륨 전송 종료 시간과 날짜를 표시합니다.



*관련 정보*

* *관계: MetroCluster* 보기에 대한 정보는 다음을 참조하세요.link:../storage-mgmt/task_monitor_metrocluster_configurations.html["MetroCluster 구성 모니터링"] .
* *관계: 지난 1개월 전송 상태* 보기에 대한 정보는 다음을 참조하세요.link:../data-protection/reference_relationship_last_1_month_transfer_status_view.html["관계: 지난 1개월 전송 상태 보기"] .
* *관계: 모든 관계* 보기에 대한 정보는 다음을 참조하세요.link:../data-protection/reference_relationship_last_1_month_transfer_rate_view.html["관계: 지난 1개월 전송률 보기"]

