---
permalink: data-protection/reference_advanced_secondary_setting_dialog_box.html 
sidebar: sidebar 
keywords: advanced, secondary, settings, dialog box 
summary: 고급 보조 설정 대화 상자를 사용하여 보조 볼륨에서 버전 유연한 복제, 다중 복사본 백업 및 공간 관련 설정을 활성화할 수 있습니다.  현재 설정을 활성화하거나 비활성화하려면 고급 보조 설정 대화 상자를 사용할 수 있습니다. 
---
= 고급 보조 설정 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
고급 보조 설정 대화 상자를 사용하여 보조 볼륨에서 버전 유연한 복제, 다중 복사본 백업 및 공간 관련 설정을 활성화할 수 있습니다.  현재 설정을 활성화하거나 비활성화하려면 고급 보조 설정 대화 상자를 사용할 수 있습니다.

공간 관련 설정은 중복 제거, 데이터 압축, 자동 증가, 공간 보장 등을 포함하여 저장되는 데이터 양을 극대화합니다.

대화 상자에는 다음 필드가 포함되어 있습니다.

* *버전 유연한 복제 활성화*
+
버전에 따라 유연한 복제 기능을 갖춘 SnapMirror 지원합니다.  버전 유연한 복제 기능을 사용하면 대상 볼륨이 소스 볼륨보다 이전 버전의 ONTAP 에서 실행 중이더라도 소스 볼륨의 SnapMirror 보호가 가능합니다.

+
** 백업 활성화
+
버전에 따른 유연한 복제가 활성화된 경우 SnapMirror 소스 데이터의 여러 스냅샷 사본을 SnapMirror 대상에 전송하여 보관할 수도 있습니다.



* *중복 제거 활성화*
+
SnapVault 관계에서 보조 볼륨에 대한 중복 제거를 활성화하여 중복된 데이터 블록을 제거하여 공간을 절약합니다.  최소 10% 이상의 공간 절약이 가능하고 데이터 덮어쓰기 속도가 빠르지 않은 경우 중복 제거를 사용할 수 있습니다.  중복 제거는 가상화된 환경, 파일 공유, 백업 데이터에 자주 사용됩니다.  이 설정은 기본적으로 비활성화되어 있습니다.  이 기능을 활성화하면 전송이 이루어질 때마다 작업이 시작됩니다.

+
** 압축 활성화
+
투명한 데이터 압축이 가능합니다.  최소 10%의 공간 절약이 가능하고, 잠재적 오버헤드가 허용 가능하며, 비수요 시간에 압축을 완료할 수 있는 충분한 시스템 리소스가 있는 경우 압축을 사용할 수 있습니다.  SnapVault 관계에서는 이 설정이 기본적으로 비활성화되어 있습니다.  중복 제거를 선택한 경우에만 압축을 사용할 수 있습니다.

** 인라인 압축
+
디스크에 데이터를 쓰기 전에 데이터를 압축하여 즉각적인 공간 절약이 가능합니다.  최대 사용량 시간대에 시스템 사용률이 50%를 넘지 않고, 시스템이 최대 사용량 시간대에 새로운 쓰기 작업과 추가 CPU 작업을 처리할 수 있는 경우 인라인 압축을 사용할 수 있습니다.  이 설정은 "압축 사용"이 선택된 경우에만 사용할 수 있습니다.



* *자동 증가 활성화*
+
연관된 집계에 사용 가능한 공간이 있는 한, 여유 공간 비율이 지정된 임계값보다 낮을 때 대상 볼륨을 자동으로 늘릴 수 있습니다.

* *최대 크기*
+
볼륨이 증가할 수 있는 최대 비율을 설정합니다.  기본값은 소스 볼륨 크기보다 20% 더 큽니다.  현재 크기가 최대 자동 증가 백분율보다 크거나 같으면 볼륨이 자동으로 커지지 않습니다.  이 필드는 자동 증가 설정이 활성화된 경우에만 활성화됩니다.

* *크기 증가*
+
소스 볼륨의 최대 백분율에 도달하기 전에 볼륨이 자동으로 커지는 백분율 증가량을 지정합니다.

* *공간 보장*
+
데이터 전송이 항상 성공적으로 이루어지도록 보조 볼륨에 충분한 공간이 할당되도록 합니다.  공간 보장 설정은 다음 중 하나일 수 있습니다.

+
** 파일
** 용량
** 없음 + 예를 들어, 총 50GB의 파일이 포함된 200GB 볼륨이 있을 수 있습니다. 하지만 해당 파일은 10GB의 데이터만 보유합니다.  볼륨 보장은 소스의 콘텐츠에 관계없이 대상 볼륨에 200GB를 할당합니다.  파일 보장은 소스에 있는 파일에 충분한 공간이 예약되도록 50GB를 할당합니다. 이 시나리오에서 없음을 선택하면 소스의 파일 데이터가 실제로 사용하는 공간에 대해 대상에 10GB만 할당된다는 것을 의미합니다.


+
공간 보장은 기본적으로 볼륨으로 설정됩니다.





== 명령 버튼

명령 버튼을 사용하면 다음 작업을 수행할 수 있습니다.

* *적용하다*
+
선택한 효율성 설정을 저장하고 보호 구성 대화 상자에서 *적용*을 클릭하면 해당 설정이 적용됩니다.

* *취소*
+
선택 사항을 취소하고 고급 대상 설정 대화 상자를 닫습니다.


