---
permalink: data-protection/reference_resynchronize_dialog_box.html 
sidebar: sidebar 
keywords: resynchronize, dialog box 
summary: 재동기화 대화 상자를 사용하면 이전에 끊어진 SnapMirror 또는 SnapVault 관계의 데이터를 재동기화한 후 대상이 읽기/쓰기 볼륨이 된 경우 해당 데이터를 재동기화할 수 있습니다.  소스 볼륨에서 필수 공통 스냅샷 복사본이 삭제되어 SnapMirror 또는 SnapVault 업데이트가 실패하는 경우에도 다시 동기화할 수 있습니다. 
---
= 재동기화 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
재동기화 대화 상자를 사용하면 이전에 끊어진 SnapMirror 또는 SnapVault 관계의 데이터를 재동기화한 후 대상이 읽기/쓰기 볼륨이 된 경우 해당 데이터를 재동기화할 수 있습니다.  소스 볼륨에서 필수 공통 스냅샷 복사본이 삭제되어 SnapMirror 또는 SnapVault 업데이트가 실패하는 경우에도 다시 동기화할 수 있습니다.



[[resynchronization-options-tab]]
== 재동기화 옵션 탭

재동기화 옵션 탭을 사용하면 재동기화하는 보호 관계에 대한 전송 우선 순위와 최대 전송 속도를 설정할 수 있습니다.

* *전송 우선권*
+
전송이 실행되는 우선 순위입니다.  보통 또는 낮음 중에서 선택할 수 있습니다.  일반 전송 우선 순위를 지정하는 정책과의 관계는 낮은 전송 우선 순위를 지정하는 정책과의 관계보다 먼저 실행됩니다.

* *최대 전송 속도*
+
네트워크를 통해 클러스터 간에 데이터가 전송되는 최대 속도를 지정합니다.  이 옵션을 선택하면 네트워크 대역폭이 지정한 값으로 제한됩니다.  숫자 값을 입력한 다음 초당 킬로바이트(KBps), 초당 메가바이트(MBps), 초당 기가바이트(GBps) 또는 TBps를 선택할 수 있습니다.  최대 전송 속도를 사용하지 않기로 선택하면 관계 간 기준 전송은 무제한입니다.





[[source-snapshot-copies-tab]]
== 소스 스냅샷 복사본 탭

소스 스냅샷 복사본 탭에는 기준 전송에 사용되는 소스 스냅샷 복사본에 대한 다음 정보가 표시됩니다.

* *소스 볼륨*
+
해당 소스 볼륨의 이름을 표시합니다.

* *목적지 볼륨*
+
선택한 대상 볼륨의 이름을 표시합니다.

* *소스 유형*
+
볼륨 유형(읽기/쓰기 또는 데이터 보호)을 표시합니다.

* *스냅샷 사본*
+
데이터 전송에 사용되는 스냅샷 복사본을 표시합니다.  스냅샷 복사 값을 클릭하면 소스 스냅샷 복사 선택 대화 상자가 표시됩니다. 이 대화 상자에서는 보호 관계 유형과 수행하는 작업에 따라 전송할 특정 스냅샷 복사를 선택할 수 있습니다.





[[command-buttons]]
== 명령 버튼

* *제출하다*
+
재동기화 프로세스를 시작하고 재동기화 대화 상자를 닫습니다.

* *취소*
+
선택 사항을 취소하고 재동기화 대화 상자를 닫습니다.


