---
permalink: data-protection/reference_configure_protection_dialog_box.html 
sidebar: sidebar 
keywords: configure, protection, dialog box 
summary: 보호 구성 대화 상자를 사용하여 클러스터의 모든 읽기, 쓰기 및 데이터 보호 볼륨에 대한 SnapMirror 및 SnapVault 관계를 만들어 소스 볼륨이나 기본 볼륨의 데이터가 복제되도록 할 수 있습니다. 
---
= 보호 구성 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
보호 구성 대화 상자를 사용하여 클러스터의 모든 읽기, 쓰기 및 데이터 보호 볼륨에 대한 SnapMirror 및 SnapVault 관계를 만들어 소스 볼륨이나 기본 볼륨의 데이터가 복제되도록 할 수 있습니다.



== 소스 탭

* *토폴로지 뷰*
+
만들고 있는 관계의 시각적 표현을 표시합니다.  토폴로지의 소스는 기본적으로 강조 표시됩니다.

* *출처 정보*
+
다음 정보를 포함하여 선택한 소스 볼륨에 대한 세부 정보를 표시합니다.

+
** 소스 클러스터 이름
** 소스 SVM 이름
** 누적 볼륨 총 크기
+
선택된 모든 소스 볼륨의 총 크기를 표시합니다.

** 누적 사용 볼륨 크기
+
선택한 모든 소스 볼륨에 대해 사용된 누적 볼륨 크기를 표시합니다.

** 소스 볼륨
+
다음 정보를 표로 표시합니다.

+
*** 소스 볼륨
+
선택한 소스 볼륨의 이름을 표시합니다.

*** 유형
+
볼륨 유형을 표시합니다.

*** SnapLock 타입
+
볼륨의 SnapLock 유형을 표시합니다.  옵션은 규정 준수, 엔터프라이즈 및 비 SnapLock 입니다.

*** 스냅샷 사본
+
기준선 전송에 사용되는 스냅샷 복사본을 표시합니다.  소스 볼륨이 읽기/쓰기인 경우 스냅샷 복사 열의 기본값은 기본적으로 새 스냅샷 복사본이 생성되고 기준 전송에 사용된다는 것을 나타냅니다.  소스 볼륨이 데이터 보호 볼륨인 경우 스냅샷 복사본 열의 기본값 값은 새 스냅샷 복사본이 생성되지 않고 모든 기존 스냅샷 복사본이 대상으로 전송됨을 나타냅니다.  스냅샷 복사 값을 클릭하면 기준 전송에 사용할 기존 스냅샷 복사본을 선택할 수 있는 스냅샷 복사본 목록이 표시됩니다.  소스 유형이 데이터 보호인 경우 다른 기본 스냅샷 복사본을 선택할 수 없습니다.









== SnapMirror 탭

SnapMirror 관계를 생성하는 동안 보호 관계에 대한 대상 클러스터, 스토리지 가상 머신(SVM), 집계를 지정할 수 있으며 대상에 대한 명명 규칙도 지정할 수 있습니다.  SnapMirror 정책과 일정을 지정할 수도 있습니다.

* *토폴로지 뷰*
+
만들고 있는 관계의 시각적 표현을 표시합니다.  토폴로지의 SnapMirror 대상 리소스는 기본적으로 강조 표시됩니다.

* *목적지 정보*
+
보호 관계에 대한 대상 리소스를 선택할 수 있습니다.

+
** 고급 링크
+
SnapMirror 관계를 만들 때 고급 대상 설정 대화 상자를 실행합니다.

** 무리
+
보호 대상 호스트로 사용할 수 있는 클러스터를 나열합니다.  이 필드는 필수입니다.

** 스토리지 가상 머신(SVM)
+
선택한 클러스터에서 사용 가능한 SVM을 나열합니다.  SVM 목록을 채우기 전에 클러스터를 선택해야 합니다.  이 필드는 필수입니다.

** 골재
+
선택한 SVM에서 사용할 수 있는 집계를 나열합니다.  집계 목록을 채우기 전에 클러스터를 선택해야 합니다.  이 필드는 필수입니다.  집계 목록에는 다음 정보가 표시됩니다.

+
*** 계급
+
여러 집계가 목적지에 대한 모든 요구 사항을 충족하는 경우 순위는 다음 조건에 따라 집계가 나열된 우선순위를 나타냅니다.

+
.... 오류 도메인 분리를 위해서는 소스 볼륨 노드와 다른 노드에 위치한 집계가 선호됩니다.
.... 클러스터 내 노드 간 부하 분산을 활성화하려면 볼륨이 적은 노드에 대한 집계가 더 좋습니다.
.... 용량 균형을 맞추기 위해서는 다른 집계보다 여유 공간이 더 많은 집계가 선호됩니다.  1등급은 세 가지 기준에 따라 집계된 결과가 가장 선호된다는 것을 의미합니다.


*** 집계 이름
+
집계의 이름

*** 사용 가능한 용량
*** 집계된 데이터에 사용 가능한 공간의 양
*** 리소스 풀
+
집계가 속한 리소스 풀의 이름



** 명명 규칙
+
대상 볼륨에 적용되는 기본 명명 규칙을 지정합니다.  제공된 명명 규칙을 사용할 수도 있고, 사용자 정의 명명 규칙을 만들 수도 있습니다.  명명 규칙에는 %C, %M, %V, %N과 같은 속성이 있을 수 있습니다. 여기서 %C는 클러스터 이름이고, %M은 SVM 이름이고, %V는 소스 볼륨이고, %N은 토폴로지 대상 노드 이름입니다.

+
입력한 내용이 올바르지 않으면 명명 규칙 필드가 빨간색으로 강조 표시됩니다.  "이름 미리 보기" 링크를 클릭하면 입력한 명명 규칙의 미리 보기가 표시되고, 텍스트 필드에 명명 규칙을 입력함에 따라 미리 보기 텍스트가 동적으로 업데이트됩니다.  관계가 생성될 때 대상 이름에 001에서 999 사이의 접미사가 추가되어 미리 보기 텍스트에 표시되는 nnn을 대체합니다. 즉, 001이 먼저 지정되고 002가 두 번째로 지정되는 식입니다.



* *관계 설정*
+
보호 관계에 사용되는 최대 전송 속도, SnapMirror 정책 및 일정을 지정할 수 있습니다.

+
** 최대 전송 속도
+
네트워크를 통해 클러스터 간에 데이터가 전송되는 최대 속도를 지정합니다.  최대 전송 속도를 사용하지 않기로 선택하면 관계 간 기준 전송은 무제한입니다.

** SnapMirror 정책
+
관계에 대한 ONTAP SnapMirror 정책을 지정합니다.  기본값은 DPDefault입니다.

** 정책 생성
+
SnapMirror 정책 만들기 대화 상자를 실행하여 새 SnapMirror 정책을 만들고 사용할 수 있습니다.

** SnapMirror 일정
+
관계에 대한 ONTAP SnapMirror 정책을 지정합니다.  이용 가능한 일정에는 없음, 5분, 8시간, 매일, 매시간, 매주가 있습니다.  기본값은 없음으로, 관계에 일정이 연관되지 않았음을 나타냅니다.  일정이 없는 관계는 저장 서비스에 속하지 않는 한 지연 상태 값이 없습니다.

** 일정 만들기
+
새로운 SnapMirror 일정을 만들 수 있는 일정 만들기 대화 상자를 실행합니다.







== SnapVault 탭

SnapVault 관계를 생성하는 동안 보호 관계에 대한 보조 클러스터, SVM 및 집계를 지정할 수 있으며 보조 볼륨에 대한 명명 규칙도 지정할 수 있습니다.  SnapVault 정책과 일정을 지정할 수도 있습니다.

* *토폴로지 뷰*
+
만들고 있는 관계의 시각적 표현을 표시합니다.  토폴로지의 SnapVault 보조 리소스는 기본적으로 강조 표시됩니다.

* *2차 정보*
+
보호 관계에 대한 보조 리소스를 선택할 수 있습니다.

+
** 고급 링크
+
고급 보조 설정 대화 상자를 시작합니다.

** 무리
+
보조 보호 호스트로 사용 가능한 클러스터를 나열합니다.  이 필드는 필수입니다.

** 스토리지 가상 머신(SVM)
+
선택한 클러스터에서 사용 가능한 SVM을 나열합니다.  SVM 목록을 채우기 전에 클러스터를 선택해야 합니다.  이 필드는 필수입니다.

** 골재
+
선택한 SVM에서 사용할 수 있는 집계를 나열합니다.  집계 목록을 채우기 전에 클러스터를 선택해야 합니다.  이 필드는 필수입니다.  집계 목록에는 다음 정보가 표시됩니다.

+
*** 계급
+
여러 집계가 목적지에 대한 모든 요구 사항을 충족하는 경우 순위는 다음 조건에 따라 집계가 나열된 우선순위를 나타냅니다.

+
.... 장애 도메인 분리를 위해서는 기본 볼륨 노드와 다른 노드에 위치한 집계가 선호됩니다.
.... 클러스터 내 노드 간 부하 분산을 활성화하려면 볼륨이 적은 노드에 대한 집계가 더 좋습니다.
.... 용량 균형을 맞추기 위해서는 다른 집계보다 여유 공간이 더 많은 집계가 선호됩니다.  1등급은 세 가지 기준에 따라 집계된 결과가 가장 선호된다는 것을 의미합니다.


*** 집계 이름
+
집계의 이름

*** 사용 가능한 용량
*** 집계된 데이터에 사용 가능한 공간의 양
*** 리소스 풀
+
집계가 속한 리소스 풀의 이름



** 명명 규칙
+
보조 볼륨에 적용되는 기본 명명 규칙을 지정합니다.  제공된 명명 규칙을 사용할 수도 있고, 사용자 정의 명명 규칙을 만들 수도 있습니다.  명명 규칙에는 %C, %M, %V, %N과 같은 속성이 있을 수 있습니다. 여기서 %C는 클러스터 이름이고, %M은 SVM 이름이고, %V는 소스 볼륨이고, %N은 토폴로지 보조 노드 이름입니다.

+
입력한 내용이 올바르지 않으면 명명 규칙 필드가 빨간색으로 강조 표시됩니다.  "이름 미리 보기" 링크를 클릭하면 입력한 명명 규칙의 미리 보기가 표시되고, 텍스트 필드에 명명 규칙을 입력함에 따라 미리 보기 텍스트가 동적으로 업데이트됩니다.  잘못된 값을 입력하면 잘못된 정보가 미리 보기 영역에 빨간색 물음표로 표시됩니다.  관계가 생성될 때 2차 이름에 001~999 사이의 접미사가 추가되어 미리 보기 텍스트에 표시되는 nnn을 대체합니다. 즉, 001이 먼저 지정되고, 002가 두 번째로 지정되는 식입니다.



* *관계 설정*
+
보호 관계에 사용되는 최대 전송 속도, SnapVault 정책 및 SnapVault 일정을 지정할 수 있습니다.

+
** 최대 전송 속도
+
네트워크를 통해 클러스터 간에 데이터가 전송되는 최대 속도를 지정합니다.  최대 전송 속도를 사용하지 않기로 선택하면 관계 간 기준 전송은 무제한입니다.

** SnapVault 정책
+
관계에 대한 ONTAP SnapVault 정책을 지정합니다.  기본값은 XDPDefault입니다.

** 정책 생성
+
SnapVault 정책 만들기 대화 상자를 실행하면 새 SnapVault 정책을 만들고 사용할 수 있습니다.

** SnapVault 일정
+
관계에 대한 ONTAP SnapVault 일정을 지정합니다.  이용 가능한 일정에는 없음, 5분, 8시간, 매일, 매시간, 매주가 있습니다.  기본값은 없음으로, 관계에 일정이 연관되지 않았음을 나타냅니다.  일정이 없는 관계는 저장 서비스에 속하지 않는 한 지연 상태 값이 없습니다.

** 일정 만들기
+
SnapVault 일정을 만들 수 있는 일정 만들기 대화 상자를 실행합니다.







== 명령 버튼

명령 버튼을 사용하면 다음 작업을 수행할 수 있습니다.

* *취소*
+
선택 사항을 취소하고 보호 구성 대화 상자를 닫습니다.

* *적용하다*
+
선택 사항을 적용하고 보호 프로세스를 시작합니다.


