---
permalink: data-protection/reference_create_schedule_dialog_box.html 
sidebar: sidebar 
keywords: create, schedule, dialog box 
summary: 일정 만들기 대화 상자를 사용하면 SnapMirror 및 SnapVault 관계 전송에 대한 기본 또는 고급 보호 일정을 만들 수 있습니다.  데이터가 자주 업데이트되는 경우 데이터 전송 빈도를 높이기 위해 새로운 일정을 만들 수도 있고, 데이터가 자주 변경되지 않는 경우 덜 빈번한 일정을 만들 수도 있습니다. 
---
= 일정 만들기 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
일정 만들기 대화 상자를 사용하면 SnapMirror 및 SnapVault 관계 전송에 대한 기본 또는 고급 보호 일정을 만들 수 있습니다.  데이터가 자주 업데이트되는 경우 데이터 전송 빈도를 높이기 위해 새로운 일정을 만들 수도 있고, 데이터가 자주 변경되지 않는 경우 덜 빈번한 일정을 만들 수도 있습니다.

SnapMirror 동기 관계에는 일정을 구성할 수 없습니다.

* *목적지 클러스터*
+
보호 구성 대화 상자의 SnapVault 탭이나 SnapMirror 탭에서 선택한 클러스터의 이름입니다.

* *일정명*
+
일정에 제공하는 이름입니다.  일정 이름은 A~Z, a~z, 0~9 문자와 ! 등의 특수 문자로 구성될 수 있습니다.  @ # $ % {캐럿} & * ( ) _ -.  일정 이름에는 다음 문자를 포함할 수 없습니다: < >.

* *기본 또는 고급*
+
사용하려는 일정 모드입니다.

+
기본 모드에는 다음 요소가 포함됩니다.

+
** 반복하다
+
예정된 환승이 발생하는 빈도.  선택 가능한 요금제로는 시간별, 일별, 주별 등이 있습니다.

** 낮
+
주간 반복을 선택하면 전송이 발생하는 요일이 지정됩니다.

** 시간
+
매일 또는 매주를 선택하면 전송이 발생하는 시간입니다.



+
고급 모드에는 다음 요소가 포함됩니다.

+
** 개월
+
1년의 월을 나타내는 쉼표로 구분된 숫자 목록입니다.  유효한 값은 0~11이며, 0은 1월을 나타냅니다.  이 요소는 선택 사항입니다.  이 필드를 비워두면 매월 이체가 발생한다는 것을 의미합니다.

** 날
+
해당 월의 날짜를 나타내는 쉼표로 구분된 숫자 목록입니다.  유효한 값은 1~31입니다.  이 요소는 선택 사항입니다.  이 필드를 비워두면 매월 매일 이체가 이루어진다는 것을 의미합니다.

** 주중
+
요일을 나타내는 쉼표로 구분된 숫자 목록입니다.  유효한 값은 0~6이며, 0은 일요일을 나타냅니다.  이 요소는 선택 사항입니다.  이 필드를 비워두면 주중 매일 이체가 발생한다는 것을 의미합니다.  요일은 지정되었지만 월의 날짜는 지정되지 않은 경우, 이체는 지정된 요일에만 발생하며 매일 발생하지 않습니다.

** 시간
+
하루의 시간을 나타내는 쉼표로 구분된 숫자 목록입니다.  유효한 값은 0~23이며, 0은 자정을 나타냅니다.  이 요소는 선택 사항입니다.

** 분
+
한 시간의 분을 나타내는 쉼표로 구분된 숫자 목록입니다.  유효한 값은 0~59입니다.  이 요소는 필수입니다.




