---
permalink: data-protection/reference_protection_storage_virtual_machine_associations_page.html 
sidebar: sidebar 
keywords: svm, association, page 
summary: 저장소 VM 연결 페이지를 사용하면 소스 및 대상 저장소 VM 간의 기존 저장소 VM 연결을 볼 수 있습니다. 
---
= 스토리지 VM 연결 이해
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 가상 머신(스토리지 VM) 연결은 파트너 애플리케이션에서 리소스 선택 및 보조 볼륨 프로비저닝을 위해 사용되는 소스 스토리지 VM에서 대상 스토리지 VM으로의 매핑입니다.

대상 스토리지 VM이 2차 대상인지 3차 대상인지에 관계없이 소스 스토리지 VM과 대상 스토리지 VM 간에 연결이 생성됩니다.  2차 대상 저장소 VM을 소스로 사용하여 3차 대상 저장소 VM과 연결을 생성할 수 없습니다.

애플리케이션 관리자 또는 스토리지 관리자는 *보호* > *스토리지 VM 연결* 페이지에서 환경의 스토리지 VM 연결을 볼 수 있습니다.

SVM을 연결하는 방법은 세 가지가 있습니다.

* *모든 스토리지 VM 연결*: 모든 기본 소스 스토리지 VM과 하나 이상의 대상 SVM 간에 연결을 생성할 수 있습니다.  즉, 현재 보호가 필요한 모든 기존 SVM과 향후 생성되는 모든 SVM이 지정된 대상 SVM과 연결됩니다.  예를 들어, 서로 다른 위치에 있는 여러 소스의 애플리케이션을 하나의 위치에 있는 하나 이상의 대상 SVM에 백업하려고 할 수 있습니다.
* *특정 스토리지 VM 연결*: 특정 소스 스토리지 VM과 하나 이상의 특정 대상 SVM 간에 연결을 생성할 수 있습니다.  예를 들어, 서로 분리된 데이터가 필요한 여러 클라이언트에 스토리지 서비스를 제공하는 경우 이 옵션을 선택하여 특정 소스 스토리지 VM을 해당 클라이언트에만 할당된 특정 대상 스토리지 VM에 연결할 수 있습니다.
* *외부 스토리지 VM과 연결*: 소스 스토리지 VM과 대상 스토리지 VM의 외부 유연 볼륨 간에 연결을 생성할 수 있습니다.




[[create-storage-vm-associations]]
== 스토리지 VM 연결 생성

스토리지 가상 머신 연결 만들기 마법사를 사용하면 파트너 보호 애플리케이션이 SnapMirror 및 SnapVault 관계와 함께 사용할 소스 스토리지 VM을 대상 스토리지 VM과 연결할 수 있습니다.  파트너 애플리케이션은 대상 볼륨의 초기 프로비저닝 시 이러한 연결을 사용하여 선택할 리소스를 결정합니다.

.시작하기 전에
* 연결하려는 스토리지 VM은 이미 존재해야 합니다.
* 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.


모든 소스 스토리지 VM 및 관계 유형의 경우 각 대상 클러스터에서 하나의 대상 스토리지 VM만 선택할 수 있습니다.

삭제 및 생성 기능을 사용하여 연결을 변경하면 향후 프로비저닝 작업에만 영향을 미칩니다.  기존 대상 볼륨은 이동하지 않습니다.

.단계
. 왼쪽 탐색 창에서 *보호* > *저장소 VM 연결*을 클릭합니다.
. *저장소 VM 연결* 페이지에서 *만들기*를 클릭합니다.
+
*스토리지 가상 머신 연결 만들기* 마법사가 시작됩니다.

. 다음 소스 중 하나를 선택하세요.
+
** *어느*
+
기본 스토리지 VM 소스와 하나 이상의 대상 스토리지 VM 간의 연결을 생성하려면 이 옵션을 선택하세요.  즉, 현재 보호가 필요한 모든 기존 스토리지 VM과 향후 생성되는 모든 스토리지 VM이 지정된 대상 스토리지 VM과 연결됩니다.  예를 들어, 서로 다른 위치에 있는 여러 소스의 애플리케이션을 하나의 위치에 있는 하나 이상의 대상 스토리지 VM에 백업하고 싶을 수 있습니다.

** *하나의*
+
하나 이상의 대상 스토리지 VM과 연관된 특정 소스 스토리지 VM을 선택하려면 이 옵션을 선택하세요.  예를 들어, 서로 분리된 데이터가 필요한 여러 클라이언트에 스토리지 서비스를 제공하는 경우 이 옵션을 선택하면 특정 스토리지 VM 소스를 해당 클라이언트에만 할당된 특정 스토리지 VM 대상에 연결할 수 있습니다.

** *없음(외부)*
+
소스 스토리지 VM과 대상 스토리지 VM의 외부 유연 볼륨 간에 연결을 생성하려면 이 옵션을 선택하세요.



. 만들려는 보호 관계 유형 중 하나 또는 둘 다를 선택하세요.
+
** * SnapMirror*
** * SnapVault*


. *다음*을 클릭하세요.
. 하나 이상의 스토리지 VM 보호 대상을 선택하세요.
. *마침*을 클릭하세요.




[[delete-storage-vm-associations]]
== 스토리지 VM 연결 삭제

소스 및 대상 스토리지 VM 간의 보조 프로비저닝 관계를 제거하기 위해 파트너 애플리케이션의 스토리지 VM 연결을 삭제할 수 있습니다. 예를 들어, 대상 스토리지 VM이 가득 차서 새로운 스토리지 VM 보호 연결을 만들 때 이 작업을 수행할 수 있습니다.

.시작하기 전에
애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

최소 하나의 스토리지 VM 연결이 선택될 때까지 *삭제* 버튼은 비활성화됩니다.  삭제 및 생성 기능을 사용하여 연결을 변경하면 향후 프로비저닝 작업에만 영향을 미치며 기존 대상 볼륨은 이동하지 않습니다.

.단계
. 왼쪽 탐색 창에서 *보호* > *저장소 VM 연결*을 클릭합니다.
. 최소한 하나의 스토리지 VM 연결을 선택하세요.
+
*삭제* 버튼이 활성화되었습니다.

. *삭제*를 클릭하세요.
+
경고 대화 상자가 표시됩니다.

. 계속하려면 *예*를 클릭하세요.
+
선택한 스토리지 VM 연결이 목록에서 제거됩니다.


