---
permalink: data-protection/reference_edit_relationship_dialog_box.html 
sidebar: sidebar 
keywords: edit, relationship, dialog box 
summary: 기존 보호 관계를 편집하여 최대 전송 속도, 보호 정책 또는 보호 일정을 변경할 수 있습니다. 
---
= 관계 편집 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 보호 관계를 편집하여 최대 전송 속도, 보호 정책 또는 보호 일정을 변경할 수 있습니다.



[[destination-information]]
== 목적지 정보

* *목적지 클러스터*
+
선택한 대상 클러스터의 이름입니다.

* *대상 SVM*
+
선택된 SVM의 이름

* *관계 설정*
+
보호 관계에 사용되는 최대 전송 속도, SnapMirror 정책 및 일정을 지정할 수 있습니다.

+
** 최대 전송 속도
+
네트워크를 통해 클러스터 간에 기준 데이터가 전송되는 최대 속도를 지정합니다.  이 옵션을 선택하면 네트워크 대역폭이 지정한 값으로 제한됩니다.  숫자 값을 입력한 다음 초당 킬로바이트(KBps), 초당 메가바이트(MBps), 초당 기가바이트(GBps), 초당 테라바이트(TBps)를 선택할 수 있습니다.  지정하는 최대 전송 속도는 1KBps보다 크고 4TBps보다 작아야 합니다.  최대 전송 속도를 사용하지 않기로 선택하면 관계 간 기준 전송은 무제한입니다.  기본 클러스터와 보조 클러스터가 동일한 경우 이 설정은 비활성화됩니다.

** SnapMirror 정책
+
관계에 대한 ONTAP SnapMirror 정책을 지정합니다.  기본값은 DPDefault입니다.

** 정책 생성
+
SnapMirror 정책 만들기 대화 상자를 실행하여 새 SnapMirror 정책을 만들고 사용할 수 있습니다.

** SnapMirror 일정
+
관계에 대한 ONTAP SnapMirror 정책을 지정합니다.  이용 가능한 일정에는 없음, 5분, 8시간, 매일, 매시간, 매주가 있습니다.  기본값은 없음으로, 관계에 일정이 연관되지 않았음을 나타냅니다.  일정이 없는 관계는 저장 서비스에 속하지 않는 한 지연 상태 값이 없습니다.

** 일정 만들기
+
새로운 SnapMirror 일정을 만들 수 있는 일정 만들기 대화 상자를 실행합니다.







[[command-buttons]]
== 명령 버튼

명령 버튼을 사용하면 다음 작업을 수행할 수 있습니다.

* *취소*
+
선택 사항을 취소하고 보호 구성 대화 상자를 닫습니다.

* *제출하다*
+
선택 사항을 적용하고 관계 편집 대화 상자를 닫습니다.


