---
permalink: data-protection/reference_select_source_snapshot_copy_dialog_box.html 
sidebar: sidebar 
keywords: select, source, snapshot, copy, dialog box 
summary: 소스 스냅샷 복사본 선택 대화 상자를 사용하여 보호 관계 간에 데이터를 전송할 특정 스냅샷 복사본을 선택하거나 관계를 초기화, 업데이트 또는 재동기화하는지 여부와 관계가 SnapMirror 인지 SnapVault 인지에 따라 달라지는 기본 동작을 선택합니다. 
---
= 소스 스냅샷 복사 대화 상자 선택
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
소스 스냅샷 복사본 선택 대화 상자를 사용하여 보호 관계 간에 데이터를 전송할 특정 스냅샷 복사본을 선택하거나 관계를 초기화, 업데이트 또는 재동기화하는지 여부와 관계가 SnapMirror 인지 SnapVault 인지에 따라 달라지는 기본 동작을 선택합니다.



[[default]]
== 기본

SnapVault 및 SnapMirror 관계에 대한 초기화, 업데이트 및 재동기화 전송에 사용되는 스냅샷 복사본을 결정하기 위한 기본 동작을 선택할 수 있습니다.

SnapVault 전송을 수행하는 경우 각 작업에 대한 기본 동작은 다음과 같습니다.

[cols="3*"]
|===
| 작업 | 소스가 읽기/쓰기일 때의 기본 SnapVault 동작 | 소스가 DP(데이터 보호)인 경우의 기본 SnapVault 동작 


 a| 
초기화
 a| 
새로운 스냅샷 사본을 만들어 전송합니다.
 a| 
마지막으로 내보낸 스냅샷 사본을 전송합니다.



 a| 
업데이트
 a| 
정책에 명시된 대로 스냅샷 복사본만 전송합니다.
 a| 
마지막으로 내보낸 스냅샷 사본을 전송합니다.



 a| 
재동기화
 a| 
최신 일반 스냅샷 복사본 이후에 생성된 모든 레이블이 지정된 스냅샷 복사본을 전송합니다.
 a| 
가장 최신으로 레이블이 지정된 스냅샷 복사본을 전송합니다.

|===
SnapMirror 전송을 수행하는 경우 각 작업에 대한 기본 동작은 다음과 같습니다.

[cols="3*"]
|===
| 작업 | 기본 SnapMirror 동작 | SnapMirror 대 SnapMirror 캐스케이드에서 관계가 두 번째 홉일 때의 기본 SnapMirror 동작 


 a| 
초기화
 a| 
새로운 스냅샷 복사본을 만들고, 새 스냅샷 복사본과 이전에 만들어진 모든 스냅샷 복사본을 전송합니다.
 a| 
소스에서 모든 스냅샷 복사본을 전송합니다.



 a| 
업데이트
 a| 
새로운 스냅샷 복사본을 만들고, 새 스냅샷 복사본과 이전에 만들어진 모든 스냅샷 복사본을 전송합니다.
 a| 
모든 스냅샷 사본을 전송합니다.



 a| 
재동기화
 a| 
새로운 스냅샷 복사본을 만든 다음 소스에서 모든 스냅샷 복사본을 전송합니다.
 a| 
2차 볼륨에서 3차 볼륨으로 모든 스냅샷 복사본을 전송하고, 최신 공통 스냅샷 복사본을 만든 후 추가된 모든 데이터를 삭제합니다.

|===


[[existing-snapshot-copy]]
== 기존 스냅샷 복사본

해당 작업에 대해 스냅샷 복사 선택이 허용되는 경우 목록에서 기존 스냅샷 복사본을 선택할 수 있습니다.

* *스냅샷 사본*
+
전송할 항목을 선택할 수 있는 기존 스냅샷 복사본을 표시합니다.

* *생성 날짜*
+
스냅샷 복사본이 생성된 날짜와 시간을 표시합니다.  스냅샷 사본은 가장 최근 것부터 가장 오래된 것 순으로 나열되며, 가장 최근 사본이 목록의 맨 위에 표시됩니다.



SnapVault 전송을 수행하고 소스에서 대상으로 전송할 기존 스냅샷 복사본을 선택하려는 경우 각 작업에 대한 동작은 다음과 같습니다.

[cols="3*"]
|===
| 작업 | 스냅샷 복사본을 지정할 때 SnapVault 동작 | 캐스케이드에서 스냅샷 복사본을 지정할 때 SnapVault 동작 


 a| 
초기화
 a| 
지정된 스냅샷 복사본을 전송합니다.
 a| 
데이터 보호 볼륨에서는 소스 스냅샷 복사본 선택이 지원되지 않습니다.



 a| 
업데이트
 a| 
지정된 스냅샷 복사본을 전송합니다.
 a| 
데이터 보호 볼륨에서는 소스 스냅샷 복사본 선택이 지원되지 않습니다.



 a| 
재동기화
 a| 
선택한 스냅샷 복사본을 전송합니다.
 a| 
데이터 보호 볼륨에서는 소스 스냅샷 복사본 선택이 지원되지 않습니다.

|===
SnapMirror 전송을 수행하고 소스에서 대상으로 전송할 기존 스냅샷 복사본을 선택하려는 경우 각 작업에 대한 동작은 다음과 같습니다.

[cols="3*"]
|===
| 작업 | 스냅샷 복사본을 지정할 때 SnapMirror 동작 | 캐스케이드에서 스냅샷 복사본을 지정할 때 SnapMirror 동작 


 a| 
초기화
 a| 
지정된 스냅샷 복사본까지 소스의 모든 스냅샷 복사본을 전송합니다.
 a| 
데이터 보호 볼륨에서는 소스 스냅샷 복사본 선택이 지원되지 않습니다.



 a| 
업데이트
 a| 
지정된 스냅샷 복사본까지 소스의 모든 스냅샷 복사본을 전송합니다.
 a| 
데이터 보호 볼륨에서는 소스 스냅샷 복사본 선택이 지원되지 않습니다.



 a| 
재동기화
 a| 
소스에서 선택한 스냅샷 복사본까지 모든 스냅샷 복사본을 전송한 다음, 최신 공통 스냅샷 복사본을 만든 후 추가된 모든 데이터를 삭제합니다.
 a| 
데이터 보호 볼륨에서는 소스 스냅샷 복사본 선택이 지원되지 않습니다.

|===


[[command-buttons]]
== 명령 버튼

명령 버튼을 사용하면 다음 작업을 수행할 수 있습니다.

* *제출하다*
+
선택 사항을 제출하고 소스 스냅샷 복사 선택 대화 상자를 닫습니다.

* *취소*
+
선택 사항을 취소하고 소스 스냅샷 복사 선택 대화 상자를 닫습니다.


