---
permalink: data-protection/reference_relationship_last_1_month_transfer_status_view.html 
sidebar: sidebar 
keywords: relationship, 1 month, transfer status, view 
summary: '관계: 지난 1개월 전송 상태 보기를 사용하면 비동기 관계에 있는 볼륨 및 스토리지 VM의 특정 기간 동안의 전송 추세를 분석할 수 있습니다.  이 페이지에는 전송이 성공했는지 실패했는지도 표시됩니다.' 
---
= 관계: 지난 1개월 전송 상태 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관계: 지난 1개월 전송 상태 보기를 사용하면 비동기 관계에 있는 볼륨 및 스토리지 VM의 특정 기간 동안의 전송 추세를 분석할 수 있습니다.  이 페이지에는 전송이 성공했는지 실패했는지도 표시됩니다.

페이지 상단의 컨트롤을 사용하면 특정 객체를 찾기 위한 검색을 수행하고, 표시되는 데이터 목록을 좁히기 위한 필터를 만들고 적용하고, 페이지에서 열을 추가/제거/재정렬하고, 페이지의 데이터를 내보낼 수 있습니다. `.csv` , `.pdf` , 또는 `.xlsx` 파일.  페이지를 사용자 지정한 후 결과를 사용자 지정 보기로 저장한 다음 이 데이터에 대한 보고서를 생성하여 정기적으로 이메일로 전송하도록 예약할 수 있습니다.  *필터* 옵션을 사용하면 선택한 스토리지 시스템(예: 볼륨만 또는 스토리지 VM만)만 볼 수 있습니다.  동일한 보고서가 저장소 페이지에 표시되며, 선택한 저장소 엔터티에 대해서만 표시됩니다.  예를 들어, 볼륨 관계를 보고 싶다면 *저장소* > *저장소 VM* > *관계: 지난 1개월 전송 상태* 메뉴 또는 *보호* > *관계* > *관계: 지난 1개월 전송 상태* 메뉴에서 저장소 VM에 대한 관계: 지난 1개월 전송 상태 보고서에 액세스하고, *필터*를 사용하여 볼륨에 대한 데이터만 볼 수 있습니다.

* *소스 볼륨*
+
소스 볼륨 이름을 표시합니다.

* *목적지 볼륨*
+
대상 볼륨 이름을 표시합니다.

* *작업 유형*
+
볼륨 전송 유형을 표시합니다.

* *작업 결과*
+
볼륨 전송이 성공했는지 여부를 표시합니다.

* *전송 시작 시간*
+
볼륨 전송 시작 시간을 표시합니다.

* *전송 종료 시간*
+
볼륨 전송 종료 시간을 표시합니다.

* *이전 기간*
+
볼륨 전송을 완료하는 데 걸린 시간(시간)을 표시합니다.

* *전송 크기*
+
전송된 볼륨의 크기(MB)를 표시합니다.

* *출처 SVM*
+
스토리지 가상 머신(SVM) 이름을 표시합니다.

* *소스 클러스터*
+
소스 클러스터 이름을 표시합니다.

* *대상 SVM*
+
대상 SVM 이름을 표시합니다.

* *목적지 클러스터*
+
대상 클러스터 이름을 표시합니다.



*관련 정보*

* *관계: 모든 관계* 보기에 대한 정보는 다음을 참조하세요.link:../data-protection/reference_relationship_all_relationships_view.html["관계: 모든 관계 보기"] .
* *관계: MetroCluster* 보기에 대한 정보는 다음을 참조하세요.link:../storage-mgmt/task_monitor_metrocluster_configurations.html["MetroCluster 구성 모니터링"] .
* *관계: 모든 관계* 보기에 대한 정보는 다음을 참조하세요.link:../data-protection/reference_relationship_last_1_month_transfer_rate_view.html["관계: 지난 1개월 전송률 보기"] .

