---
permalink: data-protection/task_configure_connection_between_workflow_automation_um.html 
sidebar: sidebar 
keywords: configure, connection, workflow, automation, unified manager 
summary: 'OnCommand Workflow Automation (WFA)과 Unified Manager 간에 보안 연결을 구성할 수 있습니다.  Workflow Automation에 연결하면 SnapMirror 및 SnapVault 구성 워크플로와 같은 보호 기능은 물론 SnapMirror 관계를 관리하는 명령도 사용할 수 있습니다.' 
---
= Workflow Automation과 Unified Manager 간 연결 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation (WFA)과 Unified Manager 간에 보안 연결을 구성할 수 있습니다.  Workflow Automation에 연결하면 SnapMirror 및 SnapVault 구성 워크플로와 같은 보호 기능은 물론 SnapMirror 관계를 관리하는 명령도 사용할 수 있습니다.

.시작하기 전에
* Workflow Automation의 설치된 버전은 5.1.1P6 이상이어야 합니다.
+
[NOTE]
====
"클러스터형 Data ONTAP 관리를 위한 WFA 팩"은 WFA 5.1.1P6에 포함되어 있으므로 과거처럼 NetAppStorage Automation Store에서 이 팩을 다운로드하여 WFA 서버에 별도로 설치할 필요가 없습니다. https://automationstore.netapp.com/pack-list.shtml["ONTAP 관리를 위한 WFA 팩"]

====
* WFA 및 Unified Manager 연결을 지원하려면 Unified Manager에서 만든 데이터베이스 사용자 이름이 있어야 합니다.
+
이 데이터베이스 사용자에게는 통합 스키마 사용자 역할이 할당되어 있어야 합니다.

* Workflow Automation에서 관리자 역할이나 아키텍트 역할이 지정되어야 합니다.
* Workflow Automation 설정을 위해서는 호스트 주소, 포트 번호 443, 사용자 이름, 비밀번호가 필요합니다.
* 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.


.단계
. 왼쪽 탐색 창에서 *일반* > *워크플로 자동화*를 클릭합니다.
. *워크플로 자동화 페이지*의 *데이터베이스 사용자* 영역에서 Unified Manager 및 워크플로 자동화 연결을 지원하기 위해 생성한 데이터베이스 사용자의 이름을 선택하고 비밀번호를 입력합니다.
. 해당 페이지의 *워크플로 자동화 자격 증명* 영역에서 워크플로 자동화 설정을 위한 호스트 이름 또는 IP 주소(IPv4 또는 IPv6)와 사용자 이름 및 비밀번호를 입력합니다.
+
Unified Manager 서버 포트(포트 443)를 사용해야 합니다.

. *저장*을 클릭하세요.
. 자체 서명 인증서를 사용하는 경우 *예*를 클릭하여 보안 인증서를 승인합니다.
+
워크플로 자동화 페이지가 표시됩니다.

. *예*를 클릭하면 웹 UI가 다시 로드되고 워크플로 자동화 기능이 추가됩니다.


*관련 정보*

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61550["NetApp 설명서: OnCommand Workflow Automation (현재 릴리스)"]
