---
permalink: data-protection/task_create_snapmirror_relationships_with_version_flexible_replication.html 
sidebar: sidebar 
keywords: create, snapmirror, relationships, version-flexible, replication, backup, option 
summary: 버전에 따라 유연한 복제 및 백업 옵션 기능을 통해 SnapMirror 관계를 만들 수 있습니다.  백업 옵션 기능을 사용하면 SnapMirror 보호를 구현하고 대상 위치에 여러 버전의 백업 사본을 보관할 수 있습니다. 
---
= 백업 옵션이 있는 버전 유연한 복제를 통해 SnapMirror 관계 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
버전에 따라 유연한 복제 및 백업 옵션 기능을 통해 SnapMirror 관계를 만들 수 있습니다.  백업 옵션 기능을 사용하면 SnapMirror 보호를 구현하고 대상 위치에 여러 버전의 백업 사본을 보관할 수 있습니다.

.시작하기 전에
* 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 워크플로 자동화를 설정해야 합니다.
* 소스 및 대상 SVM에는 각각 SnapMirror 라이선스가 활성화되어 있어야 합니다.
* 소스 및 대상 SVM에는 각각 SnapVault 라이선스가 활성화되어 있어야 합니다.
* 소스 및 대상 SVM은 각각 버전 유연한 복제를 지원하는 ONTAP 소프트웨어 버전에서 실행되어야 합니다.


SnapMirror 백업 옵션 기능으로 구성하면 볼륨 장애 조치 기능과 같은 SnapMirror 재해 복구 기능으로 데이터를 보호하고 동시에 다중 백업 사본 보호와 같은 SnapVault 기능도 제공할 수 있습니다.

.단계
. 보호하려는 볼륨에 대한 *보호 구성* 대화 상자를 표시합니다.
+
** 볼륨/상태 세부 정보 페이지의 보호 탭을 보고 있는 경우 토폴로지 보기에서 보호하려는 볼륨의 이름을 마우스 오른쪽 버튼으로 클릭하고 메뉴에서 *보호* > * SnapMirror*를 선택합니다.
** 상태: 모든 볼륨 보기를 보고 있는 경우 보호하려는 볼륨을 찾아 마우스 오른쪽 버튼을 클릭한 다음 메뉴에서 *보호* > * SnapMirror*를 선택합니다.  보호 구성 대화 상자가 표시됩니다.


. * SnapMirror*를 클릭하면 * SnapMirror* 탭을 볼 수 있습니다.
. *보호 구성* 대화 상자에서 *대상 정보* 영역과 *관계 설정* 영역을 작성합니다.
. *고급*을 클릭하면 *고급 대상 설정* 대화 상자가 표시됩니다.
. *버전-유연한 복제* 확인란이 아직 선택되어 있지 않으면 지금 선택하세요.
. 백업 옵션 기능을 활성화하려면 *백업 옵션 사용* 확인란을 선택한 다음 *적용*을 클릭합니다.
. *적용*을 클릭하세요.
+
볼륨/상태 세부 정보 페이지로 돌아갑니다.

. *볼륨/상태* 세부 정보 페이지 상단에 있는 보호 구성 작업 링크를 클릭합니다.
+
작업의 과제와 세부 정보는 작업 세부 정보 페이지에 표시됩니다.

. *작업* 세부 정보 페이지에서 *새로 고침*을 클릭하면 보호 구성 작업과 관련된 작업 목록과 작업 세부 정보가 업데이트되고 작업이 완료되는 시점을 확인할 수 있습니다.
. 작업이 완료되면 브라우저에서 *뒤로*를 클릭하여 *볼륨/상태* 세부 정보 페이지로 돌아갑니다.
+
새로운 관계는 볼륨/상태 세부 정보 페이지 토폴로지 보기에 표시됩니다.


