---
permalink: data-protection/task_abort_active_data_protection_transfer_from_health_volume.html 
sidebar: sidebar 
keywords: abort, active, data protection, transfer, volume health details page 
summary: 진행 중인 SnapMirror 복제를 중지하려면 활성 데이터 보호 전송을 중단할 수 있습니다.  기준 전송이 아닌 경우 전송에 대한 재시작 체크포인트를 지울 수도 있습니다.  볼륨 이동 등 다른 작업과 충돌하는 경우 전송을 중단할 수 있습니다. 
---
= 볼륨/상태 세부 정보 페이지에서 활성 데이터 보호 전송을 중단합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
진행 중인 SnapMirror 복제를 중지하려면 활성 데이터 보호 전송을 중단할 수 있습니다.  기준 전송이 아닌 경우 전송에 대한 재시작 체크포인트를 지울 수도 있습니다.  볼륨 이동 등 다른 작업과 충돌하는 경우 전송을 중단할 수 있습니다.

[NOTE]
====
일관성 그룹으로 보호되는 볼륨 관계는 중단할 수 없습니다.

====
.시작하기 전에
* 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 워크플로 자동화를 설정해야 합니다.


다음의 경우에는 중단 동작이 표시되지 않습니다.

* RBAC 설정에서 이 작업이 허용되지 않는 경우(예: 운영자 권한만 있는 경우)
* 볼륨 ID를 알 수 없는 경우: 예를 들어 클러스터 간 관계가 있고 대상 클러스터가 아직 검색되지 않은 경우


기준선 전송에 대한 재시작 체크포인트를 지울 수 없습니다.

.단계
. *볼륨/상태* 세부 정보 페이지의 *보호* 탭에서 중단하려는 데이터 전송에 대한 토폴로지 보기의 관계를 마우스 오른쪽 버튼으로 클릭하고 *중단*을 선택합니다.
+
전송 중단 대화 상자가 표시됩니다.

. 기준선 전송이 아닌 전송에 대한 재시작 체크포인트를 지우려면 *체크포인트 지우기*를 선택하세요.
. *계속*을 클릭하세요.
+
전송 중단 대화 상자가 닫히고 중단 작업 상태가 볼륨/상태 세부 정보 페이지 상단에 작업 세부 정보에 대한 링크와 함께 표시됩니다.

. *선택 사항:* *세부 정보 보기* 링크를 클릭하면 *작업* 세부 정보 페이지로 이동하여 추가 세부 정보를 확인하고 작업 진행 상황을 볼 수 있습니다.
. 각 작업을 클릭하면 자세한 내용을 볼 수 있습니다.
. 브라우저의 뒤로 화살표를 클릭하면 *볼륨/상태* 세부 정보 페이지로 돌아갑니다.
+
모든 작업이 성공적으로 완료되면 중단 작업이 종료됩니다.


