---
permalink: data-protection/task_create_snapmirror_relationship_with_version_flexible_replication.html 
sidebar: sidebar 
keywords: create, snapmirror, relationship, version-flexible, replication 
summary: 버전에 따라 유연한 복제를 통해 SnapMirror 관계를 만들 수 있습니다.  버전에 유연한 복제를 사용하면 소스 및 대상 볼륨이 서로 다른 ONTAP 버전에서 실행되는 경우에도 SnapMirror 보호를 구현할 수 있습니다. 
---
= 버전에 따라 유연한 복제를 통해 SnapMirror 관계 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
버전에 따라 유연한 복제를 통해 SnapMirror 관계를 만들 수 있습니다.  버전에 유연한 복제를 사용하면 소스 및 대상 볼륨이 서로 다른 ONTAP 버전에서 실행되는 경우에도 SnapMirror 보호를 구현할 수 있습니다.

.시작하기 전에
* 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 워크플로 자동화를 설정해야 합니다.
* 소스 및 대상 SVM에는 각각 SnapMirror 라이선스가 활성화되어 있어야 합니다.
* 소스 및 대상 SVM은 각각 버전 유연한 복제를 지원하는 ONTAP 소프트웨어 버전에서 실행되어야 합니다.


버전 유연한 복제 기능을 갖춘 SnapMirror 사용하면 모든 스토리지가 하나의 ONTAP 버전으로 실행되지 않는 이기종 스토리지 환경에서도 SnapMirror 보호 기능을 구현할 수 있습니다. 그러나 버전 유연한 복제 기능을 갖춘 SnapMirror 에서 수행되는 미러 작업은 기존 블록 복제 SnapMirror 에서보다 빠르게 실행되지 않습니다.

.단계
. 보호하려는 볼륨에 대한 *보호 구성* 대화 상자를 표시합니다.
+
** 볼륨/상태 세부 정보 페이지의 보호 탭을 보고 있는 경우 보호하려는 볼륨의 이름이 있는 토폴로지 보기에서 마우스 오른쪽 버튼을 클릭하고 메뉴에서 *보호* > * SnapMirror*를 선택합니다.
** 상태: 모든 볼륨 보기를 보고 있는 경우 보호하려는 볼륨을 찾아 마우스 오른쪽 버튼을 클릭한 다음 메뉴에서 *보호* > * SnapMirror*를 선택합니다.  보호 구성 대화 상자가 표시됩니다.


. * SnapMirror*를 클릭하면 * SnapMirror* 탭을 볼 수 있습니다.
. *보호 구성* 대화 상자에서 *대상 정보* 영역과 *관계 설정* 영역을 작성합니다.
+
보호하고 있는 소스 볼륨보다 이전 버전의 ONTAP 에서 실행되는 대상 SVM을 지정하고 해당 이전 버전이 버전 유연한 복제를 지원하는 경우, 이 작업은 SnapMirror 버전 유연한 복제로 자동으로 구성합니다.

. 소스 볼륨과 동일한 ONTAP 버전에서 실행되는 대상 SVM을 지정했지만 SnapMirror 버전 유연한 복제로 구성하려는 경우 *고급*을 클릭하여 버전 유연한 복제를 활성화한 다음 *적용*을 클릭합니다.
. *적용*을 클릭하세요.
+
볼륨/상태 세부 정보 페이지로 돌아갑니다.

. *볼륨/상태* 세부 정보 페이지 상단에 있는 보호 구성 작업 링크를 클릭합니다.
+
작업의 과제와 세부 정보는 작업 세부 정보 페이지에 표시됩니다.

. *작업* 세부 정보 페이지에서 *새로 고침*을 클릭하면 보호 구성 작업과 관련된 작업 목록과 작업 세부 정보가 업데이트되고 작업이 완료되는 시점을 확인할 수 있습니다.
. 작업이 완료되면 브라우저에서 *뒤로*를 클릭하여 *볼륨/상태* 세부 정보 페이지로 돌아갑니다.
+
새로운 관계는 볼륨/상태 세부 정보 페이지 토폴로지 보기에 표시됩니다.


