---
permalink: data-protection/task_update_protection_voldtls_page.html 
sidebar: sidebar 
keywords: initialize, update, protection, relationships, volume, health details page 
summary: 새로운 보호 관계에 대한 최초 기준 전송을 수행하거나, 이미 초기화된 관계를 업데이트하고 데이터를 즉시 전송하기 위해 수동적이고 예약되지 않은 증분 업데이트를 수행할 수 있습니다. 
---
= 볼륨/상태 세부 정보 페이지에서 보호 관계 초기화 또는 업데이트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새로운 보호 관계에 대한 최초 기준 전송을 수행하거나, 이미 초기화된 관계를 업데이트하고 데이터를 즉시 전송하기 위해 수동적이고 예약되지 않은 증분 업데이트를 수행할 수 있습니다.

*참고*: 일관성 그룹으로 보호되는 볼륨은 초기화하거나 업데이트할 수 없습니다.

.시작하기 전에
* 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* OnCommand Workflow Automation 설정해야 합니다.


.단계
. *볼륨/상태* 세부 정보 페이지의 *보호* 탭에서 초기화하거나 업데이트하려는 보호 관계를 토폴로지에서 찾은 다음 마우스 오른쪽 버튼을 클릭합니다.
. 메뉴에서 *초기화/업데이트*를 선택합니다.
+
또는 *작업* 메뉴에서 *관계* > *초기화/업데이트*를 선택하여 현재 세부 정보를 보고 있는 관계를 초기화하거나 업데이트합니다.

+
초기화/업데이트 대화 상자가 표시됩니다.

. *전송 옵션* 탭에서 전송 우선순위와 최대 전송 속도를 선택하세요.
. *소스 스냅샷 복사본*을 클릭한 다음, *스냅샷 복사본* 열에서 *기본값*을 클릭합니다.
+
소스 스냅샷 복사본 선택 대화 상자가 표시됩니다.

. 기본 스냅샷 복사본을 전송하는 대신 기존 스냅샷 복사본을 지정하려면 *기존 스냅샷 복사본*을 클릭하고 목록에서 스냅샷 복사본을 선택합니다.
. *제출*을 클릭하세요.
+
초기화/업데이트 대화 상자로 돌아갑니다.

. 초기화 또는 업데이트할 소스를 두 개 이상 선택한 경우 기존 스냅샷 복사본을 지정하려는 다음 읽기/쓰기 소스에 대해 *기본값*을 클릭합니다.
+
데이터 보호 볼륨에 대해 다른 스냅샷 복사본을 선택할 수 없습니다.

. 초기화 또는 업데이트 작업을 시작하려면 *제출*을 클릭하세요.
+
초기화 또는 업데이트 작업이 시작되면 볼륨/상태 세부 정보 페이지로 돌아가고, 페이지 상단에 작업 링크가 표시됩니다.

. *선택 사항:* 볼륨/상태* 세부 정보 페이지에서 *작업 보기*를 클릭하여 각 초기화 또는 업데이트 작업의 상태를 추적합니다.
+
필터링된 작업 목록이 표시됩니다.

. *선택 사항:* 각 직업을 클릭하여 세부 정보를 확인하세요.
. *선택 사항:* 브라우저의 뒤로 화살표를 클릭하여 *볼륨/상태* 세부 정보 페이지로 돌아갑니다.
+
모든 작업이 성공적으로 완료되면 초기화 또는 업데이트 작업이 완료됩니다.


