---
permalink: data-protection/task_create_snapmirror_relationship_from_health_volume.html 
sidebar: sidebar 
keywords: create, snapmirror, protection, relationship,  volume, health details page 
summary: 볼륨/상태 세부 정보 페이지를 사용하여 SnapMirror 관계를 생성하면 보호 목적으로 데이터 복제가 활성화됩니다.  SnapMirror 복제를 사용하면 소스 볼륨에서 데이터가 손실된 경우 대상 볼륨에서 데이터를 복원할 수 있습니다. 
---
= 볼륨/상태 세부 정보 페이지에서 SnapMirror 보호 관계를 만듭니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨/상태 세부 정보 페이지를 사용하여 SnapMirror 관계를 생성하면 보호 목적으로 데이터 복제가 활성화됩니다.  SnapMirror 복제를 사용하면 소스 볼륨에서 데이터가 손실된 경우 대상 볼륨에서 데이터를 복원할 수 있습니다.

.시작하기 전에
* 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 워크플로 자동화를 설정해야 합니다.


다음의 경우에는 *보호* 메뉴가 표시되지 않습니다.

* RBAC 설정에서 이 작업이 허용되지 않는 경우(예: 운영자 권한만 있는 경우)
* 볼륨 ID를 알 수 없는 경우: 예를 들어 클러스터 간 관계가 있고 대상 클러스터가 아직 검색되지 않은 경우


최대 10개의 보호 작업을 성능 저하 없이 동시에 수행할 수 있습니다.  11~30개의 작업을 동시에 실행하면 성능 저하가 발생할 수 있습니다.  30개 이상의 작업을 동시에 실행하는 것은 권장되지 않습니다.

.단계
. *볼륨/상태* 세부 정보 페이지의 *보호* 탭에서 토폴로지 보기에서 보호하려는 볼륨의 이름을 마우스 오른쪽 버튼으로 클릭합니다.
. 메뉴에서 *보호* > * SnapMirror*를 선택합니다.
+
보호 구성 대화 상자가 표시됩니다.

. * SnapMirror* 탭을 보고 대상 정보를 구성하려면 * SnapMirror*를 클릭하세요.
. 필요에 따라 *고급*을 클릭하여 공간 보장을 설정한 다음 *적용*을 클릭합니다.
. *보호 구성* 대화 상자에서 *대상 정보* 영역과 *관계 설정* 영역을 작성합니다.
. *적용*을 클릭하세요.
+
볼륨/상태 세부 정보 페이지로 돌아갑니다.

. *볼륨/상태* 세부 정보 페이지 상단에 있는 보호 구성 작업 링크를 클릭합니다.
+
해당 직무의 과제와 세부 사항은 직무 세부 정보 페이지에 표시됩니다.

. *작업* 세부 정보 페이지에서 *새로 고침*을 클릭하면 보호 구성 작업과 관련된 작업 목록과 작업 세부 정보가 업데이트되고 작업이 완료되는 시점을 확인할 수 있습니다.
. 작업이 완료되면 브라우저에서 *뒤로*를 클릭하여 *볼륨/상태* 세부 정보 페이지로 돌아갑니다.
+
새로운 관계는 볼륨/상태 세부 정보 페이지 토폴로지 보기에 표시됩니다.



구성 중에 지정한 대상 SVM이나 고급 설정에서 활성화한 옵션에 따라 결과 SnapMirror 관계는 여러 가지 가능한 변형 중 하나가 될 수 있습니다.

* 소스 볼륨과 동일하거나 더 최신 버전의 ONTAP 에서 실행되는 대상 SVM을 지정한 경우 블록 복제 기반 SnapMirror 관계가 기본 결과입니다.
* 소스 볼륨과 동일하거나 더 최신 버전의 ONTAP 에서 실행되는 대상 SVM을 지정했지만 고급 설정에서 버전 유연한 복제를 활성화한 경우, 버전 유연한 복제를 사용하는 SnapMirror 관계가 생성됩니다.
* 이전 버전의 ONTAP 에서 실행되는 대상 SVM을 지정하거나 소스 볼륨보다 상위 버전이고 이전 버전이 버전 유연한 복제를 지원하는 경우 버전 유연한 복제를 지원하는 SnapMirror 관계가 자동으로 생성됩니다.

