---
permalink: data-protection/task_create_snapmirror_relationship_from_health_volumes.html 
sidebar: sidebar 
keywords: create, snapmirror, protection, relationship, health, volumes view 
summary: 'Health: All Volumes 보기를 사용하면 동일한 스토리지 VM에서 두 개 이상의 볼륨을 선택하여 한 번에 여러 SnapMirror 보호 관계를 만들 수 있습니다.' 
---
= Health: All Volumes 보기에서 SnapMirror 보호 관계를 만듭니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Health: All Volumes 보기를 사용하면 동일한 스토리지 VM에서 두 개 이상의 볼륨을 선택하여 한 번에 여러 SnapMirror 보호 관계를 만들 수 있습니다.

.시작하기 전에
* 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 워크플로 자동화를 설정해야 합니다.


다음의 경우에는 *보호* 메뉴가 표시되지 않습니다.

* RBAC 설정에서 이 작업이 허용되지 않는 경우(예: 운영자 권한만 있는 경우)
* 볼륨 ID를 알 수 없는 경우: 예를 들어 클러스터 간 관계가 있고 대상 클러스터가 아직 검색되지 않은 경우


.단계
. *상태: 모든 볼륨* 보기에서 보호하려는 볼륨을 선택합니다.
+
또는 동일한 SVM에서 여러 보호 관계를 생성하려면 상태: 모든 볼륨 보기에서 하나 이상의 볼륨을 선택하고 도구 모음에서 *보호* > * SnapMirror*를 클릭합니다.

+
보호 구성 대화 상자가 표시됩니다.

. * SnapMirror* 탭을 보고 대상 정보를 구성하려면 * SnapMirror*를 클릭하세요.
. 필요에 따라 *고급*을 클릭하여 공간 보장을 설정한 다음 *적용*을 클릭합니다.
. * SnapMirror* 탭에서 *대상 정보* 영역과 *관계 설정* 영역을 작성합니다.
. *적용*을 클릭하세요.
+
건강: 모든 볼륨 보기로 돌아갑니다.

. *상태: 모든 볼륨 보기* 상단에 있는 보호 구성 작업 링크를 클릭합니다.
+
보호 관계를 하나만 만드는 경우 작업 세부 정보 페이지가 표시됩니다. 그러나 보호 관계를 두 개 이상 만드는 경우 보호 작업과 관련된 모든 작업 목록이 표시됩니다.

. 다음 중 하나를 수행하세요.
+
** 작업이 하나뿐인 경우 *새로 고침*을 클릭하여 보호 구성 작업과 관련된 작업 목록과 작업 세부 정보를 업데이트하고 작업이 완료되는 시점을 확인합니다.
** 두 개 이상의 직업이 있는 경우:
+
... 작업 목록에서 작업을 클릭하세요.
... *새로 고침*을 클릭하면 보호 구성 작업과 관련된 작업 목록과 작업 세부 정보가 업데이트되고 작업이 완료되는 시점을 확인할 수 있습니다.
... *뒤로* 버튼을 사용하여 필터링된 목록으로 돌아가서 다른 일자리를 확인하세요.






구성 중에 지정한 대상 SVM이나 고급 설정에서 활성화한 옵션에 따라 결과 SnapMirror 관계는 여러 가지 가능한 변형 중 하나가 될 수 있습니다.

* 소스 볼륨과 동일하거나 더 최신 버전의 ONTAP 에서 실행되는 대상 SVM을 지정한 경우 블록 복제 기반 SnapMirror 관계가 기본 결과입니다.
* 소스 볼륨과 동일하거나 더 최신 버전의 ONTAP 에서 실행되는 대상 SVM을 지정했지만 고급 설정에서 버전 유연한 복제를 활성화한 경우, 버전 유연한 복제를 사용하는 SnapMirror 관계가 생성됩니다.
* 소스 볼륨보다 이전 버전의 ONTAP 에서 실행되는 대상 SVM을 지정하고, 이전 버전이 버전 유연한 복제를 지원하는 경우, 버전 유연한 복제를 지원하는 SnapMirror 관계가 자동으로 생성됩니다.

